### ISSUE TITLE
Cannot reverse grouped legend of stack bar chart

### ISSUE THREAD

**Issue by manycoding** [plotly/plotly.py#1658] opened 2019-07-06 19:08 UTC
I want the legend groups of stacked bar charts to follow the data, i.e. if the data is displayed top to bottom, the groups should be the same.

`layout.legend.traceorder` doesn't help, "grouped+reversed" reverses the labels in group.

```
import plotly.graph_objs as go
from plotly.colors import DEFAULT_PLOTLY_COLORS

data = []
for vc in [pd.Series([10, 50, 40], index=["a","b","c"], name="group_a"),
           pd.Series([80, 20], index=["i",None], name="group_b")]:
    data = data + [
        go.Bar(
            x=[counts],
            y=[vc.name],
            name=str(value)[:30],
            orientation="h",
            legendgroup=vc.name,
            marker_color=DEFAULT_PLOTLY_COLORS[i % 10],
        )
        for i, (value, counts) in enumerate(vc.items())
    ]
layout = go.Layout(
    barmode="stack",
)
go.FigureWidget(data, layout)
```

**Comment by gvwilson** [comment] 2024-06-13 19:40
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:40 UTC
