### ISSUE TITLE
histogram with barlabels

### ISSUE THREAD

**Issue by lucanics** [plotly/plotly.py#2238] opened 2020-03-02 12:12 UTC
Hi,

For plotly.express, I cannot find a way to add barlabels to a histogram. None of the examples on this page - https://plot.ly/python/histograms/ - provide barlabels either. Here is one example:
```
import plotly.express as px
df = px.data.tips()
fig = px.histogram(df, x="total_bill")
fig.show()
```
![image](https://user-images.githubusercontent.com/56067087/75675373-56833080-5c87-11ea-8e66-259b11ad9c86.png)

It works fine with barcharts, tough:
![image](https://user-images.githubusercontent.com/56067087/75675263-1de35700-5c87-11ea-9fad-8273692a6797.png)

Is there a way to add barlables to histograms?

**Comment by emmanuelle** [comment] 2020-03-04 17:10
Hum yes this is unfortunate... Indeed at the moment the histogram trace can only have hover trace. You can compute the histogram first using pandas or `np.histogram` and display the counts using a bar chart, @SylwiaOliwia2 is currently writing a doc example for this https://github.com/plotly/plotly.py/pull/2242.

**Comment by lucanics** [comment] 2020-03-05 12:35
I was thinking of the same workaround but thought there must be a simpler solution with update_traces that I was missing. Nevetheless, good to know someone is working on a doc example for this. Let me know if I can help somehow.

**Comment by gvwilson** [comment] 2024-06-14 13:06
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:06 UTC
