### ISSUE TITLE
pathbar in Treemap appears on top of subplot_titles

### ISSUE THREAD

**Issue by Mahdis-z** [plotly/plotly.py#1825] opened 2019-10-17 15:32 UTC
Using `make_subplots` in Treemap with pathbar, turns out that `subplot_titles` appears under pathbar when click on one of the sectors in Treemap. 

<img width="449" alt="Screen Shot 2019-10-17 at 11 26 27 AM" src="https://user-images.githubusercontent.com/47799189/67023624-16088900-f0d1-11e9-8eff-d31b79ee8c6b.png">

Here is a reproducible code: 
```
import plotly.graph_objects as go
from plotly.subplots import make_subplots

labels = ["Eve", "Cain", "Seth", "Enos", "Noam", "Abel", "Awan", "Enoch", "Azura"]
parents = ["", "Eve", "Eve", "Seth", "Seth", "Eve", "Eve", "Awan", "Eve"]

fig = make_subplots(
    cols = 2, rows = 1,
    column_widths = [0.4, 0.4],
    subplot_titles = ('branchvalues: <b>remainder</b>', 'branchvalues: <b>total</b>'),
    specs = [[{'type': 'treemap', 'rowspan': 1}, {'type': 'treemap'}]]    
)

fig.add_trace(
    go.Treemap(
        labels = labels,
        parents = parents,
        values =  [10, 14, 12, 10, 2, 6, 6, 1, 4],
        textinfo = "label+value+percent parent+percent entry+percent root"), 
    row = 1, col = 1)

fig.add_trace(
    go.Treemap(
        branchvalues = "total",
        labels = labels,
        parents = parents,
        values = [65, 14, 12, 10, 2, 6, 6, 1, 4],
        textinfo = "label+value+percent parent+percent entry",
        outsidetextfont = {"size": 20, "color": "darkblue"},
        marker = {"line": {"width": 2}},
        pathbar = {"visible": False}),
    row = 1, col = 2)

fig.show()
```

**Comment by gvwilson** [comment] 2024-06-14 13:14
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:14 UTC
