### ISSUE TITLE
Efficient deep copy of graph_objs without validation

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1078] opened 2018-07-28 09:53 UTC
Consider the following:

```python
fig1 = go.Figure(...)
fig2 = go.Figure(fig1)
```

Right now, the construction of `fig2` involves the re-validation of all of the properties in fig1. But this is unnecessarily since the properties are guaranteed to be valid in fig1.

Also consider this case:
```python
go.Figure(data=[go.Scatter(marker=go.scatter.Marker(...))])
```

Here, go.Scatter should not rerun the marker validation logic, and go.Figure should not rerun the scatter trace validation logic.

We should have a fast performance path for these cases that just performs a `deepcopy` on the raw dict and splices that into a new object, without any additional validation.

See https://community.plot.ly/t/how-to-copy-figure-or-trace-object-deepcopy-no-longer-working/12166

**Comment by gvwilson** [comment] 2024-06-13 17:41
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:41 UTC
Labels: performance
