### ISSUE TITLE
Secret Links Upload Time (Python Online)

### ISSUE THREAD

**Issue by tim-sauchuk** [plotly/plotly.py#1203] opened 2018-09-26 15:49 UTC
It seems that secret links take significantly longer to upload than public or private. On average, my plots (regardless of complexity) will take 8 seconds to upload. Secret dashboards take even longer to upload, on average about 130 seconds for a dashboard with 8 plots.

**Comment by Kully** [comment] 2018-10-01 13:43
> @Kully do you have any experience or thoughts on this?

I built the dashboards API and remember setting up the code logic turning plots into secret files. I'll look into this today and do some testing.

**Comment by Kully** [comment] 2018-10-01 17:32
the `add_share_key_to_url()` function from `plotly.py` is nearly 100% to blame for the slow uploads when `sharing=secret`. There are a few components in the function slowing it down:

- ~0.8 sec v2 UPDATE (ensuring that share key is enabled)
- a 4 second buffer after hitting a v1 POST is occurring. At least one reason for it is because if you immediately hit v2 after creating the chart with v1, we intermittently get a failure and a defaulting to a private chart instead (see https://github.com/plotly/streambed/issues/9352#issue-219974547)
- about 1.1 sec for a RETRIEVE to v2 (checking if share key enabled)

That all roughly adds up to about 6 seconds give or take

This is the code snippet I am running to test this:
```python
sharing = 'secret'

import plotly.plotly as py
import plotly.graph_objs as go
import time

trace1 = go.Scatter(
    x=list(range(1)),
    y=list(range(1)),
)

data = [trace1]
a = time.time()
py.iplot(data, filename='reg-scatter-{0}'.format(time.time()), sharing=sharing, auto_open=False)
b = time.time()
print('\n total upload time: {0}'.format(b-a))
```

I did not have to reattempt to enable the sharekey in all my code runnings so far: See [that part of the code here](https://github.com/plotly/plotly.py/blob/master/plotly/plotly/plotly.py#L1329-L1335)

related issue: https://github.com/plotly/streambed/issues/4089

**Comment by gvwilson** [comment] 2024-06-13 17:39
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:39 UTC
Labels: performance, plot.ly, legacy-versions
