### ISSUE TITLE
Use tempfile module to create temporary file for offline.plot

### ISSUE THREAD

**Issue by joshburkart** [plotly/plotly.py#395] opened 2016-01-31 20:00 UTC
Right now the default file that `plotly.offline.plot` outputs to is `temp-plot.html` in the current working directory. I think it would be better to create a real temporary file using e.g. `tempfile.NamedTemporaryFile` so as not to pollute the current working directory?

Happy to contribute this myself but thought I'd test the waters first. :)

**Comment by joshburkart** [comment] 2016-01-31 21:32
Another advantage would be avoiding the situation where you make two calls to `plot` in one script without specifying a file, and two browser windows are naturally opened up, but often both contain the second plot.

**Comment by chriddyp** [comment] 2016-02-17 21:46
hey @joshburkart - 
I'm a bit hesitant to use random filenames or temporary files because I think some users could accidentely fill up their hard-drive with a bunch of temporary plot files:

```
while True:
   plot(figure) # no filename specified - if we create a random filename, then this will create a new file on every iteration
```

Is my understanding of `tempfile` correct here?

> Another advantage would be avoiding the situation where you make two calls to plot in one script without specifying a file, and two browser windows are naturally opened up, but often both contain the second plot.

I totally agree with you on this - it's really easy to accidentely overwrite a file the way we have it set up right now. 

I'm open to other suggestions!

**Comment by jonmmease** [comment] 2018-09-22 10:37
Let's revisit this as a configuration option when get to working on the `plotly.io.show` module (https://github.com/plotly/plotly.py/issues/1098)

**Comment by gvwilson** [comment] 2024-06-10 14:41
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 14:41 UTC
Labels: enhancement
