### ISSUE TITLE
Heatmap z and text missing array of array datatype in docs

### ISSUE THREAD

**Issue by scott--** [plotly/plotly.py#1535] opened 2019-04-26 05:53 UTC
The documentation for Heatmap says that z and text should be a 

> list, numpy array, or Pandas series of numbers, strings, or datetimes

However, it seems that the common usage would be to pass in a 2D array / list of lists for both z and text when constructing a heatmap?

**Comment by jonmmease** [comment] 2019-04-29 09:49
Thanks for the suggestion @scott-- , I think this is something we could detect and improve in the docstring generation logic.

**Comment by gvwilson** [comment] 2024-06-13 19:31
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:31 UTC
Labels: documentation
