### ISSUE TITLE
Losing data when reusing stream

### ISSUE THREAD

**Issue by eulerreich** [plotly/plotly.py#344] opened 2015-11-09 16:26 UTC
When I reuse a previous stream_id for a new stream, the data in the previous stream is sometimes lost, but sometimes not. Sometimes the data actually changes.

I'm certainly expecting the data to remain as they were in the previous graph. Is the official expected behavior different?

**Comment by theengineear** [comment] 2015-11-09 22:35
@eulerreich , the expected behavior is for the previous data to be forgotten. In general, a single streaming token should be used *for each trace object*. You shouldn't reuse them. If you need to generate more, you can do that at plot.ly --> https://plot.ly/settings/api/

**Comment by theengineear** [comment] 2015-11-09 22:36
I'm going to close this down, but if you think it requires a fix still, you can reopen and we can discuss more.

**Closed by theengineear** 2015-11-09 22:36 UTC

**Comment by eulerreich** [comment] 2015-11-09 23:02
Just to make sure I'm being clear about what I am doing and what I expected:

I'm training some neural networks and am using plotly streaming to get a real time graph of the training curve. Since I need to tweak the code quite often and rerun them over and over again, I can't just use a fixed number of stream ids and not reuse them. What I've been doing is just cycling through my stream ids, with each graph consisting of 3 to 5 streams. I would like to have the data remain with the graph if possible, so that, for example if some settings were conducive to really fast training and I saw the training curve dropped really quickly, then I can later go back and quickly find the model that corresponds to the graph by inspecting my plotly files. But if the data vanishes, I can't do that.

Let me know if there's a better way of doing this.

**Comment by proboscis** [comment] 2016-03-18 10:22
I'm facing exactly the same problem. Since I create hundreds of streaming graphs for monitoring neural networks, I need to either reuse the stream_id or generate more stream_ids through api. However, there seems to be no api for generating stream_id, so I'm stuck at this point.

I hope either reusing or generating stream_id will be possible through API call.
Please let me know if there is a better way to repeatedly creating multiple streaming graphs.
