### ISSUE TITLE
jupyter notebook custom mapbox style loads blank page

### ISSUE THREAD

**Issue by wollerman** [plotly/plotly.py#1515] opened 2019-04-11 20:04 UTC
I have a custom mapbox style set on my `graph_objs.Layout()`; however, this renders a blank page. I can switch the plot to use `style='light'` and everything is fine. Here is an example of the broken `style` reference: https://plot.ly/~calyxmatt/3 (line 39)

I have tried both online and offline plots without success. The token I am using has access to this style and I've even switched the style to public.

I know others have reported 'hosted inline notebooks not rendering' but this isn't the issue. Even when I run the notebook locally I see something like: 
![image](https://user-images.githubusercontent.com/1610241/55989050-3eaf5200-5c5a-11e9-9371-2715f5712520.png)

This seems like a bug to me unless I'm doing something silly configuration wise?

Thanks!

**Comment by jonmmease** [comment] 2019-04-16 10:10
Hi @wollerman, thanks for the report.

Could you check out https://github.com/plotly/plotly.js/issues/3642 and see if you think you're having the same issue?

**Comment by wollerman** [comment] 2019-04-16 16:24
@jonmmease that seems to be the same issue. Pressing the home button does re-render the scatter points and the underlying style. Here's a screenshot after pressing the home button and zooming out:

![image](https://user-images.githubusercontent.com/1610241/56227013-62431580-6029-11e9-8f3b-42a4d71ec76d.png)

I'll defer to you on closing this and tracking the other issue or not.

Thanks!

**Comment by gvwilson** [comment] 2024-06-13 19:31
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:31 UTC
Labels: question
