### ISSUE TITLE
Plotly GO Table adds x-axis/y-axis elements when adding annotation

### ISSUE THREAD

**Issue by bderider100** [plotly/plotly.py#4090] opened 2023-03-03 16:45 UTC
Hi, 

I have a function to return a GO Table. When adding an annotation to this table, it puts an x-axis and y-axis, populated with generic numbers. Not understanding why this would display with a table. 

Expected behavior is that the caption would appear outside of the table area and that x-axis and y-axis elements wouldn't be shown. Below is an image of an output table, the function code, and the code that converts the plotly visual into an image. 

I am making an issue on github because I believe this to be a bug. I tried to do a good faith search of open issues, but didn't see anything. Additionally, I tried to search all official and unofficial documentation on GO tables, but didn't find anything that elucidated this. I have functions for px.bar and px.line that doesn't add any unwanted elements yet adds the caption in the exact spot as what is shown. 

Example plot: 
![Example_PLOTLY_GO_table](https://user-images.githubusercontent.com/124708873/222776771-8561385a-1031-4e8c-a417-e31b262c3d09.jpg)

Code: 
```
def returnPlotlyGoTable(pdfData, dictChartText, strFillColorCols = 'lightsteelblue', strAlignCols = 'left', strFillColorVals = 'lightgray', strAlignVals = 'left'): 
    tmpFig = go.Figure(data = [go.Table(header = dict(values = list(pdfData.columns),                         
                                                      fill_color = strFillColorCols, 
                                                      align = strAlignCols), 
                                                      cells = dict(values = pdfData.transpose().values.tolist(), 
                                                                   fill_color = strFillColorVals, 
                                                                   align = strAlignVals, 
                                                                   format = dictChartText['d3fmt']
                                                                  )
                                       )
                              ]
                      )
    
    if 'title' in dictChartText.keys() and dictChartText['title'] != '': 
        tmpFig.update_layout(title_text = dictChartText['title'])
    tmpFig.update_layout(margin = dict(t = 150))
    if 'caption' in dictChartText.keys() and dictChartText['caption'] != '': 
        tmpFig.add_annotation(font = dict(color = 'black', size = 12), 
                                     x = 0, 
                                     y = 1.06, 
                                     showarrow = False, 
                                     text = dictChartText['caption'], 
                                     textangle = 0, 
                                     xref = 'x', 
                                     yref = 'paper'
                               )
        tmpFig.update_layout()
    return tmpFig
```

Code snippet 2
```
imgTmp = BytesIO(key2.to_image(format = 'png', width = 1980, height = 1080))

```

**Comment by alexcjohnson** [comment] 2023-03-03 16:52
`xref = 'x'` in the annotation means an x axis, so we need to make one to reference, and then a y axis comes along for the ride. For `px.bar` and `px.line` you already have x and y axes so there's nothing new to add, although this means the annotation will be positioned wherever `0` is on that x axis.

Do you mean `xref='paper'` instead? If you want it centered on the page, that would be `xref='paper', x=0.5`

**Comment by bderider100** [comment] 2023-03-03 17:07
Thanks for the reply. 

I see what you are saying. I'll make that adjustment to my code.  

Not sure if this would still be considered unexpected behavior for a table. Let me know if you'd prefer to close the ticket. I can close it based on your feedback.

**Comment by alexcjohnson** [comment] 2023-03-07 05:41
Ok great! I’ll close this issue since I do believe this is the intended behavior, but perhaps @LiamConnors would take a look at how we document `xref` and `yref` and see if we could make it clearer that `”x”` and `”y”` apply only to cartesian axes?

**Closed by alexcjohnson** 2023-03-07 05:41 UTC
