### ISSUE TITLE
Matplotlib broken_barh does not work in plotly conversion

### ISSUE THREAD

**Issue by susielu** [plotly/plotly.py#1638] opened 2019-06-26 01:42 UTC
Here is an example that works fine with matplotlib: 
```
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.broken_barh([(110, 30), (150, 10)], (10, 9), facecolors='blue')
ax.broken_barh([(10, 50), (100, 20), (130, 10)], (20, 9),
               facecolors=('red', 'yellow', 'green'))
ax.set_ylim(5, 35)
ax.set_xlim(0, 200)
ax.set_xlabel('seconds since start')
ax.set_yticks([15, 25])
ax.set_yticklabels(['Bill', 'Jim'])
ax.grid(True)
ax.annotate('race interrupted', (61, 25),
            xytext=(0.8, 0.9), textcoords='axes fraction',
            arrowprops=dict(facecolor='black', shrink=0.05),
            fontsize=16,
            horizontalalignment='right', verticalalignment='top')

plt.show()
```

But when I try to convert it to plotly it doesn't render, I am using Plotly in a Jupyter notebook offline mode: 
```
import plotly.offline as py
import plotly.tools as tls
py.init_notebook_mode(connected=True)
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.broken_barh([(110, 30), (150, 10)], (10, 9), facecolors='blue')
ax.broken_barh([(10, 50), (100, 20), (130, 10)], (20, 9),
               facecolors=('red', 'yellow', 'green'))
ax.set_ylim(5, 35)
ax.set_xlim(0, 200)
ax.set_xlabel('seconds since start')
ax.set_yticks([15, 25])
ax.set_yticklabels(['Bill', 'Jim'])
ax.grid(True)
ax.annotate('race interrupted', (61, 25),
            xytext=(0.8, 0.9), textcoords='axes fraction',
            arrowprops=dict(facecolor='black', shrink=0.05),
            fontsize=16,
            horizontalalignment='right', verticalalignment='top')


plotly_fig = tls.mpl_to_plotly(fig)
py.iplot(plotly_fig)

```

It renders with this error: 
```

/apps/python3/lib/python3.6/site-packages/plotly/matplotlylib/renderer.py:451: UserWarning:

Dang! That path collection is out of this world. I totally don't know what to do with it yet! Plotly can only import path collections linked to 'data' coordinates
```

Is there any plan to support this?

**Comment by jonmmease** [comment] 2019-06-28 12:46
Hi @susielu, thanks for the report.  We don't have any immediate plans to put much more work into the matplotlib conversion functionality.  Of course, community contributions or [funding](https://plot.ly/products/consulting-and-oem/) could certainly change that.

**Comment by gvwilson** [comment] 2024-06-13 19:33
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:33 UTC
Labels: enhancement, matplotlylib
