### ISSUE TITLE
Mapping issue related to matplotlib to plotly colorscale 

### ISSUE THREAD

**Issue by MethaneRain** [plotly/plotly.py#2189] opened 2020-02-12 19:26 UTC
In an attempt to be able to plot ```matplotlib's``` ```nipy_spectral``` colormap in ```plotly``` I ran into a small error when running the ```cmap``` through the ```matplotlib_to_plotly``` function.

Found in the ```plotly``` documentation about changing ```matplotlib``` colormap to ```plotly``` colorscale (https://plot.ly/python/v3/matplotlib-colorscales/) 

code excerpt:

```python 
def matplotlib_to_plotly(cmap, pl_entries):
    h = 1.0/(pl_entries-1)
    pl_colorscale = []

    for k in range(pl_entries):
        C = map(np.uint8, np.array(cmap(k*h)[:3])*255)
        pl_colorscale.append([k*h, 'rgb'+str((C[0], C[1], C[2]))])

    return pl_colorscale

nipy_spectral = matplotlib_to_plotly(nipy_spectral_cmap, 255)
#viridis = matplotlib_to_plotly(viridis_cmap, 255)
magma = matplotlib_to_plotly(magma_cmap, 255)
```

I generated an error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-279-094292188f26> in <module>
     36 nipy_spectral = matplotlib_to_plotly(nipy_spectral_cmap, 255)
     37 #viridis = matplotlib_to_plotly(viridis_cmap, 255)
---> 38 magma = matplotlib_to_plotly(magma_cmap, 255)

<ipython-input-279-094292188f26> in matplotlib_to_plotly(cmap, pl_entries)
     30     for k in range(pl_entries):
     31         C = map(np.uint8, np.array(cmap(k*h)[:3])*255)
---> 32         pl_colorscale.append([k*h, 'rgb'+str((C[0], C[1], C[2]))])
     33 
     34     return pl_colorscale

TypeError: 'map' object is not subscriptable
```

However, wrapping the ```map(np.uint8, np.array(cmap(k*h)[:3])*255)``` in a ```list```, I was able to generate the ```plotly``` colorscale correctly. 

---

Fixed code excerpt:

```python
def matplotlib_to_plotly(cmap, pl_entries):
    h = 1.0/(pl_entries-1)
    pl_colorscale = []

    for k in range(pl_entries):
        C = list(map(np.uint8, np.array(cmap(k*h)[:3])*255))
        pl_colorscale.append([k*h, 'rgb'+str((C[0], C[1], C[2]))])

    return pl_colorscale

nipy_spectral = matplotlib_to_plotly(nipy_spectral_cmap, 255)
#viridis = matplotlib_to_plotly(viridis_cmap, 255)
magma = matplotlib_to_plotly(magma_cmap, 255)
print("all good.")

>>> all good.
```

Sample output of newly generated ```nipy_spectral``` colorscale in ```plotly```:

```python
trace1 = go.Scatter(x=avs['S-Avs'],y=avs['GF'], opacity=0.75, name='Avs Shots',
                   mode='markers',marker=dict(
                                colorbar=dict(title='Goals/Shots'),               
                                size=8,
                                color=avs['GF']/avs['S-Avs'],
                                colorscale=nipy_spectral,
                                showscale=True)
                    )
```
![matplotlib_plotly_colorbar_example](https://user-images.githubusercontent.com/36716747/74368976-7fbd4900-4dcc-11ea-8e5c-9905bcdb43c3.png)

I can do a PR for the ```plotly.py/doc/unconverted/python/matplotlib-colorscales.md``` if desired. 

Thanks

**Comment by empet** [comment] 2020-02-12 19:45
This is an old version of the function that converts a matplotlib colormap to a plotly colorscale.  It was used with Python 2.7.
 This one works with Python 3:

```
def mpl_to_plotly(cmap, pl_entries=11, rdigits=2):
    # cmap - colormap 
    # pl_entries - int = number of Plotly colorscale entries
    # rdigits - int -=number of digits for rounding scale values
    scale = np.linspace(0, 1, pl_entries)
    colors = (cmap(scale)[:, :3]*255).astype(np.uint8)
    pl_colorscale = [[round(s, rdigits), f'rgb{tuple(color)}'] for s, color in zip(scale, colors)]
    return pl_colorscale
```

**Comment by gvwilson** [comment] 2024-06-14 13:08
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:08 UTC
