### ISSUE TITLE
Plotly installed on jupyterhub notebook produces console errors when using FigureWidget

### ISSUE THREAD

**Issue by elvinlemmens** [plotly/plotly.py#1296] opened 2018-12-05 07:34 UTC
Hi,

I've been trying to get the new FigureWidget to work in a notebook hosted through a JupyterHub instance.
I have the following packages installed:
```
ipywidgets==7.4.2
notebook==5.7.2
plotly==3.4.2`

```
The regular plotly offline mode works perfectly, however I need some more interaction with the plot, which is why I would like to use the FigureWidget.
When creating a FigureWidget in the notebook, I get the following issues in the console:
![screenshot_jupyter_plotly](https://user-images.githubusercontent.com/42866015/49497083-c974e000-f867-11e8-85ed-b3c553dce99a.PNG)

As you can see, the jupyterhub creates a user specific environment, maybe the static files aren't installed properly?

**Comment by misolietavec** [comment] 2018-12-15 19:20
I have exactly the same versions of  `ipywidgets, notebook, plotly` and got the same error messages :-)
`ipywidgets` alone work OK. After removing user configuration file (`~/.jupyter/nbconfig/notebook.json`)  `FigureWidget` works (the nbextensions are specified in system-wide file` /usr/local/etc/jupyter/nbconfig/notebook.json`). I have packages installed by `pip`, not `conda`. This behaviour I tested with local `jupyter notebook` command and also with remote `jupyterhub` instance. Do not know, why this "works for me", but maybe this can help developers in tracking problems.

**Comment by shyam334** [comment] 2019-01-18 05:11
I have a similar, if not the same problem.
Package versions : 
```
python==3.7.2
plotly==3.4.2
ipywidgets==7.4.2
notebook==5.7.4
``` 
Installed by pip, in a conda virtual environment and Basic ipywidgets seem to work. (In jupyter notebook)

I also have an identical environment, in a different machine, where it plolty/Figurewidget works.
However, I haven't yet found what is different yet.

In the working instance, I see successful requests in the browser console for : 
```
Loading extension: plotlywidget/extension

HTTP 200/304 : <hub-url>/user/<user>/nbextensions/plotlywidget/extension.js?<timestamp>
HTTP 200/304 : <hub-url>/user/<user>/nbextensions/plotlywidget/index.js?<timestamp>
```

In the non-working instance, I see a failed request in the browser console:
```
Loading failed for the <script> with source <hub-url>/user/<user>/static/plotlywidget.js

HTTP 404 - <hub-url>/user/<user>/static/plotlywidget.js?<timestamp>
```
I dont see `Loading extension: plotlywidget/extension`


In both instances I see the following : 
```
$ jupyter nbextension list
Known nbextensions:
  config dir: /home/<user>/.conda/envs/<env>/etc/jupyter/nbconfig
    notebook section
      plotlywidget/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main  enabled 
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled
```

Some debug data : 
```
$ cat ~/.conda/envs/<env>/etc/jupyter/nbconfig/notebook.d/plotlywidget.json
{
  "load_extensions": {
    "plotlywidget/extension": true
  }
}
```

Any pointers would be appreciated.

**Comment by jonmmease** [comment] 2019-01-18 11:37
Hi @shyam334,

I don't have any specific ideas of what might be causing this, but here's what I would try.

 1. Rename (or remove if you don't care about anything in it) `/usr/local/etc/jupyter/nbconfig/notebook.json` so that jupyter doesn't find any extensions outside of your conda environment.
 2. Uninstall, reinstall, and reenable the ipywidgets and plotlywidget extensions

```
$ jupyter nbextension uninstall --py --sys-prefix widgetsnbextension
$ jupyter nbextension uninstall --py --sys-prefix plotlywidget
$ jupyter nbextension install --py --sys-prefix widgetsnbextension
$ jupyter nbextension install --py --sys-prefix plotlywidget
$ jupyter nbextension enable --py --sys-prefix widgetsnbextension
$ jupyter nbextension enable --py --sys-prefix plotlywidget
```

3. Try again 🙂

**Comment by shyam334** [comment] 2019-01-21 05:43
Thanks @jonmmease 
I tried your instructions, but didn't help.
Its a bit tricky to create a reproducible example, but let me try and get back.

**Comment by elvinlemmens** [comment] 2019-01-31 09:18
Some other changes to my environment made me build my jupterhub docker container again, so starting from a fresh environment I managed to get it to work using the following steps. On the jupyterhub container shell:
```
pip install notebook ipywidgets plotly
jupyterhub nbextension enable --py widgetsnbextension
jupyterhub nbextension enable --py plotlywidget
```

Then creating a notebook:
```
import plotly.graph_objs as go
go.FigureWidget()
```

These steps worked for me.

**Comment by elvinlemmens** [comment] 2019-01-31 14:18
@jonmmease Maybe add those commands to the docs for Jupyterhub users?

**Comment by gvwilson** [comment] 2024-06-13 17:43
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:43 UTC
