### ISSUE TITLE
Figure with multiple matching `go.Scattergl` traces have wrong hover order

### ISSUE THREAD

**Issue by lamhoangtung** [plotly/plotly.py#4018] opened 2023-01-16 12:04 UTC
Hi. I discover that figure with multiple matching `go.Scattergl` traces have wrong hover order. Consider this example:
```python
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scattergl(
    x=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], y=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    line_color='rgb(0,100,80)',
    name='Normal',
))

fig.add_trace(go.Scattergl(
    x=[5, 6], y=[5, 6],
    mode='markers',
    marker_color='rgb(255,0,0)',
    name='Abnormal',
))

fig.show()
```
I get this plot:
![image](https://user-images.githubusercontent.com/26834698/212672928-8f436e6e-e92c-4775-92b4-7cbabb3e33c1.png)
When I hover on the [5,5] points, the hover text should be in Red and say "Abnormal", but its not.

If I flip the trace order like this:
```python
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scattergl(
    x=[5, 6], y=[5, 6],
    mode='markers',
    marker_color='rgb(255,0,0)',
    name='Abnormal',
))

fig.add_trace(go.Scattergl(
    x=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], y=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    line_color='rgb(0,100,80)',
    name='Normal',
))

fig.show()
```
I get this plot:
![image](https://user-images.githubusercontent.com/26834698/212673487-ee0bc478-f61e-49b1-be45-6e1a07e7c1c6.png)
Which have the correct hover text, but all the red markers are behind the green markers.

This does not happen for normal `go.Scatter` trace:
```python
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], y=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    line_color='rgb(0,100,80)',
    name='Normal',
))

fig.add_trace(go.Scatter(
    x=[5, 6], y=[5, 6],
    mode='markers',
    marker_color='rgb(255,0,0)',
    name='Abnormal',
))

fig.show()
```
![image](https://user-images.githubusercontent.com/26834698/212673997-3f54c017-2d18-46c1-8ef3-4d51b095090a.png)

So clearly this is a bug. Can someone take a look and fix this ?

Thanks for checking by!

**Comment by AaronStiff** [comment] 2023-01-26 15:05
Duplicate of #2079

**Comment by AaronStiff** [comment] 2023-01-26 15:26
A few options for workarounds:

Display both `Normal` and `Abnormal` points together:

`fig.update_layout(hovermode = "x unified")`

Display none of the `Normal` points, but display the `Abnormal` points

`fig.update_traces(hoverinfo="skip",selector={"name":"Normal"})`

**Closed** 2023-05-14 09:45 UTC
Labels: duplicate
