### ISSUE TITLE
Fill area bug while using webgl

### ISSUE THREAD

**Issue by etirikov** [plotly/plotly.py#2018] opened 2019-12-26 10:33 UTC
Hello. There is a bug while using fill area with WebGL. This is can be seen on a example from documentation, where fill area between two traces.
`import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x=[1, 2, 3, 4], y=[3, 4, 8, 3],
    fill=None,
    mode='lines',
    line_color='indigo',
    ))
fig.add_trace(go.Scatter(
    x=[1, 2, 3, 4],
    y=[1, 6, 2, 6],
    fill='tonexty', 
    mode='lines', line_color='indigo'))

fig.show()`
If I change Scatter to Scattergl, nothing is filled, drawn only two lines.
`import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scattergl(x=[1, 2, 3, 4], y=[3, 4, 8, 3],
    fill=None,
    mode='lines',
    line_color='indigo',
    ))
fig.add_trace(go.Scattergl(
    x=[1, 2, 3, 4],
    y=[1, 6, 2, 6],
    fill='tonexty', 
    mode='lines', line_color='indigo'))

fig.show()`

**Comment by emmanuelle** [comment] 2019-12-26 23:06
Hello @etirikov , thanks for opening this issue. I think this problem is the same as https://github.com/plotly/plotly.js/issues/4017, I'll cite this issue in the plotly.js one (some bugs - or features :-) - come directly from the javascript code).

**Comment by gvwilson** [comment] 2024-06-14 13:10
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:10 UTC
