### ISSUE TITLE
autoresizing behaviour

### ISSUE THREAD

**Issue by dhirschfeld** [plotly/plotly.py#1041] opened 2018-06-27 10:42 UTC
As mentioned in https://github.com/plotly/plotly.py/pull/942#issuecomment-400135253, in the JupyterLab display, in a lot of cases, it would be very nice if the plot would automatically resize when the window/tab resized.

Since there are situations where this wouldn't be desirable e.g. in the case of large/slow plots, it would be very good if this behaviour could be chosen by the user with an `autoresize` property/argument/config

**Comment by jmmease** [comment] 2018-06-27 14:20
Alright, I just pushed out `plotlywidget@0.1.1` and `plotly==3.0.0rc10` and I added responsive resizing in JupyterLab (the classic notebook doesn't seem to share the same PhosphorJS resize event).

The intended behavior is for plots to expand to fill their container on construction, and when the container is resized. But, if the figure has `layout.width` or `layout.height` specified explicitly then no resizing takes place.  

I think this is a nice balance. Figure's will resize unless you say what size you want. For plots that are expensive to resize, the user just needs to decide what size they want and it will stick there.

Give it a try and see what you think

**Comment by jonmmease** [comment] 2018-07-17 18:54
I think what you were talking about here was included in 3.0.0. Can you confirm @dhirschfeld?

**Comment by jonmmease** [comment] 2018-08-04 13:09
Going to close this, as I believe it was sufficiently addressed prior to the release of version 3.0.0. We can reopen or create a new issue if there are any other outstanding issues.

**Closed by jonmmease** 2018-08-04 13:09 UTC
Labels: enhancement

**Comment by dhirschfeld** [comment] 2018-08-08 06:14
Sorry, other priorities got in the way of testing this.

I'm now using plotly 3.1.0 with jupyterlab 0.33.7 and the plot is now automatically resizing which is great!

If I specify the height of the figure the auto-resizing no longer happens - as you mentioned above. I think it would be nice though if only the height is specified for the *width* to continue to automatically resize and vice-versa. i.e. auto-resizing would only be completely disabled if both height and width were specified.

Not sure if that's feasible?

**Comment by jonmmease** [comment] 2018-08-17 12:00
Thanks for the suggestion @dhirschfeld.  The width resizing with fixed height is being implemented in #1117

**Comment by slishak** [comment] 2019-04-30 11:25
I'm getting a similar issue to this in jupyterlab with Plotly Express. If I use `plotly_graph_objs.FigureWidget` setting fixed height but no width, the width scales as expected but the height does not. However, if I use `plotly_express.scatter`, the `height` argument is not respected and it auto-resizes both the width and the height. 

![image](https://user-images.githubusercontent.com/12515343/56958698-512af600-6b4b-11e9-8c88-a8ea224b0823.png)
