### ISSUE TITLE
FigureWidget does not work on PyCharm

### ISSUE THREAD

**Issue by shuotwang** [plotly/plotly.py#2173] opened 2020-02-10 09:14 UTC
Hi, I got an issue: the FigureWidget does not work on PyCharm. Part of function works, but it failed when I tried to use `on_selection` and `on_click` functions. 
Warning message is : 
`Cannot find reference 'FigureWidget' in 'graph_objects.py' less... (⌘F1) 
Inspection info: This inspection detects names that should resolve but don't. Due to dynamic dispatch and duck typing, this is possible in a limited but useful number of cases. Top-level and class-level items are supported better than instance items.`
PyCharm Version: 2018.2.5, Plotly version 4.5.0, system version: MacOS 10.15.2, Python 3.7
However, the same code works well on Jupyter. Any suggestions how to solve the issue?

**Comment by gvwilson** [comment] 2024-06-14 13:08
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:08 UTC
