### ISSUE TITLE
Installation problems with plotting function 

### ISSUE THREAD

**Issue by daxsoule** [plotly/plotly.py#1801] opened 2019-10-05 04:13 UTC
I have followed the documentation but am unable to get plotly to render a plot. What appears to be happening is that the installation works, importing works and then when I create a figure a big blank spot appears. No error message. I think I have read all of the relevant issue pages... anyone have an idea how to trouble shoot this? 

Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux

In this case I am using Pangeo served on the Azure cloud in JupyterLab

import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = 'notebook+plotly_mimetype'
pio.renderers.default = 'notebook' 

fig= go.Figure(data=go.Isosurface(
    x=[0,0,0,0,1,1,1,1],
    y=[1,0,1,0,1,0,1,0],
    z=[1,1,0,0,1,1,0,0],
    value=[1,2,3,4,5,6,7,8],
    isomin=2,
    isomax=6,
))

pio.show(fig)

**Comment by sursu** [comment] 2019-10-05 10:32
Looks like this occurs Jupyter Notebooks only. In JupyterLab both default renderers work: 

```python
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = 'notebook+plotly_mimetype'
pio.renderers.default = 'jupyterlab'

fig= go.Figure(data=go.Isosurface(
            x=[0,0,0,0,1,1,1,1],
            y=[1,0,1,0,1,0,1,0],
            z=[1,1,0,0,1,1,0,0],
            value=[1,2,3,4,5,6,7,8],
            isomin=2,
            isomax=6,
))

fig.show()
```

**Comment by daxsoule** [comment] 2019-10-05 10:47
@sursu When I make that change the effect is that the figure still does not appear. No errors... and no figure. When I specified "notebook" in the original post what appears to happen is that a figure is created... but it is not visible. When I change the line to:

pio.renderers.default = 'jupyterlab'

And execute the cell, it behaves as if the entire cell output is suppressed.

**Comment by gvwilson** [comment] 2024-06-14 13:15
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:15 UTC
