### ISSUE TITLE
Using domain to draw multiple parcoords only draws first trace

### ISSUE THREAD

**Issue by lordalisat** [plotly/plotly.py#1372] opened 2018-12-17 15:31 UTC
I'm trying to add several parcoords plots next to each other, to add some kind of edge splatting image 
(something like this:
![image](https://user-images.githubusercontent.com/15800976/50096704-9b54b000-0218-11e9-990f-e4a1be773585.png))

When using the domain to draw multiple parcoords (similar to how the pie is drawn in the docu), only the traces for the first parcoords are drawn:
![image](https://user-images.githubusercontent.com/15800976/50096809-d6ef7a00-0218-11e9-9c85-7786459d4823.png)

even though the debugger returns this as the data of the drawn figure:

`<class 'tuple'>: (Parcoords({
    'dimensions': [{'range': [0, 4], 'tickvals': [0], 'values': [1, 2, 3]},
                   {'range': [0, 4], 'tickvals': [0], 'values': [2, 3, 1]}],
    'domain': {'x': [0, 0.5]},
    'line': {'cmin': 0,
             'color': [4, 4, 5],
             'colorbar': {'title': 'Colorbar'},
             'colorscale': 'Greys',
             'reversescale': True},
    'showlegend': False,
    'uid': '82dbeee2-bd11-4977-bf10-09c7171a3b7a',
    'visible': True
}), Parcoords({
    'dimensions': [{'range': [0, 4], 'tickvals': [0], 'values': [1, 2, 3]},
                   {'range': [0, 4], 'tickvals': [0], 'values': [2, 3, 4]}],
    'domain': {'x': [0.5, 1.0]},
    'line': {'cmin': 0, 'color': [4, 4, 5], 'colorscale': 'Greys', 'reversescale': True},
    'showlegend': False,
    'uid': '507b8968-e5b3-4ca5-9c2a-bed702ed51ca',
    'visible': True
}))`

**Comment by jonmmease** [comment] 2018-12-21 11:42
Thanks for the report @lordalisat,

Here's a quick example that I tried:

```python
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode()

data = [
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode()

data = [
    go.Parcoords(
        line = dict(color = 'blue'),
        domain = {
            'x': [0, 0.45],
            'y': [0, 1]
        },
        dimensions = list([
            dict(range = [1,5],
                 constraintrange = [1,2],
                 label = 'A', values = [1,4]),
            dict(range = [1.5,5],
                 tickvals = [1.5,3,4.5],
                 label = 'B', values = [3,1.5]),
        ])
    ),
    go.Parcoords(
        line = dict(color = 'blue'),
        domain = {
            'x': [0.55, 1],
            'y': [0, 1]
        },
        dimensions = list([
            dict(range = [1,5],
                 constraintrange = [1,2],
                 label = 'C', values = [1,4]),
            dict(range = [1.5,5],
                 tickvals = [1.5,3,4.5],
                 label = 'D', values = [3,1.5]),
        ])
    ),
]

layout =  dict(
    title = "Multi-Parcoords Diagram",
)

fig = dict(data=data, layout=layout)
iplot(fig)
```
![newplot 35](https://user-images.githubusercontent.com/15064365/50341033-47cdb500-04eb-11e9-9732-534ebd4b56fd.png)

In my case I'm seeing the axes for both traces, but no data is appearing on the second trace. Is this what you're seeing?  I'll open a corresponding report with the plotly.js project.

**Comment by jonmmease** [comment] 2018-12-21 11:53
Also, for your particular usecase, is there a reason you couldn't create this example plot with a single `parcoords` trace (one with 8 dimensions)?

**Comment by lordalisat** [comment] 2018-12-21 13:08
This is indeed the same thing that I am seeing. The reason I am not using a single parcoords trace is that the number of values changes per dimension, as well as the weights of the traces (basically, I am using the parcoords to visualize a set of directed graphs). Thanks for trying to think with me though!

**Comment by gvwilson** [comment] 2024-06-13 17:43
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:43 UTC
Labels: bug, plotly.js
