### ISSUE TITLE
Is it possible to add a hyperlink to data points in a scatter plot or bars in a bar plot using the python api?

### ISSUE THREAD

**Issue by lx1054331851** [plotly/plotly.py#1756] opened 2019-09-06 08:44 UTC
Is it possible to add a hyperlink to data points in a scatter plot or bars in a bar plot using the python api?

Basically, i’d like to bring up another plot/dashboard/report when plot data is clicked. Unfortunately the ‘Click Events in Python’ section of the documentation is not very helpful.

**Comment by emmanuelle** [comment] 2019-09-06 13:49
Hello, would Dash solve your problem? See for example https://dash.plot.ly/interactive-graphing where one graph is updated on hover on another graph.

**Comment by lx1054331851** [comment] 2019-09-07 08:07
Hi @emmanuelle , this example [https://community.plot.ly/t/hyperlink-to-markers-on-map/17858
](https://community.plot.ly/t/hyperlink-to-markers-on-map/17858) solves my problem.

This is what I want to achive:
![c1b91ef7d031c183c6f682712fbca7e4f17df8f1](https://user-images.githubusercontent.com/12423206/64471712-6d891000-d187-11e9-8ff0-1f5c05dcc026.gif)

Through refere the above link, the below code solve the problem perfectly:
```python
from plotly.offline import plot
import pandas as pd
import plotly.graph_objs as go
import re

# mapbox_access_token = '...'

# Build scattermapbox trace and store URL's in the customdata
# property. The values of this list will be easy to get to in the
# JavaScript callback below
data = [
    go.Scatter(
        x=[1, 2, 3],
        y=[1, 3, 2],
        mode='markers',
        marker=dict(
            size=14
        ),
        name='mapbox 1',
        text=['Montreal'],
        customdata=['https://www.baidu.com', 'http://www.fabricschina.com.cn/', 'https://www.zhihu.com']
    )
]

# Build layout
layout = go.Layout(
    hovermode='closest',
)

# Build Figure
fig = go.Figure(
    data=data,
    layout=layout,
)

# Get HTML representation of plotly.js and this figure
plot_div = plot(fig, output_type='div', include_plotlyjs=True)

# Get id of html div element that looks like
# <div id="301d22ab-bfba-4621-8f5d-dc4fd855bb33" ... >
res = re.search('<div id="([^"]*)"', plot_div)
div_id = res.groups()[0]

# Build JavaScript callback for handling clicks
# and opening the URL in the trace's customdata 
js_callback = """
<script>
var plot_element = document.getElementById("{div_id}");
plot_element.on('plotly_click', function(data){{
    console.log(data);
    var point = data.points[0];
    if (point) {{
        console.log(point.customdata);
        window.open(point.customdata);
    }}
}})
</script>
""".format(div_id=div_id)

# Build HTML string
html_str = """
<html>
<body>
{plot_div}
{js_callback}
</body>
</html>
""".format(plot_div=plot_div, js_callback=js_callback)

# Write out HTML file
with open('hyperlink_fig.html', 'w') as f:
    f.write(html_str)
```

By the way, can it become a python API?

Thank you very much!

**Comment by emmanuelle** [comment] 2019-09-09 12:47
Glad you solved your problem. Regarding the Python API, this is something you can do with Dash applications, as discussed (with you I guess?) on https://community.plot.ly/t/is-it-possible-to-add-a-hyperlink-to-data-points-in-a-scatter-plot/28343/2.

**Comment by zsktju** [comment] 2020-06-26 02:35
> Hi @emmanuelle , this example [https://community.plot.ly/t/hyperlink-to-markers-on-map/17858 ](https://community.plot.ly/t/hyperlink-to-markers-on-map/17858) solves my problem.
> 
> This is what I want to achive:
> ![c1b91ef7d031c183c6f682712fbca7e4f17df8f1](https://user-images.githubusercontent.com/12423206/64471712-6d891000-d187-11e9-8ff0-1f5c05dcc026.gif)
> 
> Through refere the above link, the below code solve the problem perfectly:
> 
> ```python
> from plotly.offline import plot
> import pandas as pd
> import plotly.graph_objs as go
> import re
> 
> # mapbox_access_token = '...'
> 
> # Build scattermapbox trace and store URL's in the customdata
> # property. The values of this list will be easy to get to in the
> # JavaScript callback below
> data = [
>     go.Scatter(
>         x=[1, 2, 3],
>         y=[1, 3, 2],
>         mode='markers',
>         marker=dict(
>             size=14
>         ),
>         name='mapbox 1',
>         text=['Montreal'],
>         customdata=['https://www.baidu.com', 'http://www.fabricschina.com.cn/', 'https://www.zhihu.com']
>     )
> ]
> 
> # Build layout
> layout = go.Layout(
>     hovermode='closest',
> )
> 
> # Build Figure
> fig = go.Figure(
>     data=data,
>     layout=layout,
> )
> 
> # Get HTML representation of plotly.js and this figure
> plot_div = plot(fig, output_type='div', include_plotlyjs=True)
> 
> # Get id of html div element that looks like
> # <div id="301d22ab-bfba-4621-8f5d-dc4fd855bb33" ... >
> res = re.search('<div id="([^"]*)"', plot_div)
> div_id = res.groups()[0]
> 
> # Build JavaScript callback for handling clicks
> # and opening the URL in the trace's customdata 
> js_callback = """
> <script>
> var plot_element = document.getElementById("{div_id}");
> plot_element.on('plotly_click', function(data){{
>     console.log(data);
>     var point = data.points[0];
>     if (point) {{
>         console.log(point.customdata);
>         window.open(point.customdata);
>     }}
> }})
> </script>
> """.format(div_id=div_id)
> 
> # Build HTML string
> html_str = """
> <html>
> <body>
> {plot_div}
> {js_callback}
> </body>
> </html>
> """.format(plot_div=plot_div, js_callback=js_callback)
> 
> # Write out HTML file
> with open('hyperlink_fig.html', 'w') as f:
>     f.write(html_str)
> ```
> 
> By the way, can it become a python API?
> 
> Thank you very much!

I copy the code in my jupyter notebook atmosphere. It creats the html file with the same picture. But when i click the points in the picture. The hyperlink doesnot work. Why ?   Should I install some other packages?  I have installed plotly,jupyter,ipywidgets.

**Comment by gvwilson** [comment] 2024-06-13 19:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:49 UTC
