### ISSUE TITLE
create_gantt figure should be responsive

### ISSUE THREAD

**Issue by brylie** [plotly/plotly.py#1211] opened 2018-10-03 08:28 UTC
The `figure_factory` `create_gantt` method outputs a figure with static dimensions. As most other Plotly charts are responsive, so should be the GANTT. Please allow the GANTT chart to be responsive to page/device dimensions, rather than expecting hard-coded width and height dimensions.

**Comment by gvwilson** [comment] 2024-06-13 17:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:44 UTC
Labels: enhancement
