### ISSUE TITLE
Add plot config options to display bundle so they are available to JupyterLab and nteract

### ISSUE THREAD

**Issue by MichaelBoublil** [plotly/plotly.py#1027] opened 2018-06-04 15:30 UTC
Hello,

I'm currently working on data that cannot go online. I noticed the other day a button "edit in Chart Studio".
I tried to remove it using this tutorial in your documentation: https://plot.ly/python/configuration-options/
but even with the following code:
```
config={'showLink': False}
iplot(data, config=config)
```

the button stays.

Is there a step that I forgot ? I'd really appreciate some help to remove it.

Thank you,

Michael

**Comment by cldougl** [comment] 2018-06-04 16:02
Hi there,
Can you confirm that you're using an updated version of the python api and also that you're in offline mode (as mentioned in the [doc](https://plot.ly/python/configuration-options/) these are offline configuration options only so with online you can edit the options via the iframe query string)

<img width="1026" alt="screen shot 2018-06-04 at 11 54 58 am" src="https://user-images.githubusercontent.com/2789078/40928251-d8a6aa40-67ee-11e8-9e3d-5928b5367f9b.png">

**Comment by MichaelHalfon** [comment] 2018-06-04 16:11
I was on 2.5.x, I updated it, and I am now on the same version as you.

It still doesn't work. I tried on JLab and Notebook, they both still have the floppy disk that says "edit in Chart Studio". (By the way, on your screenshot you have it too, I don't know if that's normal).
The floppy disk is clickable.

**Comment by rysktky** [comment] 2018-06-05 09:27
i guess this works to avoid online features completely.

`config = {'showLink': False, 'displaylogo':False, 'modeBarButtonsToRemove':['sendDataToCloud']}`

**Comment by MichaelHalfon** [comment] 2018-06-05 11:08
you're right. It works well on Jupyter Notebook, but the same code doesn't work on JLab

**Comment by jonmmease** [comment] 2018-09-23 10:26
Thanks for digging into this @MichaelHalfon and @rysktky.  @rysktky 's solution above is the right way to handle this in `offline.iplot` in the classic notebook, and in `offline.plot` from anywhere.

For `offline.iplot` in JupyterLab things work a bit differently, in this case plotly.py doesn't construct the raw HTML to render the figure, but instead passes the `data`/`layout`/`frames` data structure to the front end in a display bundle, and this is then rendered by the [`@jupyterlab/plotly-extension`](https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/plotly-extension) extension.  At the moment, the config options aren't included in the display bundle and so they aren't available to `@jupyterlab/plotly-extension`.

To support this, plotly.py will need to add the config options to the display bundle data structure and `@jupyterlab/plotly-extension` will need to check for the presence of config options before creating the plot.  Similarly, to support config options in nteract, the nteract renderer would need to check for these options as well.

**Comment by gvwilson** [comment] 2024-06-13 17:41
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:41 UTC
Labels: enhancement
