### ISSUE TITLE
Subscripts and superscript in the exported svg + inkscape

### ISSUE THREAD

**Issue by Gorfar** [plotly/plotly.py#1435] opened 2019-02-12 20:09 UTC
Hello!

I am trying to add super- and subscripts in the figure, save it as *.svg and open in Inkscape. However, Inkscape cannot open it properly, all *scipts are written as the main text. Are there any possibilities to solve this? Maybe add subscripts somehow else and not via html tags?

Thank you in advance.

Code: 
```python
import plotly.graph_objs as go
import plotly.io
layout=go.Layout()
layout.xaxis.title = u"10<sup>18</sup> a<sub>0</sub>"
fig = go.FigureWidget(layout=layout)
fig
plotly.io.write_image(fig, "unnamed.svg") # save figure
```
Result:
![inkscape_plotly](https://user-images.githubusercontent.com/4509284/52664631-89427580-2f1a-11e9-9baf-6a2c2aa44b09.png)

I am using  anaconda environment on OpenSuse Leap 42.3
ipython 5.8.0
ipykernel 4.9.0
jupyter 1.0.0
jupyter_client 5.2.3
plotly 3.5.0
plotly-orca 1.1.1
inkscape 0.91

**Comment by jonmmease** [comment] 2019-02-19 11:36
Hi @Gorfar,

The superscripts/subscripts aren't actually represented internally as HTML, this is markup syntax that plotly.js should be converting to valid SVG.  Could you try opening the SVG file directly in firefox or chrome and see what you get?

@antoinerg Did you run into this issue when working on the orca/EMF support using inkscape?

**Comment by Gorfar** [comment] 2019-02-19 12:21
Hi @jonmmease,

When I open the SVG file in firefox and chrome, it works as it should be.
![image](https://user-images.githubusercontent.com/4509284/53014589-f6de2c80-3459-11e9-9434-344063a0a1aa.png)

**Comment by jonmmease** [comment] 2019-02-27 11:46
Ping @antoinerg :slightly_smiling_face:

**Comment by raulf2012** [comment] 2019-08-12 01:05
Hello @Gorfar, @jonmmease,

I am also interested in this issue as I've had trouble with exported plotly SVGs and Inkscape, although the issue doesn't resemble what @Gorfar has documented here

Instead when I ran @Gorfar's code (I updated the syntax to Plotly 4.0, see below) I produced this (**when exported into Inkscape**)
![image](https://user-images.githubusercontent.com/28916036/62841865-b53c7a80-bc61-11e9-9229-ae91b7cc75ec.png)

it deceptively seems like the problem is solved, but if you zoom in a bit you'll see that an **extra space character has been inserted next to the super/sub-scripted character** 
![image](https://user-images.githubusercontent.com/28916036/62841914-4875b000-bc62-11e9-9d09-ba0ecbeb1d31.png)


Similarly to @Gorfar, when viewed in Google chrome or some other browser the image looks normal

Any insight into this issue would be appreciated as it's really throwing a wrench into my workflow 

---

I've updated the sample code to conform to Plotly 4.0 syntax
```
import plotly.graph_objs as go

layout=go.Layout()
layout.xaxis.title = u"10<sup>18</sup> a<sub>0</sub>"
fig = go.Figure(layout=layout)

fig.write_image("unnamed.svg")
```

I'm running on Ubuntu+KDE/Plasma
```
python           3.7.3
plotly           4.0.0
plotly-orca      1.2.1
chart-studio     1.0.0
Inkscape         0.92.4
```

**Comment by raulf2012** [comment] 2019-08-12 01:40
I also wanted to note for anybody else running into these issue, that exporting directly to pdf and then converting that into pdf or importing into Inkscape seems to be a more robust workaround, at least in my limited experience

**Comment by gvwilson** [comment] 2024-06-13 19:24
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:24 UTC
