### ISSUE TITLE
go.Table appearance ignores the deafult PX template

### ISSUE THREAD

**Issue by joelostblom** [plotly/plotly.py#1869] opened 2019-11-04 23:46 UTC
`go.Table` seems to be fixed at using the plotly template, and using PX to change to other templates has no effect. Updating the plotly template even after switching to another PX default template changes the appearance of the table.

I couldn't figure out if the template `go.Table` is using is set at a location that is not overwritten when changing the PX default template, or if the plotly template is hardcoded to always be used within the table function.

I appreciate that `go.Table` is not a PX function, but since it seemingly is reading from a default template somewhere and the PX templates all specify Table colors, it would be useful if the Table appearance would change when the default PX template changes.

Here is an example of what I mean, note the comments.

```python
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go

# Plotly template
fig1 = go.Figure(data=[go.Table(header=dict(values=['A Scores', 'B Scores']),
                cells=dict(values=[[100, 90, 80, 90], [95, 85, 75, 95]]))]) 
fig1.show()

# Changing to ggplot2 doesn't anything
px.defaults.template = 'ggplot2'
fig2 = go.Figure(data=[go.Table(header=dict(values=['A Scores', 'B Scores']),
                cells=dict(values=[[100, 90, 80, 90], [95, 85, 75, 95]]))]) 
fig2.show()

# Updating the plotly template shows that go.Table is reading from the 
# plotly template rather than ignoring templates altogether.
pio.templates['plotly'].data.table[0].cells.fill.color = 'orange'
fig3 = go.Figure(data=[go.Table(header=dict(values=['A Scores', 'B Scores']),
                cells=dict(values=[[100, 90, 80, 90], [95, 85, 75, 95]]))]) 
fig3.show()
```

Fig1
![image](https://user-images.githubusercontent.com/4560057/68167009-6c484980-ff64-11e9-9586-b9e989d60178.png)

Fig2
![image](https://user-images.githubusercontent.com/4560057/68167033-7407ee00-ff64-11e9-8b3b-14b4381f7acf.png)

Fig3
![image](https://user-images.githubusercontent.com/4560057/68167044-7b2efc00-ff64-11e9-9655-3f494a066631.png)

**Comment by nicolaskruchten** [comment] 2019-11-05 00:12
Right, the PX templates apply only to the PX functions.

**Comment by nicolaskruchten** [comment] 2019-11-05 01:18
If you want to set a default template `plotly`-wide, the way to do it is to set `pio.templates.default`. `px.defaults.template` is sort of a "legacy" PX-only setting that lets you set a template when using PX without having to import anything else, following the "one import only gets you the whole thing" philosophy of PX.

**Comment by joelostblom** [comment] 2019-11-05 08:05
Thanks for clarifying. So `pio.templates.default` will affect both px and go figures, unless `px.defaults.template` is set which would leave px figures unaffected by `pio.templates.default`. On the other hand, `px.defaults.template` always affects px figures, but never go figures. I noticed that this is explained well in the docs already. 

When you say it is a legacy option, do you mean it might go away or be changed soon? Would it make sense to have `px.defaults.template` as a shortcut for `pio.templates.default` which changes both px and go figures while not requiring to import `plotly.io` or would there be negative side effects / no real advantage from that setup?

**Comment by nicolaskruchten** [comment] 2019-11-06 03:03
Legacy in this context means we added it in the past for possibly-dubious reasons, but removing or changing its behaviour now would be considered a breaking change that might break some code in the wild and so we're not willing to do that in the near future :) We can talk about it for v5!

**Comment by gvwilson** [comment] 2024-06-14 13:13
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:13 UTC
