### ISSUE TITLE
y axis labels does not appear in scatter plot when using plotly.express with 2 inputs

### ISSUE THREAD

**Issue by npcomplete2023** [plotly/plotly.py#4455] opened 2023-12-08 18:51 UTC
Hello Plotly,

I experience the following problem,
when trying to generate a figure of type 'line' with multiple traces using the plotly.express
(the traces are defined implicitly, by defining a list of list in the y argument)
the resulting figure indeed includes 2 traces as expected, 
it DOES name correctly the x axis but DOESN'T name correctly the y axis label, which is set to 'value' for some reason.
See attached an example code and a resulting graph (saved as screenshot) 

MOREOVER, you can see the same phenomenon in the plotly tutorial 
https://www.youtube.com/watch?v=GGL6U0k8WYA&t=622s
at minutes 08:50-09:00 of the video. Notice the y-axis label in the video.

Thank you

--------------------Example code--------------
```
import plotly.express as px
pxFig = px.line(x=[0,1,2,3],y=[[10,11,12,13],[12,13,14,15]], labels=dict(x='xLabel', y='yLabel'), title='my Title')
pxFig.show()
```
-------------------------------
Attached image
![plotly_bug_expressMode_multipleYvalues](https://github.com/plotly/plotly.py/assets/153299265/e63adf25-6da0-4787-bbe2-904729fa26c4)

**Comment by Coding-with-Adam** [comment] 2023-12-14 15:24
hi @npcomplete2023 
Thanks for reporting. This does look like a bug.

**Comment by Mizba-Anjum** [comment] 2023-12-29 22:41
Hello, I tried tackling this problem in #4474 Let me know if this helps, since it's my first time contributing. The issue seemed like it was a string literal "value" in the express folder

**Comment by alexcjohnson** [comment] 2024-01-04 18:22
From @nicolaskruchten in #4474:

> In wide mode, the cross dimension is internally treated as if it was called `value` so this already works, in all orientations:
> 
> ```python
> import plotly.express as px
> df = px.data.medals_wide(indexed=True)
> px.bar(df, labels=dict(value="hey there"))
> px.bar(df, labels=dict(value="hey there"), orientation='h')
> ```
> 
> There's probably a discoverability problem but my recommendation would be to add to the docs rather than modify this somewhat complex code.

> There's already some mention of this in the docs here https://plotly.com/python/wide-form/#labeling-axes-legends-and-hover-text but things could always be made clearer :)

@npcomplete2023 @Mizba-Anjum does this solve the issue for you? If so, @LiamConnors let's see what we can do to better document this. I get the feeling that there are quite a few things PX can do that I haven't discovered myself! I'll also mention [this note](https://plotly.com/python/styling-plotly-express/#builtin-plotly-express-styling-arguments):

>  labels accepts a dict whose keys are the label to rename and whose values are the desired labels.

Which is indeed exactly what you need to do here: the automatically-provided label is `value` so `labels=dict(value='new thing')` replaces it.

**Comment by Mizba-Anjum** [comment] 2024-01-11 18:51
I can confirm that using "value" works for the y label in the original example
```
import plotly.express as px
pxFig = px.line(x=[0,1,2,3],y=[[10,11,12,13],[12,13,14,15]], labels=dict(x='xLabel', value='yLabel'), title='my Title')
pxFig.show()
```
![image](https://github.com/plotly/plotly.py/assets/89572205/5245ff4b-9057-4fc0-b556-e5908a535926)

In which case it's probably best not to change anything as it seems the actual 'y' value controls something else. I think the documentation does indeed describe it well enough though there is always room for improvement on that end. For now, I think this issue and my pull request should be closed.

**Comment by Coding-with-Adam** [comment] 2024-01-18 21:25
@LiamConnors  I'm closing this issue. Feel free to open if you think we need to update the docs.

**Closed by Coding-with-Adam** 2024-01-18 21:25 UTC
Labels: bug, sev-2
