### ISSUE TITLE
document limitations in mapbox plots

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#2165] opened 2020-02-05 18:50 UTC
as outlined here: https://github.com/plotly/plotly.js/issues/815#issue-169401326

for example, color isn't supported for all symbols. this is a point of a confusion for some community members - https://community.plot.ly/t/how-to-add-a-custom-symbol-image-inside-map/6641/6

**Comment by gvwilson** [comment] 2024-06-14 13:08
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:08 UTC
