### ISSUE TITLE
Update JupyterLab compatibility of jlab chart editor

### ISSUE THREAD

**Issue by sursu** [plotly/plotly.py#1845] opened 2019-10-23 01:27 UTC
Hi, 

Could you please update the `jupyterlab` requirements to accept version 1.1.4?
With the latest version of JupyterLab, when I run:
`jupyter labextension install jupyterlab-chart-editor@1.2 --no-build`
I get:
```
An error occured.
ValueError: 
"jupyterlab-chart-editor@1.2.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLabExtension        Package
>=16.8.4 <16.9.0>=16.4.0 <16.5.0 react
>=16.8.4 <16.9.0>=16.4.0 <16.5.0 react-dom
See the log file for details:  /tmp/jupyterlab-debug-zmsa39zn.log
```

I have encountered some issues with earlier versions of JupyterLab and Plotly 4.2.1.
When I try to make an interactive plot with `FigureWidget`, it plots the stationary traces, but not the ones I'm changing.
And the teminal says:
```
[IPKernelApp] WARNING | No such comm: 720232a3fbaa4941a56c61f2ba6a1b3d
[IPKernelApp] WARNING | No such comm: 720232a3fbaa4941a56c61f2ba6a1b3d
[IPKernelApp] WARNING | No such comm: 720232a3fbaa4941a56c61f2ba6a1b3d
[IPKernelApp] WARNING | No such comm: 720232a3fbaa4941a56c61f2ba6a1b3d
[IPKernelApp] WARNING | No such comm: 720232a3fbaa4941a56c61f2ba6a1b3d
[IPKernelApp] WARNING | No such comm: 720232a3fbaa4941a56c61f2ba6a1b3d
[IPKernelApp] WARNING | No such comm: 720232a3fbaa4941a56c61f2ba6a1b3d
[IPKernelApp] WARNING | No such comm: 720232a3fbaa4941a56c61f2ba6a1b3d
[IPKernelApp] WARNING | No such comm: 720232a3fbaa4941a56c61f2ba6a1b3d
```

**Comment by sursu** [comment] 2019-11-14 16:49
Seems to have been done with the latest release (v. 4.3.0). Right?

**Comment by nicolaskruchten** [comment] 2019-11-14 19:07
No, this still isn't done.

**Comment by gvwilson** [comment] 2024-06-14 13:12
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:12 UTC
