### ISSUE TITLE
px.waterfall, px.ohlc, px.candlestick

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2145] opened 2020-01-30 14:42 UTC
The common thread between these is that they'll need a `color_increasing_sequence` and a `color_decreasing_sequence` i think

**Comment by gvwilson** [comment] 2024-06-14 13:04
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:04 UTC
