### ISSUE TITLE
Restyle colorscale with buttons

### ISSUE THREAD

**Issue by CarlAndersson** [plotly/plotly.py#2170] opened 2020-02-07 15:37 UTC
Using custom buttons to change the colorscale of a mesh trace does not behave as expected.
First, if I try to use a custom button to restyle the colorscale of a mesh using a scale existing in the python api but (I assume) not in the Javascript library, it will use some default colorscale instead.
<details>
<summary>Show code</summary>

```
import plotly

data = dict(
    type='mesh3d',
    x=[0, 1, 2, 0],
    y=[0, 0, 1, 2],
    z=[0, 2, 0, 1],
    i=[0, 0, 0, 1],
    j=[1, 2, 3, 2],
    k=[2, 3, 1, 3],
    intensity=[-1, -0.5, 0.5, 1],
    colorscale='Phase',
)

button_1 = dict(
    method='restyle', label='Change colorscale',
    args=['colorscale', 'Phase']
)

layout = {'updatemenus': [{
    'type': 'buttons', 'buttons': [button_1],
}]}

plotly.graph_objects.Figure(data, layout).show('browser')
```
</details>

<details>
<summary>Show figure output</summary>
Before clicking the button:
<img width="756" alt="Screen Shot 2020-02-07 at 16 20 57" src="https://user-images.githubusercontent.com/20397548/74041698-7136f200-49c6-11ea-88d1-19bb4562da91.png">
After clicking the button:
<img width="756" alt="Screen Shot 2020-02-07 at 16 21 13" src="https://user-images.githubusercontent.com/20397548/74041713-798f2d00-49c6-11ea-9809-360e7e0e185d.png">
</details>

The second issue I found while trying to work around this is that in order to supply a custom colorscale I need to convert it to a string and replace all `'` with `"`. This does not seem reasonable to expect the users to do.

<details>
<summary>Show code</summary>

```
import plotly

my_scale = [
    [0, 'rgb(0, 255, 0)'],
    [1, 'rgb(255, 0, 0)'],
]

data = dict(
    type='mesh3d',
    x=[0, 1, 2, 0],
    y=[0, 0, 1, 2],
    z=[0, 2, 0, 1],
    i=[0, 0, 0, 1],
    j=[1, 2, 3, 2],
    k=[2, 3, 1, 3],
    intensity=[-1, -0.5, 0.5, 1],
    colorscale=my_scale,
)

button_1 = dict(
    method='restyle', label='As list',
    args=['colorscale', my_scale]
)
button_2 = dict(
    method='restyle', label='As string',
    args=['colorscale', str(my_scale)]
)
button_3 = dict(
    method='restyle', label='As string with double qutes',
    args=['colorscale', str(my_scale).replace("'", '"')]
)

layout = {'updatemenus': [{
    'type': 'buttons', 'buttons': [button_1, button_2, button_3],
}]}
plotly.graph_objects.Figure(data, layout).show('browser')
```
</details>

<details>
<summary>Show figure output</summary>
Initial:
<img width="778" alt="Screen Shot 2020-02-07 at 16 21 46" src="https://user-images.githubusercontent.com/20397548/74042106-36818980-49c7-11ea-9e73-ea4144158da2.png">
First button:
<img width="778" alt="Screen Shot 2020-02-07 at 16 21 56" src="https://user-images.githubusercontent.com/20397548/74042133-40a38800-49c7-11ea-973a-d7149d984cb5.png">
Second button:
<img width="778" alt="Screen Shot 2020-02-07 at 16 22 09" src="https://user-images.githubusercontent.com/20397548/74042155-48632c80-49c7-11ea-89ba-5eb048a35cec.png">
Third button:
<img width="778" alt="Screen Shot 2020-02-07 at 16 22 19" src="https://user-images.githubusercontent.com/20397548/74042167-5022d100-49c7-11ea-88f6-6bad9558e3d6.png">

</details>

The ideal behavior would, imho, to be able to supply any of the colorscales available in the python api, but I can imagine that this would require quite elaborate solutions. At minimum there should be some mention of this limitation in the documentation.

As for the workaround with string quotes, I would like to see this fixed so that it is possible to just pass a list.

**Comment by emmanuelle** [comment] 2020-02-10 20:06
Hi @CarlAndersson thanks for the report, this is clearly suboptimal. For the single/double quotes this seems to be a problem with the validators which we are using before passing code to Javascript. 

In the meantime, please note that you can make use of utility functions in `plotly.colors`, for example
```
button_1 = dict(
    method='restyle', label='Change colorscale',
    args=['colorscale', str(plotly.colors.make_colorscale(plotly.colors.cyclical.Phase)).replace("'", '"')]
)
```

**Comment by yves-surrel** [comment] 2020-03-07 09:04
Thanks to the CarlAndersson's simple quote/double quote replacement, I could solve the same problem for me. It seems that the syntax of the `args=["colorscale", ...]` is very strict. This should be stated in the doc.

**Comment by gvwilson** [comment] 2024-06-14 13:06
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:06 UTC
