### ISSUE TITLE
Plotly templates do not include the titlefont attibute

### ISSUE THREAD

**Issue by hlgirard** [plotly/plotly.py#1465] opened 2019-03-14 19:49 UTC
When I create a template with `plotly.io.to_templated()`, the `titlefont` attribute is excluded from the template.
Here is a minimal example creating a simple template with the `titlefont` and `zeroline` attributes:

```python
import plotly.graph_objs as go
import plotly.io as pio

# Layout
layout = go.Layout(
        xaxis=dict(titlefont=dict(size=18), zeroline=False),
        yaxis=dict(titlefont=dict(size=18), zeroline=False),
        width=550,
        height=500,
    )

# Figure
fig = go.Figure(data=None, layout=layout)

# Create template
template = pio.to_templated(fig)
```

The resulting `template.layout` object strips the `titlefont` from the template part and puts it in the rest of the layout:

```
Layout({
    'template': {'layout': {'height': 500, 'width': 550, 'xaxis': {'zeroline': False}, 'yaxis': {'zeroline': False}}},
    'xaxis': {'title': {'font': {'size': 18}}},
    'yaxis': {'title': {'font': {'size': 18}}}
})
```

When this template is further applied to a figure, only the contents of `template` are transferred and the titlefont is ignored.

**Comment by gvwilson** [comment] 2024-06-13 19:25
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:25 UTC
Labels: bug
