### ISSUE TITLE
Minute to Minute Data Is Not Visibly Seen On Gantt Chart 

### ISSUE THREAD

**Issue by shreyastalamakki** [plotly/plotly.py#1449] opened 2019-03-05 00:01 UTC
![dash_question](https://user-images.githubusercontent.com/41263573/53771130-5bf04400-3e96-11e9-962c-b77ef0205c57.png)

Even though I have the data loaded as a list of dictionaries with {Task = 'John', Start = '2019-02-26 06:30', End = '2019-02-26 06:45', Resource = 'Pick'} the points aren't showing up on the gantt chart. If I zoom closely, I see a super minuscule point which I can't even zoom into all the way after doing several lasso-style rectangular time filters in the gantt chart.
The chart is created as follows:

`fig =  ff.create_gantt(graph_employee_data, colors=colors, index_col='Resource', title='', group_tasks=True,
                      show_colorbar=True, bar_width=10, height=500, width=1500, showgrid_x=True, showgrid_y=True)`

**Comment by jonmmease** [comment] 2019-03-07 11:47
Hi @shreyastalamakki, thanks for the report. Please add a fully reproducible example (with imports, data definition, plot display code) and the version of plotly.py that you are using.  Thanks!

**Comment by gvwilson** [comment] 2024-06-13 19:25
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:25 UTC
Labels: question
