### ISSUE TITLE
PX support for the new mapbox trace types

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1780] opened 2019-09-18 19:22 UTC
Placeholder issue, to be fleshed out.

We'll want some nice `geopandas` integration here eventually too.

See also https://github.com/plotly/plotly_express/issues/29

**Comment by martinfleis** [comment] 2019-10-17 19:57
Hi @nicolaskruchten,
if you'll need some assistance from geopandas side let me know.

**Comment by nicolaskruchten** [comment] 2019-10-18 00:16
Thanks @martinfleis ! Mostly at this point I think we're ready to think about how the `px.scatter_mapbox()` and `px.line_mapbox()` APIs can be modified to take advantage of GeoPandas, and then we'll really want to integrate for when we add `choropleth_mapbox` :) Ideas welcome!

**Comment by gvwilson** [comment] 2024-06-13 19:50
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:50 UTC
