### ISSUE TITLE
fig.append_trace() raises ValueError if row arg is not type int.

### ISSUE THREAD

**Issue by mark-datanaltek** [plotly/plotly.py#2391] opened 2020-04-16 22:02 UTC
fig.append_trace() raises ValueError if the row arg is not type int, even if arg is int-like:
DEBUG row:1, type(row):<class 'numpy.int64'>

If I explicitly cast to int with row=int(row), all is well.  The issue may be due to the isinstance check at line 1536 of basedatatypes.py?

/usr/local/lib/python3.7/site-packages/plotly/basedatatypes.py in _validate_rows_cols(name, n, vals)
   1535 
   1536             if [r for r in vals if not isinstance(r, int)]:
-> 1537                 BaseFigure._raise_invalid_rows_cols(name=name, n=n, invalid=vals)
   1538         else:
   1539             BaseFigure._raise_invalid_rows_cols(name=name, n=n, invalid=vals)

/usr/local/lib/python3.7/site-packages/plotly/basedatatypes.py in _raise_invalid_rows_cols(name, n, invalid)
   1524         )
   1525 
-> 1526         raise ValueError(rows_err_msg)
   1527 
   1528     @staticmethod

ValueError: 
        If specified, the rows parameter must be a list or tuple of integers
        of length 1 (The number of traces being added)

        Received: [1]

I am working with the latest version:
>>> import plotly
>>> plotly.__version__
'4.6.0'
>>>

**Comment by emmanuelle** [comment] 2020-05-01 21:27
Thank you @mark-datanaltek this is indeed a bug. To reproduce
```
import numpy as np
import plotly.graph_objects as go
indices_rows = np.array([0], dtype=np.int)
indices_cols = np.array([0], dtype=np.int)
fig = go.Figure()
fig.add_trace(go.Scatter(y=[1]), row=indices_rows[0], col=indices_cols[0])
fig.show()
```

**Comment by emmanuelle** [comment] 2020-05-01 21:42
This could be easily fixed by modifying slightly this line of code https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/basedatatypes.py#L1531
Since numpy is not a dependency we would have to check whether numpy is imported
```
try:
    import numpy as np
    int_type = (int, np.integer)
except ImportError:
    int_type = (int,)
....
if [r for r in vals if not isinstance(r, int_type)]:
....
```

**Comment by MCBoarder289** [comment] 2020-05-07 21:05
Thanks @emmanuelle  for tagging this as a good first issue. I'll see if I can give it a try here!

**Comment by MCBoarder289** [comment] 2020-05-07 22:20
Ran into an exception with the reproducing example once I got this working:
```
Exception: In order to reference traces by row and column, you must first use plotly.tools.make_subplots to create the figure with a subplot grid.
```

Here is one that works with a fix in place. Seeing if I can write this into a test before creating a pull request:

```
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
indices_rows = np.array([1], dtype=np.int)
indices_cols = np.array([1], dtype=np.int)
fig = make_subplots(rows=1, cols=1)
fig.add_trace(go.Scatter(y=[1]), row=indices_rows[0], col=indices_cols[0])
```

**Comment by MCBoarder289** [comment] 2020-05-08 12:42
I have put a pull request up here: https://github.com/plotly/plotly.py/pull/2451
Open to any feedback on this!

**Comment by MCBoarder289** [comment] 2020-06-03 19:08
@emmanuelle Thanks for the review! Should we link #2451 now that's been approved and merged for this ticket? I wasn't sure how to do that when I made the PR.

**Closed** 2020-06-04 15:58 UTC
Labels: bug, good first issue
