### ISSUE TITLE
Not getting the labels while creating the Grouped Bar Chart with Direct Labels using python

### ISSUE THREAD

**Issue by Pseud0n1nja** [plotly/plotly.py#1466] opened 2019-03-15 15:12 UTC
Even upon properly identifying the text for trace, labels are not getting imputed. Even the code provided under the "Grouped Bar Chart with Direct Labels" is neither resulting the labels nor throwing any error.

**Comment by jonmmease** [comment] 2019-03-15 21:39
Hi @Pseud0n1nja, could you please add a reproducible example that demonstrates the behavior you're seeing?  Or if it's something you see in one of the examples in the documentation please add the link to the documentation page.  Thanks!

**Comment by Pseud0n1nja** [comment] 2019-03-17 11:18
I even tried the template code given in the [documentation/tutorial](https://plot.ly/python/bar-charts/), that is also not displaying the labels


x = ['Product A', 'Product B', 'Product C']
y = [20, 14, 23]
y2 = [16,12,27]

trace1 = go.Bar(
    x=x,
    y=y,
    text=y,
    textposition = 'auto',
    marker=dict(
        color='rgb(158,202,225)',
        line=dict(
            color='rgb(8,48,107)',
            width=1.5),
        ),
    opacity=0.6
)

trace2 = go.Bar(
    x=x,
    y=y2,
    text=y2,
    textposition = 'auto',
    marker=dict(
        color='rgb(58,200,225)',
        line=dict(
            color='rgb(8,48,107)',
            width=1.5),
        ),
    opacity=0.6
)

data = [trace1,trace2]

py.iplot(data, filename='grouped-bar-direct-labels')

**Comment by jonmmease** [comment] 2019-03-25 22:51
Hi @Pseud0n1nja, could you place your code inside a fenced code block (See https://help.github.com/en/articles/creating-and-highlighting-code-blocks) so that it's possible to copy and paste to reproduce it. Thanks!

When I try the example from https://plot.ly/python/bar-charts/#grouped-bar-chart-with-direct-labels, here's what I see.

```python
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode()

trace1 = go.Bar(
    x=['giraffes', 'orangutans', 'monkeys'],
    y=[20, 14, 23],
    name='SF Zoo'
)
trace2 = go.Bar(
    x=['giraffes', 'orangutans', 'monkeys'],
    y=[12, 18, 29],
    name='LA Zoo'
)

data = [trace1, trace2]
layout = go.Layout(
    barmode='group'
)

fig = go.Figure(data=data, layout=layout)
iplot(fig)
```
![newplot](https://user-images.githubusercontent.com/15064365/54959295-f93b1700-4f2e-11e9-94f1-9cf6d6ffbed8.png)

This result looks correct to me, are you seeing something different?

**Comment by gvwilson** [comment] 2024-06-13 19:25
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:25 UTC
Labels: question
