### ISSUE TITLE
.pop()

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1479] opened 2019-03-26 13:54 UTC
Just to make things feel a bit more `dict`-like, everywhere we accept `.update(key=None)` we should also accept `.pop("key")`.

**Comment by chriddyp** [comment] 2019-03-26 14:25
Looking at mutable mapping (https://docs.python.org/3/library/collections.abc.html) folks might also expect 
- `popitem`
- `clear`
- `keys`
- `items`
- `values`
- `setdefault`

but I think that `pop` is probably the most common of these.

**Comment by StevenAllenKing** [comment] 2021-03-15 15:55
This dict-like `.pop("key")` seems to work on basic examples such as the below

```
import plotly.graph_objects as go

dict_of_fig = dict({
    "data": [{"type": "bar",
              "x": [1, 2, 3],
              "y": [1, 3, 2]}],
    "layout": {"title": {"text": "A Figure Specified By A Graph Object With A Dictionary"}}
})

fig = go.Figure(dict_of_fig)

fig.pop(data)

fig.show()
```

This pops the data and then shows an empty bar chart.

Was this issue resolved?

**Comment by nicolaskruchten** [comment] 2021-03-15 19:31
Some/most of the collections methods work in some/most places, but I don't think we converged on a real policy here and therefore left this issue open.

**Comment by gvwilson** [comment] 2024-06-13 19:26
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:26 UTC
Labels: enhancement
