### ISSUE TITLE
Invalid property for indicator.Gauge: steps 

### ISSUE THREAD

**Issue by Mahdis-z** [plotly/plotly.py#1713] opened 2019-08-07 20:11 UTC
Apparently there is a typo (stepss instead of steps). "stepss" is in the list of valid attributes.
```
import plotly.graph_objects as go

fig = go.Figure(data = go.Indicator(mode = "number+gauge+delta", value = 180, 
delta = {'reference': 200}, domain = {'x': [0.25, 1], 'y': [0.08, 0.25]},
title = {'text': "Revenue"}, gauge = {'shape': "bullet", 'axis': {'range': [None, 300]},
'threshold': {'line': {'color': "black", 'width': 2}, 'thickness': 0.75, 'value': 170}, 
'steps': [{'range': [0, 150], 'color': "gray"}, {'range': [150, 250],
'color': "lightgray"}], 'bar': {'color': "black"}}))

fig.update_layout(width = 300, height = 300, margin = {'t': 0, 'b':0, "l":0, "r":0})
fig.show()
```
and the error is:
 ValueError: Invalid property specified for object of type plotly.graph_objs.indicator.Gauge: 'steps'

**Comment by nicolaskruchten** [comment] 2019-08-08 18:35
Will be fixed in the next JS release: https://github.com/plotly/plotly.js/pull/4115

**Comment by gvwilson** [comment] 2024-06-13 19:45
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:45 UTC
