### ISSUE TITLE
Slow import time with python3.7

### ISSUE THREAD

**Issue by 0xbentang** [plotly/plotly.py#1783] opened 2019-09-22 04:13 UTC
OS: ubuntu 18.04
plotly version: 4.1.1 
python3.6 version: 3.6.8
python3.7 version: 3.7.3

``````
time python3.6 -c "import plotly"

real    0m0.438s
user    0m0.354s
sys     0m0.083s

``````

``````
time python3.7 -c "import plotly"

real    0m11.038s
user    0m0.410s
sys     0m0.078s
``````

Looks like it is related to plotly.io._renderers?

``````
python3.7 -X importtime -c "import plotly"

import time: self [us] | cumulative | imported package
import time:       144 |        144 | zipimport
import time:       735 |        735 | _frozen_importlib_external
import time:        84 |         84 |     _codecs
import time:       897 |        981 |   codecs
import time:       688 |        688 |   encodings.aliases
import time:      1183 |       2851 | encodings
import time:       311 |        311 | encodings.utf_8
import time:       217 |        217 | _signal
import time:       451 |        451 | encodings.latin_1
import time:        66 |         66 |     _abc
import time:       475 |        541 |   abc
import time:       498 |       1038 | io
import time:       158 |        158 |       _stat
import time:       363 |        521 |     stat
import time:       248 |        248 |       genericpath
import time:       434 |        682 |     posixpath
import time:      1497 |       1497 |     _collections_abc
import time:      1085 |       3783 |   os
import time:       301 |        301 |   _sitebuiltins
import time:       109 |        109 |     _locale
import time:       351 |        460 |   _bootlocale
import time:       433 |        433 |   types
import time:       334 |        334 |       warnings
import time:       343 |        676 |     importlib
import time:       193 |        193 |       importlib.machinery
import time:       862 |       1054 |     importlib.abc
import time:       115 |        115 |           _operator
import time:      1183 |       1298 |         operator
import time:       220 |        220 |         keyword
import time:        74 |         74 |           _heapq
import time:       330 |        404 |         heapq
import time:       189 |        189 |         itertools
import time:       297 |        297 |         reprlib
import time:       115 |        115 |         _collections
import time:      1749 |       4269 |       collections
import time:       110 |        110 |         _functools
import time:       916 |       1025 |       functools
import time:      1080 |       6373 |     contextlib
import time:       828 |       8930 |   importlib.util
import time:      2860 |       2860 |     apport_python_hook
import time:       491 |       3350 |   sitecustomize
import time:       148 |        148 |   usercustomize
import time:      2580 |      19982 | site
import time:       247 |        247 |   __future__
import time:      1018 |       1018 |         enum
import time:       154 |        154 |           _sre
import time:       515 |        515 |             sre_constants
import time:       797 |       1311 |           sre_parse
import time:       795 |       2259 |         sre_compile
import time:       261 |        261 |         copyreg
import time:      1431 |       4967 |       re
import time:       148 |        148 |           _struct
import time:       529 |        677 |         struct
import time:      8182 |       8858 |       six
import time:       366 |        366 |           _weakrefset
import time:       659 |       1025 |         weakref
import time:       167 |        167 |             org
import time:       109 |        276 |           org.python
import time:       103 |        378 |         org.python.core
import time:       525 |       1927 |       copy
import time:       248 |        248 |         _plotly_utils
import time:       772 |        772 |             numbers
import time:       376 |        376 |             collections.abc
import time:      1607 |       2755 |           _decimal
import time:       390 |       3144 |         decimal
import time:       255 |        255 |               _json
import time:       797 |       1051 |             json.scanner
import time:       746 |       1796 |           json.decoder
import time:       711 |        711 |           json.encoder
import time:       569 |       3076 |         json
import time:       237 |        237 |             time
import time:       257 |        257 |                   token
import time:      1518 |       1775 |                 tokenize
import time:       399 |       2174 |               linecache
import time:       665 |       2839 |             traceback
import time:        62 |         62 |               _string
import time:      1864 |       1926 |             string
import time:       793 |        793 |             threading
import time:        68 |         68 |             atexit
import time:      2102 |       7962 |           logging
import time:       350 |       8312 |         _plotly_utils.optional_imports
import time:       805 |      15582 |       _plotly_utils.utils
import time:       762 |        762 |       plotly.subplots
import time:       190 |        190 |       plotly.optional_imports
import time:       112 |        112 |           binascii
import time:       451 |        563 |         base64
import time:      1795 |       1795 |         textwrap
import time:       173 |        173 |           _uuid
import time:       782 |        955 |         uuid
import time:      2338 |       5649 |       _plotly_utils.basevalidators
import time:       239 |        239 |       plotly.animation
import time:       393 |        393 |           pprint
import time:       481 |        873 |         plotly.utils
import time:       518 |       1391 |       plotly.callbacks
import time:      2123 |       2123 |       plotly.validators
import time:      2919 |      44603 |     plotly.basedatatypes
import time:       476 |        476 |         plotly.graph_objs.waterfall.totals.marker
import time:       650 |       1126 |       plotly.graph_objs.waterfall.totals
import time:       310 |        310 |         plotly.graph_objs.waterfall.increasing.marker
import time:       500 |        809 |       plotly.graph_objs.waterfall.increasing
import time:       310 |        310 |       plotly.graph_objs.waterfall.hoverlabel
import time:       297 |        297 |         plotly.graph_objs.waterfall.decreasing.marker
import time:       512 |        809 |       plotly.graph_objs.waterfall.decreasing
import time:       263 |        263 |       plotly.graph_objs.waterfall.connector
import time:      1838 |       5153 |     plotly.graph_objs.waterfall
import time:       487 |        487 |       plotly.graph_objs.volume.slices
import time:       269 |        269 |       plotly.graph_objs.volume.hoverlabel
import time:       303 |        303 |         plotly.graph_objs.volume.colorbar.title
import time:       662 |        964 |       plotly.graph_objs.volume.colorbar
import time:       326 |        326 |       plotly.graph_objs.volume.caps
import time:      1699 |       3743 |     plotly.graph_objs.volume
import time:       410 |        410 |       plotly.graph_objs.violin.unselected
import time:       370 |        370 |       plotly.graph_objs.violin.selected
import time:       268 |        268 |       plotly.graph_objs.violin.marker
import time:       323 |        323 |       plotly.graph_objs.violin.hoverlabel
import time:       270 |        270 |       plotly.graph_objs.violin.box
import time:      1435 |       3073 |     plotly.graph_objs.violin
import time:       492 |        492 |       plotly.graph_objs.table.hoverlabel
import time:       535 |        535 |       plotly.graph_objs.table.header
import time:       369 |        369 |       plotly.graph_objs.table.cells
import time:      1386 |       2781 |     plotly.graph_objs.table
import time:       355 |        355 |       plotly.graph_objs.surface.hoverlabel
import time:       337 |        337 |         plotly.graph_objs.surface.contours.z
import time:       353 |        353 |         plotly.graph_objs.surface.contours.y
import time:       270 |        270 |         plotly.graph_objs.surface.contours.x
import time:       821 |       1780 |       plotly.graph_objs.surface.contours
import time:       320 |        320 |         plotly.graph_objs.surface.colorbar.title
import time:       562 |        881 |       plotly.graph_objs.surface.colorbar
import time:      1245 |       4260 |     plotly.graph_objs.surface
import time:       426 |        426 |       plotly.graph_objs.sunburst.marker
import time:       282 |        282 |       plotly.graph_objs.sunburst.hoverlabel
import time:       977 |       1685 |     plotly.graph_objs.sunburst
import time:       352 |        352 |       plotly.graph_objs.streamtube.hoverlabel
import time:       300 |        300 |         plotly.graph_objs.streamtube.colorbar.title
import time:       504 |        803 |       plotly.graph_objs.streamtube.colorbar
import time:      1912 |       3066 |     plotly.graph_objs.streamtube
import time:       397 |        397 |       plotly.graph_objs.splom.unselected
import time:       273 |        273 |       plotly.graph_objs.splom.selected
import time:       360 |        360 |           plotly.graph_objs.splom.marker.colorbar.title
import time:       600 |        960 |         plotly.graph_objs.splom.marker.colorbar
import time:       792 |       1751 |       plotly.graph_objs.splom.marker
import time:       524 |        524 |       plotly.graph_objs.splom.hoverlabel
import time:       412 |        412 |       plotly.graph_objs.splom.dimension
import time:      1679 |       5035 |     plotly.graph_objs.splom
import time:       504 |        504 |       plotly.graph_objs.scatterternary.unselected
import time:       449 |        449 |       plotly.graph_objs.scatterternary.selected
import time:       424 |        424 |           plotly.graph_objs.scatterternary.marker.colorbar.title
import time:       809 |       1232 |         plotly.graph_objs.scatterternary.marker.colorbar
import time:       997 |       2228 |       plotly.graph_objs.scatterternary.marker
import time:       322 |        322 |       plotly.graph_objs.scatterternary.hoverlabel
import time:      1717 |       5218 |     plotly.graph_objs.scatterternary
import time:       406 |        406 |       plotly.graph_objs.scatterpolargl.unselected
import time:       319 |        319 |       plotly.graph_objs.scatterpolargl.selected
import time:       296 |        296 |           plotly.graph_objs.scatterpolargl.marker.colorbar.title
import time:       625 |        921 |         plotly.graph_objs.scatterpolargl.marker.colorbar
import time:       866 |       1786 |       plotly.graph_objs.scatterpolargl.marker
import time:       270 |        270 |       plotly.graph_objs.scatterpolargl.hoverlabel
import time:      1415 |       4194 |     plotly.graph_objs.scatterpolargl
import time:       490 |        490 |       plotly.graph_objs.scatterpolar.unselected
import time:       326 |        326 |       plotly.graph_objs.scatterpolar.selected
import time:       298 |        298 |           plotly.graph_objs.scatterpolar.marker.colorbar.title
import time:       581 |        879 |         plotly.graph_objs.scatterpolar.marker.colorbar
import time:       827 |       1705 |       plotly.graph_objs.scatterpolar.marker
import time:       285 |        285 |       plotly.graph_objs.scatterpolar.hoverlabel
import time:      1454 |       4258 |     plotly.graph_objs.scatterpolar
import time:       333 |        333 |       plotly.graph_objs.scattermapbox.unselected
import time:       271 |        271 |       plotly.graph_objs.scattermapbox.selected
import time:       318 |        318 |           plotly.graph_objs.scattermapbox.marker.colorbar.title
import time:       653 |        971 |         plotly.graph_objs.scattermapbox.marker.colorbar
import time:       587 |       1557 |       plotly.graph_objs.scattermapbox.marker
import time:       287 |        287 |       plotly.graph_objs.scattermapbox.hoverlabel
import time:      1463 |       3908 |     plotly.graph_objs.scattermapbox
import time:       394 |        394 |       plotly.graph_objs.scattergl.unselected
import time:       297 |        297 |       plotly.graph_objs.scattergl.selected
import time:       316 |        316 |           plotly.graph_objs.scattergl.marker.colorbar.title
import time:       852 |       1168 |         plotly.graph_objs.scattergl.marker.colorbar
import time:      1806 |       2973 |       plotly.graph_objs.scattergl.marker
import time:       403 |        403 |       plotly.graph_objs.scattergl.hoverlabel
import time:      2004 |       6068 |     plotly.graph_objs.scattergl
import time:       465 |        465 |       plotly.graph_objs.scattergeo.unselected
import time:       332 |        332 |       plotly.graph_objs.scattergeo.selected
import time:       366 |        366 |           plotly.graph_objs.scattergeo.marker.colorbar.title
import time:       759 |       1125 |         plotly.graph_objs.scattergeo.marker.colorbar
import time:      1004 |       2129 |       plotly.graph_objs.scattergeo.marker
import time:       302 |        302 |       plotly.graph_objs.scattergeo.hoverlabel
import time:      1773 |       5000 |     plotly.graph_objs.scattergeo
import time:       331 |        331 |       plotly.graph_objs.scattercarpet.unselected
import time:       290 |        290 |       plotly.graph_objs.scattercarpet.selected
import time:       319 |        319 |           plotly.graph_objs.scattercarpet.marker.colorbar.title
import time:       635 |        954 |         plotly.graph_objs.scattercarpet.marker.colorbar
import time:       975 |       1928 |       plotly.graph_objs.scattercarpet.marker
import time:       284 |        284 |       plotly.graph_objs.scattercarpet.hoverlabel
import time:      1494 |       4325 |     plotly.graph_objs.scattercarpet
import time:       504 |        504 |       plotly.graph_objs.scatter3d.projection
import time:       326 |        326 |           plotly.graph_objs.scatter3d.marker.colorbar.title
import time:       614 |        940 |         plotly.graph_objs.scatter3d.marker.colorbar
import time:       748 |       1687 |       plotly.graph_objs.scatter3d.marker
import time:       314 |        314 |           plotly.graph_objs.scatter3d.line.colorbar.title
import time:       778 |       1091 |         plotly.graph_objs.scatter3d.line.colorbar
import time:       724 |       1815 |       plotly.graph_objs.scatter3d.line
import time:       294 |        294 |       plotly.graph_objs.scatter3d.hoverlabel
import time:      1988 |       6285 |     plotly.graph_objs.scatter3d
import time:       365 |        365 |       plotly.graph_objs.scatter.unselected
import time:       297 |        297 |       plotly.graph_objs.scatter.selected
import time:       357 |        357 |           plotly.graph_objs.scatter.marker.colorbar.title
import time:       821 |       1177 |         plotly.graph_objs.scatter.marker.colorbar
import time:       937 |       2113 |       plotly.graph_objs.scatter.marker
import time:       267 |        267 |       plotly.graph_objs.scatter.hoverlabel
import time:      1964 |       5004 |     plotly.graph_objs.scatter
import time:       383 |        383 |         plotly.graph_objs.sankey.node.hoverlabel
import time:       696 |       1078 |       plotly.graph_objs.sankey.node
import time:       305 |        305 |         plotly.graph_objs.sankey.link.hoverlabel
import time:       629 |        933 |       plotly.graph_objs.sankey.link
import time:       275 |        275 |       plotly.graph_objs.sankey.hoverlabel
import time:      1233 |       3518 |     plotly.graph_objs.sankey
import time:       342 |        342 |       plotly.graph_objs.pointcloud.marker
import time:       297 |        297 |       plotly.graph_objs.pointcloud.hoverlabel
import time:      1579 |       2218 |     plotly.graph_objs.pointcloud
import time:       386 |        386 |       plotly.graph_objs.pie.title
import time:       329 |        329 |       plotly.graph_objs.pie.marker
import time:       254 |        254 |       plotly.graph_objs.pie.hoverlabel
import time:      1250 |       2218 |     plotly.graph_objs.pie
import time:       349 |        349 |           plotly.graph_objs.parcoords.line.colorbar.title
import time:       664 |       1012 |         plotly.graph_objs.parcoords.line.colorbar
import time:       904 |       1915 |       plotly.graph_objs.parcoords.line
import time:       953 |       2868 |     plotly.graph_objs.parcoords
import time:       407 |        407 |           plotly.graph_objs.parcats.line.colorbar.title
import time:       742 |       1148 |         plotly.graph_objs.parcats.line.colorbar
import time:       849 |       1996 |       plotly.graph_objs.parcats.line
import time:       906 |       2902 |     plotly.graph_objs.parcats
import time:       433 |        433 |       plotly.graph_objs.ohlc.increasing
import time:       275 |        275 |       plotly.graph_objs.ohlc.hoverlabel
import time:       336 |        336 |       plotly.graph_objs.ohlc.decreasing
import time:      1053 |       2096 |     plotly.graph_objs.ohlc
import time:       380 |        380 |       plotly.graph_objs.mesh3d.hoverlabel
import time:       468 |        468 |         plotly.graph_objs.mesh3d.colorbar.title
import time:       629 |       1097 |       plotly.graph_objs.mesh3d.colorbar
import time:      1346 |       2823 |     plotly.graph_objs.mesh3d
import time:       576 |        576 |       plotly.graph_objs.isosurface.slices
import time:       307 |        307 |       plotly.graph_objs.isosurface.hoverlabel
import time:       325 |        325 |         plotly.graph_objs.isosurface.colorbar.title
import time:       565 |        890 |       plotly.graph_objs.isosurface.colorbar
import time:       333 |        333 |       plotly.graph_objs.isosurface.caps
import time:      1814 |       3919 |     plotly.graph_objs.isosurface
import time:       350 |        350 |       plotly.graph_objs.indicator.title
import time:       256 |        256 |       plotly.graph_objs.indicator.number
import time:       305 |        305 |         plotly.graph_objs.indicator.gauge.threshold
import time:       264 |        264 |         plotly.graph_objs.indicator.gauge.step
import time:       249 |        249 |         plotly.graph_objs.indicator.gauge.bar
import time:       344 |        344 |         plotly.graph_objs.indicator.gauge.axis
import time:      1500 |       2660 |       plotly.graph_objs.indicator.gauge
import time:       407 |        407 |       plotly.graph_objs.indicator.delta
import time:      1628 |       5299 |     plotly.graph_objs.indicator
import time:       367 |        367 |       plotly.graph_objs.histogram2dcontour.hoverlabel
import time:       331 |        331 |       plotly.graph_objs.histogram2dcontour.contours
import time:       336 |        336 |         plotly.graph_objs.histogram2dcontour.colorbar.title
import time:       625 |        961 |       plotly.graph_objs.histogram2dcontour.colorbar
import time:      1569 |       3226 |     plotly.graph_objs.histogram2dcontour
import time:      1244 |       1244 |       plotly.graph_objs.histogram2d.hoverlabel
import time:       397 |        397 |         plotly.graph_objs.histogram2d.colorbar.title
import time:       460 |        856 |       plotly.graph_objs.histogram2d.colorbar
import time:      1076 |       3176 |     plotly.graph_objs.histogram2d
import time:       352 |        352 |       plotly.graph_objs.histogram.unselected
import time:       536 |        536 |       plotly.graph_objs.histogram.selected
import time:       412 |        412 |           plotly.graph_objs.histogram.marker.colorbar.title
import time:       481 |        893 |         plotly.graph_objs.histogram.marker.colorbar
import time:      1112 |       2005 |       plotly.graph_objs.histogram.marker
import time:       384 |        384 |       plotly.graph_objs.histogram.hoverlabel
import time:      1450 |       4725 |     plotly.graph_objs.histogram
import time:       354 |        354 |       plotly.graph_objs.heatmapgl.hoverlabel
import time:       351 |        351 |         plotly.graph_objs.heatmapgl.colorbar.title
import time:       444 |        794 |       plotly.graph_objs.heatmapgl.colorbar
import time:      1229 |       2376 |     plotly.graph_objs.heatmapgl
import time:       346 |        346 |       plotly.graph_objs.heatmap.hoverlabel
import time:       325 |        325 |         plotly.graph_objs.heatmap.colorbar.title
import time:       567 |        891 |       plotly.graph_objs.heatmap.colorbar
import time:      1000 |       2235 |     plotly.graph_objs.heatmap
import time:       334 |        334 |       plotly.graph_objs.funnelarea.title
import time:       300 |        300 |       plotly.graph_objs.funnelarea.marker
import time:       265 |        265 |       plotly.graph_objs.funnelarea.hoverlabel
import time:      1292 |       2190 |     plotly.graph_objs.funnelarea
import time:       355 |        355 |           plotly.graph_objs.funnel.marker.colorbar.title
import time:       696 |       1050 |         plotly.graph_objs.funnel.marker.colorbar
import time:       825 |       1875 |       plotly.graph_objs.funnel.marker
import time:       274 |        274 |       plotly.graph_objs.funnel.hoverlabel
import time:       299 |        299 |       plotly.graph_objs.funnel.connector
import time:      1286 |       3733 |     plotly.graph_objs.funnel
import time:       331 |        331 |       plotly.graph_objs.densitymapbox.hoverlabel
import time:       341 |        341 |         plotly.graph_objs.densitymapbox.colorbar.title
import time:       590 |        931 |       plotly.graph_objs.densitymapbox.colorbar
import time:      1147 |       2407 |     plotly.graph_objs.densitymapbox
import time:       322 |        322 |       plotly.graph_objs.contourcarpet.hoverlabel
import time:       288 |        288 |       plotly.graph_objs.contourcarpet.contours
import time:       291 |        291 |         plotly.graph_objs.contourcarpet.colorbar.title
import time:       543 |        834 |       plotly.graph_objs.contourcarpet.colorbar
import time:      1355 |       2796 |     plotly.graph_objs.contourcarpet
import time:       319 |        319 |       plotly.graph_objs.contour.hoverlabel
import time:       275 |        275 |       plotly.graph_objs.contour.contours
import time:       320 |        320 |         plotly.graph_objs.contour.colorbar.title
import time:       687 |       1006 |       plotly.graph_objs.contour.colorbar
import time:      1468 |       3067 |     plotly.graph_objs.contour
import time:      1087 |       1087 |       plotly.graph_objs.cone.hoverlabel
import time:       351 |        351 |         plotly.graph_objs.cone.colorbar.title
import time:       546 |        896 |       plotly.graph_objs.cone.colorbar
import time:      1091 |       3073 |     plotly.graph_objs.cone
import time:       366 |        366 |       plotly.graph_objs.choroplethmapbox.unselected
import time:       282 |        282 |       plotly.graph_objs.choroplethmapbox.selected
import time:       269 |        269 |       plotly.graph_objs.choroplethmapbox.marker
import time:       305 |        305 |       plotly.graph_objs.choroplethmapbox.hoverlabel
import time:       332 |        332 |         plotly.graph_objs.choroplethmapbox.colorbar.title
import time:       565 |        897 |       plotly.graph_objs.choroplethmapbox.colorbar
import time:      1842 |       3958 |     plotly.graph_objs.choroplethmapbox
import time:       357 |        357 |       plotly.graph_objs.choropleth.unselected
import time:       268 |        268 |       plotly.graph_objs.choropleth.selected
import time:       293 |        293 |       plotly.graph_objs.choropleth.marker
import time:       263 |        263 |       plotly.graph_objs.choropleth.hoverlabel
import time:       309 |        309 |         plotly.graph_objs.choropleth.colorbar.title
import time:       605 |        914 |       plotly.graph_objs.choropleth.colorbar
import time:      1788 |       3880 |     plotly.graph_objs.choropleth
import time:       341 |        341 |       plotly.graph_objs.carpet.hoverlabel
import time:       371 |        371 |         plotly.graph_objs.carpet.baxis.title
import time:       566 |        937 |       plotly.graph_objs.carpet.baxis
import time:       289 |        289 |         plotly.graph_objs.carpet.aaxis.title
import time:       548 |        837 |       plotly.graph_objs.carpet.aaxis
import time:      1648 |       3761 |     plotly.graph_objs.carpet
import time:       299 |        299 |       plotly.graph_objs.candlestick.increasing
import time:       274 |        274 |       plotly.graph_objs.candlestick.hoverlabel
import time:       241 |        241 |       plotly.graph_objs.candlestick.decreasing
import time:       952 |       1764 |     plotly.graph_objs.candlestick
import time:       322 |        322 |       plotly.graph_objs.box.unselected
import time:       387 |        387 |       plotly.graph_objs.box.selected
import time:       259 |        259 |       plotly.graph_objs.box.marker
import time:       264 |        264 |       plotly.graph_objs.box.hoverlabel
import time:      1375 |       2605 |     plotly.graph_objs.box
import time:       348 |        348 |       plotly.graph_objs.barpolar.unselected
import time:       380 |        380 |       plotly.graph_objs.barpolar.selected
import time:       324 |        324 |           plotly.graph_objs.barpolar.marker.colorbar.title
import time:       488 |        812 |         plotly.graph_objs.barpolar.marker.colorbar
import time:       796 |       1607 |       plotly.graph_objs.barpolar.marker
import time:       289 |        289 |       plotly.graph_objs.barpolar.hoverlabel
import time:      1053 |       3675 |     plotly.graph_objs.barpolar
import time:       397 |        397 |       plotly.graph_objs.bar.unselected
import time:       314 |        314 |       plotly.graph_objs.bar.selected
import time:       317 |        317 |           plotly.graph_objs.bar.marker.colorbar.title
import time:       495 |        811 |         plotly.graph_objs.bar.marker.colorbar
import time:       646 |       1457 |       plotly.graph_objs.bar.marker
import time:       357 |        357 |       plotly.graph_objs.bar.hoverlabel
import time:      1366 |       3888 |     plotly.graph_objs.bar
import time:       499 |        499 |       plotly.graph_objs.area.hoverlabel
import time:       628 |       1127 |     plotly.graph_objs.area
import time:       320 |        320 |         plotly.graph_objs.layout.yaxis.title
import time:       624 |        944 |       plotly.graph_objs.layout.yaxis
import time:       308 |        308 |         plotly.graph_objs.layout.xaxis.title
import time:       229 |        229 |         plotly.graph_objs.layout.xaxis.rangeslider
import time:       311 |        311 |         plotly.graph_objs.layout.xaxis.rangeselector
import time:       675 |       1521 |       plotly.graph_objs.layout.xaxis
import time:       356 |        356 |       plotly.graph_objs.layout.updatemenu
import time:       278 |        278 |       plotly.graph_objs.layout.title
import time:       355 |        355 |           plotly.graph_objs.layout.ternary.caxis.title
import time:       481 |        836 |         plotly.graph_objs.layout.ternary.caxis
import time:       303 |        303 |           plotly.graph_objs.layout.ternary.baxis.title
import time:       366 |        668 |         plotly.graph_objs.layout.ternary.baxis
import time:       320 |        320 |           plotly.graph_objs.layout.ternary.aaxis.title
import time:       439 |        758 |         plotly.graph_objs.layout.ternary.aaxis
import time:      1081 |       3341 |       plotly.graph_objs.layout.ternary
import time:       550 |        550 |         plotly.graph_objs.layout.template.data
import time:       526 |       1075 |       plotly.graph_objs.layout.template
import time:       299 |        299 |         plotly.graph_objs.layout.slider.currentvalue
import time:       636 |        935 |       plotly.graph_objs.layout.slider
import time:       330 |        330 |       plotly.graph_objs.layout.shape
import time:       632 |        632 |           plotly.graph_objs.layout.scene.zaxis.title
import time:       479 |       1111 |         plotly.graph_objs.layout.scene.zaxis
import time:       346 |        346 |           plotly.graph_objs.layout.scene.yaxis.title
import time:      1048 |       1393 |         plotly.graph_objs.layout.scene.yaxis
import time:       321 |        321 |           plotly.graph_objs.layout.scene.xaxis.title
import time:       501 |        821 |         plotly.graph_objs.layout.scene.xaxis
import time:       338 |        338 |         plotly.graph_objs.layout.scene.camera
import time:       281 |        281 |           plotly.graph_objs.layout.scene.annotation.hoverlabel
import time:       330 |        610 |         plotly.graph_objs.layout.scene.annotation
import time:      1821 |       6093 |       plotly.graph_objs.layout.scene
import time:       308 |        308 |           plotly.graph_objs.layout.polar.radialaxis.title
import time:       728 |       1036 |         plotly.graph_objs.layout.polar.radialaxis
import time:       322 |        322 |         plotly.graph_objs.layout.polar.angularaxis
import time:     15094 |      16451 |       plotly.graph_objs.layout.polar
import time:       430 |        430 |           plotly.graph_objs.layout.mapbox.layer.symbol
import time:       633 |       1063 |         plotly.graph_objs.layout.mapbox.layer
import time:       505 |       1568 |       plotly.graph_objs.layout.mapbox
import time:       237 |        237 |       plotly.graph_objs.layout.legend
import time:       218 |        218 |       plotly.graph_objs.layout.hoverlabel
import time:       211 |        211 |       plotly.graph_objs.layout.grid
import time:       302 |        302 |         plotly.graph_objs.layout.geo.projection
import time:       570 |        872 |       plotly.graph_objs.layout.geo
import time:       368 |        368 |           plotly.graph_objs.layout.coloraxis.colorbar.title
import time:       482 |        850 |         plotly.graph_objs.layout.coloraxis.colorbar
import time:       613 |       1462 |       plotly.graph_objs.layout.coloraxis
import time:       303 |        303 |         plotly.graph_objs.layout.annotation.hoverlabel
import time:       441 |        744 |       plotly.graph_objs.layout.annotation
import time:      5570 |      42197 |     plotly.graph_objs.layout
import time:      1778 |       1778 |     plotly.graph_objs._figure
import time:       186 |        186 |     ipywidgets
import time:       924 |        924 |     plotly.graph_objs._deprecations
import time:     24279 |     272523 |   plotly.graph_objs
import time:       326 |        326 |       _plotly_utils.exceptions
import time:       188 |        513 |     plotly.exceptions
import time:       188 |        188 |       _plotly_utils.files
import time:       180 |        368 |     plotly.files
import time:       995 |       1875 |   plotly.tools
import time:       665 |        665 |       pkgutil
import time:       177 |        177 |       plotly.offline._plotlyjs_version
import time:       446 |       1287 |     plotly.offline.offline
import time:       239 |       1525 |   plotly.offline
import time:       184 |        184 |         _plotly_utils.colors._swatches
import time:       208 |        208 |         _plotly_utils.colors.colorbrewer
import time:       202 |        202 |         _plotly_utils.colors.carto
import time:       357 |        950 |       _plotly_utils.colors.qualitative
import time:       897 |        897 |         _plotly_utils.colors.plotlyjs
import time:       243 |        243 |         _plotly_utils.colors.cmocean
import time:       272 |       1412 |       _plotly_utils.colors.sequential
import time:       200 |        200 |       _plotly_utils.colors.diverging
import time:       226 |        226 |       _plotly_utils.colors.cyclical
import time:       498 |       3284 |     _plotly_utils.colors
import time:       245 |       3529 |   plotly.colors
import time:       304 |        304 |         _socket
import time:       120 |        120 |           math
import time:       116 |        116 |           select
import time:       789 |       1025 |         selectors
import time:       106 |        106 |         errno
import time:      2889 |       4321 |       socket
import time:      1215 |       1215 |         signal
import time:        72 |         72 |         _posixsubprocess
import time:       853 |       2139 |       subprocess
import time:      2053 |       2053 |             _hashlib
import time:        83 |         83 |             _blake2
import time:       108 |        108 |             _sha3
import time:       449 |       2691 |           hashlib
import time:        78 |         78 |             _bisect
import time:       295 |        373 |           bisect
import time:        56 |         56 |           _random
import time:       857 |       3976 |         random
import time:       481 |       4456 |       retrying
import time:       234 |        234 |       plotly.io._utils
import time:      1135 |      12283 |     plotly.io._orca
import time:       175 |        175 |     plotly.io.orca
import time:       216 |        216 |     plotly.io._json
import time:       374 |        374 |     plotly.io._templates
import time:       574 |        574 |         shlex
import time:       249 |        249 |           fnmatch
import time:       123 |        123 |           zlib
import time:       339 |        339 |             _compression
import time:       359 |        359 |             _bz2
import time:       383 |       1081 |           bz2
import time:       433 |        433 |             _lzma
import time:       468 |        900 |           lzma
import time:       114 |        114 |           pwd
import time:        73 |         73 |           grp
import time:       886 |       3421 |         shutil
import time:       769 |       4762 |       webbrowser
import time:       282 |       5043 |     plotly.io._html
import time:       204 |        204 |         distutils
import time:      1112 |       1315 |       distutils.version
import time:       312 |        312 |               _opcode
import time:       421 |        733 |             opcode
import time:      1410 |       2143 |           dis
import time:      2396 |       4539 |         inspect
import time:      1518 |       1518 |           http
import time:       182 |        182 |             _datetime
import time:      1231 |       1412 |           datetime
import time:       268 |        268 |             email
import time:       318 |        318 |               urllib
import time:      1423 |       1741 |             urllib.parse
import time:      1086 |       1086 |                 locale
import time:       867 |       1952 |               calendar
import time:       394 |       2346 |             email._parseaddr
import time:       286 |        286 |               email.base64mime
import time:       368 |        368 |               email.quoprimime
import time:       632 |        632 |               email.errors
import time:       218 |        218 |                 quopri
import time:       216 |        434 |               email.encoders
import time:       399 |       2117 |             email.charset
import time:       949 |       7418 |           email.utils
import time:      1237 |       1237 |             html.entities
import time:       684 |       1920 |           html
import time:      1108 |       1108 |                   email.header
import time:       456 |       1564 |                 email._policybase
import time:       943 |       2506 |               email.feedparser
import time:       359 |       2865 |             email.parser
import time:       262 |        262 |               uu
import time:       510 |        510 |               email._encoded_words
import time:       202 |        202 |               email.iterators
import time:       927 |       1899 |             email.message
import time:      1572 |       1572 |               _ssl
import time:      3755 |       5327 |             ssl
import time:      1556 |      11646 |           http.client
import time:       176 |        176 |             winreg
import time:       498 |        674 |           mimetypes
import time:       924 |        924 |           socketserver
import time:      3773 |      29282 |         http.server
import time:      2359 |      36179 |       plotly.io._base_renderers
import time:  10557514 |   10595007 |     plotly.io._renderers
import time:       573 |        573 |     plotly.io.base_renderers
import time:      1188 |   10614857 |   plotly.io
import time:       408 |        408 |   plotly.data
import time:      2146 |       2146 |   plotly._docstring_gen
import time:       313 |        313 |     plotly._version
import time:       352 |        352 |     plotly._widget_version
import time:       740 |       1404 |   plotly.version
import time:      1665 |   10900175 | plotly
``````

**Comment by btck30351** [comment] 2019-09-28 09:40
Not sure why but in python3.7 it takes a long time to get webbrowser

``````
time python -c "import webbrowser; webbrowser.get()"

real    0m17.522s
user    0m0.172s
sys     0m0.016s
``````

This slows down the initialisation of BrowserRenderer

**Comment by gvwilson** [comment] 2024-06-13 19:51
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:50 UTC
