### ISSUE TITLE
Full support for marginals on facets

### ISSUE THREAD

**Issue by harisbal** [plotly/plotly.py#2190] opened 2020-02-13 18:33 UTC
Hello,
At the moment marginals for facet plots can be placed only along the axis of the facet dimension (e.g. `marginal_y` for rows).
Nonetheless, sometimes it can be useful to show both marginals (_x and _y).
I understand that this implementing this can prove tricky but is this something that could be introduced at some point?
Cheers!

**Comment by gvwilson** [comment] 2024-06-14 13:08
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:08 UTC
