### ISSUE TITLE
`Choroplethmapbox` crashing webpage

### ISSUE THREAD

**Issue by indiana-nikel** [plotly/plotly.py#1720] opened 2019-08-12 21:25 UTC
Hello,

Very excited to use the new `Choroplethmapbox` in 4.1, but the browser (Google Chrome and IE) cannot seem to handle rendering the plot. The page crashes (Google Chromes "Aw Snap" error message) and I have to reload my Jupyter notebook, plot unrendered.

I've been following the base example on the the plotly website (https://plot.ly/python/mapbox-county-choropleth/), however I'm substituting a geoJSON file with Census block groups instead of counties. The shapefiles (https://www2.census.gov/geo/tiger/TIGER2018/BG/) are converted to geoJSON using https://mapshaper.org/.

I'm attempting to run the following:

```
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "notebook" 

#https://www2.census.gov/geo/tiger/TIGER2018/BG/ -> https://mapshaper.org/
geojson_bg = json.load(open("tl_2017_01_bg.json")) 
bgs = []
for i in range(3438): #number of blockgroups in this file
    bgs.append(geojson_bg["features"][i]["properties"]["GEOID"])

df_bg = pd.DataFrame(columns=["Blockgroup", "Metric"])
df_bg["Blockgroup"] = bgs
df_bg["Metric"] = 1

fig = go.Figure(go.Choroplethmapbox(
    geojson=geojson_bg, 
    marker_opacity=0.5, 
    marker_line_width=0,
    locations=df_bg["Blockgroup"], 
    z=df_bg["Metric"],
    colorscale="Viridis", 
    zmin=0, 
    zmax=5,
))
fig.update_layout(
    mapbox_style="carto-positron",
    mapbox_zoom=3, 
    mapbox_center = {"lat": 37.0902, "lon": -95.7129},
)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()
```

Let me know if there is more information I can provide.

Best,
Indiana

EDIT: Added in a pandas dataframe to display a value (not important what this is). This was needed to have the base example from the website render in my notebook.

**Comment by gvwilson** [comment] 2024-06-13 19:45
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:45 UTC
