### ISSUE TITLE
mpl_to_plotly doesn't work for draw_networkx_edges in networkx

### ISSUE THREAD

**Issue by LangLEvoI** [plotly/plotly.py#1566] opened 2019-05-15 23:32 UTC
Briefly, I couldn't plot edges of `networkx` using `mpl_to_plotly`. The example code is the following and detailed info shows in [stackoverflow][1]. In addtion, the return of `nx.draw_networkx_edges` method is a list of [`matplotlib.patches.FancyArrowPatch`][2].

```python
from __future__ import division

import matplotlib.pyplot as plt
import networkx as nx
from plotly.offline import (init_notebook_mode, iplot)
import plotly.tools as tls


init_notebook_mode(connected=True)

G = nx.generators.directed.random_k_out_graph(10, 3, 0.5)
pos = nx.layout.spring_layout(G)

node_sizes = [3 + 10 * i for i in range(len(G))]
M = G.number_of_edges()
edge_colors = range(2, M + 2)
edge_alphas = [(5 + i) / (M + 4) for i in range(M)]

fig = plt.figure()

nodes = nx.draw_networkx_nodes(G, pos, node_size=node_sizes, node_color='blue')
edges = nx.draw_networkx_edges(G, pos, node_size=node_sizes, arrowstyle='->',
                               arrowsize=10, edge_color=edge_colors,
                               edge_cmap=plt.cm.Blues, width=2)

plotly_fig = tls.mpl_to_plotly(fig)
iplot(plotly_fig)
```

Thanks for your help!

[1]: https://stackoverflow.com/questions/56158283/why-i-cannot-plot-edges-of-networkx-in-iplot-mpl-method-of-plotly
[2]: https://networkx.github.io/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_networkx_edges.html#networkx.drawing.nx_pylab.draw_networkx_edges

**Comment by jonmmease** [comment] 2019-05-20 10:50
Hi @LangLEvoI, thanks for the report

**Comment by 100518832** [comment] 2019-06-03 15:06
@LangLEvoI, I would just avoid the extra step of using matplotlib, just use nx and plotly directly. I have some examples of how to do network graphs directly in plotly, and I believe their are also examples on the plotly python documentation page(s).

**Comment by LangLEvoI** [comment] 2019-06-04 22:53
Hi, @100518832  thanks for your comment and the docs :) I have already done my project with "pure" `plotly` style! But I was thinking it is not so convenient to plot a directed network using `plotly` because of the arrow plotting.

**Comment by gvwilson** [comment] 2024-06-13 19:32
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:32 UTC
Labels: matplotlylib
