### ISSUE TITLE
Shortcuts for camera controls.

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#1752] opened 2019-09-05 15:33 UTC
For 3d plots, it would be nice to have shortcuts for having the camera eye at specific positions, like XZ plane (https://plot.ly/python/v3/3d-camera-controls/). Something like `camera_direction='xz'`. Would this make sense?

**Comment by gvwilson** [comment] 2024-06-13 19:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:49 UTC
