### ISSUE TITLE
create_gantt missing parameter documentation

### ISSUE THREAD

**Issue by brylie** [plotly/plotly.py#1210] opened 2018-10-03 08:25 UTC
The `figure_factory` `create_gantt` method takes several arguments. Most of the arguments are documented, but a couple of them have no documentation:

https://github.com/plotly/plotly.py/blob/2e5bf6e2f7c213295c405ece3e859f4d3f8030d1/plotly/figure_factory/_gantt.py#L584-L616

Please add missing documentation to this factory method.

**Comment by jonmmease** [comment] 2018-10-04 10:15
Thanks for taking the time to report this @brylie, looks like the undocumented arguments are `tasks`, `task_names`, `data`, and `group_tasks`.

**Comment by Juanlu001** [comment] 2018-12-17 10:06
And also `Description`, which was added here https://github.com/plotly/plotly.py/pull/588

**Comment by ethanopp** [comment] 2019-08-29 01:22
Is there a way to define the sort order on the Y-Axis of grouped tasks?

**Comment by gvwilson** [comment] 2024-06-13 17:45
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:45 UTC
Labels: documentation
