### ISSUE TITLE
powerpoint export

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1461] opened 2019-03-12 00:02 UTC
It would be pretty interesting to add a function to `plotly.io` to export figures as PowerPoint slides.

We could have a thin `write_powerpoint` wrapper on top of `python-pptx` (https://python-pptx.readthedocs.io/en/latest/). That would output a single slide PPTX presentation, optionally based on a template. This single slide could then be copied into a larger presentation.

For more complex reports, we should probably provide some documentation examples of integrating plotly figures using the `python-pptx` API.

**Comment by jackparmer** [comment] 2019-03-12 04:07
For anyone interested, Jon also had a nice vision for how chart images in ppt slides could link to the interactive version. [From Slack]

> Maybe something like `plotly.io.write_powerpoint(fig, 'output.pptx', template='template.pptx', picture_name='Image1')`

> Would use orca to create the static image to embed in the slide, and write out a standalone HTML file, and link the static image in the slide to open the HTML file in the default web browser.

> With the `plotly.io.renderer` proposal we could also add a `power_point` renderer so evaluating `show(fig, renderer='power_point')` would open a power point slide containing the figure :visage_légèrement_souriant:  https://github.com/plotly/plotly.py/issues/1459

**Comment by gvwilson** [comment] 2024-06-13 19:25
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:25 UTC
Labels: enhancement
