### ISSUE TITLE
Javascript Error: Cannot read property 'removeChild' of null when using offline mode

### ISSUE THREAD

**Issue by xxyypp** [plotly/plotly.py#1424] opened 2019-02-04 11:56 UTC
Hello, I am using Jupyter lab offline mode for drawing several 3D models. However, I always meet an error called **Javascript Error: Cannot read property 'removeChild' of null** and this error cause that no figure will be shown on the page. 

I need to restart the server and sometimes again and again.

I would like to know if this is caused by the large dataset for the model? PS, such models are repeatedly drawing in the Jupiter lab.

Code causing error:
`offline.iplot(fig, filename = 'test')`

However, using offline.plot instead of offline.iplot definitely works:

Definitely work
`offline.plot(fig, filename = 'test')`

**Comment by jonmmease** [comment] 2019-02-04 12:32
Hi @xxyypp,

Is there any chance you could make up and share an example that reproduces the error?  Either way, could you include your versions of the:
 - `plotly` Python package
 - `@jupyterlab/plotly-extension` JupyterLab extension

And could you add a screenshot of the full stack trace that appears in the browser console along with the error message?  Thanks!

**Comment by xxyypp** [comment] 2019-02-04 13:00
Hello @jonmmease ,

- plotly version is 3.5.0

- plotly-extension version is v0.18.1

The only trace of the error is: 
![image](https://user-images.githubusercontent.com/22870449/52209644-72e24d00-287c-11e9-9224-9ddad0cf6185.png)

I am currently trying to get the code snippet, but this seems a bit difficult since the data I used in my project is dynamic, I might need some time to figure out how to do.

**Comment by gvwilson** [comment] 2024-06-13 19:24
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:24 UTC
Labels: question
