### ISSUE TITLE
Display of plot is missing: Show plot/graph/chart/.. in jupyter lab #jupyter

### ISSUE THREAD

**Issue by ksuess** [plotly/plotly.py#1699] opened 2019-08-01 13:01 UTC
**pyenv** with
plotly 4.0.0

![image](https://user-images.githubusercontent.com/1144737/62295282-f74d0b80-b46c-11e9-9eb8-3e388274aa79.png)
Where is the plot; what is necessary to install/ configure?

**Comment by nicolaskruchten** [comment] 2019-08-02 12:49
There are some additional instructions for getting JupyterLab to render figures: https://plot.ly/python/getting-started/#jupyterlab-support-python-35

**Comment by fkromer** [comment] 2019-08-16 11:37
@nicolaskruchten The instructions don't work for JupyterLab v1.0.5. After building the extensions there I've a white screen showing nothing. Could you update the instructions pls?

**Comment by mustafaikizler** [comment] 2022-07-02 16:04
Any Update? Thanks

**Comment by ndrezn** [comment] 2024-11-20 19:29
Unable to reproduce, so closing unless there are folks who are still seeing the issue or feel the existing docs are incorrect.

**Closed by ndrezn** 2024-11-20 19:29 UTC
Labels: bug, P3
