### ISSUE TITLE
FigureWidget does not work properly with ipywidgets 8.x

### ISSUE THREAD

**Issue by Alexboiboi** [plotly/plotly.py#3890] opened 2022-09-14 09:42 UTC
FigureWidget does not work properly with ipywidgets 8.x

```import ipywidgets
import plotly
import plotly.graph_objects as go
import plotly.express as px

print(f"{plotly.__version__=}")
print(f"{ipywidgets.__version__=}")

fig = px.line([1, 2, 3, 4, 6])
fw = go.FigureWidget(fig)
fw
```

![image](https://user-images.githubusercontent.com/29252289/190120385-12a88f9a-7458-45df-9783-49db937140c4.png)

**Comment by alexcjohnson** [comment] 2022-09-14 16:17
duplicate of https://github.com/plotly/plotly.py/issues/3686

**Closed by alexcjohnson** 2022-09-14 16:17 UTC
