### ISSUE TITLE
Format single-line templates into multi-line JSON files

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.py#2314] opened 2020-03-25 21:24 UTC
Some templates at https://github.com/plotly/plotly.py/tree/master/packages/python/plotly/plotly/package_data/templates are presented on a single line. 
To make them `human-readable` and `git-friendly` one could possibly re-format them.

**Comment by nicolaskruchten** [comment] 2020-03-25 22:57
These are the output of code-generation so shouldn’t be too hard, but they’re also not meant to be read or edited particularly...

**Comment by archmoj** [comment] 2020-03-25 23:15
That way it can be easier to keep track of the potential changes in future.
Just as an idea - I don't have strong opinion on this.

**Comment by gvwilson** [comment] 2024-06-14 13:05
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:05 UTC
