### ISSUE TITLE
Scatter plot and 'plotly_selected'

### ISSUE THREAD

**Issue by ricleal** [plotly/plotly.py#480] opened 2016-05-25 12:25 UTC
Hello,

I have a Scatter plot with more than one curve. I use the code below to generate my plot:
```python
    data = []
    for filename in data_files:
        csv = np.genfromtxt (filename, delimiter=None,  comments='#')
        x = csv[:,0]
        y = csv[:,1]
        trace = go.Scatter(
            x=x,
            y=y,
            mode = 'lines+markers',
            name = filename.split('/')[-1],
            error_y=dict(
                type='data',
                visible=True,
                array=np.sqrt(csv[:,1]),
                thickness=1.5,
                width=3,
                opacity=0.5
            ),
        )
        data.append(trace)

    layout = go.Layout(
        height=600,
        xaxis=dict(
            autorange=True,
            type='log',
        ),
        yaxis=dict(
            autorange=True,
            type='log',
        ),
        title = "Iq chart"
    )
    fig = go.Figure(data=data, layout=layout)
``` 

Then, I use the following javascript to debug a region with `Box Select`:
```javascript
        var myDiv = $('.plotly-graph-div')[0];
        myDiv.on('plotly_selected', function(eventData) {
          console.log(eventData.points);
          for (var idx = 0; idx < eventData.points.length; idx++) {
            console.log(eventData.points[idx]);
          };
        });
```

If I have all the curves visible (as by default), I obtain the expected output:
```
[Log] [Object, Object, Object] (3)
[Log] {curveNumber: 0, pointNumber: 1, x: 0.05, y: 53.6662}
[Log] {curveNumber: 1, pointNumber: 3, x: 0.037037, y: 211.601}
[Log] {curveNumber: 1, pointNumber: 4, x: 0.0462963, y: 122.127}
```

However, if I click on the plot legend to hide some of the curves, so I end up with just one, I have the following error:
```
[Error] TypeError: undefined is not an object (evaluating 'l[0].node3.selectAll')
	exports (plotly-latest.min.js:43:13799)
	moveFn (plotly-latest.min.js:35:31101)
	r (plotly-latest.min.js:29:3768)
[Error] TypeError: undefined is not an object (evaluating 'eventData.points')
	(anonymous function)
	emit (plotly-latest.min.js:9:4087)
	emit (plotly-latest.min.js:31:23535)
	doneFn (plotly-latest.min.js:35:31436)
	a (plotly-latest.min.js:29:4028)
```

I use the the latest plotly.js:
```html
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
```

And:

```python
In [2]: import plotly
In [3]: plotly.__version__
Out[3]: '1.10.0'
```

Is this a bug, or am I doing something wrong?
Thank you

**Comment by jackparmer** [comment] 2016-05-31 05:18
Hey @etpinard - Does that `plotly.js` error look familiar?

**Comment by etpinard** [comment] 2016-05-31 14:59
Strange. I can't reproduce this in a vanilla plotly.js environment: http://codepen.io/etpinard/pen/dXPGMV

**Comment by ricleal** [comment] 2016-05-31 15:07
@etpinard I just have tried your example. If you select just one curve (clicking on the legend), leaving just `trace 0` for example, I have the error in the console:

![screen shot 2016-05-31 at 11 05 47 am](https://cloud.githubusercontent.com/assets/1866557/15679390/b85c887a-271f-11e6-932c-35ed974dabf0.png)

**Comment by etpinard** [comment] 2016-05-31 15:16
@ricleal Got it! Thanks for reporting.

This is really a plotly.js issue, so I'll close this issue and you should subscribe to https://github.com/plotly/plotly.js/issues/588 for the latest development info.

**Closed by etpinard** 2016-05-31 15:16 UTC
