### ISSUE TITLE
Feature request: zsmooth parameter for Heatmapgl

### ISSUE THREAD

**Issue by mmlanger** [plotly/plotly.py#1115] opened 2018-08-15 14:57 UTC
(First of all: FigureWidget + jupyterlab is just awesome, please continue!)
the zsmooth seems to not be implemented in `Heatmapgl` , while it is in `Heatmap`.

Could you add this in the future? 
By default `Heatmapgl` seems to use interpolation while I do like to turn it off.

**Comment by jonmmease** [comment] 2018-08-18 09:57
Hi @mmlanger , glad you're enjoying the new workflow, thanks for letting us know 🙂 

Could you create a corresponding issue for the [Plotly.js library](https://github.com/plotly/plotly.js)? Any changes in trace options or behaviors have to flow through that library first.  Once you do, just post another comment here with the link to the Plotly.js issue.

Thanks!

**Comment by mmlanger** [comment] 2018-08-18 10:05
Here goes the plotly.js issue:
https://github.com/plotly/plotly.js/issues/2924

Thanks for your response!

**Comment by gvwilson** [comment] 2024-06-13 17:40
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:40 UTC
Labels: enhancement, plotly.js
