### ISSUE TITLE
ff.create_facet_grid not supporting numpy.int dtypes

### ISSUE THREAD

**Issue by priyatharsan** [plotly/plotly.py#1400] opened 2019-01-21 16:41 UTC
Related to the issue: https://github.com/plotly/documentation/issues/1244 logged by https://github.com/Chippasaur

Throws an error:
```
ValueError: 
    Invalid value of type 'numpy.int64' received for the 'name' property of scatter
        Received value: 6

    The 'name' property is a string and must be specified as:
      - A string
      - A number that will be converted to a string
```
when the dataframe column contains numpy.int

Looks like while checking for the instance: https://github.com/plotly/plotly.py/blob/master/_plotly_utils/basevalidators.py#L1010 numpy-based dtypes should also be validated?

**Comment by jonmmease** [comment] 2019-01-23 10:53
Good idea, thanks for the suggestion @priyatharsan

**Comment by gvwilson** [comment] 2024-06-13 17:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:42 UTC
Labels: enhancement
