### ISSUE TITLE
How can i use custom symbol for marker?

### ISSUE THREAD

**Issue by pankajPizone** [plotly/plotly.py#1790] opened 2019-09-27 05:49 UTC
I need to show twitter logo as a marker symbol,

I have try to use symbolsrc with marker but its not working.

 any solution?

**Comment by gvwilson** [comment] 2024-06-14 13:15
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:15 UTC
