### ISSUE TITLE
Helper for Table trace from pandas

### ISSUE THREAD

**Issue by AbdealiLoKo** [plotly/plotly.py#1485] opened 2019-03-29 08:30 UTC
I know there is a `plotly.figure_factory.create_table` which can rake my pandas dataframe and create a table using the heatmap trace-type:
```python
df = pd.DataFrame({'a': [1,2,3,4], 'b': [4,3,2,2]})
fig = ff.create_table(df)
py.plot(fig)
```

But now that there is a go.Table trace type available, it would be awesome to have the `cells` and `header` attributes of this be auto populated from a pandas dataframe.

So, this is a feature request for a helper that converts a pd.DataFrame into a go.Table() to make it more pythonic to create that.

**Comment by AbdealiJK** [comment] 2019-03-29 09:00
Currently, I need to do:
```
df = pd.DataFrame({'a': [1,2,3,4], 'b': [4,3,2,2]})
fig = go.Figure(
    [go.Table(header={'values': df.columns}, cells={'values': [df[i] for i in df.columns]})],
)
py.iplot(fig)
```
But there is so much other info in a pandas DataFrame that can be visualized nicely (done by the to_html() in pandas):
 - If an index is present, show the index in the left automatically
 - if the multi-index is present, show that nicely in the table
 - If the index is visualized, automatically highlight that with a `cells.fill.color` attribute

**Comment by jonmmease** [comment] 2019-04-02 10:00
Thanks for the suggestion @AbdealiJK,

This might be a good fit for the new `plotly_express` library:  https://github.com/plotly/plotly_express

What do you think @nicolaskruchten.  Something like:

```python
import plotly_express as px
px.table(df) # All columns, and index
px.table(df, columns = [col1, col2, col3], index=False)  # three columns, no index
px.table(df, color=col3)  # all columns, color rows by `col3`
```
Other inspiration: https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html

-Jon

**Comment by nicolaskruchten** [comment] 2019-04-02 16:51
great idea! I've created an issue here https://github.com/plotly/plotly_express/issues/41 to continue the conversation

**Comment by AbdealiJK** [comment] 2019-04-02 17:15
I'm sorry if this is a naive and slightly unrelated question. Could you help me understand what python express aims to do which is different from plotly.py ?
Currently it looks to me as:
 - plotly.py is a thin wrapper around plotly.js with the exact same attributes and so on
 - plotly-express is a python API to create plots powered by plotly.js (via plotly.py)
Is that right?

**Comment by nicolaskruchten** [comment] 2019-04-02 18:50
That's right! Plotly Express is meant to make it easier/faster to build Plotly.py figures, often in just a single function call instead of dozens of lines of imperative code. The output of all `px` calls is a full `Figure` object that can then be customized at will. 

This article has lots more info https://medium.com/@plotlygraphs/introducing-plotly-express-808df010143d

**Comment by gvwilson** [comment] 2024-06-13 19:26
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:26 UTC
Labels: enhancement
