### ISSUE TITLE
Different colors in radar chart

### ISSUE THREAD

**Issue by benediktpascher** [plotly/plotly.py#2211] opened 2020-02-18 10:30 UTC
Hey everybody,

is there currently a way to color the background of a radar chart in different colors?
(E.g. if you have a range of 1-5, 1-3 has a different background color as 3-5)

As far as I have seen in the documentation, the background is only one color?

Thanks in advance

**Comment by sursu** [comment] 2020-02-26 00:18
You can do e.g. `fig.update_layout(polar_bgcolor='lightgreen')` to set the color to light-green.

But, you have every right to be confused: what does `plot_bgcolor` do there?

Another apparent issue: the reset-button seems to be missing from the plot.

**Comment by gvwilson** [comment] 2024-06-14 13:07
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:07 UTC
