### ISSUE TITLE
[MPL conversion] Offline plot does not show legend correctly

### ISSUE THREAD

**Issue by onewhaleid** [plotly/plotly.py#910] opened 2018-01-06 20:30 UTC
Using `plotly.offline.plot_mpl`, I am not able to create an interactive legend. In fact, the legend entries simply appear as text, without the matching line or symbol key.

`plotly 2.2.2`
`matplotlib 2.1.0`

Here is my code:

```
import matplotlib.pyplot as plt
import plotly.offline

fig, ax = plt.subplots()

ax.plot([0, 1, 2], [0, 1, 2], 'o-', label='a')
ax.plot([0, 1, 2], [0.5, 1.5, 2.5], 'o-', label='b')

ax.legend()

plotly.offline.plot_mpl(fig, filename='temp-plot.html')
```

![image](https://user-images.githubusercontent.com/11261876/34643722-2c28e4e4-f37d-11e7-92e6-582b03b18429.png)

**Comment by zeruitle** [comment] 2018-01-11 01:58
Similar situation, but I suspected not because offline?

situation 1: all gantt example can't toggle legend
https://plot.ly/python/gantt/#using-hours-and-minutes-in-times

situation 2: I tried my own offline gantt, can't toggle

situation 3: tried other offline example, it can toggle
https://plot.ly/python/offline/#plotting-offline-with-cufflinks


anyway, just want my offline gantt can toggle legend...


```
fig = ff.create_gantt(df, colors=colors, index_col='Resource', title='Daily Schedule',
                      show_colorbar=True, bar_width=0.8, showgrid_x=True, showgrid_y=True, group_tasks=True)

plotly.offline.plot(fig, filename='gantt-hours-minutes.html')
```

**Comment by Juanlu001** [comment] 2018-12-17 10:09
> my situation is I have legend on my plot, but the toggle simply not working

I reported a separate issue https://github.com/plotly/plotly.py/issues/1371 so this can stay focused on the `plot_mpl` issue.

**Comment by laserjeyes** [comment] 2018-12-21 10:34
I am experiencing the same problem: Drawing an offline Gantt chart with `group_tasks=True` shows the colorbar only if `index_col`is set to numerical values. Once `index_col` ist set to labels, `show_colorbar=True` is being ignored, no legend is shown.

**Comment by pshassett** [comment] 2019-06-12 14:01
Getting same issue using pandas plot method:
```python
import matplotlib.pyplot as plt
import plotly
import pandas as pd

time = range(20)
y1 = []
y2 = []
for i in time:
    y1.append(i**1.5)
    y2.append(i**2)
data = {'y1': y1,
        'y2': y2}
df = pd.DataFrame(data)

fig = plt.figure(figsize=(9, 5))
ax = fig.gca()
df.plot(legend=True, ax=ax)
ax.set_xlabel('x-label')
ax.set_ylabel('y-label')
lgd = plt.legend(loc='lower right', shadow=True, title='Tanks', fancybox=True)
lgd.get_frame().set_alpha(0.5)
plt.show()
plotly.offline.plot_mpl(fig, filename='./plt_fig.html', auto_open=False)
```

![plotly](https://user-images.githubusercontent.com/39605888/59357449-e4357f00-8cf8-11e9-9a9b-cd1795f90830.PNG)

**Comment by avivajpeyi** [comment] 2019-11-26 05:18
Getting the same issue... It has almost been 2 yrs since this was opened. Any updates/suggestions? 

# Code to reproduce 

```bash
$ pip install bilby
```

```python
from __future__ import division, print_function

import bilby 
import matplotlib.pyplot as plt
import plotly
import plotly.tools as tls
from matplotlib.ticker import (AutoMinorLocator)

approximants = ["IMRPhenomPv2", "SEOBNRv4"]

injection_parameters = dict(
    mass_1=141.0741,
    mass_2=113.0013,
    a_1=0.9434,
    a_2=0.2173,
    tilt_1=0,
    tilt_2=0,
    phi_jl=0,
    phi_12=0,
    luminosity_distance=1782.1610,
    theta_jn=0.9614,
    psi=1.6831,
    phase=5.2220,
    geocent_time=1242424473.5880,
    ra=0.9978,
    dec=-0.4476
)


def get_data(approximants, injection_parameters):
    generator_args = dict(
        duration=4,
        sampling_frequency=2048.,
        frequency_domain_source_model=bilby.gw.source.lal_binary_black_hole,
        parameters=injection_parameters
    )

    waveform_args = dict(reference_frequency=50.)

    approximant_data = dict()
    for approximant in approximants:
        waveform_args.update(dict(waveform_approximant=approximant))
        generator_args.update(waveform_arguments=waveform_args)
        generator = bilby.gw.WaveformGenerator(**generator_args)
        h_signal = generator.time_domain_strain(injection_parameters)
        h_time = generator.time_array
        approximant_data.update({approximant: dict(x=h_time, y=h_signal['plus'])})
    return approximant_data


def matplot_plot_data(approximant_data):
    fig, ax = plt.subplots()

    for approximant, data in approximant_data.items():
        ax.plot(data['x'], data['y'], label=approximant)

    ax.xaxis.set_minor_locator(AutoMinorLocator())
    ax.set_title('Comparing Time-Domain Data')
    ax.set_ylabel('Strain')
    ax.set_xlabel('Time (s)')
    ax.legend()
    return fig


def plotly_plot_data(fig):
    plotly_fig = tls.mpl_to_plotly(fig)
    plotly.offline.plot(plotly_fig, filename="plotly_strain.html")


data = get_data(approximants, injection_parameters)
fig = matplot_plot_data(data)
plotly_plot_data(fig)

```

# Matplotlib Plot:
![Screen Shot 2019-11-26 at 4 15 31 pm](https://user-images.githubusercontent.com/15642823/69601379-113bdb00-1068-11ea-9c9f-00802b322fb1.png)

# Plotly Plot:
![Screen Shot 2019-11-26 at 4 15 40 pm](https://user-images.githubusercontent.com/15642823/69601383-1862e900-1068-11ea-884d-35d1d1ec1e87.png)

**Comment by avivajpeyi** [comment] 2019-11-26 05:58
I came up with a hack-y fix which does the job:
```python
def plotly_plot_data(fig):
    ax_list = fig.axes
    for ax in ax_list:
        ax.get_legend().remove()

    plotly_fig = tls.mpl_to_plotly(fig)
    legend = go.layout.Legend(
        x=0.05,
        y=0.95
    )
    plotly_fig.update_layout(showlegend=True, legend=legend)
    plotly.offline.plot(plotly_fig, filename="plotly_strain.html")
```
![Screen Shot 2019-11-26 at 4 57 37 pm](https://user-images.githubusercontent.com/15642823/69603149-de94e100-106d-11ea-9601-aec6e4d79119.png)

**Comment by nicolaskruchten** [comment] 2019-11-26 14:00
We're not really maintaining the matplotlib-to-plotly conversion pipeline ourselves very much these days (although we would be happy to review and accept pull requests to it!) so the approach proposed immediately-above is probably the best way forward today.

**Comment by gvwilson** [comment] 2024-06-10 18:31
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 18:31 UTC
Labels: matplotlylib
