### ISSUE TITLE
`parallel_coordinates` rendering problem with large data

### ISSUE THREAD

**Issue by Rabeez** [plotly/plotly.py#2124] opened 2019-11-19 14:17 UTC
I have a reasonably large data frame with 165,693 rows. I made a parallel_coordinates plot with 4 variables and the output looks strange as if it's trying to plot all the lines but couldn't finish. The lines between the second and third variable don't go all the way. 
![Screenshot (5)](https://user-images.githubusercontent.com/9392057/69153772-a2f39780-0b00-11ea-8c16-3da5fc5d485b.png)

When I try to reorder by moving the second axis, the plot 'refreshes' and removes the halfway drawn lines:
![Screenshot (6)](https://user-images.githubusercontent.com/9392057/69153918-dfbf8e80-0b00-11ea-8743-1e30737da251.png)

To explain a bit further. The first 3 variables are actually categorical and I've encoded them to integers to plot using parallel coordinates which is why the lines are clustered around certain points on the first 3 axes. 

Also, I've had to hide the tick and axis labels because of reasons 🙄 , hopefully this can be debugged even with my horrible paint skills

EDIT: Tried with first 25,000 rows of the df only, got similar result.

**Comment by gvwilson** [comment] 2024-06-14 13:04
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:04 UTC
