### ISSUE TITLE
FigureWidget does not honor all template attributes

### ISSUE THREAD

**Issue by hlgirard** [plotly/plotly.py#1463] opened 2019-03-12 16:42 UTC
When using FigureWidget in a jupyter notebook, only some attributes of the active template are applied while others are ignored. For instance:

```python
import plotly.graph_objs as go
import plotly.io as pio

# Layout
layout = go.Layout(
        xaxis=dict(
            # Title
            titlefont=dict(size=18),
            # Ticks and font size
            ticks='inside',
            ticklen=4,
            tickfont=dict(size=16),
            # Grid
            showgrid = True,
            gridwidth = 1,
            # Disable zeroline
            zeroline=False, 
            # Box the plot
            linecolor = 'black',
            linewidth = 2, 
            mirror = True,
        ),
        yaxis=dict(
            titlefont=dict(size=18),
            # Ticks and font size
            ticks='inside',
            ticklen=4,
            tickfont=dict(size=16),
            # Grid
            showgrid = True,
            gridwidth = 1,
            # Disable zeroline
            zeroline=False, 
            # Box the plot
            linecolor = 'black',
            linewidth = 2, 
            mirror = True,
        ),
        width=550,
        height=500,
    )

# Figure
fig = go.Figure(data=None, layout=layout)

# Create template
template = pio.to_templated(fig)
pio.templates['boxed'] = template.layout.template
pio.templates.default = 'boxed'

# Test the template
## Toy data
data_adh = [go.Scatter(
    x = [0, 2, 2.5, 3.5, 4, 5, 5.5, 6],
    y = [1, 0.72, 0.56, 0.29, 0.27, 0.19, 0.15, 0.13],
    mode = "markers",
    )]

## Explicit layout
fig_explicit = go.FigureWidget(data_adh, layout)

## Layout from template
fig_implicit = go.FigureWidget(data_adh)
```

```fig_explicit``` results in a correctly formatted plot:
![newplot(4)](https://user-images.githubusercontent.com/8866213/54218084-40eb8880-44c3-11e9-9cef-795cc3fe779a.png)

while ```fig_implicit``` only seems to apply the tick marks and tickfont attributes but not the linewidth, width and height:
![Screen Shot 2019-03-12 at 12 36 56 PM](https://user-images.githubusercontent.com/8866213/54218236-9031b900-44c3-11e9-912b-bcd79d27a5f1.png)

The output of ```fig_implicit.layout``` shows the template was correctly read:
```
Layout({
    'template': {'layout': {'height': 500,
                            'width': 550,
                            'xaxis': {'gridwidth': 1,
                                      'linecolor': 'black',
                                      'linewidth': 2,
                                      'mirror': True,
                                      'showgrid': True,
                                      'tickfont': {'size': 16},
                                      'ticklen': 4,
                                      'ticks': 'inside',
                                      'zeroline': False},
                            'yaxis': {'gridwidth': 1,
                                      'linecolor': 'black',
                                      'linewidth': 2,
                                      'mirror': True,
                                      'showgrid': True,
                                      'tickfont': {'size': 16},
                                      'ticklen': 4,
                                      'ticks': 'inside',
                                      'zeroline': False}}}
})
```

It also seems that the ```titlefont``` attribute is not saved in the template but that should probably be a separate issue.

**Comment by jonmmease** [comment] 2019-03-12 23:45
Thanks a lot for the report @hlgirard.

It'll take a little digging to determine whether this is something in plotly.py or plotly.js. Have you tried this example with anything other than `FigureWidget`? i.e. `plotly.offline.iplot` or `plotly.offline.plot`?

**Comment by hlgirard** [comment] 2019-03-13 13:39
Thank you for looking into it.
I have tried `plotly.offline.plot(go.Figure(data))` and `plotly.offline.iplot(go.Figure(data))` and they both lead to the same result as the FigureWidget, the template is ignored.

**Comment by gvwilson** [comment] 2024-06-13 19:25
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:25 UTC
Labels: bug
