### ISSUE TITLE
offline.plot(output_type='div') add option to get JS and HTML separately

### ISSUE THREAD

**Issue by hemberger** [plotly/plotly.py#1649] opened 2019-07-01 17:10 UTC
First, I wanted to thank all the developers for their amazing work on this package!

Since the output of `offline.plot(output_type='div')` is a single string with the `<script>` packaged with the `<div>`, naively including this within a larger web page (as is reasonable to expect if using this option) means that the `<script>` tag is likely to be placed somewhere in the middle of the HTML body.

While it is not required for `<script>` tags to be placed at the end of the HTML body, it is recommended, and not doing so can have some unusual side effects **.

For now, I am resorting to parsing the returned string and then splitting it so that I have the `<div>` and `<script>` separately, which is a bit cumbersome and fragile. I was hoping we could find an interface solution to this problem. Perhaps an option to `offline.plot` that would allow returning the JS and the HTML separately?

** There is an issue (or bug, in my opinion) with Chrome in particular where the inclusion of any script tags, even an empty `<script></script>`, in the middle of the HTML body causes the DOM to partially render, and so the page flickers when it finally renders the full DOM (especially when elements change size between the the partial and full render, e.g. a full width table that is missing columns in the partial render). Using `async` is sometimes an improvement, but can never fully mitigate the flicker.

**Comment by gvwilson** [comment] 2024-06-13 19:40
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:40 UTC
