### ISSUE TITLE
Contributing instructions do not work on Windows

### ISSUE THREAD

**Issue by rockg** [plotly/plotly.py#1390] opened 2019-01-09 14:53 UTC
A step in the contributing guide is to use the command `make setup_subs`. However, this does not work easily on Windows (uses make, rm, rsync). Is it worth moving this functionality to setup.py to be more platform-agnostic? Or is there some other preferred method of setting up one's plotly.py development environment on Windows?

**Comment by jonmmease** [comment] 2019-01-12 11:32
Thanks for the suggestion @rockg.  Yeah, I'd love to get all of the functionality from the `makefile` moved into setup.py tasks and then get rid of the makefile altogether.

It looks like `git` and `rsync` are the only two commands that the makefile executes that don't have direct analogs in pure python.  We could call the same git commands using a subprocess since git works the same across platforms.  We could try replacing the rsync commands with delete and copy operations and see if the runtime is still reasonable.

Is there anything here you're interested in working on?

**Comment by rockg** [comment] 2019-01-13 14:07
I notice that `mplexporter` and `chunked_requests` already live in the plotly.py project not as submodules.  Further, the commit times in plotly are more recent than the `mplexporter` and `chunked_requests` submodule commits themselves.

For example, [plotly's mplexporter](https://github.com/plotly/plotly.py/blob/master/plotly/matplotlylib/mplexporter/exporter.py) was updated 11 months ago, but the corresponding file in the [mplexporter exporter](https://github.com/mpld3/mplexporter/blob/f61e7261b969085b11c4e3128af19b67a2aa7e74/mplexporter/exporter.py) file for the commit referenced in the submodule is 5 years old. Similarly with `chunked_requests` (5 months for the plotly file, 3 years for the chunked_requests file). Do the submodules even need to be used?

**Comment by jonmmease** [comment] 2019-01-14 11:31
Thanks for pointing that out @rockg, it looks like there has been some activity on the mplexporter project sync we last synced things up, so I'd like to keep that submodule around and then I'll sync and test it for our next release.

It doesn't look like there have been any changes made to `chunked_requests` since our last sync, and in fact I made a change to it 5 months ago without realizing it was a submodule!

@chriddyp, do you want keep `chunked_requests` as it's own repo and backport my change in https://github.com/plotly/plotly.py/commit/5138734cc035019b58b6ad26b61a6d4a074cbba7? Or should we just remove the submodule and make the plotly.py version authoritative?

**Comment by gvwilson** [comment] 2024-06-13 17:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:42 UTC
Labels: testing, documentation
