### ISSUE TITLE
Map data for Africa choropleth

### ISSUE THREAD

**Issue by rlantz-cfa** [plotly/plotly.py#1036] opened 2018-06-17 10:59 UTC
The following code produces the attached choropleth.  As you'll notice, Somalia is not completely defined.  Is there another country name used for that part of Somalia?

```
def create_map_fig(df, typ):
    traces = []
    hold = create_map_df(df)
    traces.append(Choropleth(
            locationmode = 'country names',
            locations = hold.index,
            z = hold[typ].apply(np.sum, axis = 1),
            text = hold.index,
            autocolorscale = True,
            showscale = True
            ))
    layout = Layout(
            title = "Summary of the last 12 months of {s} in HOA".format(s = str(typ)),
            margin = Margin(
                    l = 30,
                    r = 30,
                    t = 45,
                    b = 0
                ),
            geo = dict(
                    resolution = 10,
                    showframe = False,
                    showcoastlines = True,
                    showland = True,
                    landcolor = "rgb(229, 229, 229)",
                    countrycolor = "rgb(255, 255, 255)" ,
                    coastlinecolor = "rgb(255, 255, 255)",
                    projection = dict(
                        type = 'Mercator'
                        ),
                    lonaxis = dict(range = [scope['lon_min'], scope['lon_max']]),
                    lataxis = dict(range = [scope['lat_min'], scope['lat_max']]),
                    domain = dict(x = [0, 1], y = [0, 1])
                    )
            )
    return dict(data = traces, layout = layout)
```
![image](https://user-images.githubusercontent.com/34374700/41507207-ec4848b2-71fb-11e8-8ff9-9b45a107bc81.png)

**Comment by rlantz-cfa** [comment] 2018-06-18 20:27
Okay.  So I get that That region is "Somaliland", but including that `country name` in my data doesn't help.  I can't for the life of me find a reference in the documentation for the list of country names used to geo-rectify the values.

**Comment by rlantz-cfa** [comment] 2018-06-18 20:36
This appears to be a bug, as all of the ISO lists I can find do not contain Somaliland, and the `country name` options appear to follow the ISO lists.

**Comment by jonmmease** [comment] 2018-08-04 13:41
Hi @rlantz-cfa ,

Thanks for reporting this. I'm not very familiar with the inner workings of the Choropleth trace or how ISO lists work. Could you elaborate on where you think the problem is?

If there's a bug in the plotly trace this would need to be handled by the Plotly.js project first (https://github.com/plotly/plotly.js), so we may want to move the discussion to an issue of there.

**Comment by rlantz-cfa** [comment] 2018-08-05 13:59
Sure.  The map data that defines the outline for Somalia does not include the region known as Somaliland.  Somaliland has declared independence, but is not recognized internationally (hence not in the ISO list).  The issue is in the data that is used to define Somalia's boundary.  Either make an addition to the ISO list that plotly references (internally) or fix the bounding points that make up the Somalia polygon.  I have no idea where those are defined, but you're probably right that it needs to be done in the JS.

**Comment by jonmmease** [comment] 2018-09-23 10:30
I'm going to close this here for now, but feel free to open a discussion issue with the plotly.js project (https://github.com/plotly/plotly.js) so we can work through this with that team. Thanks!

**Closed by jonmmease** 2018-09-23 10:30 UTC
Labels: plotly.js
