### ISSUE TITLE
external Orca server: pio.orca.status should have a more helpful output

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.py#2222] opened 2020-02-21 19:11 UTC
As reported from user @hiramf (https://github.com/plotly/orca/issues/279#issuecomment-5897900690), when using an external orca server, the output of `pio.orca.status` is not very user-friendly:

```ipython
>>> pio.orca.status
orca status
-----------
    state: unvalidated
    executable: None
    version: None
    port: None
    pid: None
    command: None
```
It should at least display the URL of the server and ideally ping it to tell the user whether it's working/accessible.

**Comment by gvwilson** [comment] 2024-06-14 13:07
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:07 UTC
Labels: documentation
