### ISSUE TITLE
Polar Chart: automatically set axes limit to [min, max] of data

### ISSUE THREAD

**Issue by phaabe** [plotly/plotly.py#2012] opened 2019-12-19 19:26 UTC
Hey there,

I wish to set the range of each r-axis of the polar chart automatically to the maximum and minimum of the underlying data. 

```
fig = go.Figure()
fig.add_trace(go.Scatterpolar(
      r=[12662.5, 95960.0, 301275.0, 12662.5],
      theta=['a','b','c','a'],
      fill = None,
      name='anomaly',
      line={ 'color': 'red'},
      marker=dict(size=8,
                              line=dict(width=0.5,
                                        color='DarkSlateGrey')),
      mode=None,
      opacity=1
))
fig.update_yaxes(autorange=True, fixedrange= False)
fig.show()
```

update_yaxes() doesn't have any effect. Also there seems to be no specific function to update for r-axes. 

is this a missing feature or do I miss anything here?

thank you in advance for your replies!

**Comment by gvwilson** [comment] 2024-06-14 13:10
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:10 UTC
