### ISSUE TITLE
Non-unique x/y labels disappear in heatmap

### ISSUE THREAD

**Issue by bastings** [plotly/plotly.py#930] opened 2018-02-02 15:43 UTC
For some use cases of using heat maps, column/row labels are not uniqu. E.g. in machine translation, an alignment between two sentences is often expressed as a heatmap where a certain word can appear multiple times on an axis.

Steps to see the issue:

```
import plotly.plotly as py
import plotly.graph_objs as go

trace = go.Heatmap(z=[[1, 20, 30, 50, 1], [20, 1, 60, 80, 30], [30, 60, 1, -10, 20]],
                   x=['A', 'B', 'B', 'C', 'D'],
                   y=['X', 'Y', 'Z'])
data=[trace]
py.iplot(data, filename='labelled-heatmap')
```

Here one label 'B' disappears and subsequent labels are mis-aligned.
It would be great if this can be fixed, so that the result would be labels`['A', 'B', 'B', 'C', 'D']`

**Comment by jonmmease** [comment] 2018-09-22 22:40
Hi @bastings, thanks for the report! This would need to be handled in Plotly.js, so I'm going to close this as a duplicate of https://github.com/plotly/plotly.js/issues/1516, where there's been quite a bit of discussion on this already.  Feel free to add to that issue if you have concerns/use-cases that aren't covered. Thanks!

**Closed by jonmmease** 2018-09-22 22:40 UTC
