### ISSUE TITLE
Feature Request: Add Multi-category Support for Gantt Chart

### ISSUE THREAD

**Issue by mtwichan** [plotly/plotly.py#1468] opened 2019-03-18 18:48 UTC
It would be great if: https://github.com/plotly/plotly.js/pull/3300 (Multi-Category) supported  https://plot.ly/python/gantt/ (Plotly Gantt Chart). Currently at this moment it is unsupported.

**Comment by jonmmease** [comment] 2019-03-25 22:52
Thanks for the suggestion @matthewchan15

**Comment by gvwilson** [comment] 2024-06-13 19:25
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:25 UTC
Labels: enhancement
