### ISSUE TITLE
Plotly Express template margin issue

### ISSUE THREAD

**Issue by fullpwemium** [plotly/plotly.py#1689] opened 2019-07-25 20:18 UTC
Hello,

If I use px for a scatter plot with margin right and bottom set to 0, I get some strange margin on the right anyway 

```
fig = px.scatter(data, x='x', y='y')
fig.update(layout = go.Layout(margin=dict(t=0,r=0,b=40,l=40)))
```

The same works fine using 
```
fig = go.Figure()
```

If I try to set a default layout
```
import plotly.io as pio          # to set mine plot layout
pio.templates['mine'] = pio.to_templated(go.Figure().update_layout(plot_bgcolor='rgba(200,200,200,1)',legend=dict(orientation="h",y=1.1, x=.5, xanchor='center'),margin=dict(t=0,r=0,b=40,l=40))).layout.template
pio.templates.default = 'mine'
```

It works fine for 

```
fig = go.Figure()
```

but for

```
fig = px.scatter(data, x='x', y='y')
fig.show()
```

I get large padding on top, and the same weird little bit on the right.

I refer to the margin on the right as weird because when I do 

```
fig.layout
```

I only se

```
'margin': {'t': 60},
```

Even if I do 

```
fig.update(layout = go.Layout(margin=dict(t=0,r=0,b=40,l=40)))
```

afterwards, I still have the weird right margin. No the same issue with go.Figure()

**Comment by fullpwemium** [comment] 2019-07-25 22:30
Strangest thing, passing in title=" " (or just any title) applies my margins for px.line

**Comment by nicolaskruchten** [comment] 2019-07-25 23:00
So PX does do things a bit differently when the title is present: https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/express/_core.py#L1026

But I’m not sure why this would result in the behaviour described above. I’ll dig into it :)

**Comment by fullpwemium** [comment] 2019-07-25 23:12
Hi @nicolaskruchten thanks for looking at the issue

I think I found it?

https://github.com/plotly/plotly_express/blob/f6b513fbad2b7171c729f9ef0b4c77d27afebb21/plotly_express/_core.py

Line 865
```
if "title" not in layout_patch:
        layout_patch["margin"] = {"t": 60}
```

what do you think? I'm using conda otherwise I'd mess with the source

**Comment by nicolaskruchten** [comment] 2019-07-26 00:46
PX does this just to balance the whitespace above and below the plot... perhaps it's too opinionated. I'm still not sure why it impacts the right margin.

**Comment by fullpwemium** [comment] 2019-07-26 01:18
@nicolaskruchten any ideas on how to fix the issues if we have a template with margins  set to 0

**Comment by fullpwemium** [comment] 2019-07-26 11:48
@nicolaskruchten investigating further, the weird padding is added to both left and right - if this helps

**Comment by nicolaskruchten** [comment] 2019-07-26 18:24
So I can't replicate the differences you're seeing with and without title, but I can explain why `px`-created figures have what appears like a bit more right-margin. It's because of the `xaxis.domain` which is set to `[0, 0.98]` for a single-subplot `px` figure, rather than the default `[0,1]`.

**Comment by fullpwemium** [comment] 2019-07-27 05:48
@nicolaskruchten thanks for the hint - it is indeed xaxis.domain. Unfortunately setting this to [0,1] in my template is ignored by plotly.express, I have to use fig.update_layout(xaxis=dict(domain=[0,1])) after every figure...

I will try put a MWE for the title issue soon

**Comment by nicolaskruchten** [comment] 2019-07-27 17:55
Yes, the domains are set explicitly from within PX, so it will never respect the template settings.

That said, @jonmmease what's the reasoning for having the single-subplot case have a domain that's not `[0,1]` ? Is this something I had in the pre-`make_subplots` version that got carried over or is it something that `make_subplots` does or...?

**Comment by gvwilson** [comment] 2024-06-13 19:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:42 UTC
