### ISSUE TITLE
create_ternary_contour get wrong if all values are same

### ISSUE THREAD

**Issue by y-uti** [plotly/plotly.py#2098] opened 2020-01-19 00:17 UTC
Example (enthalpy is set to 1 for all points)
```
import plotly.figure_factory as ff
import numpy as np
Al = np.array([0. , 0. , 0., 0., 1./3, 1./3, 1./3, 2./3, 2./3, 1.])
Cu = np.array([0., 1./3, 2./3, 1., 0., 1./3, 2./3, 0., 1./3, 0.])
Y = 1 - Al - Cu
enthalpy = np.ones(Al.shape) # set enthalpy to 1 for all points
fig = ff.create_ternary_contour(np.array([Al, Y, Cu]), enthalpy,
                                pole_labels=['Al', 'Y', 'Cu'],
                                interp_mode='cartesian')
fig.show()
```

Result:
![newplot](https://user-images.githubusercontent.com/3460059/72672371-2b100200-3a9c-11ea-8f5e-5e29d68cb86c.png)

Note that 2d-contour works well (i.e. filled by a single color) for such a setting.

**Comment by emmanuelle** [comment] 2020-01-21 15:32
Thank you for the bug report @y-uti. It's a corner case but it really does not look good. What would you expect in such a case? A completely flat area with a single color? One problem is that the concept of contours is hard to defined for a completely uniform field...

**Comment by y-uti** [comment] 2020-01-22 00:37
Hi @emmanuelle,

> A completely flat area with a single color?

Yes. I think it is a good choice for Plotly, because 2d contour does so.
```
import plotly.graph_objects as go

fig = go.Figure(data=go.Contour(z=[[1] * 10] * 10))
fig.show()
```
![newplot](https://user-images.githubusercontent.com/3460059/72855337-74f62380-3cfa-11ea-9637-7ff7efeb1d98.png)

**Comment by gvwilson** [comment] 2024-06-14 13:09
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:09 UTC
Labels: bug
