### ISSUE TITLE
px continuous color scale range adjustment when used in Dash callback

### ISSUE THREAD

**Issue by DrGFreeman** [plotly/plotly.py#1917] opened 2019-11-22 03:31 UTC
When updating the `color` parameter of a plotly_express scatter plot from a `dcc.Dropdown` within a Dash call back and returning the output of the scatter plot into the `'figure'` property of a `dcc.Graph`, the range of the color scale (continuous) can increase if the range of the data passed to `color` increases but does not decrease automatically if the range of the data decreases.

The callback function is the following:

```python
@app.callback(Output("graph", "figure"),
              [Input('x', 'value'),
               Input("y", "value"),
               Input("couleur", "value")])
def update_graph(x, y, couleur):
    fig = px.scatter(days, x=x, y=y, color=couleur, hover_data=days.columns)
    return fig 
```

The issue can be observed in this demo app: https://flask.urandom.xyz/boltev/

1. Refresh the app to get the default parameter of the "Variable couleur" dropdown. The range of the color scale is -22 to 30.
2. Change the "Variable couleur" dropdown to "fraction battery utilisée". This variable has a range of 0 to 1 but the color scale still shows -22 to 30 hence all the points have approximately the same color.
3. Change the "Variable couleur" dropdown to "distance (km)". The colorscale changes to ~< 0 to ~420.
4. Change the "Variable couleur" dropdown to "consommation (kWh/100km)". This variable has a range of 12 to 32 approx. Just as previously, the color scale keeps the larger range and the points show with a mostly uniform color.
5. Clear the "Variable couleur" dropdown. The color scale disappears (expected).
6. Set the "Variable couleur" dropdown back to "consommation (kWh/100km)". This time, the color scale matches the range of the data.

Playing a bit with the different variables and ranges, my conclusion is that the color scale min or max values will adjust only when the new min or max is outside the range or the previously rendered color scale. If a new variable with a range contained within the current range is passed, the color scale will not change at all.

The full code of the demo app is available at https://github.com/DamdlBT/BoltEV-Dash.

```
Package              Version  
-------------------- --------- 
dash                 1.4.0    
dash-core-components 1.3.0    
dash-html-components 1.0.1    
dash-renderer        1.1.1      
plotly               4.1.1    
plotly-express       0.4.1    
```

@emmanuelle, this is one of the two issues we discussed at the PyData meetup.

**Comment by emmanuelle** [comment] 2019-11-22 04:09
Hum, this one might be related to https://github.com/plotly/plotly.js/issues/4337 and https://github.com/plotly/dash-core-components/issues/702. Thanks for helping us investigate this problem!

**Comment by gvwilson** [comment] 2024-06-14 13:12
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:12 UTC
