### ISSUE TITLE
issue:bug Parallel Category plots rendering incorrectly on Safari

### ISSUE THREAD

**Issue by databyjp** [plotly/plotly.py#2303] opened 2020-03-21 04:22 UTC
Hi,

I wanted to report that parallel category plots appear to be rendering differently on my Safari than on Chrome.

This is the output html that I am looking to render ([link](http://demo.hindsights.io/202002_nba_travel_impact/parcat.html)):

On Safari, the parallel category plot sometimes renders with duplicate category titles sometimes, like shown below (see the underlined bits!):
<img width="951" alt="safari_parcat_render" src="https://user-images.githubusercontent.com/61258750/77219186-da815780-6b65-11ea-8c81-1877f3afbf0c.png">
It seems to be dependent on the window size, as far as I can tell. 

The same thing doesn't happen on Chrome:
<img width="1040" alt="Screen Shot 2020-03-21 at 11 21 39 am" src="https://user-images.githubusercontent.com/61258750/77219215-2d5b0f00-6b66-11ea-815e-ed5dede78b4e.png">

My version numbers are:
Safari: (Version 13.0.5 (15608.5.11))
Chrome: (Version 80.0.3987.149)
Mac: (OS X Catalina 10.15.3, 2019 MBP 13')

I used this code to generate the data, and the DataFrame is [here](http://demo.hindsights.io/temp/parcat_bug_demo_data.csv):
```
travel_cats = ['home', 'travelled']
fig = px.parallel_categories(box_df, dimensions=travel_cats, color='win_num')
fig.show()
```
Thanks!

**Comment by gvwilson** [comment] 2024-06-14 13:05
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:05 UTC
