### ISSUE TITLE
FigureWidget changes the pie chart textposition when using display to view FigureWidget plot

### ISSUE THREAD

**Issue by AbhishekKumarSingh** [plotly/plotly.py#1755] opened 2019-09-06 07:09 UTC
```python
import plotly.graph_objects as go
import plotly.offline as iplot
import plotly as py
import pandas as pd
from ipywidgets.widgets import Output, HBox, VBox

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv')

val_counts = df.Postal.value_counts()
labels, values = list(val_counts.to_dict().keys()), list(val_counts.to_dict().values())

fig = go.Figure(data=[go.Pie(labels=labels, values=values, hole=0.5, textinfo='percent')])
#fig.show()

fw = go.FigureWidget(fig)

display(fw)
fw.show()
```

In the above code plot generated by `display(fw)` has textposition outside the pie chart. While fw.show() keeps the textposition intact as inside.

If I explicitly provide `textposition` info while creating a figure then both `display(fw)` and `fw.show()` generates same figure with the given textposition. Check the code below.

```python
import plotly.graph_objects as go
import plotly.offline as iplot
import plotly as py
import pandas as pd
from ipywidgets.widgets import Output, HBox, VBox

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv')

val_counts = df.Postal.value_counts()
labels, values = list(val_counts.to_dict().keys()), list(val_counts.to_dict().values())

fig = go.Figure(data=[go.Pie(labels=labels, values=values, hole=0.5, textinfo='percent', textposition='inside')])
#fig.show()

fw = go.FigureWidget(fig)

display(fw)
fw.show()
```

**Comment by gvwilson** [comment] 2024-06-13 19:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:49 UTC
