### ISSUE TITLE
Missing lines from Scatter3d when using write_image

### ISSUE THREAD

**Issue by JoshuaMitton** [plotly/plotly.py#1608] opened 2019-06-13 11:14 UTC
When using plotly.io.write_image from a jupyter notebook errors are printed to the terminal and the edges are missing from the saved plot. The error message is as follows, repeated numerous times:

`[28579:0613/120605.989566:ERROR:gles2_cmd_decoder.cc(10172)] [.Offscreen-For-WebGL-0x3c096949300]RENDER WARNING: Render count or primcount is 0.`

This is using jupyter notebooks in a conda environment and on Ubunutu. Files given below were installed:

`conda install -c plotly plotly-orca psutil`

This issue does not occur when displaying the graph and using the GUI save feature.

**Comment by gvwilson** [comment] 2024-06-13 19:33
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:33 UTC
