### ISSUE TITLE
optional_imports: Improve Warnings/Dependencies

### ISSUE THREAD

**Issue by aberndsen** [plotly/plotly.py#1038] opened 2018-06-21 12:56 UTC
I was trying to use the plotly.figure_factory.create_violin but it failed with warning 
NoneType does not have attribute gaussian_kde

It took a while for me to trace this to _violin.py, and realize that 
scipy_stats = optional_imports.get_module('scipy.stats')
was returning None.

I was working in a "fresh" virtual environment, with the following requirements:
dash==0.21.1
dash-core-components==0.23.0
dash-html-components==0.11.0
dash-renderer==0.13.0
dash-table-experiments==0.6.0
plotly==2.7.0

You can confirm scipy_stats is `None` by working in this virtualenvironment::
`
import plotly

from plotly import optional_imports
scipy_stats = optional_imports.get_module('scipy.stats')
type(scipy_stats)
`

The request is to make scipy a dependency of plotly, or improve the verbosity of the 'optional_imports' routine.

**Comment by jonmmease** [comment] 2018-08-04 13:13
Thanks for bringing this up @aberndsen , and for diagnosing the issue.

Yeah, the `create_violin` figure factory should check to make sure it's dependencies are available and say something helpful if not.

As a side note, in case you weren't aware, Plotly now has a first class violin trace (https://plot.ly/python/violin/) that's more flexible than the legacy figure factory approach here.

**Comment by gvwilson** [comment] 2024-06-13 17:41
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:41 UTC
Labels: documentation
