### ISSUE TITLE
Method to access traces by name

### ISSUE THREAD

**Issue by vlizanae** [plotly/plotly.py#1159] opened 2018-09-06 03:41 UTC
I have been working a lot with Widgets and FigureWidgets lately and I think it would be useful to be able to access some trace in a figure by its name. For example, several times I've come across the situation where I have to set a Widget to change something in each of the traces separately and the handlers typically look like this:
```python
def do_something(change):
    with fig.batch_animate():
        for trace in fig.data:
            if trace.name == 'some_name':
                change_something()
```
or as a workaround I sometimes use a lookup dictionary in the format `{name: index_in_data_list}`.
```python
def do_something(change):
    with fig.batch_animate():
        fig.data[lookup['some_name']].some_attr = something
```
nothing too important, I just think it would be a nice feature to be able to do
```python
def do_something(change):
    with fig.batch_animate():
        fig.get_trace(name='some_name').some_attr = something
```
without having to handle the lookup manually (maybe there's already something like this that I don't know about).

**Comment by jonmmease** [comment] 2018-09-06 12:58
Hi @vlizanae , this is an interesting idea. Here are a couple of details that would need to be worked out.
 - Is a linear search acceptable (performance wise), or would we need to maintain a map from trace names to trace objects/indexes? Keeping this map up to date would require a bit of effort in a few places in the code base.
 - What happens if two traces have the same name?
 - What happens if no trace by that name is present?

**Comment by vlizanae** [comment] 2018-09-08 00:15
Those are good points. In my opinion:

- A linear search is fine, as the number of traces shouldn't be that large in most of the cases.
- I never thought about two traces having the same name before, probably the most consistent way is if the method returns a list with all the corresponding traces, that would also solve the problem where the name is not present.

**Comment by gvwilson** [comment] 2024-06-13 17:39
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:39 UTC
Labels: enhancement
