### ISSUE TITLE
deprecation warning in mpl_to_plotly

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1606] opened 2019-06-11 14:24 UTC
The is_frame_like function was deprecated in Matplotlib 3.1 and will be removed in 3.3.

/Users/nicolas/miniconda2/envs/nb/lib/python3.6/site-packages/plotly/matplotlylib/mpltools.py:368: MatplotlibDeprecationWarning:

**Comment by jonmmease** [comment] 2019-06-15 12:43
Do you know what the suggested replacement is?

**Comment by ndrezn** [comment] 2020-08-11 16:06
Checking to see if this issue was ever addressed--running into it when using `plotly.tools.mpl_to_plotly`, and it means that the function does not work when using the most recent version of matplotlib.

**Comment by nicolaskruchten** [comment] 2020-08-11 16:07
Not addressed, and will eventually stop working. I will probably deprecate `mpl_to_plotly` soon as we're not working on it at all.

**Comment by ndrezn** [comment] 2020-08-11 16:09
Any alternatives? Or should I just change the function to just remove the `mpl_to_plotly` requirement?

**Comment by gvwilson** [comment] 2024-06-13 19:33
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:33 UTC
