### ISSUE TITLE
on-prem accounts cannot upload with grid_ops, etc, from plotly.py

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.py#1189] opened 2018-09-20 17:44 UTC
PlotlyRequestError - bad API for grid_ops, dashboard_ops, presentation_ops in plotly.py

Using buildly(on-prem)

```python
import plotly 
plotly.tools.set_config_file(plotly_domain='https://buildly.plotly.systems/',
                                             plotly_ssl_verification=False)
plotly.tools.set_credentials_file(username=xxxxxxx, api_key=xxxxxxxxxx)
```

`.upload` functions for dashboard_ops, presentation_ops, grid_ops, are not working. For grid_ops, the following error gets returned

```
---------------------------------------------------------------------------
PlotlyRequestError                        Traceback (most recent call last)
<ipython-input-9-f4e8f29b5161> in <module>()
      4 column_2 = Column([4, 2, 5], 'voltage')
      5 grid = Grid([column_1, column_2])
----> 6 py.grid_ops.upload(grid, 'time vs voltage')

/Users/adamkulidjian/Desktop/Adam/plotly/plotly.py/plotly/plotly/plotly.pyc in upload(cls, grid, filename, world_readable, auto_open, meta)
   1009             payload['parent_path'] = parent_path
   1010 
-> 1011         response = v2.grids.create(payload)
   1012 
   1013         parsed_content = response.json()

/Users/adamkulidjian/Desktop/Adam/plotly/plotly.py/plotly/api/v2/grids.pyc in create(body)
     16     """
     17     url = build_url(RESOURCE)
---> 18     return request('post', url, json=body)
     19 
     20 

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/retrying.pyc in wrapped_f(*args, **kw)
     47             @six.wraps(f)
     48             def wrapped_f(*args, **kw):
---> 49                 return Retrying(*dargs, **dkw).call(f, *args, **kw)
     50 
     51             return wrapped_f

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/retrying.pyc in call(self, fn, *args, **kwargs)
    204 
    205             if not self.should_reject(attempt):
--> 206                 return attempt.get(self._wrap_exception)
    207 
    208             delay_since_first_attempt_ms = int(round(time.time() * 1000)) - start_time

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/retrying.pyc in get(self, wrap_exception)
    245                 raise RetryError(self)
    246             else:
--> 247                 six.reraise(self.value[0], self.value[1], self.value[2])
    248         else:
    249             return self.value

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/retrying.pyc in call(self, fn, *args, **kwargs)
    198         while True:
    199             try:
--> 200                 attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
    201             except:
    202                 tb = sys.exc_info()

/Users/adamkulidjian/Desktop/Adam/plotly/plotly.py/plotly/api/v2/utils.pyc in request(method, url, **kwargs)
    166         content = response.content if response else 'No content'
    167         raise exceptions.PlotlyRequestError(message, status_code, content)
--> 168     validate_response(response)
    169     return response

/Users/adamkulidjian/Desktop/Adam/plotly/plotly.py/plotly/api/v2/utils.pyc in validate_response(response)
     78         message = content if content else 'No Content'
     79 
---> 80     raise exceptions.PlotlyRequestError(message, status_code, content)
     81 
     82 

PlotlyRequestError: Bad API key
```

**Comment by Kully** [comment] 2018-09-20 20:33
With further investigation, this looks like a v2 endpoint issue with on-prem domain names, eg. 'https://buildly.plotly.systems'

`py.sign_in()` returns an error message, even though having those credentials filled out in the credentials file doesn't create any errors for producing a plain scatter:

eg.
```
import plotly.plotly as py
py.iplot([{'x': range(10), 'y': range(10)}])
```
works fine

**Comment by cldougl** [comment] 2018-09-24 16:53
> py.sign_in() returns an error message

@Kully can you provide more information like what the error message is? Furthermore, can you test if this is an issue with version 3+ or did this work in plotly.py 2.7?

**Comment by cldougl** [comment] 2018-09-24 19:16
this issue will also affect `py.icreate_animations` https://plot.ly/python/animations/#online-mode

**Comment by Kully** [comment] 2018-09-24 21:43
> @Kully can you provide more information like what the error message is?

`PlotlyRequestError: Bad API key`

Even making a get request under the same domain returns the same error:

```
from __future__ import absolute_import

from plotly.api.v2.utils import build_url, request

RESOURCE = 'users'
url = build_url(RESOURCE, route='current')
request('get', url)
```

**Comment by Kully** [comment] 2018-09-24 21:43
> Furthermore, can you test if this is an issue with version 3+ or did this work in plotly.py 2.7?

I've checked versions 2.7 and 3.5 - it is an issue in both of them

**Comment by Kully** [comment] 2018-09-25 19:58
I've been digging deeper into this bug and this is what I have so far.
---
To really figure out what's going on, I am testing a regular pro account against an on-prem account. I am making a bare bones `get` request to USERS endpoint of v2 since that is where the problem lies (iplot and plot work fine for on-prem users AFAIK)

```python
v2.utils.request('get', 'https://api.plot.ly/v2/users/current')
```

The issue seems to be hovering around the authorization key that is passed in headers of the request body, with the form `Basic {username_encoded}{api_encoded}`

#### pro account
For the pro account, the `authorization` value doesn't make a difference. We get a **200**

#### on-prem account
2. For the on-prem account, a correct `authorization` value (what gets passed normally) returns a **401**: `PlotlyRequestError: Bad API key`

Say the normally computed authorization key is `'Basic Y2hlbHNlYTplQTA3d1Uwb2g5dVNOODNvNnFRdQ='`

then...

`'Basic Y2hlbHNlYTplQTA3d1Uwb2g5dVNOODNvNnFRdQ='` -> 401
`''` -> 200
`'B Y2hlbHNlYTplQTA3d1Uwb2g5dVNOODNvNnFRdQ='` -> 200
`'Y2hlbHNlYTplQTA3d1Uwb2g5dVNOODNvNnFRdQ='` -> 200

I can even change the word Basic to Rasic, or B and I still get a 200
---
NB
I am testing with `https://buildly.plotly.systems`
`requests` version - 2.10.0

**Comment by gvwilson** [comment] 2024-06-13 17:39
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:39 UTC
Labels: bug, plot.ly, legacy-versions
