### ISSUE TITLE
Buttons: update method not behaving as expected

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2328] opened 2020-03-28 07:27 UTC
In the doc example https://plotly.com/python/custom-buttons/#update-button, traces are not updated as planned when clicking on the buttons. Curiously, removing the layout part or switching to restyle method instead of update makes it work again.

Next step: make a codepen to submit an issue in plotly.js.

**Comment by emmanuelle** [comment] 2020-03-28 09:18
Update: the problem only exists in Firefox, not in Chrome.

**Comment by gvwilson** [comment] 2024-06-14 13:04
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:04 UTC
Labels: bug
