### ISSUE TITLE
subplot_titles fails with more than 2 titles.

### ISSUE THREAD

**Issue by lordlycastle** [plotly/plotly.py#874] opened 2017-11-08 12:06 UTC
Create a figure as shown below, and supplying tiles results in `list index out of range` error. And it's not even my list that is raising this. So this is a bug in plotly.

````
figure = tools.make_subplots(rows=3,
                                 cols=3,
                                 specs=[[{'is_3d': True}, {'rowspan': 3, 'colspan': 2, 'is_3d': False}, None],
                                        [{'is_3d': True}, None, None],
                                        [{'is_3d': False}, None, None]],
                                 subplot_titles=['1', '2', '',
                                                 '4', '', '',
                                                 '5', '', ''],
                                 # I've also tried this.
                                # subplot_titles=['1', '2', '4', '5'],
                                 )

# Here is the code where it raises the error. 
# It's obviously not the subplot_titles list I supply that is causing it.
plot_titles = []
    for index in range(len(subplot_titles)):
        if not subplot_titles[index]:
            pass
        else:
            plot_titles.append({'y': subtitle_pos_y[index],
                                'xref': 'paper',
                                'x': subtitle_pos_x[index],
                                'yref': 'paper',
                                'text': subplot_titles[index],
                                'showarrow': False,
                                'font': graph_objs.Font(size=16),
                                'xanchor': 'center',
                                'yanchor': 'bottom'
                                })

            layout['annotations'] = plot_titles
````

**Comment by empet** [comment] 2017-11-08 12:22
@lordlycastle Plotly doesn't work with  `subplot_titles` when there is at least one cell with a 3d plot.

**Comment by lordlycastle** [comment] 2017-11-20 16:58
Yeah I noticed. So do you guys plan on never adding that ability?

**Comment by jonmmease** [comment] 2018-09-22 22:03
Duplicate of https://github.com/plotly/plotly.py/issues/520

**Closed by jonmmease** 2018-09-22 22:03 UTC
