### ISSUE TITLE
Text Orientation -plotly express horizontal bar

### ISSUE THREAD

**Issue by bangxiangyong** [plotly/plotly.py#1719] opened 2019-08-12 10:30 UTC
The text orientation of the bar values doesn't seem right, is there a way to rotate it to be correct? 

![image](https://user-images.githubusercontent.com/8087472/62859295-9cc97000-bcf4-11e9-933a-b0f4011c95e3.png)

**Comment by gvwilson** [comment] 2024-06-13 19:45
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:45 UTC
