### ISSUE TITLE
Most markers not visible unless chart is double-clicked with plotly.express `animation_frame`

### ISSUE THREAD

**Issue by eliasdabbas** [plotly/plotly.py#1674] opened 2019-07-20 19:01 UTC
Creating an animated `plotly.express` chart using `animation_frame` works fine, but I realized that when selecting a certain value on the slider, most markers are not visible. It all works fine when I double click on the chart. 

`plotly==4.0.0`
`pandas==0.24.2`

```
import random
import plotly.express as xp
import pandas as pd
import plotly

df = pd.DataFrame({
    'date': pd.date_range('2019-01-01', '2019-12-31'),
    'number': random.choices(range(1,200), k=365)
    
})
df['month'] = df['date'].dt.month
df.head()

	date	      number	 month
0	2019-01-01	152	1
1	2019-01-02	127	1
2	2019-01-03	39	1
3	2019-01-04	195	1
4	2019-01-05	69	1

xp.scatter(df, x='date', y='number', animation_frame='month')
```
Selecting month 6 gives the following empty chart: 

<img width="971" alt="Screen Shot 2019-07-20 at 10 55 01 PM" src="https://user-images.githubusercontent.com/15708966/61582887-91de4e00-ab41-11e9-901d-aeaf5cf7022d.png">

After double-clicking the chart it looks fine: 

<img width="959" alt="Screen Shot 2019-07-20 at 10 55 10 PM" src="https://user-images.githubusercontent.com/15708966/61582889-a15d9700-ab41-11e9-887e-9ebffdb19526.png">

Any idea what might be causing that? 
Thanks!

**Comment by jonmmease** [comment] 2019-07-21 09:50
Hi @eliasdabbas, thanks for taking the time to report this.  Do you seem the same behavior when using a numeric (rather than datetime) x-axis?

Do you have any ideas on this @nicolaskruchten?

**Comment by eliasdabbas** [comment] 2019-07-21 10:33
Thanks @jonmmease  
I just tried with a numeric x-axis. Yes, the issue is still there.

**Comment by nicolaskruchten** [comment] 2019-07-21 19:05
The issue is that when using `animation_frames`, the axis range is computed using only the initial frame (at the moment) meaning that you must manually set the x and y range to include all of the data when animating, in order for data to be visible in all frames.

This is unfortunate, and we'll try to automate it in the future :)

**Comment by eliasdabbas** [comment] 2019-07-22 22:28
Interesting feature actually. I tried setting `range_x` and `range_y`, and the behavior is now different. It shows the whole range, as if hiding everything but the selected month. 

There might be an issue though, and here is what I'm getting using the same data frame: 

```
xp.scatter(df, x='date', y='number', animation_frame='month', 
           range_x=[df['date'].min(), df['date'].max()],
           range_y=[df['number'].min(), df['number'].max()]
          )
```

<img width="356" alt="Screen Shot 2019-07-23 at 12 21 45 AM" src="https://user-images.githubusercontent.com/15708966/61669323-e4557100-acdf-11e9-9eb4-86016f6fde00.png">

Moving from month 1 to 2 to 3, I get the above. 

Now, double-clicking any month, would expand the points to cover the whole chart. Clicking month 3, for example, would limit the x range of the chart to that month:

<img width="866" alt="Screen Shot 2019-07-23 at 12 23 00 AM" src="https://user-images.githubusercontent.com/15708966/61669371-1f57a480-ace0-11e9-9978-a56126f9322a.png">


Now, if I go to another month, say 8, it shows an empty chart, because the x range is now defined as month 3. You would have to double click again to show data points of month 8.  

<img width="869" alt="Screen Shot 2019-07-23 at 12 24 39 AM" src="https://user-images.githubusercontent.com/15708966/61669418-4c0bbc00-ace0-11e9-80b5-b503978ecea5.png">

Is this the intended behavior, or is there any way to get the user to click on a month and get that month's points without double-clicking? Because it would seem that are no data points and the user might think there is nothing there. 
Thanks

**Comment by nicolaskruchten** [comment] 2019-07-23 14:41
This is, unfortunately, the intended behaviour at the moment: the slider does not impact the range of the chart.

**Comment by eliasdabbas** [comment] 2019-07-23 15:24
I see. OK, thanks!

**Comment by joelostblom** [comment] 2019-11-04 23:52
Are the axes ranges set to the extent of the data in the first frame before plotting or are they automatically adjusted after the data points have been plotted on the canvas? If the former, would it be possible to set the axes to the extent of the entire data set instead of the data to be added to the first frame? If it is the latter, I guess all the frames need to be looped through and the min/max axes values recorded and then used to readjust all frames?

**Comment by nicolaskruchten** [comment] 2019-11-05 01:25
Today Plotly.js auto-ranges to the first frame, but in the near future it will actually transition ranges as well as data, and/or internally auto-range all frames. I don't want to code this into the Python layer at this time as undoing that to defer to the JS layer would cause unnecessary churn.

Today the recommendation is to manually set the ranges on your animations to ensure things look good in all frames.

**Comment by gvwilson** [comment] 2024-06-13 19:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:42 UTC
