### ISSUE TITLE
Links in tables not properly working

### ISSUE THREAD

**Issue by tlhendri** [plotly/plotly.py#1687] opened 2019-07-25 13:51 UTC
When configuring a anchor in a data cell, link formatting is displayed in browser but link does not properly function.

Using from https://plot.ly/python/table/#basic-table
```
import plotly.offline as poff
import plotly.graph_objects as go

fig = go.Figure(data=[go.Table(header=dict(values=['A Scores', 'B Scores']),
                 cells=dict(values=[['<a href=www.github.com>100</a>', 90, 80, 90], [95, 85, 75, 95]]))
                     ])

poff.plot(fig, filename='test.html')
```
Also, when the anchor is configured as the cell value, cell fill color does not seem to be correctly applied.

**Comment by tz0604** [comment] 2021-01-10 00:05
did you try placing double quotes "" around www.github.com ?

**Comment by gvwilson** [comment] 2024-06-13 19:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:42 UTC
