### ISSUE TITLE
[Feature Request] use own style.json instead of mapbox access token

### ISSUE THREAD

**Issue by anderl80** [plotly/plotly.py#1431] opened 2019-02-09 11:28 UTC
I'd wish the package also offered the possibility to use a self defined style.json like when you use Mapbox natively in JS. Using this specification (and using OSM tiles) makes the mapbox_access_token obsolete.

**Comment by jonmmease** [comment] 2019-02-19 11:20
Hi @anderl80, thanks for your interest here.  Would you mind moving this issue to the plotly.js project at https://github.com/plotly/plotly.js?  This is where this kind of change would need to take place. Thanks!

**Comment by gvwilson** [comment] 2024-06-13 19:24
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:24 UTC
Labels: plotly.js
