### ISSUE TITLE
x-axis errorbars fail on Scatter with datetime axis

### ISSUE THREAD

**Issue by tomaszps** [plotly/plotly.py#1488] opened 2019-04-02 02:00 UTC
X-axis error bars do not show up when using date times with scatter plots. There's a small chance I'm just getting the syntax wrong here, but I've tried a bunch of variants. 

Reproducible example: (I ran this in a jupyter notebook but I've seen the same behavior in a dash app.)

```
import numpy as np
import pandas as pd
import time

import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.plotly as py

t0 = time.time()
t1 = t0 + 1e2
t2 = t0 + 2e2

xs = pd.to_datetime(np.array([t0,t1,t2])*1e9)

data = [
    go.Scatter(
        x=xs,
        y=[6, 10, 2],
        error_x=dict(
            type='data',
            array=[pd.to_datetime(t2*1e9)-pd.to_datetime(t1*1e9), pd.to_datetime(t2*1e9)-pd.to_datetime(t1*1e9),  pd.to_datetime(t2*1e9)-pd.to_datetime(t1*1e9)],
            visible=True
        )
    )
]

iplot(data)


data = [
    go.Scatter(
        x=xs,
        y=[6, 10, 2],
        error_x=dict(
            type='data',
            symmetric=False,
            array=[pd.to_datetime(t2*1e9), pd.to_datetime(t2*1e9), pd.to_datetime(t2*1e9)],
            arrayminus=[pd.to_datetime(t1*1e9), pd.to_datetime(t1*1e9), pd.to_datetime(t1*1e9)],
            visible=True
        )
    )
]

iplot(data)

data = [
    go.Scatter(
        x=xs,
        y=[6, 10, 2],
        error_x=dict(
            type='data',
            array=[t1-t2, t1-t2, t1-t2],
            visible=True
        )
    )
]

iplot(data)
```

**Comment by jonmmease** [comment] 2019-04-04 09:42
Thanks for the report @Sakrejda-atsu, I've opened https://github.com/plotly/plotly.js/issues/3722 in the plotly.js project to discuss with the plotly.js team.  One note is that for ploty.js, the numeric representation of dates is in milliseconds rather than nanoseconds (like pandas).

So the example that I would have expected to work is

```python
import numpy as np
import pandas as pd
import time

import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode()

t0 = time.time()
t1 = t0 + 1e2
t2 = t0 + 2e2

xs_numeric = np.array([t0,t1,t2])*1e3
xs = pd.to_datetime(xs_numeric)

data = [
    go.Scatter(
        x=xs_numeric,
        y=[6, 10, 2],
        error_x=dict(
            type='data',
            array=[t2*1e3 - t1*1e3, t2*1e3 - t1*1e3,  t2*1e3 - t1*1e3],
            visible=True
        )
    )
]

layout = go.Layout(xaxis={'type': 'date'})

fig = go.Figure(data, layout=layout)
iplot(fig)
```
![newplot-6](https://user-images.githubusercontent.com/15064365/55545968-57d56300-569c-11e9-9bd7-5b02f0529bfc.png)

But still no error bars appear.

**Comment by thatneat** [comment] 2019-10-28 23:24
as you might expect, the same issue occurs in plotly express. I did something generally like:
```python
px.scatter(
    my_df,
    x='timestamp',
    y='some numeric column',
    error_x='timedelta column'
)
```
changing `error_x` to `error_y` makes the error bars show up on the numeric axis, but they won't show up on the X axis where I want them.

**Comment by tomaszps** [comment] 2020-04-20 04:30
In the end I went with gantt charts for representing this type of data/prediction. I hope it may serve as a useful alternative for anyone who looks up this issue. I probably should have started there anyway, given what I was trying to represent.

**Comment by gvwilson** [comment] 2024-06-13 19:27
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:27 UTC
Labels: bug, plotly.js
