### ISSUE TITLE
docs: write_html/to_html

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1959] opened 2019-06-23 11:47 UTC
Any use of `plotly.offline.plot(filename=...)` for the purpose of writing out html should be replaced with `fig.write_html(...)`

Maybe we should replace https://plot.ly/python/html-reports/ with some simple examples of writing out figures as standalone html files with `fig.write_image`.  

PR docs for `write_image` in https://github.com/plotly/plotly.py/pull/1474

**Comment by gvwilson** [comment] 2024-06-13 19:33
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:33 UTC
