### ISSUE TITLE
graphs from plotly >= 5.8 don't render in databricks

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/plotly.py#3756] opened 2022-06-02 15:57 UTC
displaying a python figure in an iframe within databricks works with plotly==5.7 but when I attempt to do it using 5.8 it fails with `Uncaught SyntaxError: Unexpected token '&&'`:

![Screenshot from 2022-06-02 10-56-02](https://user-images.githubusercontent.com/41019918/171659221-e7f7e274-c6bd-4822-8a66-1ac4825fa236.png)

**Comment by fwetdb** [comment] 2022-06-07 19:20
**How to fix:**
1. by plotly: publish a new plotly version on Pypi that fixes this error
2. by users:
Until the fix is released by plotly on pypi, users can self-fix via adding the following code to their python scripts or notebooks:
```python
import plotly.io._html as piohtml
piohtml._mathjax_config = """<script type="text/javascript">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>"""
```

**Background:**
This error also affects Databricks notebooks with plotly==5.8.0
I stumbled across this as part of my work for Databricks.

The root cause of the error is in https://github.com/plotly/plotly.py/blob/HEAD/packages/python/plotly/plotly/io/_html.py#L23

There is a duplicate, consequent `&&`

The line should say:
```if (window.MathJax && window.MathJax.Hub && && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}\```

**Comment by nicolaskruchten** [comment] 2022-06-07 19:22
Thanks @fwetdb! I'm embarrassed that that got through code review 🙈

**Comment by fwetdb** [comment] 2022-06-07 19:28
You're welcome! I am glad that I could help! Without plotly being so widely used and open-source at the same time, this fix (including the investigation) would have been neither needed nor possible.

What are your thoughts on the timeline when the fix can be released, @nicolaskruchten ?
Should I open a PR or will you do it internally?

**Comment by nicolaskruchten** [comment] 2022-06-07 19:50
No need for a PR, I can do it. I will try to do a point release tonight or tomorrow morning.

**Comment by fwetdb** [comment] 2022-06-07 20:14
Awesome, thank you for the fast reaction!

**Comment by fwetdb** [comment] 2022-06-07 21:58
There is a stackoverflow question that relates to this. I wanted to comment but I do not have enough reputation for that. Also, I was not able to answer.

Can someone please refer them to here?
https://stackoverflow.com/questions/72466969/plotly-uncaught-syntaxerror-unexpected-token

**Comment by nicolaskruchten** [comment] 2022-06-08 13:37
@fwetdb I can't reply to a closed question either, sorry

**Comment by nicolaskruchten** [comment] 2022-06-08 13:37
(actually I can comment, and I did)

**Comment by nicolaskruchten** [comment] 2022-06-08 14:43
https://github.com/plotly/plotly.py/releases/tag/v5.8.1 is out!

**Comment by fwetdb** [comment] 2022-06-09 21:53
I tried to verify the bug fix but it seems to me like the release does not contain the new code?

Here is what I executed in a cell in a binder notebook e.g. the one at bamboolib.com/demo
```python
!pip install plotly==5.8.1

import plotly
plotly.__version__ # 5.8.1

import plotly.io._html as piohtml
display(piohtml._mathjax_config)  # still contains the duplicate &&

import plotly.express as px
df = px.data.medals_long()

fig = px.bar(df, x="medal", y="count", color="nation")
fig
```

This still shows the error (because the mathjax config is still the old one).

What do you think @nicolaskruchten ?

**Comment by nicolaskruchten** [comment] 2022-06-10 14:41
Huh, that's very strange. I'll admit I didn't do this check myself, I merged the PR and ran the build process so something must be wrong with the build process :(

I'll dig into it and do another release. Sorry!

**Comment by nicolaskruchten** [comment] 2022-06-10 15:06
Another release, coming up!

**Comment by nicolaskruchten** [comment] 2022-06-10 16:46
OK here we go: https://github.com/plotly/plotly.py/releases/tag/v5.8.2

Sorry and thanks for pointing this out :)

**Closed by nicolaskruchten** 2022-06-10 16:46 UTC

**Comment by fwetdb** [comment] 2022-06-10 17:44
Great, thank you and I validated that 5.8.2 works as expected.
Again, awesome response time!
