### ISSUE TITLE
Multiple figures on a single page without using subplot.

### ISSUE THREAD

**Issue by syamajala** [plotly/plotly.py#1642] opened 2019-06-28 11:09 UTC
It would be nice if subplot could be abstracted away in the case where you only want a single row (or column) of plots and just want to scroll left/right (or up/down). 

Ideally, I would like to just be able to make individual figures and maybe have some object with say an append_figure function that takes them and converts them to a subplot under the hood before plotting. It could be laid out either vertically or horizontally. 

I often do not know that I want to look at multiple plots on a single page until I've seen one plot. Having to go back and convert everything to using the subplot api after the fact is a burden.

**Comment by jonmmease** [comment] 2019-06-28 13:04
Hi @syamajala, thanks for the suggestion.  One of the key to making this, and several other subplot feature requests, possible is to make all of the subplot logic available lazily so that you can add additional subplots to a figure after it has been created.

This should be possible, but it's quite a bit more bookkeeping since we would need to be able to reposition basically the entire figure each time a new subplot is added.

As another workflow all together, you could make your figures as `FigureWidget` instances and then use the ipywidgets `HBox` / `VBox` to display separate figures next to each other in the same output cell.

**Comment by qianxuanyon** [comment] 2020-01-10 10:36
How to merge multiple figures I currently use plotly.express and don't know how to merge them together or please tell me how to reverse figures

**Comment by gvwilson** [comment] 2024-06-13 19:34
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:34 UTC
Labels: make_subplots
