### ISSUE TITLE
Hover data doesn't map for create_facet_grid from figure factory

### ISSUE THREAD

**Issue by SandyJJS** [plotly/plotly.py#1558] opened 2019-05-08 17:04 UTC
Incorrect data will appear on tool tip when using a facet grid plot. 
In the example provided below the data shows the Chevrolet Corvette 8 cylinder has a manual(m6) transmission:

`manufacturer     model  displ  year  cyl        trans  drv  cty  hwy fl  
   chevrolet  corvette    7.0  2008    8   manual(m6)    r   15   24  p`

but the tool tip shows auto(s6), see photo:
![facet_plot](https://user-images.githubusercontent.com/18241942/57393722-9ab6b900-71bb-11e9-96d2-410f616596a2.jpg)

Code to reproduce:

`import plotly.offline as py
import plotly.figure_factory as ff
import pandas as pd

mpg = pd.read_table('https://raw.githubusercontent.com/plotly/datasets/master/mpg_2017.txt')
eight_cyl = mpg[mpg['cyl'] == 8]

print(eight_cyl[eight_cyl['displ'] == 7.0])

fig = ff.create_facet_grid(
    mpg,
    x='displ',
    y='cty',
    facet_col='cyl',
    text=mpg['trans'].values,
    hoverinfo = 'text'
)

py.plot(fig)`

**Comment by jonmmease** [comment] 2019-05-10 12:14
Hi @SandyJJS,

Thanks for the report.  To be honest we probably won't put much more effort into the `create_facet_grid` figure factory because we're focused on `plotly_express` which offers much more flexible faceting functionality.  Have you tried out https://www.plotly.express/ for this usecase?

That said, if someone wants to take a look and debug this we'd be happy to merge in any fixes!

**Comment by isemaj** [comment] 2019-06-18 15:05
@jonmmease can I contribute to this issue?

**Comment by jonmmease** [comment] 2019-06-18 18:15
Hi @isemaj, sure.  Have you tried reproducing this plot with `plotly_express`?  That's the first step I'd like to see.

**Comment by isemaj** [comment] 2019-06-19 07:36
Here's the `plotly_express` version, I'm not sure if this is the one that you're looking for but here it shows the right value which is `manual(m6`).

![Screenshot from 2019-06-19 15-33-01](https://user-images.githubusercontent.com/39540851/59745628-cc856a00-92a7-11e9-9018-78527d61ae35.png)

**Comment by gvwilson** [comment] 2024-06-13 19:32
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:32 UTC
Labels: bug
