### ISSUE TITLE
Add fallback command-line mode for orca image export

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1617] opened 2019-06-15 12:29 UTC
The `plotly.io.write_image`/`to_image` functions start an orca server and send image export requests to the orca server over a local port.  This provides the best performance for repeated image export requests, but at times folks have had trouble with this local server connection. See
 - https://github.com/plotly/plotly.py/issues/1460
 - https://github.com/plotly/plotly.py/issues/880#issuecomment-502343459

It would be useful to provide to option to call orca in command-line mode.  This would involve writing the figure to a temporary file, calling `orca  graph` on the file to create a temporary image file, then reading the image file bytes into memory, and deleting both temporary files.  This would be quite a bit slower (1-2 seconds per image), but it would likely be more reliable for some environments since it does not require communication over a local port.

The API should be designed along with https://github.com/plotly/plotly.py/issues/1570.

**Comment by gvwilson** [comment] 2024-06-13 19:33
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:33 UTC
Labels: enhancement
