### ISSUE TITLE
about datetime and ployly.offline.plot

### ISSUE THREAD

**Issue by TuoFeiLun** [plotly/plotly.py#1492] opened 2019-04-04 03:59 UTC
When I use ployly.offline.plot , the x_axis's data is datetime(example 2019-2-12 0:12:22), the time of plot figure is changed after i exec plot(changed to 2019-2-11 16:12:22) , the datetime is later 8 hours than my original datetime data .

**Comment by jonmmease** [comment] 2019-04-04 10:04
Hi @TuoFeiLun, I think this is a duplicate of https://github.com/plotly/plotly.py/issues/209. That plotly.py is automatically treating all times as UTC.  This is something we plan to address in version 4.  I'm going to close this for now, but please let me know if you don't think this is the same problem discussed in #209.  Thanks!

**Closed by jonmmease** 2019-04-04 10:04 UTC
