### ISSUE TITLE
Feature: Zoom of Chloropleth Map Parameter

### ISSUE THREAD

**Issue by KangboLu** [plotly/plotly.py#1910] opened 2019-11-20 14:30 UTC
Can the team add a zoom feature for Chloropleth map for user to set the zoom of the map by setting a zoom parameter?

**Comment by gvwilson** [comment] 2024-06-14 13:11
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:11 UTC
