### ISSUE TITLE
?consider? --minimize=False in jupyter extension installation (at readme instruction)

### ISSUE THREAD

**Issue by abngal** [plotly/plotly.py#1887] opened 2019-11-09 13:43 UTC
On my local, I have pulled latest docker image: `jupyter/datascience-notebook`
Plotly chart is not visible at jupyter _(using sample at readme)_, thus I followed readme instruction  _(image below)_ for installing extension `jupyterlab-plotly` at jupyter.
![image](https://user-images.githubusercontent.com/33404820/68529438-c3ba3100-0339-11ea-96df-0b6f3ac0d986.png)

I encountered jupyter lab build error until I modified `jupyter lab build` to [`jupyter lab build
--minimize=False`](https://github.com/jupyterlab/jupyterlab/issues/7180#issuecomment-538633748). After which I can now see the plotly graph.

related errors:
https://github.com/jupyterlab/jupyterlab/issues/7003
https://github.com/plotly/plotly.py/issues/1483

I also added `strict-ssl false` at `~/.yarnrc` but I'm not sure It made a difference.

Maybe adding `--minimize=False` parameter, by default, to the readme build instruciton will save time for others _(though I'm not totally sure it is the correct way)_.

**Comment by gvwilson** [comment] 2024-06-14 13:13
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:13 UTC
