### ISSUE TITLE
hexadecimal color definition with alpha

### ISSUE THREAD

**Issue by Drumbits** [plotly/plotly.py#1651] opened 2019-07-02 03:18 UTC
Hi,

It seems plotly.py does not support hexadecimal color definition when it includes alpha.
This issue might be related to issue #1416, though the latter is declared as solved, while my issue is still valid with version 3.10.0. It appeared in version 3.0 (no issue with version 2.7)
A very simple offline notebook code to show the problem:

import plotly.graph_objs as go
import plotly.offline as po

po.init_notebook_mode(connected=True)
c = '#112233ff'
po.iplot([go.Scatter(x=[1, 2], y=[1, 1], line=dict(color=c))])

Without alpha, or with plotly 2.7.0, this code works.

**Comment by jonmmease** [comment] 2019-07-03 14:50
Thanks for the report @Drumbits

**Comment by gvwilson** [comment] 2024-06-13 19:40
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:40 UTC
Labels: bug
