### ISSUE TITLE
How do I shink/scale a point according to mean value of the dataset?

### ISSUE THREAD

**Issue by eromoe** [plotly/plotly.py#1710] opened 2019-08-07 08:32 UTC
I have code: 

```
import plotly.graph_objects as go

d1 = ...
d2 = ...

fig = go.Figure()
fig.add_trace(go.Scatter(x=d1.x, y=d1.y, fill='tozeroy', name='Old',)) # fill down to xaxis
fig.add_trace(go.Scatter(x=d2.x, y=d2.y, fill='tonexty', name='New',)) # fill to trace0 y
fig.show()

```

The result :

[![enter image description here][1]][1]

Because the `X=0` point is extremly larger than others(mean value) , I have to remove it to plot a nice plot :

[![enter image description here][2]][2]

But actully I also want plot `X=0` point  like :

[![enter image description here][3]][3]

Is any good way to do this ?

  [1]: https://i.stack.imgur.com/NGfQV.png
  [2]: https://i.stack.imgur.com/K4Ana.png
  [3]: https://i.stack.imgur.com/ci0Cz.png

**Comment by Batalex** [comment] 2019-08-12 12:04
I think of two techniques you could use:
- if you are confortable with log axes you could use one on the `y`
- if you prefer the straightforward confort of a linear axe, filter the points causing the issue from the dataframe (e.g. anything outside 3 interquartile range should do the trick) and add [annotations](https://plot.ly/python/text-and-annotations/)/[shapes ](https://plot.ly/python/shapes/) to obtain the desired effect.

**Comment by gvwilson** [comment] 2024-06-13 19:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:44 UTC
