### ISSUE TITLE
Include `scene_(x|y|z)axis_title` in the 3D surface plots example

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#2073] opened 2020-01-15 18:43 UTC
https://plot.ly/python/3d-surface-plots/

**Comment by emmanuelle** [comment] 2020-01-15 20:09
@chriddyp would it be ok with you to add instead a link to https://plot.ly/python/3d-axes/ in all 3d charts tutorials, with a sentence like "for configuring the axis and the scene of xx plots. go to the 3d axes tutorial"? Or we could do both...

**Comment by gvwilson** [comment] 2024-06-14 13:09
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:09 UTC
