### ISSUE TITLE
Plotly v4.1.0 offline fig.show() still requests online 'cdn' website.

### ISSUE THREAD

**Issue by kozmers** [plotly/plotly.py#1742] opened 2019-08-29 05:44 UTC
It takes a long time to show the figure in plotly webpage(as browser renderer)  in offline plotly test.
The reason is plotly still request mathjax.js from the online cdn. 
A line of <script> can be found in the webpage source.
> <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script>

My solution now is changing [include_mathjax=**False**] in plotly/io/_base_renderers.py [#line 723, BrowserRenderer.render(fig_dict)]，original is include_mathjax='cdn' .

Below is a short test code,
```
from plotly import graph_objects as go
import pandas as pd
import numpy as np
N = 10
df = pd.DataFrame(dict(x=np.random.randn(N),  y=np.random.randn(N)))
trace = {
        'type': 'scatter',
        'x': df['x'],
        'y': df['y'],
}
fig = go.Figure(data=[trace])
fig.show()
```

**Comment by ziliangok** [comment] 2019-08-29 09:21
I do not have this issue, maybe your installation are not correctly.

**Comment by kozmers** [comment] 2019-08-30 01:13
> I do not have this issue, maybe your installation are not correctly.
I reinstalled with `pip uninstall plotly` then `pip install -U plotly`.  Issue is still there( with fig.show()).
Then,
I tried fig.write_html('test.html'), the output html doesn't have that MathJax.js cdn url script.
Below is the difference of the sources of two html output (fig.show v.s. fig.write_html)
1. fig.show:
in chrome , view-source:http://127.0.0.1:64903/
```
<html>
--
  | <head><meta charset="utf-8" /></head>
  | <body>
  | <div>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script type="text/javascript">if (window.MathJax) {MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>
  | <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
  | <script type="text/javascript">/**
  | * plotly.js v1.49.1
  | * Copyright 2012-2019, Plotly, Inc.
  | * All rights reserved.
  | * Licensed under the MIT license
  | */
...
```
2. fig.write_html:
in chrome, view-source:file:///test.html
```
<html>
--
  | <head><meta charset="utf-8" /></head>
  | <body>
  | <div>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script type="text/javascript">if (window.MathJax) {MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>
  | <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
  | <script type="text/javascript">/**
  | * plotly.js v1.49.1
  | * Copyright 2012-2019, Plotly, Inc.
  | * All rights reserved.
  | * Licensed under the MIT license
  | */
...
```

Obviously fig.show has this line `<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script type="text/javascript">if (window.MathJax) {MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>`

**Comment by ziliangok** [comment] 2019-08-30 01:24
My friends and me using plotly 4.1.0 work perfectly with jupyter notebook.
The code you provided works well too. 
Could you please try create a new virtual environment and test it again?
By the way, I'm using python 3.6.2.

**Comment by kozmers** [comment] 2019-08-30 23:02
Thanks for you kindly reply, ziliangok.
Html source code string proving there has a fully online url script line.
Figure shows slowly under a lower speed network,if there's no network, figure shows very fast because the connection to cdn fails directly. This is why running on your side looks well, speed is the surface of things,
Browser shows only a blank page with a processing icon in a long time when plotly running in a  separated local network without internet, 
That's not related to the version of python and jupyter environment, I'm not going to test them.

**Comment by gvwilson** [comment] 2024-06-13 19:47
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:47 UTC
