### ISSUE TITLE
Plotly 3.2.0 troubles with Pandas Series date time display

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [plotly/plotly.py#1160] opened 2018-09-06 12:10 UTC
Migrated to the latest version of Plotly and have troubles to display date time data in a Scatter plot.
Using the same Python code passing Pandas DateTime columns:
3.1.1. give us the following output:
```
"x": ["2015-09-05 14:30:00", ...
```
3.2.0 give us:
```
"x": [1441463400000000000, ...
```

**Comment by jonmmease** [comment] 2018-09-06 12:43
Thanks for reporting this @VelizarVESSELINOV ,

Looks like an oversight from https://github.com/plotly/plotly.py/pull/1149

**Comment by jonmmease** [comment] 2018-09-08 23:49
Fixed in  #1163 and will be released next week as part of 3.2.1.  I'm hoping to publish a release candidate of 3.2.1 on Monday, and it would be great if you could give it a try 🙂  Thanks again for the report!

**Closed by jonmmease** 2018-09-08 23:49 UTC
Labels: bug

**Comment by jonmmease** [comment] 2018-09-10 14:08
3.2.1rc1 is available. If you have time to confirm the issue is fixed for you that would great. Instructions at https://github.com/plotly/plotly.py/tree/release_3.2.1.

**Comment by pe224** [comment] 2018-09-14 08:55
Can confirm that timestamps are correctly displayed again in 3.2.1rc1.
Thanks for your work and the fast fix.
