### ISSUE TITLE
Improve documentation of the 'color' param

### ISSUE THREAD

**Issue by fluhus** [plotly/plotly.py#2164] opened 2020-02-05 17:18 UTC
On functions like `scatter` or `bar`, the documentation reads:

>**color** (str or int or Series or array-like) – Either a name of a column in `data_frame`, or a pandas Series or array_like object. Values from this column or array_like are used to assign color to marks.

I am missing the meaning of the values. Like, *what color is 5?*

I think it should be explained what numeric values and string values are allowed and how they are interpreted. I would suggest an actual correction, but I really don't know what color 5 is. :-)

**Comment by jdamiba** [comment] 2020-02-12 22:32
Hi @fluhus! Thanks for reaching out. You are correct that the reference documentation for this attribute is a bit terse.

You might find the following documentation pages to have useful information and examples:

https://plot.ly/python/discrete-color/
https://plot.ly/python/builtin-colorscales/
https://plot.ly/python/colorscales/

In brief, you can use the name of a column in your DataFrame as the `color` parameter, like this:

```python
import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
fig.show()
```

`species` is the name of a column in the `df` DataFrame which contains `strings`.  By saying `color='species'`, we are declaring that all data points in the iris dataset which are of the same species should be colored the same.

Similarly, we could use a column in the `df` DataFrame with `integer` data instead of string data, like `species_id`.

I hope this answered your question- feel free to follow up if you need more clarification!

**Comment by fluhus** [comment] 2020-02-13 07:56
Hi @jdamiba, thanks for getting back to me!
I guess documentation is as good as how many people have tried to use it :)

My question is about how should I represent colors in the input. How do I make something red, blue, etc. and what should I expect if I give numbers.

I was going to demonstrate by setting `color='fluhus'`, and it actually gave me an informative error message:

```
Invalid value of type 'builtins.str' received for the 'color' property of scatter.marker
        Received value: 'fluhus'

    The 'color' property is a color and may be specified as:
      - A hex string (e.g. '#ff0000')
      - An rgb/rgba string (e.g. 'rgb(255,0,0)')
      ...
```

That's exactly what I was missing! Kudos for the error message. Would be great to have that in the documentation of the color param (or a link to a page that has it).

For numeric values it can still be clearer. Right now the error message reads:

```
A number that will be interpreted as a color according to scatter.marker.colorscale
```

Would be helpful to explain *how* they are mapped. Something like "The minimal and maximal values are mapped to the left and right ends of the colorscale respectively. Other values are transformed linearly to the colors between." (if my understanding is correct).

I hope I clarified.

**Comment by gvwilson** [comment] 2024-06-14 13:08
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:08 UTC
