### ISSUE TITLE
Issue with callback function on sankey 

### ISSUE THREAD

**Issue by xanderwallace85** [plotly/plotly.py#2337] opened 2020-03-31 06:58 UTC
Hi there!

I just realized an issue when applying a callback function - such as on_click() - to nodes/links of the sankey diagram. More specifically, the function cannot distinguish between links and nodes and can cause unwanted events or out-of-index error. This is because we have [1, ... , L] and [1, ..., N] as (overlapping) indexes for links and nodes respectively. Let's take the following example:

```
def update_color(trace, points, state):
     # Compute new color array
     new_color = np.array(fig.data[0].node.color)
     new_color[points.point_inds[0]] = “red”
     # Update color of the nodes with given index
     with fig.batch_update():
         fig.data[0].node.color = new_color
fig.data[0].on_click(update_color)
```
Since the id of links and nodes overlap, when I click on any link, for instance, the id of the link is used to choose and color the node with that id. Clearly, often there are more links than nodes, than such click can also lead to an out-of-index error.

Maybe there is a way to distinguish nodes from links?

**Comment by gvwilson** [comment] 2024-06-14 13:04
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:04 UTC
