### ISSUE TITLE
Image to showing on plotly

### ISSUE THREAD

**Issue by chisom812** [plotly/plotly.py#1857] opened 2019-11-01 16:31 UTC
Hi
Please I am having an issue with my plotly. I use jupyter notebook and plotly version 3.1. When I use the iplot to plot an image the code runs perfectly but the image doesn't reflect. But sometimes it does reflect depending on my computer mood. I got a suggestion that I should restart and run the code and so many other suggestions but the issue has not been resolved permanently. The image may show today and will seize showing tomorrow. Please I need suggestions

**Comment by emmanuelle** [comment] 2019-11-01 18:00
Hello, could you please copy here a code sample to reproduce your problem (ideally with dummy data so that the code is standalone).
2 more points
- please consider upgrading to plotly.py 4.2 since we made some major improvements, including crucial API changes
- when you mention an image, do you mean a figure ? The image trace will only be available in the next plotly,py release (which should be out in two weeks I think)

**Comment by gvwilson** [comment] 2024-06-14 13:13
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:13 UTC
