### ISSUE TITLE
Overlapping boxplots in violinplot

### ISSUE THREAD

**Issue by falfaroalmagro** [plotly/plotly.py#1634] opened 2019-06-20 13:48 UTC
Hi,

I was using the last example in [https://plot.ly/python/violin/#advanced-violin-plot](https://plot.ly/python/violin/#advanced-violin-plot) with my own data, and the fact that the boxplots overlap makes the plot a bit confusing, specially when dealing with many different split violin plots (i.e. More than 20).

You can see an example of what I am talking about in that very same example if you zoom in one of the violin plots:

![Screen Shot 2019-06-20 at 15 37 48](https://user-images.githubusercontent.com/1914694/59853729-c0fe7580-9371-11e9-8900-0d87df3743bb.png)

When zoomed, it does not look important, as I said, it makes the plot confusing in my data:

<img width="1563" alt="Screen Shot 2019-06-20 at 15 46 10" src="https://user-images.githubusercontent.com/1914694/59854196-ba243280-9372-11e9-950b-bf6a0f5407f9.png">

Cheers

**Comment by jonmmease** [comment] 2019-06-28 12:42
Hi @falfaroalmagro, thanks for the report.  Do you have in mind how you would ideally like the boxes to behave for two-sided violin plots?  For your case, where you have so many violins, it might make sense to hide the boxes altogether by setting `box.visible=False`.

**Comment by falfaroalmagro** [comment] 2019-06-28 14:11
Hi, @jonmmease. Thanks for your answer. Removing the boxes may be an option in my case, but I still think that the overlapping looks wrong. There is no reason for making them overlap. It does not improve the visualisation and it impairs the aesthetics. How would I ideally like the boxes? Not-overlapping.

**Comment by gvwilson** [comment] 2024-06-13 19:33
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:33 UTC
Labels: question
