### ISSUE TITLE
setup.py test - `TypeError: clientresp() missing 1 required positional argument: 'data'`

### ISSUE THREAD

**Issue by aodhan-domhnaill** [plotly/plotly.py#965] opened 2018-03-08 18:14 UTC
Trying to run the tests, I get

```
$ python setup.py test
running test
running egg_info
writing plotly.egg-info/PKG-INFO
writing dependency_links to plotly.egg-info/dependency_links.txt
writing requirements to plotly.egg-info/requires.txt
writing top-level names to plotly.egg-info/top_level.txt
reading manifest file 'plotly.egg-info/SOURCES.txt'
writing manifest file 'plotly.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    zip_safe=False)
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 204, in loadTestsFromName
    test = obj()
TypeError: clientresp() missing 1 required positional argument: 'data'
```

I am working off the master branch at commit, 
```
$ git log | head -1
commit 86d5e6b1453c3c865999134c65ac7c0c7f1c2ecc
```

**Comment by jonmmease** [comment] 2018-09-22 23:03
Hi @aidan-plenert-macdonald , thanks for your interest in testing 🙂  The tests have been reworked quite a bit since the version 3 release. If you're still interested, could you give it a try again with the current master?

**Comment by jonmmease** [comment] 2018-09-22 23:08
Actually, I think the issue is the `python setup.py test` command. We run our tests using a combination of `nosetests` and `pytest`. See commands in `tox.ini`.  That said, it would be nice if `python setup.py test` did the right thing, but I haven't looked into how to configure this.

**Comment by GabrielSimonetto** [comment] 2020-12-28 19:38
I believe this issue is deprecated since tests are now run on pytest

**Comment by gvwilson** [comment] 2024-06-10 18:28
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 18:28 UTC
Labels: testing
