### ISSUE TITLE
Old broken Dash examples used in plotly.py doc

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#1963] opened 2019-11-22 13:32 UTC
One example is https://community.plot.ly/t/choropleth-map-with-dash/31659 but there must be others

**Comment by gvwilson** [comment] 2024-06-14 13:11
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:11 UTC
