### ISSUE TITLE
Feature: use scalar field for color of go.Scatterternary (or figure factory)

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#1500] opened 2019-04-07 15:34 UTC
I'm trying to write an example showing how to make a ternary scatter plot, based on Quartz-Clay-Carbonate ternary plots used in the oil and gas industry such as https://bit.ly/2IjtQgL. For such examples, it would be great to have a keyword argument which would be a scalar (such as the index of the oil field for this specific example), and could be used for the color or size of the markers. 

I'm not sure whether this could be added to  ``go.Scatterternary``, or whether a figure factory should be created instead?

**Comment by emmanuelle** [comment] 2019-04-07 15:48
![ternary_oil](https://user-images.githubusercontent.com/263366/55686006-98630400-595c-11e9-826b-b6908ed1f5e7.png)

**Comment by nicolaskruchten** [comment] 2019-04-08 01:45
A couple of notes:

* In order to get things added to `go.Scatterternary` they must first be added to the matching trace type in plotly.js
* In general wherever possible we should try to build stuff on top of `plotly_express` instead of build new figure factories except in complex cases like the ternary contour stuff
* As it happens, `plotly_express` will happily accept a dataframe column to split traces on colours or symbols, so it could be a good avenue here :)

**Comment by emmanuelle** [comment] 2019-04-08 07:09
Thank you @nicolaskruchten! I finally took the time to take a look at ``plotly express``, and it's amazing! Regarding the docs, should the doc tutorials of ``plotly.py`` add links to the doc of ``plotly express``? Is there already a discussion of how to organize the two docs?

**Comment by jonmmease** [comment] 2019-04-08 13:09
> Regarding the docs, should the doc tutorials of plotly.py add links to the doc of plotly express?

Yes, the current plan is that we're going to pull plotly_express into plotly.py for plotly.py version 4.  Version 4 is also going to change the recommend approach to displaying figures (See https://github.com/plotly/plotly.py/pull/1474) so we're going to need to do a full docs overhaul for that.  My thinking was that we would bring plotly_express into all of the doc pages at the same time.

**Comment by nicolaskruchten** [comment] 2019-04-08 14:30
I'm glad you like it @emmanuelle :D

I'm thinking of adding a note to some of the figure factories in the short run saying "check out Plotly Express", just to start bleeding off some of that traffic and directing more users to PX so we can get some more early adopters.

**Comment by ycaokris** [comment] 2019-04-08 19:07
@emmanuelle @nicolaskruchten save type of issue.  I've been working on a dash mock with same type of figure as following:

<img width="672" alt="Screen Shot 2019-04-08 at 2 35 50 PM" src="https://user-images.githubusercontent.com/35306149/55749383-c86adf80-5a0e-11e9-82ca-6bd892d621b1.png">

Except for color traces, what may be worth to add on is annotation implementation with ref to a, b, and c axis, since it seems current scatterternary doesn't support 3D annotation, so that I'd have to do x and y. 
Let me know if there's a workaround I've missed and look forward to updates on PX

<img width="717" alt="Screen Shot 2019-04-08 at 2 57 26 PM" src="https://user-images.githubusercontent.com/35306149/55749443-ea646200-5a0e-11e9-81e4-6a49022d1e58.png">

**Comment by emmanuelle** [comment] 2019-04-08 19:56
@ycaokris you can use a Scatterternary with the a, b, c coordinates you need, invisible markers and use the ``text`` keyword argument for the annotations, would this work for you?

**Comment by emmanuelle** [comment] 2019-04-08 19:57
Also your app looks pretty cool @ycaokris !

**Comment by ycaokris** [comment] 2019-04-08 20:59
> Also your app looks pretty cool @ycaokris !

Thanks for suggestion, it works! Just adding another layer of scatterternary with mode='text'. The only problem is overlap of three layers (scatter, contour, text) is making the plot fully crowded. I'll probably add a controller for conditional display of annotations

**Comment by gvwilson** [comment] 2024-06-13 19:30
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:30 UTC
