### ISSUE TITLE
Unequal rowheights with make_subplots() specs

### ISSUE THREAD

**Issue by konsti-papa** [plotly/plotly.py#2131] opened 2020-01-27 10:09 UTC
Hi everyone,

When creating a figure with make subplots and defining the subplots via specs, the overall rows semm to have unequal heights. I expected the rowheights to be equal so that a subplot mit rowspan 10 is 10 times bigger than a subplot mit rowspan 1..
For more detail, please take a look at my Topic on this in the plotly community forum [here](https://community.plot.ly/t/rowheights-in-make-subplots-unequal-with-specs/33860?u=konsti_papa).

**Comment by gvwilson** [comment] 2024-06-14 13:09
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:09 UTC
