### ISSUE TITLE
import chart-studio

### ISSUE THREAD

**Issue by AlissaStuart** [plotly/plotly.py#1854] opened 2019-10-30 17:21 UTC
hello.
What is the correct syntax for importing chart-studio into the Jupiter notebook? I tied searching it on Google and found this code `import chart-studio.plotly as py` but is says invalid syntax
The course I'm taking uses import plotly.plotly as py, which is outdated 
Thank you

**Comment by empet** [comment] 2019-10-30 17:25
@AlissaStuart   `import chart_studio.plotly as py`

**Comment by gvwilson** [comment] 2024-06-14 13:13
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:13 UTC
