### ISSUE TITLE
KeyError: 71

### ISSUE THREAD

**Issue by CasellaJr** [plotly/plotly.py#3474] opened 2021-11-16 21:41 UTC
Thanks for your interest in plotly.py!!

I was creating an histogram with plotly:
```from plotly.offline import plot, iplot, init_notebook_mode
import plotly.graph_objs as go
from plotly.subplots import make_subplots
import plotly.express as px
import plotly.graph_objs as gobj
import plotly.figure_factory as ff

#age
hist_data =[coralys_data["age"].values]
group_labels = ['age'] 

fig = px.histogram(hist_data, x=coralys_data["age"], marginal="box", hover_data=hist_data, nbins=58,
                   title="Age distribution plot")
fig.show()
```

Here I obtain the error:
```ValueError: All arguments should have the same length. The length of column argument `df[wide_variable_0]` is 1, whereas the length of  previously-processed arguments ['hover_data_0'] is 14699```

But ok, maybe I am doing something wrong. But the problem is if I remove the last command:
`fig = px.histogram(hist_data, x=coralys_data["age"])
fig.show()`
I obtain
`KeyError: 71`

What is this error 71?

**Comment by AaronStiff** [comment] 2023-02-13 11:26
Duplicate of #4040.

Yes, definitely an open bug. We'll use the above issue to track this as we've had a couple of other duplicates like this.

**Closed by AaronStiff** 2023-02-13 11:26 UTC
Labels: duplicate
