### ISSUE TITLE
pio.to_templated not behaving as expected

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#1920] opened 2019-11-22 20:03 UTC
```
>>> fig = go.Figure(layout={'title': 'Figure Title', 'font': {'size': 20, 'family': 'Courier'}})                                             
>>> fig                                                                                                                                      
Figure({
    'data': [],
    'layout': {'font': {'family': 'Courier', 'size': 20}, 'template': '...', 'title': {'text': 'Figure Title'}}
})
>>> pio.to_templated(fig)                                                                                                                    
Figure({
    'data': [], 'layout': {'template': '...', 'title': {'text': 'Figure Title'}}
})
```

The style properties should go to the template I think?

**Comment by nicolaskruchten** [comment] 2019-11-22 21:01
This is working as intended, it's just that `template` is suppressed in the output AND your figure also has the default template on board... Here's another way of looking at it:

![image](https://user-images.githubusercontent.com/203523/69460150-6498eb00-0d41-11ea-94f5-8e88cc3c03aa.png)

**Comment by nicolaskruchten** [comment] 2019-11-22 21:02
Also we should document `pio.to_templated()` in https://plot.ly/python/templates/ :)

**Comment by emmanuelle** [comment] 2019-11-22 21:07
Got it, thanks. I got confused by the fact that the template is suppressed in the output (which is a good thing!). I'll let this one open until we document the feature.

**Comment by gvwilson** [comment] 2024-06-14 13:12
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:12 UTC
