### ISSUE TITLE
Autocomplete not working in Pycharm

### ISSUE THREAD

**Issue by Shourai** [plotly/plotly.py#1682] opened 2019-07-24 12:50 UTC
While using plotly 4.0 combined with Pycharm the autocompletion for `plotly.graph_objects` is not working.
Also the references to the objects are not found either, but the script does work.
I see some people on the [community site](https://community.plot.ly/t/problem-pycharm-cannot-auto-hintting-with-plotly/26195) with the same issue.

![Untitled](https://user-images.githubusercontent.com/10200748/61794454-8761d400-ae21-11e9-873d-a752052b79b3.png)
Works fine for e.g. pandas:
![Untitled2](https://user-images.githubusercontent.com/10200748/61794455-8761d400-ae21-11e9-8cb3-0a13bf0cefad.png)

No completion is found when I type `go.` either.

However when I use `import plotly.graph_objs as go`, the references _are_ found.
But the autocompletion still doesn't work.
I have tried `File > Invalidate Cache/Restart`, to no avail.

There has been an issue like this before but it seems it had been solved: https://github.com/plotly/plotly.py/issues/389

When I open the same virtualenv within VScode the autocompletion works fine. 
(The extension uses jedi for autocompletion I think).
![Untitled3](https://user-images.githubusercontent.com/10200748/61794453-8761d400-ae21-11e9-9fe9-d5c2dc97af02.png)

I am not sure if this is an issue with plotly or pycharm.

**Comment by jonmmease** [comment] 2019-07-25 09:44
Hi @Shourai, thanks for the report.

What version of PyCharm are you using?  I mostly develop plotly.py in PyCharm and I've not seen this problem before.  Here's what I get when I create a simple PyCharm project on MacOS with PyCharm version 2019.1.3 with an environment with plotly.py 4.0.0 installed.

![Screen Shot 2019-07-25 at 5 41 27 AM](https://user-images.githubusercontent.com/15064365/61864260-17922e80-ae9f-11e9-868a-c560d9f62f25.png)

![Screen Shot 2019-07-25 at 5 43 32 AM](https://user-images.githubusercontent.com/15064365/61864295-28db3b00-ae9f-11e9-989b-c782936a95dd.png)

**Comment by Shourai** [comment] 2019-07-25 11:11
Hey @jonmmease, thanks for your work on plotly!

The screenshots in the first post were taken on Pycharm 2019.1.3 Professional edition on Windows 10.
I could have sworn it was working before the update to plotly 4.0.
After downgrading plotly to 3.10 it is not working either.

A few minutes after I posted the issue Pycharm version 2019.2 came out, so I thought about removing everything and installing pycharm from scratch without any plugins.
Created a new virtual environment and only installed plotly 4.0
However it still does not work.

Tried it also with Pycharm 2019.2 on a mac running Mojave, no luck there either.

`plotly.express` _is_ working however.

**Comment by cipold** [comment] 2019-07-25 22:41
Same issue here on PyCharm CE 2018.3 on latest Arch Linux
![image](https://user-images.githubusercontent.com/10324452/61913577-e3ba1600-af3d-11e9-8263-acbb17858dfe.png)
The code executes properly only code completion does not work and the warning is shown.

**Comment by jonmmease** [comment] 2019-08-17 11:03
Hi All, I'm still now sure why this is happening for some folks.  One thing that we can in 4.2 that might help is that we'll switch things around and output the code generation to the `plotly.graph_objects` directory, and have the alias point from `plotly.graph_objs` to `plotly.graph_objects` instead of the other way around.

**Comment by nicolaskruchten** [comment] 2019-08-17 14:50
I still wonder if __all__ has something to do with it...

**Comment by niklasinde** [comment] 2019-10-19 14:33
It looks like it has something to do with the graphs_object file being to big:
![image](https://user-images.githubusercontent.com/15488549/67146546-68da7000-f28c-11e9-9536-5d1740605977.png)

This can be solved (on mac) by going to:

**Help > Edit Custom Properties**

Then add:

`idea.max.intellisense.filesize=500000`

Then restart Pycharm
[(Stackoverflow link)](https://stackoverflow.com/questions/23057988/file-size-exceeds-configured-limit-2560000-code-insight-features-not-availabl)

After this intellisense worked as expected:
![image](https://user-images.githubusercontent.com/15488549/67146713-fe2a3400-f28d-11e9-8f5f-bc7c159399ed.png)

**Comment by zbl-96** [comment] 2020-12-02 06:51
the same problem in vscode use pylance language server .anyone have suggest?

**Comment by technic** [comment] 2021-09-18 19:20
There is a related issue for pylance https://github.com/microsoft/pylance-release/issues/512
Why this custom `relative_import` hack is needed?

**Comment by technic** [comment] 2021-09-18 19:33
How about changing if guard here
https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/graph_objs/__init__.py
to
```python
if sys.version_info < (3, 7) or TYPE_CHECKING:
```
this solves an issue with vscode+pylance for me, and in runtime the import is still lazy.
Shall I make a PR?

**Comment by JP-Ellis** [comment] 2021-10-14 21:29
Looks like this issue might be a duplicate of #1103 ?

**Comment by nicolaskruchten** [comment] 2022-05-04 11:41
This issue will be resolved in the next version of Plotly.py which will come out in a few days, and includes some goodies like https://github.com/plotly/plotly.py/pull/3708 which lets you autocomplete off of the result of functions like `px.scatter()` as well :)

**Closed by nicolaskruchten** 2022-05-04 11:41 UTC
