### ISSUE TITLE
Integration with Datashader (datetime conversions)

### ISSUE THREAD

**Issue by pedroallenrevez** [plotly/plotly.py#1270] opened 2018-11-07 12:03 UTC
Following conversation with @jonmmease on https://github.com/plotly/plotly.py/issues/1266 .

In the example specified in https://plot.ly/python/change-callbacks-datashader/ we can see a datashading example. This example doesn't use datetime indexes tho.

In order to datashade, the axis cannot be datetime since this causes problems when aggregating points. In order to solve this, we must convert the datetimes to ints (in milliseconds) before sending in the data for datashading. 

This process is tedious and error-prone on the side of the user.

As stated by @jonmmease 
_I do want to build a convenient interface for doing what this example notebook does, probably as a new figure factory in the plotly.figure_factor package. This datashader-based figure factory would directly accept dask data structures and feed them into the datashader library to perform server-side rendering._

This, with the addition of datetime conversions, would be on par with Holoviews, in terms of big data plotting.

**Comment by jonmmease** [comment] 2018-11-07 12:35
Thanks for raising the issue @pedroallenrevez!

Cross reference https://github.com/plotly/plotly.py/issues/1207 for discussion of datetime conversions.
Cross reference #1266 for discussion of dask's relationship with datashader

**Comment by pedroallenrevez** [comment] 2018-11-08 11:41
Cross reference https://github.com/plotly/plotly.py/issues/1272 for discussion of plot reset animation problems.

**Comment by gvwilson** [comment] 2024-06-13 17:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:44 UTC
Labels: enhancement
