### ISSUE TITLE
on_click() is applied to all traces in PlotWidget with hovermode='closest'

### ISSUE THREAD

**Issue by JovanVeljanoski** [plotly/plotly.py#1853] opened 2019-10-30 14:37 UTC
Hello,

I believe I have found a bug. Please consider the following example. I am plotting to scatter plots (two traces) in a single PlotWidget figure. Then I would like to have an event, only when one of the traces is clicked. When the other is clicked, I expect nothing to happen.  Here is a reproducible code snippet:

```
import plotly.graph_objects as go

def my_func(trace, points, selector):
    print('- - - New click- - -')
    print(trace)
    print('')
    print('')
    print(points)
    print()


_scatter_0 = go.Scatter(x=[1, 2, 3, 4, 5], y=[1, 2, 3, 4, 5], name='0', mode='markers', hovertext=None, hovertemplate=None)
_scatter_1 = go.Scatter(x=[5, 3, 5, 0, 1], y=[5, 2, 3, 3, 2], name='1', mode='markers', hovertext=None, hovertemplate=None)
_layout = go.Layout(hovermode='closest')
fig = go.FigureWidget(data=[_scatter_0, _scatter_1], layout=_layout)

fig.data[0].on_click(my_func)
```

Things work as expected when I click on _scatter_0. However, whenever I click on _scatter_1, the `myfunc` function is still called, and with the wrong trace. Here is the output of `my_func` when I click the first point from _scatter_0:

```
- - - New click- - -
Scatter({
    'mode': 'markers',
    'name': '0',
    'uid': '99c9a167-e45f-4199-a472-7b4b0a68e819',
    'x': [1, 2, 3, 4, 5],
    'y': [1, 2, 3, 4, 5]
})


Points(point_inds=[],
       xs=[],
       ys=[],
       trace_name='0',
       trace_index=0)
```

The expectation is that nothing should happen, i.e. no click event was defined for `fig.data[1]` Am I doing something wrong perhaps? 
Any help or advice would be highly appreciated. 

Thank you!

**Comment by gvwilson** [comment] 2024-06-14 13:14
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:14 UTC
