### ISSUE TITLE
Embed plotly figure in _repr_html_?

### ISSUE THREAD

**Issue by allefeld** [plotly/plotly.py#3085] opened 2021-02-22 05:54 UTC
I have a custom class whose instances contain complex data, and I have defined a `_repr_html_` method so I can get a quick overview by evaluating the object in a notebook.

I would now like to embed a plotly `Figure` of the data in that HTML representation, along these lines:

````python
def _repr_html_(self):
    fig = go.Figure()
    fig.add_scatter(...)
    return '<h1>Name of object</h1>' + fig.to_html(full_html=False, include_plotlyjs='cdn')
````

However, there only appears a blank space where the plot should be.

Displaying the figure in the notebook by evaluating the Figure object works,
as does writing the code returned by `to_html` to a file and opening it in a browser.

Can this be done, and if yes, how?

> Debian 10.8, Python 3.8.8
> plotly 4.14.3, ipykernel 5.5.0, jupyter_client 6.1.11, jupyter_core 4.7.1
> Notebook in VS Code 1.53.2, Python extension 2021.2.1, Jupyter extension 2021.2.0

**Comment by andybaumgar** [comment] 2021-06-25 21:14
I have this issue as well.  The docs for fig.to_html state that the return type is "Representation of figure as an HTML div string", but I get `None`.

In my use case I am using the Python generated div `str` to be included in a json response to the frontend application that will then render it.

**Comment by nicolaskruchten** [comment] 2021-06-26 12:14
I can't reproduce this problem with `to_html()` returning `None`... Here's what I see:

![image](https://user-images.githubusercontent.com/203523/123512593-5534fe80-d656-11eb-94d6-0f6c7f9dc6d0.png)

Regarding the initial issue above, it's normal that no plot appears like this... Rendering external Javascript in a notebook is quite tricky and we only manage it via our `renderers` framework. Re-embedding Plotly outputs like this is not going to be particularly easy and is not really what `.to_html()` is designed for.

**Comment by allefeld** [comment] 2021-06-28 20:18
> Regarding the initial issue above, it's normal that no plot appears like this... Rendering external Javascript in a notebook is quite tricky and we only manage it via our `renderers` framework. Re-embedding Plotly outputs like this is not going to be particularly easy and is not really what `.to_html()` is designed for.

Thanks for the information. From my side, this issue can be closed.

**Comment by andybaumgar** [comment] 2021-06-28 21:53
I got around this by just reading the produced html file.  I realized I am also running an older version 4.9.0, so it may be fixed in more recent versions.

**Closed** 2021-06-28 22:10 UTC
