### ISSUE TITLE
`Figure.add_vline()` annotations and shape positions do not match on log plots

### ISSUE THREAD

**Issue by sharkweek** [plotly/plotly.py#4012] opened 2023-01-10 17:48 UTC
When adding a `vline` to a plot with a logarithmic x-axis, the `x` parameter is interpreted differently for annotations than it is for the placement of the line. The lines are placed at the literal x-location on the x-axis, while annotations are placed at the 10^x location.

For example, using the literal location will produce the line as intended, but the annotations are missing because they're off at 10^25.

```python
fig.add_vline(
    x=25,
    annotation_text='25'
)
```
![lines](https://user-images.githubusercontent.com/18335862/211623169-fe6439e5-3081-4a3d-94c8-5787bd2d4b23.png)

If I were to input the `x` parameter using the 10^n convention used throughout plotly for log plots, then I get the correct annotations, but the line will now be located off at log(25) (≈1.38).

```python
fig.add_vline(
    x=np.log10(25),
    annotation_text='25'
)
```

![annotations](https://user-images.githubusercontent.com/18335862/211623090-98d1bc07-d45e-415b-b202-4508e0f79657.png)

I'm on Windows 10 using Plotly v5.9.0 and Python 3.9.15.

**Comment by AaronStiff** [comment] 2023-01-26 14:46
Duplicate of #2580

**Closed** 2024-07-05 12:55 UTC
Labels: duplicate
