### ISSUE TITLE
Properties of a figure's `layout` aren't auto-suggested in Jupyter

### ISSUE THREAD

**Issue by malmaud** [plotly/plotly.py#1695] opened 2019-07-29 19:20 UTC
Very happy about all the great changes in Plotly 4.0! 

This is a minor quality-of-life issue:

In Jupyter, the properties of a figure's layout don't autocomplete:

```python
[1] from plotly.graph_objs import FigureWidget
[2] f=FigureWidget()
[3] f.layout.<press tab here>
```

Pressing 'tab' at the end of `f.layout.` doesn't suggest layout properties. Since there are so many layout properties, I think it would be helpful to suggest eg `title`, `xaxis` so I wouldn't have to rely on an external reference to remember all their names.

**Comment by gvwilson** [comment] 2024-06-13 19:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:44 UTC
