### ISSUE TITLE
404 GET /custom/slidemode/main.js?

### ISSUE THREAD

**Issue by t0mst0ne** [plotly/plotly.py#502] opened 2016-06-09 15:35 UTC
I found the error with ( 404 GET /custom/slidemode/main.js? ) when 
1. The first ipynb cell is markdown , and specific word inside " # Plotly" 
2. import plotly and call iplot then save ipynb
3. restart the ipynb again, both terminal and chrome debugger showed the error 404 GET /custom/slidemode/main.js?

If :
Move the first cell ( markdown format with # Plotly ) below the code , or remove the "# Plotly" in the Markdown cell would return to normal

Example:
Error 404 https://gist.github.com/0de5f9a037160a7a6a5349cd36fb5ef1
normal https://gist.github.com/26126e155f37025a494444556612a348 => s/P/p/ in first cell

Env:

MacBookPro 13 OSX 10.10.5 

jupyter                   1.0.0                    py35_3  
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py35_0  
jupyter_console           4.1.1                    py35_0  
jupyter_core              4.1.0                    py35_0
ipython                   4.2.0                    py35_1  
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py35_0 
plotly                    1.12.0                    <pip>
cufflinks                 0.7.2                     <pip>

**Comment by jonmmease** [comment] 2018-09-22 12:06
Closing as I'm unable to reproduce the issue with version 3.  Feel free to open a new issue against version 3 if you're still having trouble with this.

**Closed by jonmmease** 2018-09-22 12:06 UTC
