### ISSUE TITLE
Plotly.io.to_json Renders Polar Plots with Radians instead of Degrees

### ISSUE THREAD

**Issue by ancantus** [plotly/plotly.py#1916] opened 2019-11-22 02:24 UTC
Discovered this bug when using `plotly.to_json()` on a `go.FigureWidget()` object containing a `go.Scatterpolar()`. Within the Jupyter notebook environment the polar plot renders correctly:

```
import plotly.graph_objects as go
import numpy as np

fig = go.FigureWidget(data=go.Scatterpolar(r=np.ones(9), theta=np.arange(0, 2*np.pi + np.pi/4, step=np.pi/4)))
fig
```
![jupyter_screenshot](https://user-images.githubusercontent.com/1694065/69392440-e20d2d00-0d3a-11ea-97e3-ed787dde6475.png)

But once exported to json using the `plotly.io.to_json()` command:
```
from plotly.io import to_json

with open('/tmp/plotly_figure.json', 'w') as output_file:
    output_file.write(to_json(fig))
```
The resulting json file does not render correctly in plotly.js:
![js_screenshot](https://user-images.githubusercontent.com/1694065/69392529-27315f00-0d3b-11ea-9a51-4a5ebce7df1d.png)

Some digging shows the output .json renders the theta values in radians rather than degrees (required by the plotly.js API):
```
{
  "data": [
    {
      "r": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
      "theta": [
        0.0,
        0.7853981633974483,
        1.5707963267948966,
        2.356194490192345,
        3.141592653589793,
        3.9269908169872414,
        4.71238898038469,
        5.497787143782138,
        6.283185307179586
      ],
      "type": "scatterpolar"
    }
  ],
# layout information skipped
}
```

**Workaround:**
If the input range for theta is in degrees, `to_json()` output works normally.
```
import plotly.graph_objects as go
import numpy as np

fig = go.FigureWidget(data=go.Scatterpolar(r=np.ones(9), theta=np.arange(0, 360 + 45, step=45)))
fig
```

**Comment by gvwilson** [comment] 2024-06-14 13:12
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:12 UTC
