### ISSUE TITLE
Support non-cartesian hover events

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1177] opened 2018-09-14 10:04 UTC
Currently the trace.on_hover method doesn't work for non-cartesian trace types like `parcoords` and `sankey`.  The reason these don't just work is because the structure of the callback data from Plotly.js doesn't match that from the cartesian trace types.

For parallel coordinates the Python callback signature for hover/unhover could match that of the cartesian plots.  For `sankey` the hover data should probably be a new structure since the hover data is at the link or node level rather than points level.

While we're at it. We should specialize the docstrings for certain traces and raise an exception when someone tries to install an event callback on a trace that doesn't support it.

**Comment by gvwilson** [comment] 2024-06-13 17:39
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:39 UTC
Labels: enhancement
