### ISSUE TITLE
plotly.tools.make_subplots does not support go.Table

### ISSUE THREAD

**Issue by AbdealiLoKo** [plotly/plotly.py#1295] opened 2018-12-04 23:45 UTC
I have a case where i was trying to place tables in a gris (1 row, 3 columns)

```python
import plotly
import plotly.graph_objs as go
subplot_traces = [go.Table(cells={"values": [["a"], ["b"]]}),
                  go.Table(cells={"values": [["c"], ["d"]]})]
figure = plotly.tools.make_subplots(rows=1, cols=3)
for isubplot, subplot_trace in enumerate(subplot_traces):
    figure.append_trace(subplot_trace, 1, isubplot + 1)
```

Error:
```
This is the format of your plot grid:
[ (1,1) x1,y1 ]  [ (1,2) x2,y2 ]  [ (1,3) x3,y3 ]

----------------------------------------------------------------------
ValueError                           Traceback (most recent call last)
<ipython-input-68-4d0180560ee7> in <module>()
      5 figure = plotly.tools.make_subplots(rows=1, cols=3)
      6 for isubplot, subplot_trace in enumerate(subplot_traces):
----> 7     figure.append_trace(subplot_trace, 1, isubplot + 1)

~/anaconda3/lib/python3.6/site-packages/plotly/basedatatypes.py in append_trace(self, trace, row, col)
   1212 """, DeprecationWarning)
   1213
-> 1214         self.add_trace(trace=trace, row=row, col=col)
   1215
   1216     def _set_trace_grid_position(self, trace, row, col):

~/anaconda3/lib/python3.6/site-packages/plotly/basedatatypes.py in add_trace(self, trace, row, col)
   1059         return self.add_traces(data=[trace],
   1060                                rows=[row] if row is not None else None,
-> 1061                                cols=[col] if col is not None else None
   1062                                )[0]
   1063

~/anaconda3/lib/python3.6/site-packages/plotly/basedatatypes.py in add_traces(self, data, rows, cols)
   1142         if rows is not None:
   1143             for trace, row, col in zip(data, rows, cols):
-> 1144                 self._set_trace_grid_position(trace, row, col)
   1145
   1146         # Make deep copy of trace data (Optimize later if needed)

~/anaconda3/lib/python3.6/site-packages/plotly/basedatatypes.py in _set_trace_grid_position(self, trace, row, col)
   1249                                 "An axis object for ({r},{c}) subplot "
   1250                                 "cell got deleted.".format(r=row, c=col))
-> 1251             trace['xaxis'] = ref[0]
   1252             trace['yaxis'] = ref[1]
   1253

~/anaconda3/lib/python3.6/site-packages/plotly/basedatatypes.py in __setitem__(self, prop, value)
   2781             # ### Validate prop ###
   2782             if prop not in self._validators:
-> 2783                 self._raise_on_invalid_property_error(prop)
   2784
   2785             # ### Get validator for this property ###

~/anaconda3/lib/python3.6/site-packages/plotly/basedatatypes.py in _raise_on_invalid_property_error(self, *args)
   2961                                  full_obj_name=full_obj_name,
   2962                                  invalid_str=invalid_str,
-> 2963                                  prop_descriptions=self._prop_descriptions))
   2964
   2965     def update(self, dict1=None, **kwargs):

ValueError: Invalid property specified for object of type plotly.graph_objs.Table: 'xaxis'
```

System setup:
Python 3.6
Plotly 3.4.0

**Comment by jonmmease** [comment] 2018-12-05 11:35
Hi @AbdealiJK,

That's correct, `make_subplots` does not currently support `table` traces. Thanks for the suggestion.
 
The alternative is to manually position your table traces using the `table.domain` property.

**Comment by gvwilson** [comment] 2024-06-13 17:43
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:43 UTC
Labels: enhancement, make_subplots
