### ISSUE TITLE
px functions for various 3d traces

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2144] opened 2020-01-30 14:41 UTC
What's a good input format for the various 3d traces that PX doesn't support yet? `surface` kind of maps onto `heatmap` but other than that it's not clear what a good `data_frame` equivalent is.

**Comment by emmanuelle** [comment] 2020-01-30 14:52
The following traces take 1D arrays as arguments: isosurface, volume, mesh3d, cone, streamtube. So actually that dataframe format would make sense for these traces.

**Comment by gvwilson** [comment] 2024-06-14 13:04
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:04 UTC
