### ISSUE TITLE
Speed of rendering static images

### ISSUE THREAD

**Issue by sursu** [plotly/plotly.py#1775] opened 2019-09-16 22:41 UTC
I'm translating the [Robust Gaussian Processes in Stan](https://betanalpha.github.io/assets/case_studies/gp_part1/part1.html) tutorial to Python.

In the process of doing that I've encountered a speed issue. Plotly is slow at plotting many (a few thousand) traces.

**Reproducible example** (plotting the Posterior Realizations - 3.2 in the tutorial): 

Download the [`bag.pkl`](https://drive.google.com/open?id=1w2wOYssYmaIXIT7FnniQniEMY9XuYzIZ) file, then run:

```python
import pickle
import plotly.graph_objects as go

# Plot Gaussian process realizations
def plot_gp_realizations(fit, data, true):
    fig = go.Figure()
    for f in fit.extract()['f_predict']:
        fig.add_scatter(x=data['x_predict'], y=f, line_width=0.7, line_color='#8F2727', opacity=0.1)
    fig.add_scatter(x=data['x_predict'], y=true['f_total'], line_color='black', line_width=3)
    fig.add_scatter(x=data['x_predict'], y=data['y_predict'], mode='markers', marker_size=5, marker_color='#5183A1', marker_line = dict(color='white', width=1))
    fig.add_scatter(x=data['x'], y=data['y'], mode='markers', marker_size=9, marker_color='black', marker_line = dict(color='white', width=1.3))
    fig.layout.update(title='Posterior Realizations', showlegend=False, height=600)
    fig.show(renderer='svg', height=600, width=1000)


# Load bag
with open('bag.pkl', 'rb') as f:
    bag = pickle.load(f)

# Plot Gaussian process realizations
plot_gp_realizations(bag['pred_fit'], bag['data'], bag['true_realization'])
```

![image](https://user-images.githubusercontent.com/12001304/64998005-c02e9e80-d8e2-11e9-8374-c2fc6601dc44.png)

4000 lines over 500 data points.

Plotly takes ~30s to render the svg image.
R does it in ~2 seconds.

Now, the image in plotly is way better than the one displayed by R, but I'm wondering whether the speed can be improved further.

**Comment by nicolaskruchten** [comment] 2019-09-17 01:28
When rendering more than around 2000 points in line or scatter plots, we recommend using `scattergl` rather than `scatter` traces, for performance: https://plot.ly/python/webgl-vs-svg/

**Comment by sursu** [comment] 2019-09-17 09:24
I've set the `fig.add_scatter` from the loop to `fig.add_scattergl` and that is only marginally faster: ~27 seconds.
I suppose it's because the traces from the loop are only over 500 points.

Apart from that, the quality of the image has decreased. And the plot is bit messed up:

![image](https://user-images.githubusercontent.com/12001304/65029206-9d7da380-d93d-11e9-818f-c07d99b2ed86.png)

**Comment by gvwilson** [comment] 2024-06-13 19:50
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:50 UTC
