### ISSUE TITLE
X-axis title appears above graph when using showticklabels=False

### ISSUE THREAD

**Issue by Coding-with-Adam** [plotly/plotly.py#4295] opened 2023-07-24 21:44 UTC
This issue was reported by a community member in [this post](https://community.plotly.com/t/x-axis-title-is-above-the-graph-after-upgrade-from-dash-version-2-7-to-2-9/74161).
It appears that this bug is tied to certain Plotly versions ("If I upgrade plotly to 5.14.0 and stay with dash 2.7.1 the x-axis title is on top")

```
import numpy as np
import plotly.express as px

x_values = np.linspace(0, 100, 10)
y_values = np.linspace(0, 100, 10)

fig = px.line(x=x_values, y=y_values, labels={"x": "X-axis label", "y": "Y-axix label"})

fig.update_xaxes(
    showline=True,
    linecolor="black",
    mirror=True,
    range=[x_values.min(), x_values.max()],
    fixedrange=True,
    showticklabels=False,
)
fig.update_yaxes(
    showline=True,
    linecolor="black",
    mirror=True,
    range=[0, 100],
    fixedrange=True,
)
fig.show()
```
![image](https://github.com/plotly/plotly.py/assets/32049495/a92abae0-d81f-49d3-a37c-e6d15371bb25)

Update the x_axes to `showticklabels=True`, and the problem disappears.

**Comment by alexcjohnson** [comment] 2023-07-24 21:55
Duplicate of https://github.com/plotly/plotly.js/issues/6552

**Closed by alexcjohnson** 2023-07-24 21:55 UTC
