### ISSUE TITLE
RuntimeError: npm dependencies failed to install

### ISSUE THREAD

**Issue by dustiny5** [plotly/plotly.py#1746] opened 2019-08-31 01:25 UTC
I created a new environment in anaconda, installed packages and extensions. Not sure what is going on. Some online resources say it's a yarn issue, but unsure if it is. Any help will be appreciated.

Steps to install virtual env, packages, and extension:
```
(base) conda create -n env_name python=3.7 pandas numpy -y
(base) conda activate env_name`
(env_name) conda install -c plotly plotly plotly_express -y
(env_name) jupyter labextension uninstall @jupyterlab/plotly-extension

Building jupyterlab assets
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  C:\Users\Dustin\AppData\Local\Temp\jupyterlab-debug-ojsuussz.log
```

Here's my debug file:
[jupyterlab-debug-ojsuussz.log](https://github.com/plotly/plotly.py/files/3561946/jupyterlab-debug-ojsuussz.log)

Here's the packages in my environment:
```
 attrs-19.1.0-py37_1
  backcall-0.1.0-py37_0
  blas-1.0-mkl
  bleach-3.1.0-py37_0
  ca-certificates-2019.5.15-1
  certifi-2019.6.16-py37_1
  colorama-0.4.1-py37_0
  decorator-4.4.0-py37_1
  defusedxml-0.6.0-py_0
  entrypoints-0.3-py37_0
  icc_rt-2019.0.0-h0cc432a_1
  icu-58.2-ha66f8fd_1
  intel-openmp-2019.4-245
  ipykernel-5.1.2-py37h39e3cac_0
  ipython-7.8.0-py37h39e3cac_0
  ipython_genutils-0.2.0-py37_0
  ipywidgets-7.5.1-py_0
  jedi-0.15.1-py37_0
  jinja2-2.10.1-py37_0
  jpeg-9b-hb83a4c4_2
  json5-0.8.5-py_0
  jsonschema-3.0.2-py37_0
  jupyter-1.0.0-py37_7
  jupyter_client-5.3.1-py_0
  jupyter_console-6.0.0-py37_0
  jupyter_core-4.5.0-py_0
  jupyterlab-1.0.2-py37hf63ae98_0
  jupyterlab_server-1.0.0-py_1
  libpng-1.6.37-h2a8f88b_0
  libsodium-1.0.16-h9d3ae62_0
  m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp-6.1.0-2
  m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  markupsafe-1.1.1-py37he774522_0
  mistune-0.8.4-py37he774522_0
  mkl-2019.4-245
  mkl-service-2.0.2-py37he774522_0
  mkl_fft-1.0.14-py37h14836fe_0
  mkl_random-1.0.2-py37h343c172_0
  msys2-conda-epoch-20160418-1
  nbconvert-5.5.0-py_0
  nbformat-4.4.0-py37_0
  nodejs-12.8.1-0
  notebook-6.0.0-py37_0
  numpy-1.16.4-py37h19fb1c0_0
  numpy-base-1.16.4-py37hc3f5095_0
  openssl-1.1.1c-he774522_1
  pandas-0.25.1-py37ha925a31_0
  pandoc-2.2.3.2-0
  pandocfilters-1.4.2-py37_1
  parso-0.5.1-py_0
  patsy-0.5.1-py37_0
  pickleshare-0.7.5-py37_0
  pip-19.2.2-py37_0
  plotly-4.0.0-py_0
  plotly_express-0.4.0-py_0
  prometheus_client-0.7.1-py_0
  prompt_toolkit-2.0.9-py37_0
  pygments-2.4.2-py_0
  pyqt-5.9.2-py37h6538335_2
  pyrsistent-0.14.11-py37he774522_0
  python-3.7.4-h5263a28_0
  python-dateutil-2.8.0-py37_0
  pytz-2019.2-py_0
  pywinpty-0.5.5-py37_1000
  pyzmq-18.1.0-py37ha925a31_0
  qt-5.9.7-vc14h73c81de_0
  qtconsole-4.5.4-py_0
  retrying-1.3.3-py37_2
  scipy-1.3.1-py37h29ff71c_0
  send2trash-1.5.0-py37_0
  setuptools-41.0.1-py37_0
  sip-4.19.8-py37h6538335_0
  six-1.12.0-py37_0
  sqlite-3.29.0-he774522_0
  statsmodels-0.10.1-py37h8c2d366_0
  terminado-0.8.2-py37_0
  testpath-0.4.2-py37_0
  tornado-6.0.3-py37he774522_0
  traitlets-4.3.2-py37_0
  vc-14.1-h0510ff6_4
  vs2015_runtime-14.15.26706-h3a45250_4
  wcwidth-0.1.7-py37_0
  webencodings-0.5.1-py37_1
  wheel-0.33.4-py37_0
  widgetsnbextension-3.5.1-py37_0
  wincertstore-0.2-py37_0
  winpty-0.4.3-4
  zeromq-4.3.1-h33f27b4_3
  zlib-1.2.11-h62dcd97_3
```

**Comment by AlexAndorra** [comment] 2020-02-23 17:20
Hi Dustin,
Have you ever figured out this error? I have the exact same one trying to configure plotly for jupyterlab and I can't figure out a way to solve it 🤔 
Thanks in advance!

**Comment by dustiny5** [comment] 2020-02-23 18:40
Hi Alexandre,
Yeah I got it to work by creating a new virtual environment. What I did was:
1. In conda cmd create a new virtual env(I installed python 3.7 for mine) . 
2. Install libraries on the new virtual env:    - https://anaconda.org/plotly/plotly
    - https://anaconda.org/plotly/plotly_express

    - https://anaconda.org/conda-forge/nodejs

    - https://plot.ly/python/getting-started/            - Followed the installed instructions on JupyterLab Support 3.5+
3. Open Anaconda GUI, Install application jupyter lab by clicking the gear icon
4. In conda cmd, activate newly created virtual env and type jupyter lab build

I think this is how I did it. It's been awhile since I've installed it and I hope this helps.


    On Sunday, February 23, 2020, 09:20:17 AM PST, Alexandre ANDORRA <notifications@github.com> wrote:  
 
 
Hi Dustin,
Have you ever figured out this error? I have the exact same one trying to configure plotly for jupyterlab and I can't figure out a way to solve it 🤔
Thanks in advance!

**Comment by AlexAndorra** [comment] 2020-02-23 22:32
Hi Dustin,
Thanks a lot for this detailed answer -- really useful!
If I understand correctly, the problem was coming from the virtual env
itself, so creating a new one solved the issue?

**Comment by dustiny5** [comment] 2020-02-23 22:47
Hi Alexandre,
You don’t have to create a new virtual env, but it is generally a best practice to do. 
When installing to your base/root environment there’s a chance that the libraries will conflict with other libraries giving you weird errors. So I created a new virtual env to prevent it.
What i think solved the issue was installing the node.js library and updating the jupyter notebook. Sent from Yahoo Mail for iPhone


On Sunday, February 23, 2020, 2:32 PM, Alexandre ANDORRA <notifications@github.com> wrote:

Hi Dustin,
Thanks a lot for this detailed answer -- really useful!
If I understand correctly, the problem was coming from the virtual env
itself, so creating a new one solved the issue?

**Comment by AlexAndorra** [comment] 2020-02-23 22:54
Yeah, I'm already working in a venv, installed node and updated jupyterlab. 
But the venv is quite big and I used it a lot before, so maybe something is messing up with jupyer lab's build? That's why I'll try with a brand new venv -- we'll see 🤷‍♂

**Comment by jtlz2** [comment] 2020-04-03 08:11
@AlexAndorra Any progress on this? :\

**Comment by AlexAndorra** [comment] 2020-04-03 08:48
Not really -- I already had a virtual env for the project I was working on,
so I didn't want to migrate all of it just because of Plotly. So I used
Bokeh successfully in that same v-env.
If you do need Plotly though, I think Dustin's answer is good: the error
was coming from node.js. So, I'm betting creating a new v-env and a new
associated jupyter kernel would have solved the issue. Hope this helps!

**Comment by gvwilson** [comment] 2024-06-13 19:48
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:48 UTC
