### ISSUE TITLE
Windrose example from plot.ly not working

### ISSUE THREAD

**Issue by rr5577** [plotly/plotly.py#1131] opened 2018-08-23 14:59 UTC
I just did a fresh install to try plotly.py and wanted to try the pandas windrose example from the plotly site ( https://plot.ly/pandas/wind-rose-charts/ ).

```
import pandas as pd
import colorlover as cl
import numpy as np
import plotly.plotly as py
import plotly.graph_objs as go


df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/wind_rose.csv')
df.head()

data = []
counter = 0
for col in df.columns:
    if col != 'r':
        data.append(
            go.Area(t=df['r'],
                    r=df[col],
                    marker=dict(color=cl.scales['9']['seq']['PuBu'][counter]),
                    name=col+' m/s' ) )
        counter+=1
layout = go.Layout(
    title='test wr',
    font=dict(
        size=16
    ),
    
    radialaxis=dict(
        ticksuffix='%'
    ),
    orientation=270,
    barmode="stack"
    
)
fig = go.FigureWidget(data=data, layout=layout)
fig

```

but i only get a blank output cell.

if i remove the `barmode="stack"` kwarg, the plot renders, but without data:
![image](https://user-images.githubusercontent.com/31547476/44533132-20114080-a6f5-11e8-9c04-556b419cea24.png)

Plotly Version: 3.1.1
![image](https://user-images.githubusercontent.com/31547476/44533464-e1c85100-a6f5-11e8-97e3-1aba84bb860b.png)

**Update:**
i managed to get the plot and data to display, it seems using the pandas columns for "r" and "t" values doesn´t work (as in #1116).

However, dynamically updating the plot (e.g. changing title color) doesn´t work.
![image](https://user-images.githubusercontent.com/31547476/44569623-509bbd80-a77b-11e8-9ab2-f5653b6af019.png)

**Comment by jonmmease** [comment] 2018-08-24 09:45
Hi @rr5577 , thanks for taking the time to report this.

Yeah, it looks like the Plotly.js JavaScript library is choking when plotly.py is passed a pandas series or numpy array.  And I can also reproduce you're issue of not being able to update the title properties.

These issues should be addressed when this trace type is replaced with a new trace that uses the Polar 2.0 infrastructure.  See https://github.com/plotly/plotly.js/issues/2810 for some discussion.

I'll leave this issue open until the new trace is released and included with plotly.py.

**Comment by jonmmease** [comment] 2018-09-23 10:53
plotly.py 3.3 is going to include plotly.js 1.41 which includes the new `barpolar` trace type (https://github.com/plotly/plotly.js/pull/2954). This is the much more capable successor to the polar area traces used in this example.

**Comment by rr5577** [comment] 2018-09-23 11:12
Thanks for the update, looking forward to trying it!

**Comment by jonmmease** [comment] 2018-09-26 19:39
`barpolar` trace included in upgrade to plotly.js 1.41.3 in #1202, will be released in plotly.py 3.3.0 soon.

```python
import plotly.graph_objs as go
fig = go.FigureWidget()
fig.add_barpolar(r=[1, 3, 2], theta=[0, 45, 90])
fig.add_barpolar(r=[3, 5, 1], theta=[0, 45, 90])
fig.add_barpolar(r=[2, 1, 6], theta=[0, 45, 90])
fig
```
![newplot 4](https://user-images.githubusercontent.com/15064365/46104582-b4157280-c1a1-11e8-8063-87d4bc953e10.png)

See https://github.com/plotly/documentation/issues/1100 for progress on updating the windrose documentation to use `barpolar`.  Thanks for reporting!

**Closed by jonmmease** 2018-09-26 19:39 UTC
Labels: enhancement, plotly.js

**Comment by rr5577** [comment] 2018-10-19 06:31
This works great now (dynamically updating the plot as well). Only the code from the python example specifying the (layout) axis seems to be obsolete (it doesn´t do anything when changed).
After changing that it worked:
```
layout = go.Layout(
    title='test wd',
    font=dict(size=16), 
    polar=dict(
        radialaxis=dict(ticksuffix="%",angle=45,tickfont=dict(size=12)),
        angularaxis=dict(direction="clockwise",tickfont=dict(size=14)),
    ),
```
    
![image](https://user-images.githubusercontent.com/31547476/47201193-511a9400-d379-11e8-8d71-8782955cb6f4.png)
