### ISSUE TITLE
Problems when integrating with kivy python

### ISSUE THREAD

**Issue by vhk2018** [plotly/plotly.py#1273] opened 2018-11-13 12:18 UTC
After plotting the graph offline using plotly.offline.plot, the graph comes out fine as a html file. 

Then I display this html file inside a kivy app which is imported by this line 
from kivy.garden.cefpython import CEFBrowser

This imported module somehow affects the plotly function, since when I try to plot again after importing  CEFBrowser, plotly.offline.plot will incur the error: 
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "C:\project\lib\site-packages\plotly\offline\offline.py", line 493, in plot
     get_plotlyjs(),
   File "C:\project\lib\site-packages\plotly\offline\offline.py", line 41, in get_plotlyjs
     plotlyjs = pkgutil.get_data('plotly', path).decode('utf-8')
   File "C:\project\lib\pkgutil.py", line 578, in get_data
     loader = get_loader(package)
   File "C:\project\lib\pkgutil.py", line 462, in get_loader
     return find_loader(fullname)
   File "C:\project\lib\pkgutil.py", line 475, in find_loader
     loader = importer.find_module(fullname)
 TypeError: find_module() takes exactly 3 arguments (2 given)

The online plot got no issue with CEFBrowser, but the offline version is not working. This error only occurs after the above import module.
I need help on how to solve this. Thank you!!!

**Comment by jonmmease** [comment] 2018-11-15 10:50
Hi @vhk2018,

I'm not familiar with the kivy library, but here's what I think is going on.

 1. plotly.py uses `pkgutil` to load it's resources (https://docs.python.org/3/library/pkgutil.html)
 2. `pkgutil.get_data` internally calls `importer.find_module(fullname)` with a single argument. This matches the `find_module` specification (https://docs.python.org/3/library/imp.html#imp.find_module)
 3. kivy implements a custom importer with a custom `find_module` method that takes 2 arguments (See https://github.com/kivy/kivy/blob/96dfa5b55ed74c8223152dd84cd478bfed03e90b/kivy/garden/__init__.py#L85).

So I think the source of the issue is that kivy's importer is conflicting with the standard library `pkgutil` importer.  I'd recommend opening an issue with the kivy project, but feel free to reference this explanation.

**Comment by jonmmease** [comment] 2018-12-01 11:06
Closing as I don't think this is an issue in plotly.py. Feel free to follow up if you or the kivy folks want to talk through it any more.

**Closed by jonmmease** 2018-12-01 11:06 UTC
