### ISSUE TITLE
Display percentages on Sankey diagram [feature request]

### ISSUE THREAD

**Issue by guyts** [plotly/plotly.py#1779] opened 2019-09-18 14:34 UTC
I find it will be very useful having the option to display percentages alongside the absolute numbers on Sankey diagrams created with plotly.
For example, if the base node has sum of values of 100 going out of it in 5 flows, each flow accounting for 20% of the overall 100, I would like to display the 20 (value) and the 20% alongside (or instead, or toggle).

**Comment by Normale** [comment] 2023-12-01 01:14
Any updates on this one? :)

**Comment by Coding-with-Adam** [comment] 2023-12-01 21:06
hi @Normale, 
We don't have any updates on this feature request. It's currently not on our feature development roadmap.

**Comment by gvwilson** [comment] 2024-06-13 19:50
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:50 UTC
Labels: feature, p4
