### ISSUE TITLE
new feature - scattermapbox3d

### ISSUE THREAD

**Issue by bandersen23** [plotly/plotly.py#2037] opened 2020-01-07 02:40 UTC
Is there a possibility of creating a `scattermapbox3d` graph object? Essentially allowing the X,Y plane to be a `scattermapbox` layer with a Z axis (the map wouldn't need to persist into the Z Axis). This would be extremely useful for plotting geospatial data and an attribute alongside for example. Does this seem possible? 

If this is something that can be done with current features, I apologize. Thank you for all that you do!

**Comment by empet** [comment] 2020-01-07 07:39
No, there isn't a `scattermapbox3d` graph object. Instead you can define a map included in a z-plane  as a list of scatter3d objects, like this one:  [https://plot.ly/~empet/14375](https://plot.ly/~empet/14375).  It was created from a topojson file, converted to geojson.  x and y coordinates are the lons and lats of France boundaries, respectively the centers of France regions, read from the geojson file, while the list of z-coordinates is constant, i.e. z= [h]*len(x), where h is the height of the plane where the map is plotted.

**Comment by bandersen23** [comment] 2020-01-07 19:14
Thank you! That is helpful in the interim. What is the chance we can add 3d mapbox capabilities? It'd be super helpful to be able to add height to plots on a mapbox map.

**Comment by empet** [comment] 2020-01-07 20:08
As far as I know from this blogpost, https://blog.mapbox.com/taking-our-maps-to-the-next-dimension-dbeee37a7c4c, the Mapbox team is trying different methods to create 3d maps, but we can't know when the project will be implemented. 
Hence it  is   unlikely to be defined  a Plotly mapbox3d graph object in the near future.

**Comment by gvwilson** [comment] 2024-06-14 13:09
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:09 UTC
