### ISSUE TITLE
Spacing for title reduced when using tools.make_subplots with subplot_titles

### ISSUE THREAD

**Issue by AbdealiLoKo** [plotly/plotly.py#1406] opened 2019-01-25 09:01 UTC
I was using the `utils.make_subplots` and realized that the space given to the Title of the plot reduces if I use this compared to the other standard plots.

The plot with standard scatter:
<img width="1624" alt="screen shot 2019-01-25 at 2 27 45 pm" src="https://user-images.githubusercontent.com/2200743/51735420-67896780-20ad-11e9-9de5-28355cde3135.png">
The plot with `make_subplots`:
<img width="1599" alt="screen shot 2019-01-25 at 2 27 31 pm" src="https://user-images.githubusercontent.com/2200743/51735421-67896780-20ad-11e9-9519-227a1a0d2921.png">

As you can see the space below the title has reduced when using make_subplot.
It looks like the title of the subplot has eaten into that margin.

Here is some code to reproduce:

```python
import random

import plotly
import plotly.offline as py
import plotly.graph_objs as go

myplots = [
    {
        "trace": go.Scatter(
            x=[random.randint(0, 10) for i in range(10)],
            y=[random.randint(0, 10) for i in range(10)],
            mode='markers', name='MyName{}'.format(i)),
        "title": "MyTitle{}".format(i),
        'xaxis': {"title": "MyXAxis{}".format(i)},
        'yaxis': {"title": "MyYAxis{}".format(i)},
    } for i in range(8)
]

NCOL = 4
NROW = math.ceil(len(myplots) / NCOL)
figure = plotly.tools.make_subplots(
    rows=NROW, cols=NCOL, subplot_titles=[i['title'] for i in myplots])

figure['layout'].update(title='My overall title', showlegend=False, height=400)
for isubplot, subplot in enumerate(myplots):
    figure.append_trace(subplot['trace'], math.floor(isubplot / NCOL) + 1, (isubplot % NCOL) + 1)
    figure['layout']['xaxis{}'.format(isubplot + 1)].update(subplot['xaxis'])
    figure['layout']['yaxis{}'.format(isubplot + 1)].update(subplot['yaxis'])

standard_fig = go.Figure([o['trace'] for o in myplots], {"title": "My overall Title", "height": 400})
subplot_fig = figure
```

Expected behaviour:
The `layout.margin.t` attribute should be the distance between the top of the chart and the top of the `subplot_titles` values

Versions:
Plotly Py: 3.4.0
Python: 3.6.4

**Comment by jonmmease** [comment] 2019-01-25 11:09
Hi @AbdealiJK,

Thanks for the report.  The main problem that I'm seeing with this subplot figure is that the layout algorithm seems to break down when there are so many subplots is a relatively short figure, causing the bottom subplot titles to overlap with the xaxis in the subplot above.

But that doesn't sound like what you are referring to.

> The `layout.margin.t` attribute should be the distance between the top of the chart and the top of the subplot_titles values

I'm not sure I understand what you mean by this.  If this were true, wouldn't the top subplot titles ("MyTitle1" and "MyTitle2") overlap with the main figure title ("My overall title")?

**Comment by AbdealiJK** [comment] 2019-01-25 23:37
Was looking at the function for `make_subplots` and realized that the reason is that the `subplot_titles` for the top row are at Y-location `1` and the yanchor is `bottom`. Hence it is basically going out of the `paper`.

I tried setting `yanchor` to be `top` but that makes the title overlap with the chart itself.


 - We could set `layout.margin.t` and increase it by `16` (the font size of the title) more than the default value
 - We could set the `heights` and `grid` (i think) appropriately so that the graphs move down slightly when the title is being added.

**Comment by AbdealiJK** [comment] 2019-01-27 03:33
So, the way it works for me is I generate some plots in python and I send it over to different clients/websites/apps.
I try to keep as little style information in my plots as possible.

The client(s) then take my data/layout then apply some styling depending on which theme they are using. One of the clients was trying to use a slightly more compact theme and the default margin was quite high for the plotly - so, in all their plots they have reduced the margin causing the other plots to look nice, but the plot by `make_subplot` does not look good.

But I guess that since this spacing calculation is happening in plotly.py and not plotly.js - this is not something they can control?
Note: While the title control in 3.5.0 is awesome, it still isn't ideal in my opinion because it involved custom coding for this specific type of plot on all the client sides if they want to change margin.

But it is definitely the workaround I will use for now :) Thanks!

Just some thoughts for a scenario like this ...
**Approach 1**:
Is there any way for plotly.js to use variables in their JSON values ?
Like if we use something like `x: "${layout.margin.t} + 1}"` it should be able to calculate the value on the fly ?

**Approach 2**:
I notice that the subplot titles are being calculated as annotations with plotly.py - maybe this could have a property in plotly.js and calculated during rendering ?

**Comment by AbdealiJK** [comment] 2019-01-27 03:35
So, the way it works for me is I generate some plots in python and I send it over to different clients/websites/apps.
I try to keep as little style information in my plots as possible.

The client(s) then take my data/layout then apply some styling depending on which theme they are using. One of the clients was trying to use a slightly more compact theme and the default margin was quite high for the plotly - so, in all their plots they have reduced the margin causing the other plots to look nice, but the plot by `make_subplot` does not look good.

But I guess that since this spacing calculation is happening in plotly.py and not plotly.js - this is not something they can control?
Note: While the title control in 3.5.0 is awesome, it still isn't ideal in my opinion because it involved custom coding for this specific type of plot on all the client sides if they want to change margin.

But it is definitely the workaround I will use for now :) Thanks!

Just some thoughts for a scenario like this ...
**Approach 1**:
Is there any way for plotly.js to use variables in their JSON values ?
Like if we use something like `x: "${layout.margin.t} + 1}"` it should be able to calculate the value on the fly ?

**Approach 2**:
I notice that the subplot titles are being calculated as annotations with plotly.py - maybe this could have a property in plotly.js and calculated during rendering ?

**Comment by jonmmease** [comment] 2019-01-28 11:20
Thanks for explaining your workflow. That makes sense.  I think for resizing with subplot titles to behave properly the titles would need to be handled by plotly.js.

Plotly.js does have it's own version of subplots now (these were added relatively recently, after the `make_subplots` function was already in plotly.py). See https://plot.ly/javascript/subplots/.  So it might make sense for title properties to be added to these subplots directly in plotly.js.  Feel free to open an issue to discuss this on the plotly.js project at https://github.com/plotly/plotly.js/issues.

**Comment by gvwilson** [comment] 2024-06-13 17:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:42 UTC
Labels: question, make_subplots
