### ISSUE TITLE
Table cells font is colored not according to the provided list

### ISSUE THREAD

**Issue by drenout** [plotly/plotly.py#1241] opened 2018-10-23 21:34 UTC
I created the next color list for my table:
```python
color_schema = [
            ['white', 'white', ... , 'white'],
            ....
            ['white', 'white', ... , 'white'],
            ['red', 'green', ... , 'green'],
        ]
...
table = go.Table(
        domain=dict(x=xdomain, y=ydomain),
        header=dict(
            values=METRICS,
            line=dict(color='#506784'),
            fill=dict(color='#2d5378'),
            font=dict(color='#dfd9d3', size=12),
            align=['left'] * 5
        ),
        cells=dict(
            values=[columns[metric] for metric in METRICS],
            line=dict(color='#506784'),
            fill=dict(color='#404653'),
            font=dict(color=color_schema),
            align=['left'] * 5,
            height=35,
        ),
        columnwidth=columnwidth,
    )
```
I expected to see white font color for all the columns except the last one, only one cell with the red and remaining cells with the green font color for the last column:
![image](https://user-images.githubusercontent.com/26801119/47390685-cca77880-d6cc-11e8-8510-ae375cdfc227.png)

But when I scroll the table down, the next appeared cell in the last column has red font color as well: 
![image](https://user-images.githubusercontent.com/26801119/47390806-11331400-d6cd-11e8-8981-38bb48fa4d82.png)

And every scrolled screen I see the red font color, although red color was defined only once. 

I tried to use the `color_schema ` for the ` fill=dict(color=color_schema )` and `line=dict(color=color_schema)` and it worked perfectly - I saw only one red cell/line

plotly==3.3.0
python 3.6.5 and 2.7.15rc1 (tried on both)
OS - Ubuntu 18.04.1 LTS

**Comment by jonmmease** [comment] 2018-10-24 12:34
Hi @drenout, thanks for the report.  Could you update your example with some simple sample data so that we have something to run to reproduce what you're seeing?  Thanks!

**Comment by drenout** [comment] 2018-10-24 17:33
Python code with repro:
```python
import plotly
import plotly.graph_objs as go


header = ['First', 'Second', 'Third']
column = ['Pears' for _ in range(50)]
last_column = column[:]
last_column[0] = 'Apples'

colors = ['green' for _ in range(50)]
last_color = colors[:]
# only one red color is defined
last_color[0] = 'red'

values = [column, column, last_column]
color_schema = [colors, colors, last_color]

table = go.Table(
    header=dict(
        values=header,
    ),
    cells=dict(
        values=values,
        font=dict(color=color_schema),
    ),
)

layout = go.Layout(
    autosize=False,
    width=500,
    height=500,
)
fig = dict(data=[table], layout=layout)
plotly.offline.plot(fig, filename='font_color_bug.html')
```

I expected to see only 'Apples' with red font color, but if you scroll table down, you'll see 'Pears' with red color as well in the last column

**Comment by jonmmease** [comment] 2018-10-26 10:41
Thanks for the example @drenout, I was able to reproduce this in Plotly.js directly. I created an issue with the Plotly.js project at https://github.com/plotly/plotly.js/issues/3167. I'm going to close this issue now since plotly.py will pick up any future fixes made in plotly.js automatically.

Thanks again for taking the time to report this and to make up the reproducible example!

**Closed by jonmmease** 2018-10-26 10:41 UTC
