### ISSUE TITLE
Add react method to FigureWidget to replace full figure contents 

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1521] opened 2019-04-15 10:33 UTC
It would be nice to have a `react` method on `FigureWidget` to be able to replace the entire figure contents in a single command.  This would be useful for updating a displayed `FigureWidget` with a new figure generated by a figure factory or `plotly_express`.

Cross reference: https://community.plot.ly/t/plotly-express-hover-selecting-event-only-partially-working/22136 for

**Comment by gvwilson** [comment] 2024-06-13 19:31
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:31 UTC
Labels: enhancement
