### ISSUE TITLE
Non-opaque crossings for parallel categories 

### ISSUE THREAD

**Issue by harisbal** [plotly/plotly.py#2203] opened 2020-02-16 15:43 UTC
Hello,
I'm trying to figure out how to cancel the opacity for the crossing lines for a parallel categories figure.
What bothers me is that setting explicitly the alpha value of the line color to 1 does not result in non-opaque crossings.
I also tried to amend the colorscale but this didn't work either.
```
df = px.data.tips()
fig = px.parallel_categories(df)

fig.update_traces(line_color='rgba(0,0,255,1.0)')

cscale = [[0.0, 'rgba(0,0,255,1)'], [1.0, 'rgba(0,0,255,1)']]
fig.update_layout(coloraxis_colorscale=cscale) 
fig.show()
```
![image](https://user-images.githubusercontent.com/6556306/74607740-e8b20300-50e3-11ea-961c-eb0478123ddc.png)

I'm I missing something? Thank you in advance!

**Comment by gvwilson** [comment] 2024-06-14 13:08
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:08 UTC
