### ISSUE TITLE
Cannot Animate Plot by pandas.Timestamp

### ISSUE THREAD

**Issue by johnmccain** [plotly/plotly.py#1737] opened 2019-08-23 18:23 UTC
Attempting to animate a plot using a pandas Timestamp column results in an exception.

Using Python 3.6.8, plotly_express==0.4.1, plotly==4.1.0

Code to replicate:
```python
import plotly_express as px
import pandas as pd

# create a dataframe with mock data
df = pd.DataFrame(
    [
        {"x": 1, "y": 1, "date": "2018-01-01"},
        {"x": 2, "y": 1, "date": "2018-01-02"},
        {"x": 3, "y": 1, "date": "2018-01-03"},
    ]
)
df["date"] = pd.to_datetime(df["date"])
df.head()

#       date | x | y
# 2018-01-01 | 1 | 1
# 2018-01-02 | 2 | 1
# 2018-01-03 | 3 | 1

# attempt to plot
px.scatter(df, x="x", y="y", animation_frame="date")

```

Exception & stack trace:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\jmccain\AppData\Local\Programs\Python\Python36\lib\site-packages\plotly\express\_chart_types.py", line 52, in scatter
    return make_figure(args=locals(), constructor=go.Scatter)
  File "C:\Users\jmccain\AppData\Local\Programs\Python\Python36\lib\site-packages\plotly\express\_core.py", line 874, in make_figure
    orders, sorted_group_names = get_orderings(args, grouper, grouped)
  File "C:\Users\jmccain\AppData\Local\Programs\Python\Python36\lib\site-packages\plotly\express\_core.py", line 859, in get_orderings
    key=lambda g: orders[col].index(g[i]) if g[i] in orders[col] else -1,
  File "C:\Users\jmccain\AppData\Local\Programs\Python\Python36\lib\site-packages\plotly\express\_core.py", line 859, in <lambda>
    key=lambda g: orders[col].index(g[i]) if g[i] in orders[col] else -1,
ValueError: Timestamp('2018-01-01 00:00:00') is not in list
```

I found the cause of the issue, in [_core.py:847](https://github.com/plotly/plotly.py/blob/6eb94f0fd817e1d399e458232e26ae58721a1dee/packages/python/plotly/plotly/express/_core.py#L847)

Pandas `.unique()` method returns a NumPy array, and as given in the [examples section](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.unique.html), it will convert a `pandas.Timestamp` to a `numpy.datetime64`.
```python
>>> pd.Series([pd.Timestamp('2016-01-01') for _ in range(3)]).unique()
array(['2016-01-01T00:00:00.000000000'], dtype='datetime64[ns]')
```

The `uniques` list defined at _core.py:847 uses the `.unique()` method, converting the series of `pandas.Timestamp` into an array of `numpy.datetime64`
```python
uniques = args["data_frame"][col].unique()
```

This distinction is relevant on line 857:
```python
group_names = sorted(
    group_names,
    key=lambda g: orders[col].index(g[i]) if g[i] in orders[col] else -1
)
```

Which causes the ValueError when `.index()` does not find a matching element due to this behavior of pandas.Timestamp and numpy.datetime64 seen here:

```python
>>> pandas.Timestamp('2018-01-01 00:00:00') in [numpy.datetime64('2018-01-01T00:00:00.000000000')]
True
>>> [numpy.datetime64('2018-01-01T00:00:00.000000000')].index(pandas.Timestamp('2018-01-01 00:00:00'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Timestamp('2018-01-01 00:00:00') is not in list
```

**Comment by johnmccain** [comment] 2019-09-09 17:43
Having dug a little deeper, the issue around animating by pandas.Timestamp goes beyond the code segment I addressed above.  Is animating by date supported functionality?  If not, would this be better as a feature request?

**Comment by toships** [comment] 2019-12-17 17:24
have the same issue

**Comment by javid-jouzdani** [comment] 2020-03-06 12:46
Thank you toships,
worked for me too.

**Comment by robroc** [comment] 2020-04-24 14:28
I have this problem too. A simpler workaround that worked for me is passing: 
`animation_frame = df.datecolumn.astype(str)`

**Comment by JorgeMiguelGomes** [comment] 2021-04-19 12:46
> I have this problem too. A simpler workaround that worked for me is passing:
> `animation_frame = df.datecolumn.astype(str)`

This works perfectly! Thank you!

**Comment by riyadparvez** [comment] 2021-08-16 15:55
Is there any plan to fix this issue?

**Comment by gvwilson** [comment] 2024-06-13 19:46
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:46 UTC
Labels: bug
