### ISSUE TITLE
Support TileLayer and/or image overlay for scattermapbox

### ISSUE THREAD

**Issue by meteoDaniel** [plotly/plotly.py#1260] opened 2018-11-05 15:41 UTC
folium (leaflet.js), openLayers or mapbox gl and other interactive map tools are able to deal with TileLayers or image overlays.

It would be great to implement this to plotly.

Best regards
Daniel

**Comment by jonmmease** [comment] 2018-11-06 11:32
Thanks for the suggestion.  I'm going to close this as a duplicate of your plotly.js issue https://github.com/plotly/plotly.js/issues/3173.  This would need to be implemented in plotly.js first, and then plotly.py would get support automatically.

**Closed by jonmmease** 2018-11-06 11:32 UTC

**Comment by meteoDaniel** [comment] 2018-11-06 11:48
I am mainly interested in python but i think you will implement new features on all platforms ;)
