### ISSUE TITLE
Odd behavior of subplot figure when resetting axes or selecting / deselecting in legend

### ISSUE THREAD

**Issue by jhthompson12** [plotly/plotly.py#1766] opened 2019-09-10 22:07 UTC
Hi, 

I've not experienced this before with subplots, but I'm noticing it now with the following figure which contains 2 subplots:
![image](https://user-images.githubusercontent.com/45108842/64654092-fcdb3100-d3dc-11e9-8bdf-4c053e9adf5a.png)

This is the code to get there:

`from _plotly_future_ import v4_subplots
    from plotly.subplots import make_subplots
    import plotly.graph_objs as go
    from plotly.offline import plot'

    fig = make_subplots(rows=2, cols=1, shared_xaxes=True)
    before = ['Effective Load', 'Effective Renewable', 'Effective Total Generation', 'Effective SoCo Gens', 'Ramprate before ES']
    after = ['Load after ES', 'Effective Renewable', 'ES Power', 'Total Generation after ES', 'SoCo Gen after ES', 'Ramprate after ES']

    for col in before:
        fig.add_trace(go.Scatter(
                                    x=grid_data_with_hood.index,
                                    y=grid_data_with_hood[col],
                                    name=col,
                                    line=dict(shape='vh')
                                ),
                        row=1, col=1)

    for col in after:
        fig.add_trace(go.Scatter(
            x=grid_data_with_hood.index,
            y=grid_data_with_hood[col],
            name=col,
            line=dict(shape='vh')
        ),
            row=2, col=1)

    plot(fig, filename = 'before_and_after_ES.html')`

If I isolate a scatter in one of the plots by double clicking it in the legend, the left limit of the x-axis seems to expand zooming the graph out a little: 
![image](https://user-images.githubusercontent.com/45108842/64654136-22683a80-d3dd-11e9-9352-da878c469646.png)

If i add another trace to the same subplot, it happens again:
![image](https://user-images.githubusercontent.com/45108842/64654166-3dd34580-d3dd-11e9-8a01-446ec6ac1572.png)

this will continue to happen as more plots are added or hidden from this subplot. If I choose to unhide a scatter from the OTHER subplot, it reset's the axis:
![image](https://user-images.githubusercontent.com/45108842/64654201-59d6e700-d3dd-11e9-8c1d-5cb219749200.png)

If i try to reset the axes manually by double clicking the plot or pressing the "reset axes" toolbar button, it does it again!
![image](https://user-images.githubusercontent.com/45108842/64654242-74a95b80-d3dd-11e9-881e-c1bdfa0d3ce4.png)

As far as I can tell it happens on Chrome, Firefox, and IE and also persists after downgrading from 4.1.1 to 3.10 to 3.9 to 3.8.1

Let me know if any other info would be useful, thanks for the help!

**Comment by gvwilson** [comment] 2024-06-13 19:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:49 UTC
