### ISSUE TITLE
Violin Plots not Grouping into Multiple Violins

### ISSUE THREAD

**Issue by Omniportance** [plotly/plotly.py#1389] opened 2019-01-04 22:24 UTC
This seems to be an issue I experienced after updating plotly.py to 3.5.0, and  the issue persists whether I install from conda or from pip

Based on the example from here: https://plot.ly/python/violin-plot/
Using the code provided:

```
np.random.seed(619517)
Nr = 250
y = np.random.randn(Nr)
gr = np.random.choice(list("ABCDE"), Nr)
norm_params = [(0, 1.2), (0.7, 1), (-0.5, 1.4), (0.3, 1), (0.8, 0.9)]

for i, letter in enumerate("ABCDE"):
    y[gr == letter] *= norm_params[i][1] + norm_params[i][0]
df = pd.DataFrame(dict(Score = y, Group = gr))

fig = ff.create_violin(df, data_header='Score', group_header='Group',
                       height=500, width=800)
plotly.offline.plot(fig, filename='C:\\Users\\USERNAME\\Documents\\PyPlots\\Multiple Violins.html')
```

The same problem persists with my own data, the plots end up overlapping rather than grouping. This was literally working fine yesterday on an older version (3.4.2) of plotly, but now I cannot update or create multiple violin plots, despite no change in code.

The output looks something like this:

![image](https://user-images.githubusercontent.com/46386737/50714159-392fe380-103d-11e9-91a3-ac15b8e23933.png)

**Comment by nicolaskruchten** [comment] 2019-01-05 00:08
Maybe related? https://github.com/plotly/plotly.js/issues/3390

**Comment by Omniportance** [comment] 2019-01-05 00:12
> Maybe related? plotly/plotly.js#3390

I wouldn't be surprised that they are related. I don't use plotly.js but the issue seems to be rather similar.

**Comment by nicolaskruchten** [comment] 2019-01-05 00:15
Ah well Plotly.py is a wrapper for Plotly.js so you are kind of using it :)

**Comment by Omniportance** [comment] 2019-01-05 00:19
> Ah well Plotly.py is a wrapper for Plotly.js so you are kind of using it :)
I know, just not how to precisely word it that way - although I hear there are some minor differences, where some things updated in Plotly.js don't necessarily get updated in Plotly.py because it could break

**Comment by Omniportance** [comment] 2019-01-05 00:56
> Ah well Plotly.py is a wrapper for Plotly.js so you are kind of using it :)

Fair, because I have heard about their being minor differences - with some parts of plotly.py not updating when plotly.js updates because of the potential for it to break, that's why I think this issue is probably still relevant to plotly.py users

**Comment by jonmmease** [comment] 2019-01-05 11:03
Thanks for taking the time to report this @Omniportance.  I think there's a good chance that it's related to plotly/plotly.js#3390, but I'll leave this open here as well as a reminder to double check once plotly/plotly.js#3390 is addressed in plotly.js.

**Comment by etpinard** [comment] 2019-01-07 16:40
Hmm,

https://user-images.githubusercontent.com/46386737/50714159-392fe380-103d-11e9-91a3-ac15b8e23933.png

looks like a violin generated from the plotly.py figure factory.

**Comment by jonmmease** [comment] 2019-01-08 11:06
Yeah, good point @etpinard.  We should still get to the bottom of this, but the recommended way to create violin plots is now to use the first-class violin trace (https://plot.ly/python/violin/#multiple-traces) rather than the figure factory.

I looked into this a bit, and something seems odd with the layout.  Here's the layout that results from https://plot.ly/python/violin-plot/#multiple-violins.

```
 'layout': {'autosize': False,
               'height': 500,
               'hovermode': 'closest',
               'showlegend': False,
               'title': {'text': 'Violin and Rug Plot'},
               'width': 800,
               'xaxis': {'mirror': False,
                         'range': [-0.3519296977351358, 0.30994141477927983],
                         'showgrid': False,
                         'showline': False,
                         'showticklabels': False,
                         'ticks': '',
                         'title': {'text': 'B'},
                         'zeroline': False},
               'xaxis2': {'mirror': False,
                          'range': [-0.7016703968670251, 0.6013919973891876],
                          'showgrid': False,
                          'showline': False,
                          'showticklabels': False,
                          'ticks': '',
                          'title': {'text': 'C'},
                          'zeroline': False},
               'xaxis3': {'mirror': False,
                          'range': [-0.37874143756128675, 0.33228453130107233],
                          'showgrid': False,
                          'showline': False,
                          'showticklabels': False,
                          'ticks': '',
                          'title': {'text': 'E'},
                          'zeroline': False},
               'xaxis4': {'mirror': False,
                          'range': [-0.46963617536888913, 0.40803014614074096],
                          'showgrid': False,
                          'showline': False,
                          'showticklabels': False,
                          'ticks': '',
                          'title': {'text': 'A'},
                          'zeroline': False},
               'xaxis5': {'mirror': False,
                          'range': [-0.4956026892691915, 0.4296689077243263],
                          'showgrid': False,
                          'showline': False,
                          'showticklabels': False,
                          'ticks': '',
                          'title': {'text': 'D'},
                          'zeroline': False},
               'yaxis': {'autorange': True,
                         'mirror': False,
                         'showgrid': False,
                         'showline': True,
                         'showticklabels': True,
                         'ticklen': 4,
                         'title': {'text': ''},
                         'zeroline': False}}
```

The traces representing each violin group are assigned to different xaxis numbers.  The figure factory doesn't (and hasn't ever as far as I can tell) specify an explicit domain for the different xaxis objects.

We can add an explicit domain to each xaxis, which I expect will take care of the problem. but @etpinard @nicolaskruchten can you think of any reason why the default behavior here might have changed?

**Comment by gvwilson** [comment] 2024-06-13 17:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:42 UTC
Labels: bug, plotly.js
