### ISSUE TITLE
Uncaught ReferenceError: Plotly is not defined

### ISSUE THREAD

**Issue by maddukurisrinivasarao** [plotly/plotly.py#1595] opened 2019-06-03 16:44 UTC
I am trying to create plots from jupyter kernel (based on ProcessMetaKernel) and display plots in jupyter notebook.

My Jupyter kernel code is

class MyKernel(ProcessMetaKernel):
    def do_execute_direct(self, code, silent=True):
        import plotly
        import plotly.graph_objs as go
        plot_div=plotly.offline.plot({"data": [go.Scatter(x=[1, 2, 3, 4], y=[4, 3, 2, 1])],"layout": 
        go.Layout(title="hello world")}, auto_open=False, output_type='div',include_plotlyjs=True)
        self.Display(HTML(data=plot_div))
        return code

**Comment by jonmmease** [comment] 2019-06-05 10:09
Hi @maddukurisrinivasarao,

For inline display in the classic JupyterNotebook, it doesn't work to load plotly.js using a `<script>` tag (which is what `include_plotlyjs=True` does), instead it seems to be necessary to load plotly.js using `requirejs`.  This is what the built-in `offline.iplot` function does.

Take a look at the `HtmlRenderer`/`NotebookRenderer` at https://github.com/plotly/plotly.py/blob/7cce28331781f189aaf545ab2476889f1bfe720c/plotly/io/_base_renderers.py#L222 for details.  You may be able to borrow some of this logic for your custom kernel.

Hope that helps!

**Comment by gvwilson** [comment] 2024-06-13 19:32
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:32 UTC
Labels: question
