### ISSUE TITLE
Sankey and snap arrangement 

### ISSUE THREAD

**Issue by xanderwallace85** [plotly/plotly.py#2338] opened 2020-03-31 07:06 UTC
Hi there!

I have noticed some users asked how to compute the width of the nodes in the sankey diagram. Knowing that would be very helpful to increase flexibility and allow users for a better control of the (manual) nodes placement. Could you document how the snap arrangement works and how it avoids overlaps? Maybe a function that return the (normalized) width of the given nodes could be introduced?

**Comment by gvwilson** [comment] 2024-06-14 13:04
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:04 UTC
