### ISSUE TITLE
Heatmap categorical axis not recognized as categorical

### ISSUE THREAD

**Issue by plpla** [plotly/plotly.py#1510] opened 2019-04-09 18:56 UTC
I was trying to create an heat-map offline and the categorical axis is not recognized properly.
In the following example, the X axis is interpreted as numerical values and the heat-map is empty. 

```mport numpy as np
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot
import plotly
print(plotly.__version__)    #3.7.1
init_notebook_mode()

trace = go.Heatmap(z=np.random.rand(2, 9), y=["A", "B"], x=["1E1", "2A1", "3E2", "2A2", "1A1", "3A1", "1E2", "3E3", "1A2"],  colorscale="Viridis")
iplot([trace])
```

![Empty](https://user-images.githubusercontent.com/1944849/55827054-4f838a80-5ad7-11e9-9d83-78899212fa39.png)

**Comment by jonmmease** [comment] 2019-04-10 11:02
Thanks for the report @plpla,

This seems to be an issue with the Plotly.js logic for automatically choosing the axis type.  The workaround is be explicit that you want a categorical x-axis

```python
import plotly.graph_objs as go
import numpy as np

from plotly.offline import init_notebook_mode, iplot
import plotly
print(plotly.__version__)    #3.7.1
init_notebook_mode()

trace = go.Heatmap(z=np.random.rand(2, 9),
                   y=["A", "B"],
                   x=["1B1", "2A1", "3E2", "2A2", "1A1", "3A1", "1E2", "3E3", "1A2"],
                   colorscale="Viridis")
fig = go.Figure(data=[trace],
                layout={'xaxis': {'type': 'category'}})
iplot(fig)
```
![newplot (16)](https://user-images.githubusercontent.com/15064365/55873654-3671ec80-5b5e-11e9-91a9-45d4746e2534.png)

@plotly/plotly_js How does the categorical axis detection algorithm work?  Is it getting thrown off because some of these strings contain representations of valid numbers?

**Comment by etpinard** [comment] 2019-04-10 12:44
Ha, our auto-type algo must think `3E2` is `300` in exponential notation. Switching those `E` to e.g. `B` seems to make things work ok: https://codepen.io/etpinard/pen/oOZeXp?editors=1010

**Comment by etpinard** [comment] 2019-04-10 12:44
The full algo is here: https://github.com/plotly/plotly.js/blob/54586b86e09b34aa1a669cdf30e088e36dd32cd0/src/plots/cartesian/axis_autotype.js

**Comment by nicolaskruchten** [comment] 2019-04-17 13:07
the operative part of that link above is `// require twice as many DISTINCT categories as distinct numbers` so basically all the `xEy` count as distinct numbers and the others as categories.

**Comment by gvwilson** [comment] 2024-06-13 19:30
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:30 UTC
Labels: question
