### ISSUE TITLE
Boxplot breaks with color-by on this dataset

### ISSUE THREAD

**Issue by adamerose** [plotly/plotly.py#1828] opened 2019-10-18 04:20 UTC
```
import pandas as pd
import plotly.express as px
df = pd.read_csv('http://www.sharecsv.com/dl/ebe52d00c57c258856474071ca53879c/df.csv')
fig = px.box(df,x='week',y='speed',color='type')
```
Dataset:
http://www.sharecsv.com/s/ebe52d00c57c258856474071ca53879c/df.csv

Output:
![image](https://user-images.githubusercontent.com/10884874/67065392-23a72880-f13c-11e9-977e-9e7be304011d.png)

Output without color='type':
![image](https://user-images.githubusercontent.com/10884874/67065441-551ff400-f13c-11e9-94bd-d180ec63d833.png)

**Comment by gvwilson** [comment] 2024-06-14 13:14
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:14 UTC
