### ISSUE TITLE
Visualization of text annotations 

### ISSUE THREAD

**Issue by danyaljj** [plotly/plotly.py#999] opened 2018-04-29 15:36 UTC
Does Plotly have examples for text annotation visualization? 
Here is an example from here: http://nlp.cogcomp.org/ 
<img width="339" alt="screen shot 2018-04-29 at 11 34 59 am" src="https://user-images.githubusercontent.com/2441454/39408253-6c66470a-4ba1-11e8-8a63-da824da35bbc.png">

Basically, the goal is to create such graphs (text, some spans, and their edges), for a given text and its annotation **on the fly**. 

If you have something like this, better to make it more explicit and highlight it since this would bring so attention from AI and Natural Language Processing community to your library.

**Comment by gvwilson** [comment] 2024-06-13 17:38
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:38 UTC
Labels: enhancement
