### ISSUE TITLE
Add more projection options to Mapbox map layers in Python

### ISSUE THREAD

**Issue by wybert** [plotly/plotly.py#4189] opened 2023-05-04 20:04 UTC
Hi, I would like to see projection support in Mapbox map layers like, `px.scatter_mapbox`, such as  'globe' projection (which will make a tile-based 3d globe map). I noticed that [Plotly is integrated with Mapbox-gl](https://plotly.com/python/mapbox-layers/), and the [Mapbox-GL support different projections](https://docs.mapbox.com/mapbox-gl-js/guides/projections/), so it should be easy to have this option in Plotly. It looks like it's already supported in `scatter_geo` (see the [doc](https://plotly.com/python-api-reference/generated/plotly.express.scatter_geo.html))but not Mapbox layers.

See projections support in Mapbox-GL [here](https://docs.mapbox.com/mapbox-gl-js/guides/projections/). See what's looks like with projection here,
<img width="681" alt="image" src="https://user-images.githubusercontent.com/5254627/236315193-3090e555-630b-4a50-89e0-806d0d93dca0.png">
<img width="682" alt="image" src="https://user-images.githubusercontent.com/5254627/236315273-e46555ff-4a7b-4f62-9c4d-17597e7fc26e.png">

The code by the support the function should look like,

```python
import pandas as pd
us_cities = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/us-cities-top-1k.csv")

import plotly.express as px

fig = px.scatter_mapbox(us_cities, lat="lat", lon="lon", hover_name="City", hover_data=["State", "Population"],
                        color_discrete_sequence=["fuchsia"], zoom=3, height=300)
fig.update_layout(
    mapbox_style="white-bg",
    mapbox_layers=[
        {
            "below": 'traces',
            "sourcetype": "raster",
            "sourceattribution": "United States Geological Survey",
            "source": [
                "https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/{z}/{y}/{x}"
            ]
        }
      ])
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0}, projection= 'globe')
fig.show()
```
the `projection` option can be configured to support more projections

**Comment by alexcjohnson** [comment] 2023-05-05 14:02
duplicate of https://github.com/plotly/plotly.js/issues/6591, I'll comment over there.

**Closed by alexcjohnson** 2023-05-05 14:02 UTC
