### ISSUE TITLE
ImportError: No module named '_plotly_future_'

### ISSUE THREAD

**Issue by apal90** [plotly/plotly.py#1663] opened 2019-07-12 20:52 UTC
I have been using plotly stably on my Windows laptop with python 3.6 a long time. I just tried running the  same program on a linux machine with python 3.5.2, and I get the following error while importing plotly:

```
~/workspace_python/plottingFunctions.py in <module>
     25 
     26 #import plotly.plotly as py
---> 27 import plotly.graph_objs as go
     28 import plotly.figure_factory as FF
     29 

~/.local/lib/python3.5/site-packages/plotly/__init__.py in <module>
     28 
     29 from __future__ import absolute_import
---> 30 from _plotly_future_ import _future_flags
     31 
     32 from plotly import (

ImportError: No module named '_plotly_future_'
```

How do I fix this? Is this an incompatibility problem with python 3.5?

**Comment by jonmmease** [comment] 2019-07-16 09:58
Hi @apal90,

It sounds like you might have a corrupt installation or you may have multiple versions of the `plotly` package installed. Try uninstalling and reinstalling like this

```
$ pip uninstall plotly
$ conda uninstall plotly # If you have conda installed
$ pip install plotly
```

Does that help?

**Comment by innyso** [comment] 2019-07-16 13:45
same thing happened to me when I tried to use plotly in jupyter notebook with python 3.7

**Comment by gvwilson** [comment] 2024-06-13 19:41
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:41 UTC
