### ISSUE TITLE
Sankey diagram nodes with  dynamic heigth

### ISSUE THREAD

**Issue by ChibahAbdelwahab** [plotly/plotly.py#1935] opened 2019-11-30 15:48 UTC
Hello,
I'm using the python Sankey diagram, where a node is a group of users and a link is a user migration from a group to another,

The problem is that in my groups, users are not unique, so the node size is not realistic when it's computed according to the incoming and outgoing flow (same user may come from different groups) 

How can I dynamically set the size of my nodes?

**Comment by gvwilson** [comment] 2024-06-14 13:11
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:11 UTC
