### ISSUE TITLE
CORS needed to use some tile servers with mapbox

### ISSUE THREAD

**Issue by jontis** [plotly/plotly.py#4126] opened 2023-03-28 00:14 UTC
Some tile servers needs CORS for mapbox to be able to GET the tiles. 
I can turn off the check in browser, but that doesn't seem the right way to do it.

Could this be added in the function?

Kindly

**Comment by AaronStiff** [comment] 2023-03-30 16:28
Marking this as a duplicate of #4137 just because that one has a few extra details.

**Closed by AaronStiff** 2023-03-30 16:28 UTC
Labels: duplicate
