### ISSUE TITLE
RGBA: alpha value rounding error 

### ISSUE THREAD

**Issue by jessicahinojosa** [plotly/plotly.py#1999] opened 2019-12-11 19:28 UTC
I'm trying to write to an image file with a very low rgba opacity (below 0.01). When executed in a notebook, low opacity objects render correctly, but it appears that during export, the alpha value (set at 0.002) rounds to 0, and nothing appears.  

Is there a way to pass the un-altered alpha level all the way to the png/jpeg creation?

Example:

``` python
import numpy as np
import plotly.graph_objects as go
from iallocate import iAllocatePlot
from plotly.offline import init_notebook_mode, iplot, plot
from plotly.graph_objs import *

fig = go.Figure(data=go.Scatter(
    x = np.random.randn(1000),
    y = np.random.randn(1000),
    mode='markers',
    marker=dict(
        size=40,
        color='rgba(255, 0, 0, .002)',
    )
))


# Set options common to all traces with fig.update_traces
fig.update_traces(mode='markers', marker_line_width=0)
fig.update_layout(title='Styled Scatter',
                  yaxis_zeroline=False, xaxis_zeroline=False,
                  paper_bgcolor = 'rgba(0,0,0,0)',
                  plot_bgcolor = 'rgba(0,0,0,0)')


fig.show()

fig.write_image(f"test.png",width=1000,height=950)

from IPython.display import Image
Image(filename='test.png')
```

![image](https://user-images.githubusercontent.com/12767823/70653305-d87c3400-1c19-11ea-850d-c591d877a645.png)

**Comment by gvwilson** [comment] 2024-06-14 13:10
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:10 UTC
