### ISSUE TITLE
Cannot set x-axis to side='top' for second chart in subplot with shared_yaxes=True

### ISSUE THREAD

**Issue by kasparthommen** [plotly/plotly.py#1553] opened 2019-05-06 14:00 UTC
Hi all,

I'm trying to display two charts with shared y-axes side-by side and with their respective x-axes shown at the top. This works for the 1st chart on the left, but not for the 2nd one on the right, see the minimal example below. Am I doing something wrong or is this a bug?

Note that it works fine if I change `shared_yaxes` to `False` but I really need them shared.

```python
import plotly.plotly as py
import plotly.graph_objs as go
from plotly import tools
from plotly.offline import init_notebook_mode, iplot

init_notebook_mode()

trace_left = go.Scatter(x=[3, 2, 5], y=[1, 2, 3], name='Left')
trace_right = go.Scatter(x=[2, 6, 7], y=[1, 2, 4], name='Right')

fig = tools.make_subplots(rows=1, cols=2, specs=[[{}, {}]], shared_yaxes=True)
fig.append_trace(trace_left, 1, 1)
fig.append_trace(trace_right, 1, 2)

layout = go.Layout(
    xaxis=dict(side='top'),
    xaxis2=dict(side='top'),   # <- 2nd x-axis should be on top as well but isn't
)

fig['layout'].update(layout)
iplot(fig, filename='issue')
```

![06-05-2019 15-55-36](https://user-images.githubusercontent.com/49198627/57229997-a7021100-7017-11e9-805e-7ea1b7afe920.png)

**Comment by jonmmease** [comment] 2019-05-10 11:35
Hi @kasparthommen,

Thanks for the report. I'm not exactly sure what's going wrong with the current version of `make_subplots`, but the new `make_subplots` version that will be the default in plotly.py version 4 (See https://github.com/plotly/plotly.py/pull/1528) seems to behave as you would expect.  You can try this out now using the `v4_subplots` future flag. For example:

```python
from _plotly_future_ import v4_subplots
import plotly.graph_objs as go
from plotly import tools
from plotly.offline import init_notebook_mode, iplot

init_notebook_mode()

trace_left = go.Scatter(x=[3, 2, 5], y=[1, 2, 3], name='Left')
trace_right = go.Scatter(x=[2, 6, 7], y=[1, 2, 4], name='Right')

fig = tools.make_subplots(rows=1, cols=2, specs=[[{}, {}]], shared_yaxes=True)
fig.append_trace(trace_left, 1, 1)
fig.append_trace(trace_right, 1, 2)

layout = go.Layout(
    xaxis=dict(side='top'),
    xaxis2=dict(side='top'),   # <- 2nd x-axis should be on top as well but isn't
)

fig['layout'].update(layout)
iplot(fig, filename='issue')
```
![newplot-14](https://user-images.githubusercontent.com/15064365/57524449-d05fbd00-72f5-11e9-8402-d66d047ac861.png)

You can also make this a little bit more concise using the `update_xaxes` method added in version 3.9 (See https://github.com/plotly/plotly.py/pull/1548).

```python
from _plotly_future_ import v4_subplots
import plotly.graph_objs as go
from plotly import tools
from plotly.offline import init_notebook_mode, iplot

init_notebook_mode()

trace_left = go.Scatter(x=[3, 2, 5], y=[1, 2, 3], name='Left')
trace_right = go.Scatter(x=[2, 6, 7], y=[1, 2, 4], name='Right')

fig = tools.make_subplots(
    rows=1,
    cols=2,
    shared_yaxes=True
).update_xaxes(side='top')

fig.append_trace(trace_left, 1, 1)
fig.append_trace(trace_right, 1, 2)

iplot(fig, filename='issue')
```

**Comment by kasparthommen** [comment] 2019-05-17 06:50
Hi @jonmmease 

Thanks for your reply, I'll try that!

I assume this means that there won't be a fix for the current version? If so then please mark this issue as closed/wont-fix or whatever you see fit, thanks.

**Comment by gvwilson** [comment] 2024-06-13 19:32
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:32 UTC
Labels: make_subplots, V4
