### ISSUE TITLE
Feature Request: Arrow Keys for Panning 

### ISSUE THREAD

**Issue by SterlingButters** [plotly/plotly.py#1258] opened 2018-11-05 00:57 UTC
I think it would nice to implement the use of arrow keys for panning in plots because for larger data sets there is a bit of a lag in switching between manipulation tools, plus it would be nice not to have to those few extra clicks. 

Hard for me to gauge the difficulty of implementation but I thought it would be worth a mention.

Also just decided to do a quick google search and found several others seem to like the idea though for plotly.js: 

https://github.com/plotly/plotly.js/issues/562

**Comment by jonmmease** [comment] 2018-11-05 11:49
Hi @SterlingButters,

Thanks for the suggestion, having some way to respond to keystrokes would be a nice feature in general.  There would be some design questions to consider, for instance whether this would be a change in plotly.js or only plotly.py.

Also, for you immediate use-case, if you shift+left click in zoom mode you can perform a pan action without changing tools.  Similarly, if you shift+left click in pan mode you can perform a zoom action without changing tools.

**Comment by SterlingButters** [comment] 2018-11-05 16:53
@jonmmease I agree! And I would guess maybe the implementation would be in plotly.js with an eventlistener for the corresonding keyCodes for the arrow keys. 

Interestingly enough, my immediate-use case deals with 3D plots for which your suggestion did not seem to work (at least in Safari).

**Comment by gvwilson** [comment] 2024-06-13 17:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:44 UTC
Labels: enhancement
