### ISSUE TITLE
grouped histogram: first bar becomes invisible when range is specified to start at smallest value

### ISSUE THREAD

**Issue by abeinrucker** [plotly/plotly.py#1744] opened 2019-08-30 14:51 UTC
I have integer valued data and a grouping variable. When I plot a histogram grouped by a categorical variable, the bars appear just right and left of the value they represent. When I specify a range starting from the smallest value, the most left bar disappears. (plotting online)

#the following python code produces a histogram with 2 bars, but 3 bars should be visible 
df = pd.DataFrame(np.array([[1, 'a'], [1, 'b'], [2, 'a']]),
                    columns=['values', 'group'])
fig = px.histogram(df, x="values", 
                   y="values", 
                   title='histogram of 3 values',
                   color="group",
                   barmode='group',
                   range_x=[1, 2])

**Comment by gvwilson** [comment] 2024-06-13 19:48
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:48 UTC
