### ISSUE TITLE
Unable to define opacity of markers for Scatter3D using rgba

### ISSUE THREAD

**Issue by blondegeek** [plotly/plotly.py#1416] opened 2019-01-28 19:49 UTC
I originally posted this in the [plotly community forums](https://community.plot.ly/t/how-to-define-opacity-per-point-for-scatter3d/18621) and it was recommend I instead post this as an issue.

I would like to define the opacity per point for a Scatter3D plot. I’ve tried to do this by defining a rgba color per point, but the alpha component seems to be treated as white (example code below). Any suggestions? Thanks!

```
import plotly
import plotly.graph_objs as go
import plotly.offline as off
plotly.offline.init_notebook_mode(connected=False)
import numpy as np

x_max = 2
num_bins = 20

linspace = np.linspace(-x_max, x_max, num_bins)
X, Y, Z = np.meshgrid(linspace, linspace, linspace)

gaussian = lambda x: np.exp(-np.sum(np.power(x, 2), 0, keepdims=False)/0.5)

coords = np.concatenate((np.expand_dims(X.flatten(), 0),
                         np.expand_dims(Y.flatten(), 0),
                         np.expand_dims(Z.flatten(), 0)), 0)

gaussian_coords = gaussian(coords)

color_scale = lambda x: 'rgba(255, 0, 0, {})'.format(np.round(x, 2))

half = int(20**3/2)

trace1 = go.Scatter3d(
    x=X.flatten()[:half],
    y=Y.flatten()[:half],
    z=Z.flatten()[:half],
    mode='markers',
    marker=dict(
        size=10,
        color = list(map(color_scale, 
                         gaussian_coords.flatten().tolist()[:half])),
        line=dict(width=0, color='rgba(0, 0, 0, 0)'),
        # opacity=0.5  # Toggle this to see the Gaussian shape more clearly
    )
)

data=[trace1]

layout=go.Layout(height=600, width=600)

fig=go.Figure(data=data, layout=layout)
off.iplot(fig)
```

**Comment by jonmmease** [comment] 2019-01-29 10:58
Example with 
```
x_max = 2
num_bins = 10
```
![scatter3d_transperance](https://user-images.githubusercontent.com/15064365/51903719-e1aa3c80-238a-11e9-8664-9e70738bd6cb.gif)

**Comment by jonmmease** [comment] 2019-01-29 11:18
Thanks for the report @blondegeek,

I've opened up a pair of plotly.js issues based on this example.
 - https://github.com/plotly/plotly.js/issues/3492
 - https://github.com/plotly/plotly.js/issues/3493

Please check them out and double check that they capture the issues you're seeing.

**Comment by blondegeek** [comment] 2019-01-29 22:32
Hi @jonmmease. Thanks for your responsiveness and filing the plotly.js issues. I hadn't actually noticed the second issue regarding gridlines until I saw the issue. The first issue certainly captures what I was seeing.

**Comment by archmoj** [comment] 2019-03-11 14:19
@jonmmease plotly/plotly.js#3492 & plotly/plotly.js#3493 are closed; so we may close this issue?

**Comment by gvwilson** [comment] 2024-06-13 19:24
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:24 UTC
Labels: plotly.js
