### ISSUE TITLE
can not run plotly in google colab

### ISSUE THREAD

**Issue by TAOGZ** [plotly/plotly.py#2257] opened 2020-03-09 05:22 UTC
I am using colab to run my code.
However, colab can not run the following code while I can run it in my computer.

```
from sklearn.decomposition import PCA
from sklearn import preprocessing
# Set charts to view inline`
%matplotlib inline`

def plot_explained_variance(pca):
    import plotly
    from plotly.graph_objs import Bar, Line
    from plotly.graph_objs import Scatter, Layout
    from plotly.graph_objs.scatter import Marker
    from plotly.graph_objs.layout import XAxis, YAxis
    plotly.offline.init_notebook_mode() # run at the start of every notebook
   
    explained_var = pca.explained_variance_ratio_
    cum_var_exp = np.cumsum(explained_var)
    
    plotly.offline.iplot({
        "data": [Bar(y=explained_var, name='individual explained variance'),
                 Scatter(y=cum_var_exp, name='cumulative explained variance')
            ],
        "layout": Layout(xaxis=XAxis(title='Principal components'), yaxis=YAxis(title='Explained variance ratio'))
    })
        

# Create a minimum and maximum processor object
min_max_scaler = preprocessing.MinMaxScaler()

# Create a standard processor object
standard_scaler = preprocessing.StandardScaler()

# Create an object to transform the data to fit minmax processor
# X_scaled = min_max_scaler.fit_transform(X)
X_scaled = standard_scaler.fit_transform(X)
        
# Examine the evolution of individual explained variance and cumulative explained variance.
pca_test = PCA(n_components=X.shape[1])
X_pca_test = pca_test.fit(X_scaled)
plot_explained_variance(pca_test)
```

Thank you very much.

**Comment by nicolaskruchten** [comment] 2020-03-09 12:58
The code above looks like it's written for Plotly.py v3.x but the most recent version (and the one installed on Google Colab by default) is v4.5.0. If you want to try downgrading your version on Google Colab you can do so with something like `!pip install plotly==3.11` or you can check out our [Migration Guide](https://plot.ly/python/v4-migration/) to see if you can adapt your code to the new version.

All that said, the code above looks like it should run unmodified as it's using deprecated but not removed functions (like `plotly.offline.iplot()`). If you can provide a fully-runnable version of this code (i.e. including some sample data for `X`) I can take a look :)

**Comment by TAOGZ** [comment] 2020-03-09 15:15
> 
> 
> The code above looks like it's written for Plotly.py v3.x but the most recent version (and the one installed on Google Colab by default) is v4.5.0. If you want to try downgrading your version on Google Colab you can do so with something like `!pip install plotly==3.11` or you can check out our [Migration Guide](https://plot.ly/python/v4-migration/) to see if you can adapt your code to the new version.
> 
> All that said, the code above looks like it should run unmodified as it's using deprecated but not removed functions (like `plotly.offline.iplot()`). If you can provide a fully-runnable version of this code (i.e. including some sample data for `X`) I can take a look :)

Thank you very much.
I would like to provide my code and associated dataset.
May I ask how can i share them with you?

**Comment by nicolaskruchten** [comment] 2020-03-09 18:25
Can you create a gist or just inline them into this issue please?

**Comment by TAOGZ** [comment] 2020-03-10 01:20
> 
> 
> Can you create a gist or just inline them into this issue please?


Can you please try the following code?
Plotly is used in the last part. Please see the comment.
And I also attach the dataset which is only 640KB.
Thank you very much.

```
# import package
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter('ignore', DeprecationWarning)
%matplotlib inline 
import missingno as mn

# print('Pandas:', pd.__version__)
# print('Numpy:',np.__version__)

# load the used car dataset from csv file
df = pd.read_csv('used-cars-price-train-data.csv') # read in the csv file
df.drop('id', axis=1, inplace=True) # drop the 'id' column because this column is redundant.
df.head() # show the first five rows

# manipulating the data

# transform the unit of Mileage from km/kg to km/l 
print(df.Mileage)

# find those with string km/kg
rows_with_kmkg = df['Mileage'].str.contains('km/kg').fillna(False)

for i,kmkg_row in df[rows_with_kmkg].iterrows():
    mileage = float(kmkg_row['Mileage'][:-5])/1.355 # the last five elements are unit, so we extract only number here
    df.at[i,'Mileage'] = '{:.2f} kmpl'.format(mileage) 
    
# find those with string kmpl
rows_with_kmpl = df['Mileage'].str.contains('kmpl').fillna(False)
df['Mileage'] = df.Mileage.str.strip('kmpl') # drop out all the kmpl string

df.rename(columns={'Mileage':'Mileage/kmpl'}) # put the kmpl in the name

df.Mileage = df.Mileage.astype(float) # transform the data into float type
print(df.Mileage)

df.Engine = df.Engine.str.strip('CC')
df.rename(columns={'Engine':'Engine/CC'})
df.Engine = df.Engine.astype(float)


df.rename(columns={'Power':'Power/bhp'})
df.Power = df.Power.str.strip('bhp')
df.Power = df.Power.astype(float)

# transform the oridinal data of Owner_Type to integer
df.replace(to_replace=['First', 'Second', 'Third', 'Fourth & Above'], value=[1, 2, 3, 4], inplace = True)
df.Owner_Type = df.Owner_Type.astype(int)
# transform the nominal data of Transmission to one hot encoding 
df.replace(to_replace=['Manual', 'Automatic'], value=[0, 1], inplace = True)
df.Transmission = df.Transmission.astype(int)

#transform the nominal data of Fuel_Type to one hot encoding

a = pd.get_dummies(df.Fuel_Type,prefix = 'Fuel_Type')

a = pd.DataFrame(a) 

df = pd.concat([df,a], axis=1)


#transform the nominal data of Location to one hot encoding
a = pd.get_dummies(df.Location,prefix = 'Location')

a = pd.DataFrame(a) 

df = pd.concat([df,a], axis=1)

# extract the brand name from Name
a = df.Name.str.split(' ')
Brand = []
for i,row in df.iterrows():
    Brand.append(a[i][0])
    
Brand = pd.Series(Brand)
Brand.name = 'Brand'

df = pd.concat([df,Brand], axis=1)

print(df.Brand)


# transform the nominal data to one hot encoding Brand

a = pd.get_dummies(df.Brand,prefix = 'Brand')

a = pd.DataFrame(a) 

df = pd.concat([df,a], axis=1)

# impute based upon the K closest samples (rows) 
from sklearn.impute import KNNImputer
import copy

# get object for imputation
knn_obj = KNNImputer(n_neighbors=5)

# create a numpy matrix from pandas numeric values to impute
temp = df[['Mileage','Engine','Seats','Power']].to_numpy()

# use sklearn imputation object
knn_obj.fit(temp)
temp_imputed = knn_obj.transform(temp)
#    could have also done:
# temp_imputed = knn_obj.fit_transform(temp)

df_imputed = copy.deepcopy(df) # not just an alias
df_imputed[['Mileage','Engine','Seats','Power']] = temp_imputed

del df_imputed['Name']
del df_imputed['Location']
del df_imputed['Fuel_Type']
del df_imputed['New_Price']
del df_imputed['Price']
del df_imputed['Brand']

label = df_imputed.Price_range
y = label.to_numpy() # build target vector

df_imputed = df_imputed.drop(['Price_range'], axis=1)

Data = df_imputed
X = Data.to_numpy() # build feature matrice
X.shape


# ======This is the main part=============
from sklearn.decomposition import PCA
from sklearn import preprocessing
# Set charts to view inline
%matplotlib inline

def plot_explained_variance(pca):
    import plotly
    from plotly.graph_objs import Bar, Line
    from plotly.graph_objs import Scatter, Layout
    from plotly.graph_objs.scatter import Marker
    from plotly.graph_objs.layout import XAxis, YAxis
    plotly.offline.init_notebook_mode() # run at the start of every notebook
    
    explained_var = pca.explained_variance_ratio_
    cum_var_exp = np.cumsum(explained_var)
    
    plotly.offline.iplot({
        "data": [Bar(y=explained_var, name='individual explained variance'),
                 Scatter(y=cum_var_exp, name='cumulative explained variance')
            ],
        "layout": Layout(xaxis=XAxis(title='Principal components'), yaxis=YAxis(title='Explained variance ratio'))
    })
        

# Create a minimum and maximum processor object
min_max_scaler = preprocessing.MinMaxScaler()

# Create a standard processor object
standard_scaler = preprocessing.StandardScaler()

# Create an object to transform the data to fit minmax processor
# X_scaled = min_max_scaler.fit_transform(X)
X_scaled = standard_scaler.fit_transform(X)
        
# Examine the evolution of individual explained variance and cumulative explained variance.
pca_test = PCA(n_components=X.shape[1])
X_pca_test = pca_test.fit(X_scaled)
plot_explained_variance(pca_test)
```
[used-cars-price-train-data.zip](https://github.com/plotly/plotly.py/files/4309706/used-cars-price-train-data.zip)

**Comment by gvwilson** [comment] 2024-06-14 13:06
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:06 UTC
