### ISSUE TITLE
Proposal to provide my data interpolation algorithms in Python

### ISSUE THREAD

**Issue by dkennard3** [plotly/plotly.py#1532] opened 2019-04-21 16:48 UTC
Hello everyone, 

I'd like to propose an addition to this project that utilizes various forms of data interpolation algorithms that I've written in Python. I believe that implementing one or more of these algorithms would prevent the appearance of jagged lines in data, creating smoother curves in graph representations. I believe it would benefit many Plotly users. I have had previous experience with numerical analysis and graphing in MatPlotLib, and I wanted to share my files for other individuals to use.  

I have various algorithms ranging from Hermite, Lagrange, Piecewise Linear, Romberg, Taylor's method, RK method, and 2-step method for interpolating data points.

If anyone is interested in viewing or implementing these files, I am more than happy to share them!

**Comment by jonmmease** [comment] 2019-04-29 09:45
Hi @dkennard3, thanks for the offer.  In general, new interpolation algorithms would need to be added to the JavaScript library (https://github.com/plotly/plotly.js) as a new `scatter.line.shape` enumeration value.  See https://plot.ly/python/line-charts/#interpolation-with-line-plots for some examples of what's already supported.

Does that make sense?

**Comment by gvwilson** [comment] 2024-06-13 19:31
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:31 UTC
