### ISSUE TITLE
broken examples

### ISSUE THREAD

**Issue by mathematicalmichael** [plotly/plotly.py#1961] opened 2019-09-30 21:41 UTC
callbacks for color-changing doesn't work on this page:
plotly.py-docs/python/parallel-categories-diagram.md  / https://plot.ly/python/parallel-categories-diagram/
i.e. the videos don't match behavior when running the code snippet

**Comment by gvwilson** [comment] 2024-06-14 13:11
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:11 UTC
