### ISSUE TITLE
ERROR: raise exceptions.PlotlyRequestError(message, status_code, content)

### ISSUE THREAD

**Issue by YurRee** [plotly/plotly.py#727] opened 2017-04-07 03:41 UTC
```
    trace1 = go.Scatter(
        x=days_ago,
        y=get_jira_issues(type, 'created'),
        line=Line(color='rgb(206,69,60)'),
        name='<b>create</b>',
        connectgaps=True
    )
    trace2 = go.Scatter(
        x=days_ago,
        y=get_jira_issues(type, 'resolutiondate'),
        line=Line(color='rgb(74,180,70)'),
        name='<b>resolved</b>',
    )
    data = [trace1, trace2]
    layout = go.Layout(title=type, width=300, height=640)
    fig = go.Figure(data=data, layout=layout)

    py.image.save_as(fig, filename=filename + '.png')
```

I got this error below.

```
Traceback (most recent call last):
  File "/Users/Lee/Documents/RRX/git/DailyReport-Project/send_email.py", line 22, in <module>
    send.send_mail()
  File "/Users/Lee/Documents/RRX/git/DailyReport-Project/connect_smtp.py", line 49, in send_mail
    jira_dataItem.update_chart()
  File "/Users/Lee/Documents/RRX/git/DailyReport-Project/jira_dataItem.py", line 142, in update_chart
    plotly_chat.make_chart('friend', 'friend')
  File "/Users/Lee/Documents/RRX/git/DailyReport-Project/plotly_chat.py", line 54, in make_chart
    py.image.save_as(fig, filename=filename + '.png')
  File "/Users/Lee/.pyenv/versions/3.6.1/lib/python3.6/site-packages/plotly/plotly/plotly.py", line 831, in save_as
    img = cls.get(figure_or_data, format, width, height, scale)
  File "/Users/Lee/.pyenv/versions/3.6.1/lib/python3.6/site-packages/plotly/plotly/plotly.py", line 744, in get
    response = v2.images.create(payload)
  File "/Users/Lee/.pyenv/versions/3.6.1/lib/python3.6/site-packages/plotly/api/v2/images.py", line 18, in create
    return request('post', url, json=body)
  File "/Users/Lee/.pyenv/versions/3.6.1/lib/python3.6/site-packages/plotly/api/v2/utils.py", line 153, in request
    validate_response(response)
  File "/Users/Lee/.pyenv/versions/3.6.1/lib/python3.6/site-packages/plotly/api/v2/utils.py", line 79, in validate_response
    raise exceptions.PlotlyRequestError(message, status_code, content)
plotly.exceptions.PlotlyRequestError: Unknown Image Server Error
```

Any Help?

**Comment by cldougl** [comment] 2017-04-07 17:53
@BroderickLee the `py.image.save_as()` function is not an offline function. So to use that function you must be signed in.
More information on exporting images online and offline can be found in this doc: https://plot.ly/python/static-image-export/

**Comment by BroderickLee** [comment] 2017-04-08 05:49
@cldougl Yeah, I've already signed in, and with the following one:

`py.sign_in('yuli', 'XZDVIEvKAfPAYecZn15Q')`

My account type is community

**Comment by cldougl** [comment] 2017-04-08 12:28
@BroderickLee can you include the full code, i.e. how you're importing plotly?

**Comment by BroderickLee** [comment] 2017-04-10 03:51
```
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.graph_objs import *

py.sign_in('xxx', 'XXXVIEvKAfPAYecZn15QX')

def make_chart(type, filename):
    trace1 = go.Scatter(
        x=days_ago,
        y=get_jira_issues(type, 'created'),
        line=Line(color='rgb(206,69,60)'),
        name='<b>create</b>',
        connectgaps=True
    )
    trace2 = go.Scatter(
        x=days_ago,
        y=get_jira_issues(type, 'resolutiondate'),
        line=Line(color='rgb(74,180,70)'),
        name='<b>resolved</b>',
    )
    data = [trace1, trace2]
    layout = go.Layout(title=type, width=300, height=640)
    fig = go.Figure(data=data, layout=layout)

    py.image.save_as(fig, filename=filename + '.png')
```

Oh, my bad sorry. here is my code and what advice?

**Comment by cldougl** [comment] 2017-04-10 14:55
Unfortunately I cannot reproduce your issue. I would try running 
```
import plotly.tools
plotly.tools.get_config_file()
```

to make sure that your config file is set correctly (to the default options). You'll want to make sure it looks like this:

```
{u'auto_open': True,
 u'plotly_api_domain': u'https://api.plot.ly',
 u'plotly_domain': u'https://plot.ly',
 u'plotly_streaming_domain': u'stream.plot.ly',
 u'sharing': u'public',
 u'world_readable': True}
```

**Comment by sohamnavadiya** [comment] 2017-04-14 06:42
I also got the same error but after upgrading it to latest version it is not reproducing.

**Comment by cldougl** [comment] 2017-04-14 12:07
We're currently looking into intermittent issues with the image server

**Comment by MarcoBuster** [comment] 2017-05-11 14:27
Any updates?

**Comment by jonmmease** [comment] 2018-09-20 12:50
Plotly.py added built-in retry logic to help with server timeout errors in version 3.0.0.  Going to close this as I think plotly.py is now doing everything it can to help with this.

**Closed by jonmmease** 2018-09-20 12:50 UTC

**Comment by erdemalpkaya** [comment] 2020-03-18 02:06
Did we solve the issue?
