### ISSUE TITLE
Support of openstreetmap map tile

### ISSUE THREAD

**Issue by pe-perry** [plotly/plotly.py#1370] opened 2018-12-16 03:18 UTC
It looks like plotly/dash only support mapbox and google-map. Would the dev team consider to add some features supporting [openstreetmap map tile](https://wiki.openstreetmap.org/wiki/Tile_servers)? Or is there some workarounds already (so far, I don't find any on Internet)? Thank you! :)

**Comment by jonmmease** [comment] 2018-12-21 11:35
Thanks for the suggestion @kitman0804. Do you know if Mapbox itself supports OSM map tiles?  If so this might be something that could be handled in [plotly.js](https://github.com/plotly/plotly.js). 

Otherwise, I wonder what it would take to extract/convert png images from a tile server. From here it might be possible to use an approach like this datashader example (https://plot.ly/python/change-callbacks-datashader/).

**Comment by kitman0804** [comment] 2018-12-22 14:16
Thanks for your reply @jonmmease.

As I know, [the Mapbox Streets tileset source data is derived from OpenStreetMap.](https://www.mapbox.com/help/define-osm/) rather than using OSM map tiles directly that doesn't require a token.

It would be cool if there is some integration between [plot.js](https://github.com/plotly/plotly.js/) and some existing JS library, e.g. [leaflet.js](https://leafletjs.com/), I hope it won't be too complex.

**Comment by empet** [comment] 2018-12-22 16:34
@kitman0804 There is a Python library, `osmnx` [https://github.com/gboeing/osmnx](https://github.com/gboeing/osmnx), that can be used to retrieve  from OpenStreetMap, data for places.
 (`place` is the name of a string variable in `osmnx` that defines a region on the map).
 `osmnx` provides functions to define, analyze, and plot street networks, as matplotlib figures.
 
 In this notebook [https://plot.ly/~empet/15043](https://plot.ly/~empet/15043) you can see how based on this library and performing a query  for the restaurants in a bounding box around the Lake Como, Italy, I plotted information as a Plotly scattermapbox.
 
 More precisely,  I retrieved and defined a geo-dataframe via `osmnx`,  for the boundary of the Lake Como (colored in blue), and  the city Como (colored with a red linecolor).  The boundaries of these `places` are defined as layers in Mapbox.
  
  In the second part I defined a query, via Overpass API, for restaurant nodes in a bounding box around the lake. I extracted their geographic position and name,
  and defined a plotly `scattermapbox` trace.
  
  Here [https://plot.ly/~empet/15000] (https://plot.ly/~empet/15000) is an example of street network retrieved with the `osmnx`, and plotted with Plotly, by defining a custom function that returns   data for a plotly plot  of the network.

**Comment by gvwilson** [comment] 2024-06-13 17:43
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:43 UTC
Labels: enhancement
