### ISSUE TITLE
go.Heatmapgl doesn't update axes

### ISSUE THREAD

**Issue by sean-bam** [plotly/plotly.py#1749] opened 2019-08-31 23:23 UTC
Thanks for making some awesome graphing software, as a new user I'm getting some great plots already. However, I ran into one issue using HeatmapGL. I noticed that`fig.update_xaxes` and `fig.update_yaxes` doesn't seem to work with go.Heatmapgl. Here is an example where passing arguments to `fig.update_xaxes` doesn't do anything. Are there any workarounds? I'm especially interested in labeling the x-axis with ticks. 
```
fig = go.Figure(data=go.Heatmapgl(
                   z=[[1, 20, 30, 50, 1], [20, 1, 60, 80, 30], [30, 60, 1, -10, 20]],
                   x=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                   y=['Morning', 'Afternoon', 'Evening']))

fig.update_xaxes(title_text = 'X axis title should go here',
                     titlefont=dict(size=16,family='Raleway', color='grey'),
                     showgrid=False,
                     automargin = True,
                     ticks = 'outside',
                     tickwidth = 2,
                     nticks = 20,
                     tickangle=-45)
fig.show()
```

**Comment by gvwilson** [comment] 2024-06-13 19:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:49 UTC
