### ISSUE TITLE
create_animation doesn't handle mix of dict and graph_objs

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1616] opened 2019-06-15 11:56 UTC
See https://community.plot.ly/t/i-am-trying-to-create-bar-chart-animation-using-plotly-python-and-want-to-take-it-online/24589.

When a figure that contains a mix of `dict` and `graph_objs` is passed, there is an error raised in `chart_studio.plotly.create_animations`.

**Comment by gvwilson** [comment] 2024-06-13 19:33
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:33 UTC
Labels: bug, V4
