### ISSUE TITLE
Cell in Jupyter Lab is larger than the figure.

### ISSUE THREAD

**Issue by polakowo** [plotly/plotly.py#1745] opened 2019-08-30 22:52 UTC
Any way to make that Jupyter Lab cell match the provided figure size? Currently, it displays lots of white space at the bottom.

![Screen Shot 2019-08-31 at 00 49 15](https://user-images.githubusercontent.com/2664108/64054831-2c8e6b80-cb89-11e9-8ae2-ca21069bb4e5.png)

**Comment by polakowo** [comment] 2019-08-31 09:16
Using the following code resolved the issue. Seems to be a problem with `show` method.

```
fig = go.FigureWidget(data=data, layout=layout)
fig
```

**Comment by gvwilson** [comment] 2024-06-13 19:48
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:48 UTC
