### ISSUE TITLE
hover data not updating for all counties in a choropleth map

### ISSUE THREAD

**Issue by paneja4** [plotly/plotly.py#1037] opened 2018-06-20 18:18 UTC
Hello,

I searched for the issue I am facing but was not able to find any reference. I am working on a very basic choropleth map for counties in Florida and trying to pull in hoverdata which I need to use for further analysis. Hoverdata is correctly updated for most counties when we hover but as seen in the attached, looks like for a few counties even though we have values against them and we see appropriate color scale coding, we do not see any hover data for them.

In the attached, we see hover labels as well as the hover data for the Broward county but neither for the Monroe county.

Thanks for help!

code:-

fips = df_sample['FIPS'].tolist()
values = df_sample['Unemployment Rate (%)'].tolist()

fig = ff.create_choropleth(
    fips=fips, values=values,scope=['Florida'],
     title='USA by Unemployment %',
    legend_title='% unemployed'
)

app.layout=html.Div([html.Div([dcc.Graph(id='my-graph',figure=fig)]),
                    html.Div(id='my-hoverdata')])

@app.callback(
    Output('my-hoverdata', 'children'),
    [Input('my-graph', 'hoverData')])
def callback_image(hoverData):
    return json.dumps(hoverData, indent=2)

![hoverdata](https://user-images.githubusercontent.com/10531850/41676810-1f27b404-74b6-11e8-9611-e6241212c331.PNG)

**Comment by chriddyp** [comment] 2018-06-20 19:43
Duplicate of https://github.com/plotly/dash/issues/274

**Closed by chriddyp** 2018-06-20 19:43 UTC
