### ISSUE TITLE
Rendering of Matplotlib linestyle=':' needs to be updated in par with 'dash' property

### ISSUE THREAD

**Issue by priyatharsan** [plotly/plotly.py#1123] opened 2018-08-20 20:42 UTC
Code sample:
```
ax4.plot(y4 * points, linestyle=':', color=color, linewidth=3)
ax4.set_xlabel('Line Type :')

plotly_fig = tls.mpl_to_plotly( fig )
```

The error message is:
```
ValueError: 
    Invalid value of type '__builtin__.str' received for the 'dash' property of scatter.line
        Received value: 'circle'

    The 'dash' property is a string and must be specified as:
      - One of the following strings:
            ['solid', 'dot', 'dash', 'longdash', 'dashdot',
            'longdashdot']
      - A number that will be converted to a string
```

**Comment by MeraX** [comment] 2019-03-19 20:24
I think I encountered a related bug:
Self contained code sample:
```
import plotly.offline
import matplotlib.pyplot as plt
import matplotlib
import plotly

print('using matplotlib', matplotlib.__version__, 'and plotly', plotly.__version__)

x = range(10)

fig, ax = plt.subplots()
ax.plot(x, x, linestyle=':', linewidth=2)
plotly.offline.plot_mpl(fig) 
```
using matplotlib 2.2.0 and plotly 3.7.0

Error:
```
ValueError: 
    Invalid value of type 'builtins.str' received for the 'dash' property of scatter.line
        Received value: 'dotted'

    The 'dash' property is an enumeration that may be specified as:
      - One of the following dash styles:
            ['solid', 'dot', 'dash', 'longdash', 'dashdot', 'longdashdot']
      - A string containing a dash length list in pixels or percentages
            (e.g. '5px 10px 2px 2px', '5, 10, 2, 2', '10% 20% 40%', etc.)
```
I have no clue, what is going on here, but the problem is linewidth=2 in my case. Any other value like 2.1, 1.5, 3, etc. worked for me, but 2 triggers this error.

**Comment by gvwilson** [comment] 2024-06-13 17:40
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:40 UTC
Labels: matplotlylib
