### ISSUE TITLE
Plotly in JupyterLab Has Very Small Height

### ISSUE THREAD

**Issue by mstumbo** [plotly/plotly.py#4226] opened 2023-06-02 00:38 UTC
I started a new miniconda environment and installed the latest python (3.10.10), Jupyter Lab, Plotly, and ipywidgets. When I graph with plotly, the height of the graph is very small, 16px, which squishes the graph. See image.

Here's the versions of the packages I'm using:
```
ipykernel                 6.23.1             pyh736e0ef_0    conda-forge
ipython                   8.13.2             pyhd1c38e8_0    conda-forge
ipywidgets                8.0.6              pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            8.2.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0           py310h2ec42d9_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.6.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.1              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.22.1             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.7              pyhd8ed1ab_1    conda-forge
plotly                    5.14.1             pyhd8ed1ab_0    conda-forge
```

![image](https://github.com/plotly/plotly.py/assets/7925514/2034d803-4680-44a4-a99d-4f5ba26bfaaf)

**Comment by alexcjohnson** [comment] 2023-06-02 17:24
Duplicate of #4066 and working on a fix in #4217

**Closed by alexcjohnson** 2023-06-02 17:24 UTC

**Comment by mstumbo** [comment] 2023-06-02 18:00
Thanks @alexcjohnson - apologies for missing #4066.

**Comment by mstumbo** [comment] 2023-06-02 18:08
For my use, downgrading to Jupyerlab 3.6.4 works just fine.
