### ISSUE TITLE
Feature Request: Enable multiple y-axis in px

### ISSUE THREAD

**Issue by claesnn** [plotly/plotly.py#2228] opened 2020-02-25 18:31 UTC
Currently, making multiple y-axis is difficult and requires quite some code: https://plot.ly/python/multiple-axes/#multiple-axes

Is it possible to implement this in plotly.express? Implementation together with issue 2224 would be perfect.

**Comment by gvwilson** [comment] 2024-06-14 13:07
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:07 UTC
