### ISSUE TITLE
Mime type rendering requires nbformat>=4.2.0 but it is not installed

### ISSUE THREAD

**Issue by JingZhang918** [plotly/plotly.py#3285] opened 2021-07-03 13:49 UTC
Hey guys, please help me! I've tried what I can. But I still got error. Help!!!

<img width="1111" alt="WX20210703-153948@2x" src="https://user-images.githubusercontent.com/27002833/124356363-f7845180-dc15-11eb-9602-742b397495b6.png">

**Comment by stipid** [comment] 2021-07-11 04:37
I have same problem while running in vscode 1.58

**Comment by nicolaskruchten** [comment] 2021-07-11 10:21
Yes, you need to install the required version.

**Comment by uriva** [comment] 2021-09-23 17:59
+1
https://stackoverflow.com/questions/69304838/plotly-cannot-find-nbformat

**Comment by KaneOne** [comment] 2022-01-08 06:45
+1

**Comment by Karlheinzniebuhr** [comment] 2023-01-30 22:05
+1 win10 python 3.9 vscode 1.74.3

**Comment by helioprado** [comment] 2023-02-06 16:52
I have the same problem, does anyone know the solution for it?

**Comment by nicolaskruchten** [comment] 2023-02-06 16:55
Yes, you need to install `nbformat` with the required version.

**Comment by Crypticat** [comment] 2023-02-13 14:10
I had the same problem. Posted the solution here:
[https://stackoverflow.com/a/75436915/3595697](url)

**Comment by yussyafridayusfi** [comment] 2023-04-30 09:26
I had some problem, I try this solution then clear output and run manually again. it works for me.
https://stackoverflow.com/questions/66557543/valueerror-mime-type-rendering-requires-nbformat-4-2-0-but-it-is-not-installed

**Comment by shuoyang2000** [comment] 2023-06-14 18:12
> I had some problem, I try this solution then clear output and run manually again. it's works for me. https://stackoverflow.com/questions/66557543/valueerror-mime-type-rendering-requires-nbformat-4-2-0-but-it-is-not-installed

This also works for me. Remember to restart the kernel :)

**Comment by ketipotova** [comment] 2023-08-03 11:10
i just restarted the kernel and it helped.

**Comment by Grazys** [comment] 2023-09-27 00:15
I went to cmd as administrator and put **`pip install nbformat`** and it worked

**Comment by Grazys** [comment] 2023-09-27 00:16
Or, if you need to upgrade de **nbformat**, you need to put **`pip install --upgrade nbformat`**

**Comment by afeld** [comment] 2023-10-26 15:54
I installed `nbformat` and that fixed the error in the original post, but ran into a subsequent problem.

Running

```python
import plotly.io as pio
pio.renderers.default = "notebook_connected+pdf"
```

I got `AttributeError: module 'isoduration' has no attribute 'DurationParsingException'`. Full trace:

![Screenshot 2023-10-26 at 9 47 09 AM copy](https://github.com/plotly/plotly.py/assets/86842/ca2bb77c-64ba-4079-b835-0cb8dd5e9ac5)


This was fixed by installing `isoduration`, which is apparently [a transitive dependency of nbformat->jsonschema](https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-formats). It's still unclear to me where that need is coming from. I'm also having trouble reproducing when creating an environment from scratch. Sharing in case any else runs into the same issue.

**Comment by moresanket4003** [comment] 2024-06-26 05:16
Restart your vscode or juypyter notebook

**Comment by gvwilson** [comment] 2024-07-11 13:45
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Closed by gvwilson** 2024-07-11 13:45 UTC

**Comment by Alphashivesh** [comment] 2025-07-11 09:43
Just install the required format of abformat and restart the kernel again, then it will work for sure.
