### ISSUE TITLE
Feature: utility function to retrieve color corresponding to fraction of color scale

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#1911] opened 2019-11-20 15:14 UTC
For example in matplotlib one can do `plt.cm.viridis(0.2)`. This can be useful to set the color of lines for example.

**Comment by gvwilson** [comment] 2024-06-14 13:12
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:12 UTC
