### ISSUE TITLE
Plot rendering becomes very slow with many images

### ISSUE THREAD

**Issue by matwilso** [plotly/plotly.py#978] opened 2018-03-25 01:09 UTC
I am trying to use plotly's `Scatter` to plot around 3000 RGB images of size 32x32 <br>(or about 3\*32\*32\*3000=~9 MB of data total).

plotly becomes very slow when I try to do this.  I don't think this is too much data to display (because D3 examples like [this](https://cs.stanford.edu/people/karpathy/tsnejs/) run fine), but the renderer seems to be handling it especially poorly.  I recorded a gif (below) of trying to explore the data, and a few things to notice are how it is generally laggy and how during zooming or panning, the images momentarily correspond with the wrong points in the graph.  This second point makes me think there is some inefficiency that may be a relatively easy fix to get better performance, but I'm not sure.

Basically, my point in raising this Issue is to ask:
- Is there a different way I should be doing this, that could be added to [this documentation](https://plot.ly/python/images/#add-multiple-images)? Or is this the best/only way in plotly, and I should use something else for now?
- Are there any plans or could there be plans made to support more performant image displaying? 

Thanks! :slightly_smiling_face: 

![slow_plotly](https://user-images.githubusercontent.com/19582683/37870257-55da6fea-2f8e-11e8-99b0-47362431b611.gif)

Here is the snippet of code that I am using to plot.

```python
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=True)


def get_images(path=data_path):
    """return a list of dictionaries for all images"""
    x=X_tsne[:,0]
    y=X_tsne[:,1]
    max_x = np.max(x)
    max_y = np.max(x)
    
    for i in range(len(x)):
        d = dict(
xref="x",
            yref="y",
            sizex=max_x/10,
            sizey=max_y/10,
            xanchor="center",
            yanchor="middle",
            x=x[i],
            y=y[i],
            source=get_thumbnail_path(i),
        )
        dlist.append(d)
        
    return dlist

images = get_images()

# plot all points from tsne
trace=go.Scatter(
    x=X_tsne[:,0],
    y=X_tsne[:,1],
    mode='markers',
    marker= dict(size= 14,
                line= dict(width=1),
                opacity= 0.0
               ),
    text=names)

# layout with images, where each image corresponds with a data point
layout=go.Layout(
    images=images,
    title= 't-SNE',
    hovermode='closest',
    showlegend= False
)
fig = go.Figure(data=[trace], layout=layout)
iplot(fig)
```

**Comment by sandeeprepakula** [comment] 2018-06-05 12:02
Checkout below link

https://github.com/YaleDHLab/pix-plot/

**Comment by gvwilson** [comment] 2024-06-13 17:38
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:38 UTC
Labels: performance, plotly.js
