### ISSUE TITLE
marker symbol for px.scatter_mapbox

### ISSUE THREAD

**Issue by sdementen** [plotly/plotly.py#2138] opened 2020-01-30 05:54 UTC
Is itpossible to specify the symbol marker when using plotly express scatter_mapbox (https://plot.ly/python-api-reference/generated/plotly.express.scatter_mapbox.html) ?

I do not see anything like the symbol argument found in https://plot.ly/python-api-reference/generated/plotly.express.scatter.html

**Comment by gvwilson** [comment] 2024-06-14 13:08
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:08 UTC
