### ISSUE TITLE
Could we add "paper" as an x and y anchor for choropleth colorbars?

### ISSUE THREAD

**Issue by mbkupfer** [plotly/plotly.py#1487] opened 2019-04-01 22:00 UTC
I'm able to set them as paper in plotly chart studio, but I'm not able to do this in my application because of a value error. I took a peak at the [choropleth validator xanchor](https://github.com/plotly/plotly.py/blob/master/plotly/validators/choropleth/colorbar/_xanchor.py), but wasn't to sure how to make the changes myself so I thought I would try and first see if this would be an easy fix. 

The error I get is:
```
Invalid value of type 'builtins.str' received for the 'xanchor' property of choropleth.colorbar
        Received value: 'paper'

```

**Comment by mbkupfer** [comment] 2019-04-01 22:04
For reference: https://plot.ly/create/?fid=mbkupfer:8&fid=mbkupfer:7#/

**Comment by jonmmease** [comment] 2019-04-04 09:21
Hi @mbkupfer, thanks for the suggestion.

The `'paper'` coordinate specification is usually associated with the `xref`/`yref` properties. e.g. `fig.layout.shape.xref = 'paper'`.  The `xanchor` property is used to specify which point on the object is being positioned by `x` and `y`.

Colorbars don't have `xref`/`yref` properties because, I believe, they are always specified in `'paper'` coordinates.  They don't offer, for example, the ability to position them with respect to individual `xaxis`/`yaxis` pairs.

I haven't looked at the code in chart studio for this, but does it offer options other than `'paper'` for position the colorbar?

**Comment by mbkupfer** [comment] 2019-04-04 17:00
Hi @jonmmease , my issue was the result of the colorbar overlapping the plot so I figured setting it to paper would force it to not. That said, I think I figured out how to properly configure the colorbar to not do that. 

>I haven't looked at the code in chart studio for this, but does it offer options other than 'paper' for position the colorbar?

It doesn't specifically mention this, but it does allow me to set it. From the choropleth docstrings, the only options I see are `'left', 'center', 'right'`

All in all, I think this is just a question of configuration so feel free to close if the colorbar is in fact always specified in `paper`.

**Comment by gvwilson** [comment] 2024-06-13 19:26
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:26 UTC
Labels: question
