### ISSUE TITLE
Inconsistent overlaying areas coloring

### ISSUE THREAD

**Issue by harisbal** [plotly/plotly.py#2009] opened 2019-12-17 16:50 UTC
Hello,
I believe that the resulting colors from overlaying filled areas is wrong. 
Disabling the "Base" trace in the following examples  makes the problem more obvious. 
[Problematic example-1](https://plot.ly/~step2smart/27/#/)
[Properly working example-2](https://plot.ly/~step2smart/20/#/)

Maybe I get something wrong but I believe that the colors between the overlaying and the non-overlaying areas are swapped. For instance, in example-1 the grey area should be orange since only one trace is plotted there.
![image](https://user-images.githubusercontent.com/6556306/71015978-2521ac80-20fd-11ea-9844-4e74980cd724.png)

I'm I getting something wrong?
Kind regards

**Comment by nicolaskruchten** [comment] 2019-12-17 17:40
Wow that does look super weird! Let me look into it :)

**Comment by harisbal** [comment] 2019-12-17 18:27
I believe the same happens in the second plot [here](https://plot.ly/python/filled-area-plots/)

**Comment by alexcjohnson** [comment] 2019-12-17 18:45
What's happening is all the traces have semitransparent fills, and the blue trace is filling _up_ to the yellow (blue + yellow makes gray). You see the expected blue color in the couple of places the blue is higher than yellow.

So then the question is: what would be a better way to display this?

**Comment by alexcjohnson** [comment] 2019-12-17 19:01
The difference is in each trace's `fill` attribute - sounds like you want `fill='tozeroy'` and you got `fill='tonext'`, which became the default when the traces were all added to `stackgroup="1"` (implying they should be treated as stacked rather than independently filling to zero).

That's how it works from the plotly.js side anyway, would be curious how that was generated from the Python side :)

**Comment by harisbal** [comment] 2019-12-17 21:11
Thanks for pointing this out @alexcjohnson.
Setting `fill='tozeroy'` sorted it out indeed.

**Comment by gvwilson** [comment] 2024-06-14 13:10
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:10 UTC
