### ISSUE TITLE
Some shapes of the subplots surpass the graph limits

### ISSUE THREAD

**Issue by jonsnowseven** [plotly/plotly.py#2928] opened 2020-11-23 17:57 UTC
## Bug

Shapes added to subplots with `yref` of the form `y*0 domain` surpass the graph limits.

## More information

After some debug I noticed that the `clip-path` CSS property of the underlying HTML element for the elements with `yref` of the form `y*0 domain` have a different `clip-path`.

## Steps to reproduce

1. Execute the following code
    ```python
    # ----- Imports

    import pandas as pd
    import random
    import datetime
    import seaborn as sns
    from plotly import graph_objects as go, offline as pyo
    from plotly.subplots import make_subplots    

    sns.set(color_codes=True)
    sns.set_context("paper")
    pyo.init_notebook_mode()


    # ----- Body

    NUM_CLUSTERS = 20
    DEFAULT_PALETTE = "gist_ncar"
    DEFAULT_SEED = 0
    VOLUME_COL = "num"
    CLUSTERS_IDS = [i for i in range(NUM_CLUSTERS)]


    def get_global_colours(
        clusters,
        palette_name: str = DEFAULT_PALETTE,
        seed_num: int = DEFAULT_SEED,
    ) -> dict:
        rnd = random.Random(seed_num)
        clusters_size = len(clusters)
        colors = sns.color_palette(palette_name, n_colors=clusters_size).as_hex()
        rnd.shuffle(colors)
        return {partition: colors[index] for index, partition in enumerate(clusters)}


    # create mock dataframe
    df = pd.DataFrame.from_records(
        [
            {
                "num": i,
                "index": random.randint(1, 100),
                "cluster_id": random.choice(CLUSTERS_IDS),
            }
            for i in range(100)
        ]
    )

    # set index
    df.set_index(["cluster_id", "index"], inplace=True)

    # create subplots
    fig = make_subplots(
        rows=NUM_CLUSTERS,
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.01,
    )

    # 
    colour_dict = get_global_colours(CLUSTERS_IDS)

    # update layout to add button
    fig.update_layout(**{
        "updatemenus": [
            {
                "type": "buttons",
                "active": 0,  # start button inactive
                "buttons": [
                    {
                        "label": "Hide highlight",
                        "method": "relayout",
                        "args2": [
                            "shapes",
                            [
                                {
                                    "fillcolor": "darkorange",
                                    "line": {"width": 0},
                                    "opacity": 0.25,
                                    "type": "rect",
                                    "x0": 50,
                                    "x1": 100,
                                    "xref": "x",
                                    "y0": 0,
                                    "y1": 1,
                                    "yref": "y domain"
                                    if cluster_idx == 0
                                    else "y%s domain" % (cluster_idx + 1),  # noqa: WPS323
                                }
                                for cluster_idx in CLUSTERS_IDS
                            ],
                        ],
                        "args": ["shapes", []],
                    },
                ],
            },
        ],
    })

    # adding plots
    for position, cluster in enumerate(CLUSTERS_IDS):
        cluster_df = df.loc[cluster]
        fig.add_trace(
            go.Scatter(
                x=list(cluster_df.index),
                y=list(cluster_df[VOLUME_COL]),
                name=cluster,
                fill="tozeroy",
                mode="lines",
                line_color=colour_dict[cluster] if colour_dict else None,
            ),
            row=position + 1,
            col=1,
        )

    display(fig)
    ```
1. Untoggle "Hide highlight"
1. Zoom one time (should be enough)
1. You can edit `NUM_CLUSTERS` and repeat the previous steps to check bug being reproduced

## Screenshots

<img width="1053" alt="screenshot1" src="https://user-images.githubusercontent.com/25992803/99996249-601f6c00-2db3-11eb-9f67-4ab6496bad9e.png">
<img width="1053" alt="screenshot2" src="https://user-images.githubusercontent.com/25992803/99996254-61509900-2db3-11eb-8ea1-86ddb6b1e569.png">
<img width="1053" alt="screenshot3" src="https://user-images.githubusercontent.com/25992803/99996258-61e92f80-2db3-11eb-82e6-7321be0d85b5.png">

**Comment by nicolaskruchten** [comment] 2020-11-24 19:10
This does seem like a bug but I can't replicate it with the code you've provided above... Can you please try to make a smaller reproducible test case? If this is not possible, please choose one single figure and upload the file resulting from `fig.write_json("file.json")` for us to use to reproduce :)

**Comment by jonsnowseven** [comment] 2020-11-25 08:54
Hi @nicolaskruchten.
I was my bad, you need some extra steps to replicate. I've updated the issue description.

Just to the following (after executing the code):

1. Untoggle "Hide highlight"
1. Zoom one time (should be enough)

After these additional steps, you should see the issue.

**Comment by nicolaskruchten** [comment] 2020-11-25 19:44
If you're at all able to provide a slightly more narrowed-down example that would be really helpful :)

**Comment by jonsnowseven** [comment] 2020-11-26 08:32
Hi @nicolaskruchten. 

Here you go. I think I cannot narrow it down anymore. If you change with `NUM_SUBPLOTS` to numbers multiples of 10, you'll see the issue.

Do not forget to **zoom inside the area of the inserted shapes**. The issue happens when zoom focus is within the shapes.

```python
import seaborn as sns
from plotly import graph_objects as go
from plotly import offline as pyo
from plotly.subplots import make_subplots

sns.set(color_codes=True)
sns.set_context("paper")
pyo.init_notebook_mode()

NUM_SUBPLOTS = 20

# create subplots
fig = make_subplots(
    rows=NUM_SUBPLOTS,
    cols=1,
    shared_xaxes=True,
    vertical_spacing=0.01,
)

# update layout to add button
fig.update_layout(**{
    "shapes":  [{
            "fillcolor": "darkorange",
            "line": {"width": 0},
            "opacity": 0.25,
            "type": "rect",
            "x0": 0,
            "x1": 5,
            "xref": "x",
            "y0": 0,
            "y1": 1,
            "yref": "y domain"
            if subplot_idx == 0
            else "y%s domain" % (subplot_idx + 1),  # noqa: WPS323
        }
        for subplot_idx in range(NUM_SUBPLOTS)
    ],
})

# adding plots
for position, i in enumerate(range(NUM_SUBPLOTS)):
    fig.add_trace(
        go.Scatter(
            x=list(range(10)),
            y=list(range(10)),
            name=str(i),
            fill="tozeroy",
            mode="lines",
        ),
        row=position + 1,
        col=1,
    )

display(fig)
```

I hope this helps.

**Comment by jonsnowseven** [comment] 2020-12-03 10:24
@nicolaskruchten, is there example more adequate to replicate?

**Comment by jonsnowseven** [comment] 2020-12-10 10:49
Any news regarding this issue?

**Comment by nicolaskruchten** [comment] 2020-12-10 13:08
We'll try to get it fixed in the next release in the new year, sorry it didn't get prioritized for the last release :)

**Comment by gvwilson** [comment] 2024-06-24 15:59
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-24 15:59 UTC
