### ISSUE TITLE
Feature Request: Center a large table's scrollbar

### ISSUE THREAD

**Issue by vab2048** [plotly/plotly.py#1806] opened 2019-10-07 09:37 UTC
Hi, 

I had already asked this question on the forum here: https://community.plot.ly/t/how-can-i-center-a-large-table/29148 but was unable to find a way to achieve what I want.

Essentially, I would like the ability to control where the scroll bar is set in a table:
1.  when the table figure is rendered for the first time. 
2. and when a cell in the table is clicked.

For more illustration, if you look at the page here (https://plot.ly/python/table/) there is a table called "NHL Entry Draft 2013". The feature (1) would allow me to specify when the figure is displayed that the scrollbar is already set to a specific row. Below I have illustrated having it set to the row for 'Kyle Platzer'.

![Scroll bar moved to 'Kyle Platzer'](https://i.imgur.com/e3g8Hro.png)

For feature (2) it would mean if I were to click a cell (let's say the "name" heading cell) it would automatically move the scroll bar to the center of the table - so it is around 'Kyle Platzer'.

Do these features already exist or can I achieve the same functionality somehow within plotl.ly already?

Thanks.

**Comment by vab2048** [comment] 2019-10-27 15:04
Any idea on how controlling the scrollbar programmatically  can currently be achieved in plotly?

**Comment by nicolaskruchten** [comment] 2019-10-27 15:24
I’m not aware of any way to do this today.

**Comment by vab2048** [comment] 2019-10-28 15:36
@nicolaskruchten As an alternative, if I were to use the data table 'paging' functionality (https://dash.plot.ly/datatable/callbacks) is there a way to set the default page which is loaded in the table? E.G. have it load to page 5 out of 10 by default?

**Comment by nicolaskruchten** [comment] 2019-10-29 04:20
So the `table` trace type of Plotly.py and Dash DataTable are two totally separate/unrelated approaches to rendering tables, and yes, I believe you can do this with Dash DataTables

**Comment by gvwilson** [comment] 2024-06-14 13:14
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:14 UTC
