### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HTTP_PORT'

### ISSUE THREAD

**Issue by Bosebcc** [plotly/plotly.py#1053] opened 2018-07-09 14:28 UTC
Traceback (most recent call last):
  File "offlineExample.py", line 1, in <module>
    import plotly.plotly
  File "/usr/local/lib/python2.7/dist-packages/plotly/__init__.py", line 31, in <module>
    from plotly import (plotly, dashboard_objs, graph_objs, grid_objs, tools,
  File "/usr/local/lib/python2.7/dist-packages/plotly/plotly/__init__.py", line 10, in <module>
    from . plotly import (
  File "/usr/local/lib/python2.7/dist-packages/plotly/plotly/plotly.py", line 28, in <module>
    from requests.compat import json as _json
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 53, in <module>
    vendored('urllib3')
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 35, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/lib/python2.7/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python2.7/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
  File "/usr/lib/python2.7/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/lib/python2.7/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/home/pi/Coding/Realsat/sunTracking/examples/plotly/random.py", line 1, in <module>
    import plotly.graph_objs as go
  File "/usr/local/lib/python2.7/dist-packages/plotly/graph_objs/__init__.py", line 14, in <module>
    from plotly.graph_objs.graph_objs import *  # this is protected with __all__
  File "/usr/local/lib/python2.7/dist-packages/plotly/graph_objs/graph_objs.py", line 34, in <module>
    from plotly import exceptions, graph_reference
  File "/usr/local/lib/python2.7/dist-packages/plotly/exceptions.py", line 10, in <module>
    from plotly.api.utils import to_native_utf8_string
  File "/usr/local/lib/python2.7/dist-packages/plotly/api/utils.py", line 3, in <module>
    from requests.compat import builtin_str, is_py2
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 43, in <module>
    import cookielib
  File "/usr/lib/python2.7/cookielib.py", line 53, in <module>
    DEFAULT_HTTP_PORT = str(httplib.HTTP_PORT)
AttributeError: 'module' object has no attribute 'HTTP_PORT'

Here is the code I try to use which is from the website.
import plotly
import plotly.graph_objs as go

plotly.offline.plot({
    "data": [go.Scatter(x=[1, 2, 3, 4], y=[4, 3, 2, 1])],
    "layout": go.Layout(title="hello world")
}, auto_open=True)

**Comment by jonmmease** [comment] 2018-07-17 18:53
Hi @Bosebcc ,
I'm not able to reproduce the error you're seeing. Could you include the result of `$ pip list` (and `$ conda list` if you're also using conda).
Thanks!

**Comment by jonmmease** [comment] 2018-09-20 12:56
Closing for now. Feel free to follow up with the requested info if you're still having trouble

**Closed by jonmmease** 2018-09-20 12:56 UTC
Labels: question
