### ISSUE TITLE
Get a graph of the difference between a reference and other data

### ISSUE THREAD

**Issue by devauxto** [plotly/plotly.py#1673] opened 2019-07-20 13:04 UTC
Hi !

I'm looking for a way to be able to switch from the natural scatter display, to the difference (absolute or relative) from a selected reference to other series.

Actually, when you simple click on a series title in the legend, the other series are hidden.
My need is to take this selected series as reference, and to compute the difference with others (and to be able to configure if the difference must be display in absolute or percentage diff with the ref).

Is there actually a way to do this kind of stuff, without having to manage some inputs to select the reference and to compute the difference before creating a graph ?

**Comment by jonmmease** [comment] 2019-07-21 09:49
Hi @devauxto,
There's nothing built-in to do this. But you could probably make something pretty close using [Dash](https://dash.plot.ly/) or [FigureWidget](https://plot.ly/python/#chart-events) in the JupyterNotebook. 

Neither of these approaches expose the legend click events unfortunately, so you would probably need to use a dropdown widget or something for selecting the reference trace.  Good luck!

**Comment by gvwilson** [comment] 2024-06-13 19:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:42 UTC
