### ISSUE TITLE
Link to dcc.Graph in plotly.py config doc page

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2191] opened 2020-02-13 18:54 UTC
In https://plot.ly/python/configuration-options/, we should say that the config dict can be passed to `dcc.Graph` inside a Dash app.

**Comment by gvwilson** [comment] 2024-06-14 13:08
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:08 UTC
