### ISSUE TITLE
Plot with shaded regions

### ISSUE THREAD

**Issue by sursu** [plotly/plotly.py#1748] opened 2019-08-31 14:50 UTC
I want to produce a simple plot with shaded regions.

Here is an example:

```python
import numpy as np
import plotly.graph_objects as go

np.random.seed(11111)

# Set up
N = 500
p11 = p22 = 0.95
σ1 = 1
σ2 = 4

# Simulate states
s = np.zeros(N)
for i in range(1,N):
    if s[i-1] == 0:
        s[i] = np.random.binomial(n=1, p=1-p11)
    else:
        s[i] = np.random.binomial(n=1, p=p22)

# Collect observations in those states
x = (s*σ2 - (s-1)*σ1) * np.random.normal(size=N) 

# Shaded regions with change at midpoint
shade = []
for i in range(1,len(s)):
    if  s[i] == s[i-1]:
        shade.append([i, s[i]])
    else:
        shade.append([i-0.5, s[i-1]])
        shade.append([i-0.5, s[i]])
        shade.append([i, s[i]])
shade = np.array(shade).T
```

Plot with `FigureWidget()`:
```python
fig = go.FigureWidget()
fig.add_scatter(y = x)
fig.layout.update(title='Data', showlegend=False)
fig
```
![newplot](https://user-images.githubusercontent.com/12001304/64065233-76b83100-cc0b-11e9-8648-8cc235b3001f.png)

and then the next piece of code, where I use the yaxis range to scale the shaded region, produces what I want:
```python
rng = fig.layout.yaxis.range
fig.add_scatter(x = shade[0], y=(shade[1]*rng[1] - (shade[1]-1)*rng[0]), 
                fill='toself', fillcolor='lightblue', line_width=0, opacity=0.5)
fig.layout.yaxis.range = rng
```
![newplot (1)](https://user-images.githubusercontent.com/12001304/64065236-83d52000-cc0b-11e9-8fff-aed2c67968d1.png)

---

Now, a number of questions and issues:

**Question 1**:
How do I produce the same plot with `Figure()` and not with `FigureWidget()`?

**Question 2**:
How do I plot the shaded region in the background, so that I could hoover over the trace?

---

**Issue 1**:
I use JupterLab. If we go to `Kernel` > `Reset Kernel and Run all Cells...`
or simply rerun all the code fast, we get the following error:

![image](https://user-images.githubusercontent.com/12001304/64065365-f4c90780-cc0c-11e9-9dc3-4899996d71a8.png)

**Issue 2**:
I had to run:
```python
fig.layout.yaxis.range = rng
```
in order to reset the yaxis range to the value it had before. Omitting that line would result in this plot:
![newplot (3)](https://user-images.githubusercontent.com/12001304/64065456-48882080-cc0e-11e9-8d7b-32ec2281bf12.png)

Howevee, if we produce the plot by including the line, select some region and then reset the plot, that ultimately results in the same padded plot:

![Peek 2019-08-31 16-47](https://user-images.githubusercontent.com/12001304/64065542-280c9600-cc0f-11e9-9a5c-5930bcc70eb1.gif)

In fact, it suffices to press `Reset Axes` to observe that.

**Issue 3**:

If we now change the seed to 1: 
```python
np.random.seed(1)
```
and rerun the code, we get:

![newplot (2)](https://user-images.githubusercontent.com/12001304/64065381-35288580-cc0d-11e9-9fc9-3cd3de8c609f.png)

Why do I get this anomalistic plot? 

---

<details>
<summary>System Details</summary>
<br>
Ubuntu 18.04.3 LTS
<br>
JupyterLab
<br>
Python 3.7.3
<br>
Plotly version: 4.1.0
</details>

---
UPDATE 1:

**Issue 3**: It seems that that happens if the state `s` terminates in 1. So I just need to add another line after the loop for `shade`:
```python
shade.append([i, 0])
```

<br>

UPDATE 2:

Another **Issue**:
sometimes when I run the exactly same code, `fig.layout.yaxis.range` won't give me anything and the next line will result in an `IndexError: too many indices for array`.

**Comment by gvwilson** [comment] 2024-06-13 19:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:49 UTC
