### ISSUE TITLE
Legend for marker size 

### ISSUE THREAD

**Issue by AbdulwahabDev** [plotly/plotly.py#2236] opened 2020-02-28 03:30 UTC
Hello 

I'm trying to but legend for marker size in Sccater plot
there is some plot to describe what I want ( See Prediction Cost on the right )

![Plot With Legend for marker size ](https://user-images.githubusercontent.com/34792253/75507440-1c4d3100-59f2-11ea-9a2a-95df432f8ab3.jpeg)

I did all what I want except show legend for the marker size 
Is there any property can solve my issue 

 
![image](https://user-images.githubusercontent.com/34792253/75507607-a39aa480-59f2-11ea-9d1c-640aad2afa4d.png)
 
 

My Code 
```
fig = go.Figure()    
fig.add_trace( 
                go.Scatter(
                            x=YearData,
                            y=RatingData,
                            name=Key,
                            text=textHover,
                            marker_size=SizeData,
                            hoverinfo= "text"
                          )
             )
    
  

fig.update_traces(mode='markers', marker=dict(sizemode='area', sizeref=2.*65/(40.**2), line_width=2))

fig.update_layout(  title='تقييم مستشفيات وزارة الصحة في مدينة الرياض',
                    xaxis=dict( title='عام التقييم', gridcolor='white', type='log', gridwidth=2, ),
                    yaxis=dict( title='التقييم من 5', gridcolor='white', gridwidth=2, ),
                    paper_bgcolor='rgb(243, 243, 243)',
                    plot_bgcolor='rgb(243, 243, 243)',)
fig.show()
```

thanks :)

**Comment by AbdulwahabDev** [comment] 2020-03-03 02:27
any help ... :(

**Comment by gvwilson** [comment] 2024-06-14 13:06
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:06 UTC
