### ISSUE TITLE
iplot in jupyter displays an outdated plot

### ISSUE THREAD

**Issue by eulerreich** [plotly/plotly.py#322] opened 2015-10-08 22:00 UTC
Suppose I have a cell that computes the datapoints to be displayed and also feed them into `iplot`. Sometimes, after updating the part of the cell that changes the datapoints or the style of the plot object (`Scatter3d`, `Surface`, etc), I get back the old chart instead of the new one (and not any faster than usual, so it doesn't seem like a problem of caching).

**Comment by theengineear** [comment] 2015-10-09 06:22
Mind pasting a minimal working example of this?

**Comment by eulerreich** [comment] 2015-10-09 06:57
In a Jupyter cell, I ran

```
def get_torus_surface(radius_u, radius_v, num_pts_u=40, num_pts_v=40):
    u = np.linspace(0, 2 * np.pi, num_pts_u) # overall orbit
    v = np.linspace(0, 2 * np.pi, num_pts_v) # orbit of orbit; v = 0 is the outermost point  
    x, y, z = torus3D.from_angle_range(u, v, radius_u, radius_v)
    return Surface(
                    x=x,
                    y=y,
                    z=z,
                    opacity=.5,
                    showscale=False,
                    name='torus'
            )
radius_u = 1
radius_v = 1/2.  
torus = get_torus_surface(radius_u, radius_v)
data = Data([torus])
layout = Layout(title='outdated_plot-test', autosize=True)
figure = Figure(data=data, layout=layout)
py.iplot(figure, filename='outdated_plot-test')
```

This made the following picture underneath the cell
![image](https://cloud.githubusercontent.com/assets/4183609/10387647/c45967c0-6e28-11e5-9285-9f12b3903313.png)

Now I add the line 
```
torus.opacity = 1
```
after
```
torus = get_torus_surface(radius_u, radius_v)
```

and evaluate the cell again. I get the same picture back.

But if I go the graph's own page, then I see
![image](https://cloud.githubusercontent.com/assets/4183609/10387678/0ad7ba8a-6e29-11e5-8ce8-bf065b39e813.png)

**Comment by jonmmease** [comment] 2018-09-22 09:56
Closing this for now since I don't believe this is a problem anymore, and the example above is not reproducible. Feel free to open a new issue against version 3 if this is still a problem

**Closed by jonmmease** 2018-09-22 09:56 UTC
