### ISSUE TITLE
Matplotlib is_frame_like is deprecated, and will be removed soon

### ISSUE THREAD

**Issue by tvst** [plotly/plotly.py#1568] opened 2019-05-19 05:48 UTC
To repro, run this:
```python
import matplotlib.pyplot as plt
import plotly.tools
f = plt.figure()
plt.plot([1,2,3,4])
plotly.tools.mpl_to_plotly(f)
```
...which will result in this warning being printed to the console:
```
(...)/lib/python3.6/site-packages/plotly/matplotlylib/mpltools.py:368: MatplotlibDeprecationWarning:                                     
The is_frame_like function was deprecated in Matplotlib 3.1 and will be removed in 3.3.
```

**Comment by jonmmease** [comment] 2019-05-20 11:26
Thanks @tvst

**Comment by ycaokris** [comment] 2019-05-21 19:07
I had this same issue when trying to run tls.mpl_to_plotly() in python3.7 when I was plotting survival curve in dash app following [survival-analysis-r-vs-python](https://plot.ly/ipython-notebooks/survival-analysis-r-vs-python/). 
Also Userwarning same as raised in this [community thread] like: (https://community.plot.ly/t/some-parts-of-figure-not-displayed-when-converting-matplotlib-figure-to-plotly-figure-and-displaying-on-webpage-with-dash/14449)
Again it's not an issue affecting app performance, just console logging.

**Comment by AdvancingMind** [comment] 2020-07-02 17:25
I am also facing the same issue, the portion of my code where I am using plt (matplotlib.pyplot as plt) :
```
```
    figure = plt.figure(figsize= size, facecolor= 'white')
    subplot = figure.add_subplot(1,1,1)
     .
     .
     .
    rectangle = plt.Rectangle((tx,H), width, height, color=mycolor)
    subplot.add_patch(rectangle)

    plt.xlim([0, max_x])
    plt.ylim([0,H])
    plt.yticks(pos_labels, labels)
```
    .
    .
```
plotly throws the warning:

> The is_frame_like function was deprecated in Matplotlib 3.1 and will be removed in 3.3.
> 
> /users/a/.conda/envs/tf_gpu/lib/python3.7/site-packages/plotly/matplotlylib/renderer.py:512: UserWarning:
> 
> I found a path object that I don't think is part of a bar chart. Ignoring.

And misses all the rectangles, and all the y-axis labels set by 'plt.yticks(pos_labels, labels)'.

**Comment by nicolaskruchten** [comment] 2020-07-04 13:08
Indeed, our matplotlib conversion utility should be considered deprecated at this point as it isn’t being actively maintained to track deprecations and changes in matplotlib itself so it works best with older versions of matplotlib. I should update the docstrings accordingly.

**Comment by nicolaskruchten** [comment] 2020-07-04 13:09
That said, if someone wants to work on it to bring it back up to date I’d be happy to work with them to integrate the changes :)

**Comment by gvwilson** [comment] 2024-06-13 19:32
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:32 UTC
Labels: matplotlylib
