### ISSUE TITLE
Gantt chart legend does not toggle

### ISSUE THREAD

**Issue by astrojuanlu** [plotly/plotly.py#1371] opened 2018-12-17 10:08 UTC
The Gantt examples from the documentation can't toggle the resources:

https://plot.ly/python/gantt/#using-hours-and-minutes-in-times

This was already reported in https://github.com/plotly/plotly.py/issues/910#issuecomment-356799770, but I'm opening a separate issue to not clutter the original one.

![Gantt](https://user-images.githubusercontent.com/3409397/34805075-f2f6616e-f6b6-11e7-9d5b-9daa7efe8931.png)

**Comment by jonmmease** [comment] 2018-12-17 11:59
Thanks for opening the dedicated issue @Juanlu001.

This would be nice, and I think it would be possible with some restructuring of the figure factory.  Right now the rectangles are drawn as `layout.shape` objects, which aren't actually connected to a legend entry.  To get toggling to work, the rectangles could be drawn as `scatter` traces with a `fill=toself`.

**Comment by laserjeyes** [comment] 2018-12-21 10:35
I am experiencing the same problem: Drawing an offline Gantt chart with `group_tasks=True` shows the colorbar only if `index_col`is set to numerical values. Once `index_col` ist set to labels, `show_colorbar=True` is being ignored, no legend is shown.

**Comment by gvwilson** [comment] 2024-06-13 17:43
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:43 UTC
Labels: enhancement
