### ISSUE TITLE
Bar plot shows number with a lot zeros after dot on Y axis.

### ISSUE THREAD

**Issue by javidsch** [plotly/plotly.py#2247] opened 2020-03-05 15:12 UTC
Why 0.150000000000000002, not only 0.15?
![image](https://user-images.githubusercontent.com/28500366/75994700-05cc3b80-5f04-11ea-98b6-b7c10eddf8fa.png)

**Comment by nicolaskruchten** [comment] 2020-03-05 19:39
This kind of rendering artifact happens sometimes unfortunately. The reason is roughly that 0.15 and 0.150000000000000002 are basically the same floating-point number. It should be possible to lock down the tick label formatting with `ticklabelformat` though.

If you could provide some reproducible code I could try to look into whether or not this is a regression...

**Comment by javidsch** [comment] 2020-03-06 09:14
Could not find `ticklabelformat` property, but there is `tickformat`.

It's related to `tickformat = '$'`, if remove `$ `sign it works. But it needs to show dollar/currency.
```
  layout = go.Layout( title='Part1'
                      , yaxis = go.layout.YAxis(tickformat = '$')
                      , template = "none")
```

**Comment by gvwilson** [comment] 2024-06-14 13:06
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:06 UTC
