### ISSUE TITLE
[BUG] The position relationships of translucent points are shown incorrectly in Scatter3D

### ISSUE THREAD

**Issue by Kevinckyy** [plotly/plotly.py#4477] opened 2024-01-08 10:03 UTC
Hello! I ran into this problem when I used translucent colors  for markers on scatter3d. It seems that the points later in the order will always cover the points drawn first. There're the screenshots and the code to generate them:

![image](https://github.com/plotly/plotly.py/assets/44802223/56147e8a-8881-4729-b030-bcbf25649b76)
![image](https://github.com/plotly/plotly.py/assets/44802223/5b6ee6ac-7189-4d97-9c7a-29d74dc8c564)

```python
import plotly
plotly.__version__
# '5.18.0'
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(
  go.Scatter3d(
    x = [0,1,1], y=[0,1,0], z=[0,1,1],
    mode = 'markers',
    marker = dict( color = ['rgba(200,150,100,0.8)', 'rgba(100,200,150,0.8)' ])
  )
)
```

**Comment by Coding-with-Adam** [comment] 2024-01-08 19:45
hi @Kevinckyy 
Thanks for reporting this.
Transparency and ordering in 3D is a known problem, and a challenging problem in the graphics research community. For us, it goes all the way back to https://github.com/plotly/plotly.js/issues/1267 .

**Comment by gvwilson** [comment] 2024-07-11 22:17
duplicate of several earlier reports

**Closed by gvwilson** 2024-07-11 22:17 UTC
