### ISSUE TITLE
Exporting image from Plotly Offline After Interaction SVG error

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1264] opened 2018-11-06 11:01 UTC
Placeholder to investigate: https://community.plot.ly/t/exporting-svg-from-plotly-offline-after-interaction/14868/10

Repository: https://github.com/alexpreynolds/flow-cytometry-visualization

notebook (nbviewer): http://nbviewer.jupyter.org/github/alexpreynolds/flow-cytometry-visualization/blob/master/FlowCytometryVisualization.ipynb

**Comment by ReubenM** [comment] 2019-10-16 16:39
Double quotes are not properly handled / escaped within style attributes concerning fonts.

**Comment by NEGU93** [comment] 2020-03-13 14:31
Please, I will also like this feature. Png format has a too low quality for me.

It would be nice the "Download plot as png" button lets you select different types of formats (jpeg, SVG, etc.)

**Comment by gvwilson** [comment] 2024-06-13 17:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:44 UTC
Labels: bug
