### ISSUE TITLE
Support size (N,1) numpy arrays where 1D arrays are supported

### ISSUE THREAD

**Issue by alexfeld** [plotly/plotly.py#700] opened 2017-02-22 21:27 UTC
When I create my graphic using the online servers everything looks great. If I use the same commands but switch to the `offline.plot`  function, only part of my figure is correctly drawn. If I then click the "export to plot.ly" button at the bottom, everything appears normal. There are no errors in my console. I tried this with Google Chrome and Firefox. I'm using version 2.0.2 of plotly.py.

**Comment by cldougl** [comment] 2017-02-22 21:28
Hey @alexfeld are you able to provide a reproducible example/code snippet of the issue you're experiencing?

**Comment by alexfeld** [comment] 2017-02-22 21:57
I have an HTML file that displays the behavior. Unfortunately I haven't been able to reproduce it with a simpler example. The code that I'm using to plot this is quite complex.

**Comment by cldougl** [comment] 2017-02-22 21:58
By any chance are you using latex syntax in the plot? This is a current/known issue for offline plots.

**Comment by alexfeld** [comment] 2017-02-22 22:16
No, there is no latex.

**Comment by cldougl** [comment] 2017-02-22 22:18
Thanks --
Unfortunately if you don't have a reproducible example that you can provide or more information, we won't be able to progress any further with the issue.

**Comment by alexfeld** [comment] 2017-02-22 22:21
I understand. I'm working on trying to get a simpler example working, but as I said, I'm only noticing this when my plot gets complicated.

**Comment by alexfeld** [comment] 2017-02-22 23:17
I finally got an example working. Please see below. The data sample data does not display in offline mode. In my other example the mean line does not appear either, but I bet this is due to the same bug.

```(python)
import plotly
from plotly import plotly as py
from plotly import offline
from plotly.graph_objs import Scatter

import numpy as np


def hex2rgb(hexcolor):
    hexcolor = [hexcolor[1+2*i:1+2*(i+1)] for i in range(3)]
    r,g,b = [int(n,16) for n in hexcolor]
    return (r,g,b)

# x = np.random.uniform(0,1,11)
# yn = x**2 + np.random.randn(x.size)*0.05

x = np.random.uniform(-3.,3.,(20,1))
yn = np.sin(x) + np.random.randn(20,1)*0.05

xvec = np.linspace(-4,4,1001)

y = np.sin(xvec)
yp = np.sin(xvec) + 1.
ym = np.sin(xvec) - 1.
specs = [[{'is_3d': 0 }]]
figure = plotly.tools.make_subplots(1,1, specs=specs)

fcolor = 'rgba(114, 159, 207, 0.3)'

kwargs={'opacity':0.3, 'line':{'color':'#204a87', 'width':0.4}, 'mode':'lines'}
trace1 = Scatter(x=x, y=yn, mode='markers', marker=plotly.graph_objs.Marker(symbol='x', color='black', colorscale=None))
trace0 = Scatter(x=xvec, y=y, mode='line', line=plotly.graph_objs.Line(color='#3465a4', width=2))
trace3 = Scatter(x=xvec, y=yp, fillcolor=fcolor, fill='tonextx', showlegend=True, name='filltest', legendgroup='filltest_fill_(1,1)', **kwargs)
trace2 = Scatter(x=xvec, y=ym, fillcolor=fcolor, showlegend=False, name='filltest', legendgroup='filltest_fill_(1,1)', **kwargs)

figure.layout.font = plotly.graph_objs.Font(family="Raleway, sans-serif")
figure.append_trace(trace0, 1, 1)
figure.append_trace(trace1, 1, 1)
figure.append_trace(trace2, 1, 1)
figure.append_trace(trace3, 1, 1)

py.plot(figure)
offline.plot(figure)
```

**Comment by alexfeld** [comment] 2017-02-22 23:44
It appears that this is due to the array shape of the input data. If I change the `x` creation to `x=np.random.uniform(-3,3,21)` the plotting works both on and off line.

**Comment by cldougl** [comment] 2017-02-24 16:23
Simple example:
```
import plotly
from plotly import plotly as py
from plotly import offline
from plotly.graph_objs import Scatter

import numpy as np

x = np.random.uniform(-1,1,(10,1))
yn = np.sin(x)

trace = Scatter(x=x, y=yn, mode='markers')
py.iplot([trace])
offline.iplot([trace])
```

scatter plots where x/y ndarrays have a shape of (x,x) fail to render offline
(* shape should be (x,))

**Comment by cldougl** [comment] 2017-02-24 16:34
Thanks for taking the time to include that example @alexfeld ! Can you let me know the reasoning/use case for passing  `x = np.random.uniform(-3.,3.,(20,1))` rather than `x = np.random.uniform(-3.,3.,20)`
For scatter plots, x and y should be 1 dimensional.

**Comment by alexfeld** [comment] 2017-02-24 20:28
No problem! Sorry it took me so long. This issue arises when using `plotly` in a scientific setting. Often you are working with column vectors for mathematical reasons. This behavior would be confusing in that context, especially if you are used to using `matplotlib`.

**Comment by gvwilson** [comment] 2024-06-10 18:29
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 18:29 UTC
Labels: enhancement
