### ISSUE TITLE
errors in https://plotly.com/python/3d-surface-plots/

### ISSUE THREAD

**Issue by DavidKershaw** [plotly/plotly.py#2323] opened 2020-03-27 08:49 UTC
In the "Passing x and y data to 3D Surface Plot" example:
[SurfacePlotError.txt](https://github.com/plotly/plotly.py/files/4391881/SurfacePlotError.txt)
line 8 should read
x, y = np.linspace(0, 1, sh_1), np.linspace(0, 1, sh_0),
or alternately leave line 8 unchanged & then line 9 should read
fig = go.Figure(data=[go.Surface(z=z, x=y, y=x)]),
because in z[i.j] i is always the y axis & j is the x axis.
The corresponding plot  in https://plotly.com/python/3d-surface-plots/ was not made with the code above it. If I run the above example code with the Mt Bruno elevation data, in my plot you can clearly see the 25th row of the data & the 1.0 element of x are missing because z.shape is (25,24) and when there is a dimension mismatch Surface still does a plot using the minimums of the x & y mismatched dimensions.
If sh0 were 2*sh1 you would see a plot with half of Mt Bruno missing the way the example is erroneously coded.
There is also something wrong with the Topographical 3D Surface Plot just above it. If I run that example  code and hover over the max x, max y point I see x: 23, y: 24, z: 3.568177 just as you'd expect since z.shape is (25,24). But if I hover over the max x, max y point in the Topographical 3D Surface Plot in https://plotly.com/python/3d-surface-plots/ I see x: 24, y: 24, z: 3.568177. Clearly it was not made with the code above it.
What's wrong with both plots in https://plotly.com/python/3d-surface-plots/ is that the first character of the header of the Mt Bruno file is a comma which means that the first element of each subsequent row is just the row index. The panda code didn't strip that first column out, as it should, so that the row indices were used for elevations in both plots. If you hover over all the x=0 points in both plots you'll see z=row index value. This error made z.shape=(25,25) which is why the 2 plots came out the same.
The pandas doc page for DataFrame.values
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html
says "Only the values in the DataFrame will be returned, the axes labels will be removed". I don't know why it didn't work as I don't use pandas.

**Comment by nicolaskruchten** [comment] 2020-03-27 13:09
Thanks for this bug report! The plots are definitely generated using the code above them, as this is an automated process that happens every time the docs are modified. We'll look into the discrepancies you're reporting though :)

**Comment by nicolaskruchten** [comment] 2020-03-27 13:17
So for me running this locally, `z.shape = (25,25)` because Pandas returns the first column as part of `z.values`. This is wrong, indeed, as the first column is basically a set of indices rather than actual data, and it is visible in the plot as a small slope along one side of the surface running from (x,y)=(0,0) to (0,1) with z increasing from 0 to 24. 

Everything else seems internally-consistent to me...?

**Comment by DavidKershaw** [comment] 2020-03-27 19:41
Hello Nicolas,

In the surface plots tutorial lets call the "Topographical 3D Surface Plot"
example, code 1 & plot 1 and the "Passing x and y data to 3D Surface Plot"
example, code 2 & plot 2.
Modify code 1 & code 2 so that you stop using row indices as elevations and
then z.shape = (25,24). Run the repaired versions of  code 1 & code 2 and
you will see that plot 1 is correct but in plot 2 row 25 of the Mt Bruno
elevation data is missing. Plot 2 stops at row 24 of the the data. Also in
plot 2 hover over what should be the x=1 edge of the plot and you'll see
that it is also missing. Plot 2 stops at x: 0.9583333.
This is because you have reversed x & y. The dimension of x should always
be the # of columns in the data (24 in this case) and  the dimension of y
should always be the # of rows in the data (25 in this case).
By the way, I would rather see plotly.graph_objects.Surface() raise an
error when there is a dimension mismatch instead of still doing a plot
using the minimums of the x & y mismatched dimensions and throwing out some
of the data.
In particular if z.shape had been (25,12) then plot 2 would have half the
mountain missing instead of just 1 row of the data.

David Kershaw

**Comment by DavidKershaw** [comment] 2020-03-28 06:04
Just to be completely clear:

After you modify code 1 & code 2 so that you stop using row indices as
elevations and z.shape = (25,24), then if in code 2 you change the one line
fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])
to
fig = go.Figure(data=[go.Surface(z=z, x=y, y=x)]),
when you run code 1 & code 2, the plot 1 & plot 2 surfaces will now be
identical.

David Kershaw

**Comment by empet** [comment] 2020-03-28 11:25
@DavidKershaw is right!  I gave here [https://nbviewer.jupyter.org/gist/empet/0bab6c7a3e230eb9cfa2a633bcad0fe0](https://nbviewer.jupyter.org/gist/empet/0bab6c7a3e230eb9cfa2a633bcad0fe0), an illustrating example with `len(x)` different from `len(y)`.

**Comment by gvwilson** [comment] 2024-06-14 13:04
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:04 UTC
