### ISSUE TITLE
JSON serializable error

### ISSUE THREAD

**Issue by zekiblue** [plotly/plotly.py#2097] opened 2020-01-17 21:50 UTC
Dear all:

I am using plotly 4.4.1 on Jupiter notebook, anaconda 

I have data frame where one row contains sets. When I use plot, it gives an error of TypeError: Object of type set is not JSON serializable, but I am not using that specific column in the visualization. I found a way around the dropping the column for visualization, but this error seems to be a bit unnecessary since I do not use the column. I did not have this issue in 4.4.0, but I could find a way to go back to that version

**Comment by emmanuelle** [comment] 2020-01-21 15:34
Hi @gammazplaude thanks for the report. Would you be able to reproduce the problem in a standalone code snippet (using dummy data, or you can upload your data somewhere) which you would paste here?

**Comment by gvwilson** [comment] 2024-06-14 13:09
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:09 UTC
