### ISSUE TITLE
Width adjustment with fig.show()

### ISSUE THREAD

**Issue by sursu** [plotly/plotly.py#1706] opened 2019-08-05 19:41 UTC
Plotly 4.0.0 

I use JupyterLab.

There is a small issue with `fig.show()`:
![Peek 2019-08-05 21-32](https://user-images.githubusercontent.com/12001304/62490152-eda70900-b7c8-11e9-9c08-50e47785a5f1.gif)

Notice how the plot adjusts to the width of the window. I think it should behave just like `fig`:

![Peek 2019-08-05 21-33](https://user-images.githubusercontent.com/12001304/62490170-f566ad80-b7c8-11e9-921e-635ded7a93a3.gif)

which appears already adjusted.

**Comment by jonmmease** [comment] 2019-08-06 09:43
Hi @sursu, thanks for the report. The difference here is that you're using a `FigureWidget` in the case above which has different rendering path than `fig.show()` uses.

If you don't need to make in-place updates to the figure after displaying it, you could switch to using a standard `Figure` object. When this object displays itself it will use the same rendering approach as `fig.show()` and so you should see the same behavior.

**Comment by sursu** [comment] 2019-08-06 10:06
I still don't understand why `fig.show()` should display that flickering behavior, be it with `Figure` or `FigureWidget`.

**Comment by jonmmease** [comment] 2019-08-17 10:06
> I still don't understand why fig.show() should display that flickering behavior, be it with Figure or with FigureWidget.

I wasn't saying that either *should* have the flickering behavior. Just that they have different rendering code paths, so it's not too surprising for them to have slightly different behavior.  Thanks again for the report.

**Comment by gvwilson** [comment] 2024-06-13 19:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:44 UTC
Labels: bug
