### ISSUE TITLE
Create trellis plot with linegraphs

### ISSUE THREAD

**Issue by fkolokathi** [plotly/plotly.py#1716] opened 2019-08-09 09:53 UTC
I would like to create a trellis plot in which each plot would be a linegraph. I cannot find  a corresponding trace_type I can use with create_facet_grid to create one. Is there a way to do it?

**Comment by nicolaskruchten** [comment] 2019-08-09 12:41
Yes, you can follow the examples here https://plot.ly/python/facet-plots/ but use `px.line()` instead of `px.scatter()`

**Comment by gvwilson** [comment] 2024-06-13 19:45
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:45 UTC
