### ISSUE TITLE
[Feature request] Toggle spikelines for specific trace

### ISSUE THREAD

**Issue by ericvmueller** [plotly/plotly.py#1653] opened 2019-07-02 12:56 UTC
I am combining several 3d scatter traces in a single axis/layout, some of which are intended to be interactive, and some of which are simply visual aids. For the latter traces, I would like to disable spikelines, however, AFAIK this feature can only be toggled for _all_ traces in a layout. 

Adding an option like `showspikes` to individual traces would allow this, if possible.

**Comment by gvwilson** [comment] 2024-06-13 19:40
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:40 UTC
