### ISSUE TITLE
Potential typo in contributing.md in "Update to a new version of Plotly.js" section

### ISSUE THREAD

**Issue by akonsta** [plotly/plotly.py#2028] opened 2020-01-04 01:49 UTC
As I was setting up my development `environment` (I am on a Mac with Mojave, OS 10.14.6 and using PyCharm), I came to the section "Update to a new version of Plotly.js"  The instructions say that the command  to run updateplotlyjs is:

`$ python setup.py updateplotlyjs`

When I typed that command, setup.py was not found.  Since I was installing  per the instructions (using Virtualenv), I am guessing others on a Mac will get the same error.  I believe the command should be:

`$ python packages/python/plotly/setup.py updateplotlyjs`

At least that is what worked for me.  Also, it would be helpful to me if this section provided some insight as to when this command should be run.  Is there a way to find out that I am using the wrong version?  Are there any version conflicts I should worry about (i.e., version x of plotly.min.js is not compatible with version y of plotly.py or version z of Python)?  If so, where can I find those conflicts listed?

---Andrew

P.S.  I am new to contributing to OS, so I wasn't sure if this was the correct place to make this comment.  My apologies if this was the wrong place to raise this.

**Comment by gvwilson** [comment] 2024-06-14 13:09
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:09 UTC
