### ISSUE TITLE
Use CI to attempt auto-merge docprod into master?

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2204] opened 2020-02-17 15:46 UTC
Any reason we shouldn't just add that to the current CI? @jdamiba @emmanuelle 

We'd only want to do this if things merged cleanly. Or we might want to do a rebase or something to avoid the merge commit

**Comment by gvwilson** [comment] 2024-06-14 13:08
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:08 UTC
