### ISSUE TITLE
Cannot render mapbox scatter plot on Chart Studio.

### ISSUE THREAD

**Issue by AlexKaravaev** [plotly/plotly.py#1697] opened 2019-07-29 21:36 UTC
Hi! 
I have a very strange problem and maybe I am not setting things up correctly.

I have created a chart, that uses mapbox api key to retrieve tiles and it is working as expected at offline jupyter notebook and looks fine and dandy. However, when I want to export it to the online Chart Studio, the final plot appear to me blank. 

If open web console I see 
```"Unhandled promise rejection Error: "An API access token is required to use Mapbox GL"```
However I set it up api key both in the code and in the profile settings. 

In the code it looks like this
```python
layout = go.Layout(autosize=False,
                   mapbox= dict(accesstoken=access_token,
                                bearing=10,
                                pitch=0,
                                zoom=10.5,
                                center= dict(lat=59.939,
                                             lon=30.344),
                                style=custom_style),
                    width=900,
                    height=600, 
                    title = "air_pollution_record")
```
where the access_token is the string with copypasted access token.

This is the code, that I am using to push it to the Chart Studio
```python
import chart_studio
import chart_studio.plotly as py

chart_studio.tools.set_credentials_file(username='alex492',stream_ids=stream_api_key, api_key=plotly_api_key)
chart_studio.tools.set_config_file(sharing='public')

py.plot(fig, filename='air_pollution_saint-petersburg_4')
```
This is the link to the code, if needed I can provide a local copy of jupyter notebook:

**https://plot.ly/~alex492/33/#code**

You can see, that I have even exposed the api key public, but still no results.

**Comment by nicolaskruchten** [comment] 2019-07-30 01:09
To host Mapbox maps on Chart Studio, you need to input your mapbox token here: https://plot.ly/settings/mapbox

**Comment by AlexKaravaev** [comment] 2019-07-30 05:37
Yes, I did. Even two times with two different tokens.

**Comment by gvwilson** [comment] 2024-06-13 19:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:44 UTC
