### ISSUE TITLE
Adding a Mesh3d or Scatter3d to a subplot scene containing many Scatter3d objects already, changes size of the scene.

### ISSUE THREAD

**Issue by Helveg** [plotly/plotly.py#1793] opened 2019-10-01 14:43 UTC
If I add one of 2 or both of a Mesh3d and a Scatter3d trace to a subplot scene containing 157 Scatter3d traces already, the size of the scene seems to change, how can I restore it to its original shape? It shouldn't change size in the first place IMHO. The ranges of the axis stay the same but the length of the y axis drastically changes.

<img src="https://i.imgur.com/ItnzsPC.png" alt="https://i.imgur.com/ItnzsPC.png"></img>

The Mesh3d and Scatter3d code:
```python
def plot_cube(fig, origin, size, **kwargs):
    edges, faces = plotly_cube(origin, size)
    fig.add_trace(edges, **kwargs)
    fig.add_trace(faces, **kwargs)

def plotly_cube(origin, size):
    return plotly_cube_edges(origin, size), plotly_cube_faces(origin, size)

def plotly_cube_faces(origin, size):
    # 8 vertices of a cube
    x = origin[0] + np.array([0, 0, 1, 1, 0, 0, 1, 1]) * size
    y = origin[0] + np.array([0, 1, 1, 0, 0, 1, 1, 0]) * size
    z = origin[0] + np.array([0, 0, 0, 0, 1, 1, 1, 1]) * size
    return go.Mesh3d(
        x=x, y=z, z=y,
        # i, j and k give the vertices of the mesh triangles
        i = [7, 0, 0, 0, 4, 4, 6, 6, 4, 0, 3, 2],
        j = [3, 4, 1, 2, 5, 6, 5, 2, 0, 1, 6, 3],
        k = [0, 7, 2, 3, 6, 7, 1, 1, 5, 5, 7, 6],
        opacity=0.3
    )

def plotly_cube_edges(origin, size):
    x = origin[0] + np.array([0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]) * size
    y = origin[0] + np.array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1]) * size
    z = origin[0] + np.array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0]) * size
    return go.Scatter3d(
        x=x, y=z, z=y, mode='lines',
        line=dict(
            width=1.,
            color=(0., 0., 0., 1.)
        )
    )
```

The 157 traces are made like this:
```python
def get_branch_trace(compartments):
    x = [c.start[0] for c in compartments]
    y = [c.start[1] for c in compartments]
    z = [c.start[2] for c in compartments]
    # Add branch endpoint
    x.append(compartments[-1].end[0])
    y.append(compartments[-1].end[1])
    z.append(compartments[-1].end[2])
    return go.Scatter3d(
        x=x, y=z, z=y, mode='lines',
        line=dict(
            width=1.,
            color=(0., 0., 0., 1.)
        )
    )
```

And the figure is created as follows:
```python
def plot_eli_voxels(morphology, voxel_positions, voxel_compartment_map):
    fig = make_subplots(
        rows=1, cols=2,
        specs=[[{'type': 'scene'}, {'type': 'scene'}]]
    )
    for trace in plot_morphology(morphology, return_traces=True):
        fig.add_trace(
            trace,
            row=1, col=1
        )
    for trace in plot_morphology(morphology, return_traces=True):
        fig.add_trace(
            trace,
            row=1, col=2
        )
    fig.update_layout(showlegend=False)
    plot_cube(fig, np.array([100., 100., 20.]), 20., row=1, col=2)
    set_scene_range(fig.layout.scene1, morphology.get_plot_range())
    set_scene_range(fig.layout.scene2, morphology.get_plot_range())
    fig.write_html("../test_figure.html", auto_open=True)

def set_scene_range(scene, bounds):
    scene.xaxis.range=bounds[0]
    scene.yaxis.range=bounds[2]
    scene.zaxis.range=bounds[1]
```

And so the reshaping only happens when I plot either or both the cube faces or cube edges.

**Comment by Helveg** [comment] 2019-10-01 14:47
Also, this resizing does not happen if I don't draw the other Scatter3d traces:

<img src="https://i.imgur.com/50nAygl.png">

**Comment by gvwilson** [comment] 2024-06-14 13:15
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:15 UTC
