### ISSUE TITLE
math module has no attribute 'isclose'

### ISSUE THREAD

**Issue by javierggt** [plotly/plotly.py#1218] opened 2018-10-07 16:46 UTC
I got the following error:
>   File "/Users/javier/Library/Python/2.7/lib/python/site-packages/plotly/matplotlylib/mpltools.py", line 68, in convert_dash
    if (math.isclose(float(dash_array[1]), 0.)):
AttributeError: 'module' object has no attribute 'isclose'

It turns out that math.isclose was introduced in version 3.4.6, so it seems there should be a version check here. Perhaps it is easier to use numpy.isclose (this is matplotlib, after all).

**Comment by javierggt** [comment] 2018-10-08 16:11
Sure. Here it is:

```python
def main():
    import numpy as np
    from matplotlib import pyplot as plt
    figure = plt.figure('my_figure', clear=True)
    x = np.array([245.47089156850285, 426.57951880159254,
                  741.3102413009177, 977.2372209558101])
    y = np.array([0.022331681268342514, 0.005960481954187414,
                  0.0014765077815567915, 0.0005871572999836056])
    plt.plot(x, y, ":k")
    return figure


import plotly.tools as tls
fig = tls.mpl_to_plotly(main())

```

**Comment by javierggt** [comment] 2018-10-08 16:12
the key is the line format, if I do `plt.plot(x, y, "-k")`, it works.

**Comment by gvwilson** [comment] 2024-06-13 17:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:44 UTC
Labels: matplotlylib
