### ISSUE TITLE
Support custom hover text in create_choropleth figure factory

### ISSUE THREAD

**Issue by rahul-n** [plotly/plotly.py#1020] opened 2018-05-30 07:40 UTC
Hi Team ,
I was able to create county choropleth map using create_choropleth function ( https://plot.ly/python/county-choropleth/ ).

When we hover over county it shows data using..... (as shown below)  
County 
State 
FIPS 
Value tag.

Is there a way to customized this text so that it display only county name and another tag attribute with value ?
For example :- 
County : Westmoreland 
Population : Value1 
Disease Count : Value2.

**Comment by Kully** [comment] 2018-05-30 20:09
Right now these values and tags are hard-coded into the figure factory so unfortunately you cannot easily do this at the time. They are coded as shown below:

```
t_c = (
    'County: ' + county_name_str + '<br>' +
    'State: ' + state_name_str + '<br>' +
    'FIPS: ' + padded_f + '<br>Value: ' + str(values[index])
)
```

For now you could write a script that will parse through all the data in your figure and pick out the ones that contain `text` as a parameter (i.e. the hoverdata), then replace the text with whatever you want.

Hope this helps.

**Comment by jmmease** [comment] 2018-06-04 13:09
Here's an example that elaborates on @Kully 's suggestion. It's based on the first example from https://plot.ly/python/county-choropleth/. Here I construct the figure using `create_choropleth` as before, but then I modify the hover trace's text (to remove FIPS and add an `Other` value) before displaying it.

```python
fips = ['06021', '06023', '06027',
        '06029', '06033', '06059',
        '06047', '06049', '06051',
        '06055', '06061']

values1 = range(len(fips))
values2 = range(100, 100+ len(fips))

fig = ff.create_choropleth(fips=fips, values=values)

# Modify tooltip
hover_trace = [t for t in fig['data'] if 'text' in t][0]
for i, label in enumerate(hover_trace['text']):
    
    # Remove FIPS
    new_label = label.replace("FIPS: %s<br>" % fips[i], "")
    
    # Add a new value
    new_label += "<br>Other: %d" % values2[i]
    
    # Update trace text
    hover_trace['text'][i] = new_label

iplot(fig)
```
<img width="1022" alt="screen shot 2018-06-04 at 9 04 06 am" src="https://user-images.githubusercontent.com/15064365/40919083-6aef7d00-67d6-11e8-860e-3bafb4d6cb31.png">

It probably would make sense to make it possible to customize this text directly in `create_choropleth` in the future, but hopefully this example shows how you can work around that in the meantime.

**Comment by chessybo** [comment] 2018-09-18 01:05
no matter what i do it just tells me module 'plotly.figure_factory' has no attribute 'create_choropleth'

**Comment by Kully** [comment] 2018-09-18 01:51
> no matter what i do it just tells me module 'plotly.figure_factory' has no attribute 'create_choropleth'

Strange. What version are you using?

I assume it was working for you at some point because you made the issue.

**Comment by chessybo** [comment] 2018-09-18 03:47
it never worked. I’m using whatever it installs, with Conda install

where does it look when it sees the figure factory module? In the Cindy folder there are several figure factory folders scattered about

**Comment by jonmmease** [comment] 2018-09-23 00:15
Hi @chessybo, we're going to use this issue to track the possibility of adding a new feature to the `create_choropleth` figure factory.

If you're having trouble using this figure factory at all, please make sure that you have plotly.py 3.2 installed. Then if you are still having trouble, please open a new issue. Thanks!

**Comment by chessybo** [comment] 2018-09-23 02:12
@jonmmease

It was installing into the “pkgs” directory for some reason, I just just copy/pasted the modules over.


Also you need to make a way to outline the state I scoped in on without outlining the counties. Currently any attempt to do that results in nothing happening.

😁 thank you and pretty please

**Comment by jonmmease** [comment] 2018-09-23 11:35
@chessybo , as requested above please do not post to this issue thread again unless your comment is related to customizing choropleth hover text. Also, please don't tell an open source maintainer what they "need" to do.  We value constructive feedback and feature requests, but feature demands will be largely ignored.  Thanks for your understanding.

**Comment by chessybo** [comment] 2018-09-23 12:57
@jonmmease I didn’t “demand” anything. I said please. 

You requested IF I was still having trouble to open a new issue. I was not still having trouble. So I did not open a new issue. therefore your statement that you “requested above to not post about anything unrelated to create_choropleth” is not true, you never made that specific request.

Also, please don’t make untrue statements on Github, they will be ignored. Thanks for your understanding.

**Comment by jonmmease** [comment] 2018-09-23 13:56
@chessybo Since it seems there has been some misunderstanding here, and this subthread is not helpful for the public record of this issue, I'm going to go ahead and delete our exchange from this issue.  Feel free to open a new issue describing your request above and we can start a new discussion in good faith. Thanks

**Comment by nickmuchi87** [comment] 2020-09-21 12:48
Just checking if any update has been made to alow a cutomised hovertemplate in FF?

**Comment by gvwilson** [comment] 2024-06-13 17:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:42 UTC
Labels: enhancement
