### ISSUE TITLE
Correct 2d_density doc string

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.py#1024] opened 2018-05-31 19:41 UTC
`from plotly.figure_factory create_2d_density` should be `from plotly.figure_factory import create_2d_density`

lowercase the `D` in `d` for `fig = create_2D_density(x, y)`:

******************************
Example 1: Simple 2D Density Plot
```
import plotly.plotly as py
from plotly.figure_factory create_2d_density

import numpy as np

# Make data points
t = np.linspace(-1,1.2,2000)
x = (t**3)+(0.3*np.random.randn(2000))
y = (t**6)+(0.3*np.random.randn(2000))

# Create a figure
fig = create_2D_density(x, y)

# Plot the data
py.iplot(fig, filename='simple-2d-density')
```

Example 2: Using Parameters
```
import plotly.plotly as py
from plotly.figure_factory create_2d_density

import numpy as np

# Make data points
t = np.linspace(-1,1.2,2000)
x = (t**3)+(0.3*np.random.randn(2000))
y = (t**6)+(0.3*np.random.randn(2000))

# Create custom colorscale
colorscale = ['#7A4579', '#D56073', 'rgb(236,158,105)',
              (1, 1, 0.2), (0.98,0.98,0.98)]

# Create a figure
fig = create_2D_density(
    x, y, colorscale=colorscale,
    hist_color='rgb(255, 237, 222)', point_size=3)

# Plot the data
py.iplot(fig, filename='use-parameters')
```

**Comment by gvwilson** [comment] 2024-06-13 17:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:42 UTC
Labels: documentation
