### ISSUE TITLE
Error when trying to export maplotlib with imshow and colorbar  to plotly

### ISSUE THREAD

**Issue by YonatanSimson** [plotly/plotly.py#1000] opened 2018-05-01 12:23 UTC
plotly: 2.0.0
matplotlib: 2.2.2
python: 3.6.3
OS: Ubuntu LST 14.04 LTS

Code:
```
import matplotlib.pylab as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
import numpy as np

# Plotly
import plotly
import plotly.plotly as py
import plotly.tools as tls

irs_ = np.random.random_integers(0, 255, (200, 200, 4))
fig, axes = plt.subplots(2, 2)
for i, ax in enumerate(axes.ravel()):
    im = ax.imshow(irs_[:, :, i])
    divider = make_axes_locatable(ax)
    cax = divider.append_axes("right", size="5%", pad=0.05)
    plt.colorbar(im, cax=cax)
    ax.set_title('Image #{}'.format(i))
plt.tight_layout()
plotly_fig = tls.mpl_to_plotly(fig)
plotly.offline.plot(plotly_fig, filename='file.html')
plt.show()
```

Resulting errors:
```
Aw. Snap! You're gonna have to hold off on the selfies for now. Plotly can't import images from matplotlib yet!
Dang! That path collection is out of this world. I totally don't know what to do with it yet! Plotly can only import path collections linked to 'data' coordinates
```

Is this due to plotly not support imshow conversion to matplotlib?

**Comment by gnthibault** [comment] 2018-09-05 12:58
Definitely interested in this feature as well

**Comment by primakov** [comment] 2022-04-08 12:58
need this feature for an interactive dashboard, very sad its still not there :(

**Comment by nicolaskruchten** [comment] 2022-04-08 14:51
We're not really maintaining the matplotlib conversion code very much these days, but there is a `px.imshow()` method within Plotly now, so you could give that a try: https://plotly.com/python/imshow/

**Comment by gvwilson** [comment] 2024-06-13 17:38
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed as completed by gvwilson** 2024-06-13 17:38 UTC
