### ISSUE TITLE
Color exceed lines for fill in scatter3d

### ISSUE THREAD

**Issue by jhxu0416** [plotly/plotly.py#1206] opened 2018-09-27 20:04 UTC
In the 3d filled line example(https://plot.ly/python/3d-filled-line-plots/), the color does not fill the area within the line perfectly.

When I try some more curved and oscillating line, the fill result becomes worse by exceeding the line.
<img width="322" alt="screen shot 2018-09-27 at 4 01 46 pm" src="https://user-images.githubusercontent.com/24378622/46171603-fc4e9680-c26e-11e8-8ac7-0aab31bc7012.png">

**Comment by jonmmease** [comment] 2018-10-01 11:05
Hi @jhxu0416 , thanks for the report. I added a comment to https://github.com/plotly/plotly.js/issues/2352 with my thoughts on what's going on.  In short, i think the issue here is with the example, not the library.

@empet, if you have a moment I'd be interested in your perspective on this.

**Comment by rpanai** [comment] 2020-02-25 17:34
Hi @jonmmease it looks to me that the fill attribute has a bug. Here a reproducible example.

```python
import numpy as np
import plotly.graph_objs as go

m = 6
n = 5
mat = np.random.uniform(size=(m,n)).round(1).repeat(2).reshape(m,n*2)

x = np.arange(2*n)
y = np.ones(2*n)
fig = go.Figure()
for i in range(m):
    fig.add_trace(go.Scatter3d(x=x,
                               y=y*i,
                               z=mat[i,:],
                               mode="lines",
                               surfaceaxis=1 # broken
))
fig.show()
```

**Comment by gvwilson** [comment] 2024-06-13 17:39
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:39 UTC
