### ISSUE TITLE
mpl_to_plotly doesn't convert negative values properly in bar graph

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/plotly.py#1082] opened 2018-07-30 14:42 UTC
Bar graphs with negative values created in matplotlib are not converted properly by mpl_to_plotly as all negative values are turned positive.

From [this](https://community.plot.ly/t/matplotlib-bar-chart-wont-plot-negative-numbers/2137) community post.

```python
import matplotlib.pyplot as plt
import plotly.tools as tls
import plotly.offline as py
py.init_notebook_mode()

y = [3, 10, -7, 5, 3, -4.5, 6, 8.1]
N = len(y)
x = range(N)
width = 1/1.5
plt.bar(x, y, width, color="blue")


fig = plt.gcf()
print('MatPlotLib figure')
plt.show()

plotly_fig = tls.mpl_to_plotly(fig)
print('mpl_to_plotly figure')
py.iplot(plotly_fig)

#the y-axis data in the plotly_fig is all positive
print('The converted plotly y data: {}\nThe original y data:{}'.format(plotly_fig['data'][0]['y'],y))

#manually set the y-axis data and the plot works
plotly_fig['data'][0]['y']=y
py.iplot(plotly_fig)
```

**Comment by jonmmease** [comment] 2018-08-04 11:32
Thanks for the report and example @michaelbabyn !

**Comment by jonmmease** [comment] 2018-08-04 22:59
Cross reference #428

**Comment by gvwilson** [comment] 2024-06-13 17:40
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:40 UTC
Labels: matplotlylib
