### ISSUE TITLE
Plotting online to a folder with multiple layers doesn't work after 4.0 upgrade

### ISSUE THREAD

**Issue by dpsugasa** [plotly/plotly.py#1794] opened 2019-10-02 15:23 UTC
After upgrading to 4.0, plotting online fails with a long folder path. 

The following error occurs. Shortening the file path to 'Folder/filename' works as expected.

```
~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\chart_studio\api\v2\utils.py in validate_response(response)
     68     try:
---> 69         parsed_content = response.json()
     70     except ValueError:

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\requests\models.py in json(self, **kwargs)
    884                     pass
--> 885         return complexjson.loads(self.text, **kwargs)
    886 

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\json\decoder.py in decode(self, s, _w)
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\json\decoder.py in raw_decode(self, s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

PlotlyRequestError                        Traceback (most recent call last)
c:\Users\dustins\OneDrive - Northlight Group\Code_Data_Repo\Macro_Data\Time_Series\GDP_RFF_fred_stat_inputs.py in 
    260 data = [trace1, trace2]
    261 figure = go.Figure(data=data, layout=layout)
--> 262 py.iplot(figure, filename = 'Macro_Data/GDP/LSTM/full-series')
    263 
    264 

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\chart_studio\plotly\plotly.py in iplot(figure_or_data, **plot_options)
    133     if "auto_open" not in plot_options:
    134         plot_options["auto_open"] = False
--> 135     url = plot(figure_or_data, **plot_options)
    136 
    137     if isinstance(figure_or_data, dict):

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\chart_studio\plotly\plotly.py in plot(figure_or_data, validate, **plot_options)
    243         # Create parent directory
    244         if parent_path:
--> 245             file_ops.ensure_dirs(parent_path)
    246             payload["parent_path"] = parent_path
    247 

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\chart_studio\plotly\plotly.py in ensure_dirs(cls, folder_path)
    960                 pass
    961             else:
--> 962                 raise e
    963 
    964 

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\chart_studio\plotly\plotly.py in ensure_dirs(cls, folder_path)
    955         """
    956         try:
--> 957             cls.mkdirs(folder_path)
    958         except exceptions.PlotlyRequestError as e:
    959             if "already exists" in e.message:

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\chart_studio\plotly\plotly.py in mkdirs(cls, folder_path)
    945 
    946         """
--> 947         response = v2.folders.create({"path": folder_path})
    948         return response.status_code
    949 

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\chart_studio\api\v2\folders.py in create(body)
     16     """
     17     url = build_url(RESOURCE)
---> 18     return request("post", url, json=body)
     19 
     20 

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\retrying.py in wrapped_f(*args, **kw)
     47             @six.wraps(f)
     48             def wrapped_f(*args, **kw):
---> 49                 return Retrying(*dargs, **dkw).call(f, *args, **kw)
     50 
     51             return wrapped_f

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\retrying.py in call(self, fn, *args, **kwargs)
    210                 if not self._wrap_exception and attempt.has_exception:
    211                     # get() on an attempt with an exception should cause it to be raised, but raise just in case
--> 212                     raise attempt.get()
    213                 else:
    214                     raise RetryError(attempt)

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\retrying.py in get(self, wrap_exception)
    245                 raise RetryError(self)
    246             else:
--> 247                 six.reraise(self.value[0], self.value[1], self.value[2])
    248         else:
    249             return self.value

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\retrying.py in call(self, fn, *args, **kwargs)
    198         while True:
    199             try:
--> 200                 attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
    201             except:
    202                 tb = sys.exc_info()

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\chart_studio\api\v2\utils.py in request(method, url, **kwargs)
    178         content = response.content if response else "No content"
    179         raise exceptions.PlotlyRequestError(message, status_code, content)
--> 180     validate_response(response)
    181     return response

~\AppData\Local\Continuum\anaconda3\envs\quantlib\lib\site-packages\chart_studio\api\v2\utils.py in validate_response(response)
     70     except ValueError:
     71         message = content if content else "No Content"
---> 72         raise exceptions.PlotlyRequestError(message, status_code, content)
     73 
     74     message = ""

PlotlyRequestError: 
```

**Comment by nicolaskruchten** [comment] 2019-10-16 01:41
I'm sorry, I'm really not able to replicate this error locally... The following code runs fine on this end and creates a figure called `test` in a folder called `second` in a folder called `first`:

```python
import chart_studio.plotly as py
py.iplot(dict(data=dict(x=[1,2,3], y=[1,3,2])), filename="first/second/test")
```

If you could provide more context around your environment and the code you're running, that would really help us debug this problem for you. If you're a paying customer of Chart Studio Cloud, please feel free to reach us via the Intercom widget in the app itself for priority access to our staff and a private environment to share information :)

**Comment by gvwilson** [comment] 2024-06-14 13:14
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:14 UTC
