### ISSUE TITLE
Create country choropleth hover regression

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1429] opened 2019-02-08 11:32 UTC
Originally reported at https://community.plot.ly/t/county-choropleths-not-displaying-hoverinfo-in-offline-mode/19241

The hover tooltips for the figure produced by `create_choropleth` are sometimes not being displayed properly with recent versions of plotly.js.

```python
import plotly as py
import plotly.figure_factory as ff

import numpy as np
import pandas as pd

df_sample = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/minoritymajority.csv')
df_sample_r = df_sample[df_sample['STNAME'] == 'California']

values = df_sample_r['TOT_POP'].tolist()
fips = df_sample_r['FIPS'].tolist()

colorscale = [
    'rgb(193, 193, 193)',
    'rgb(239,239,239)',
    'rgb(195, 196, 222)',
    'rgb(144,148,194)',
    'rgb(101,104,168)',
    'rgb(65, 53, 132)'
]

fig = ff.create_choropleth(
    fips=fips, values=values, scope=['CA', 'AZ', 'Nevada', 'Oregon', ' Idaho'],
    binning_endpoints=[14348, 63983, 134827, 426762, 2081313], colorscale=colorscale,
    county_outline={'color': 'rgb(255,255,255)', 'width': 0.5}, round_legend_values=True,
    legend_title='Population by County', title='California and Nearby States'
)
```

Plotting this figure in the most recent version of plotly.js (1.44.3) results in no hover tooltips
```
py.offline.plot(fig,
                filename='choropleth_california_and_surr_states_outlines',
                include_plotlyjs='https://cdn.plot.ly/plotly-1.44.3.min.js')
```

But using 1.42.3 the tooltips are dipslayed as expected
```
py.offline.plot(fig,
                filename='choropleth_california_and_surr_states_outlines',
                include_plotlyjs='https://cdn.plot.ly/plotly-1.42.3.min.js')
```

**Comment by neilaronson** [comment] 2019-04-22 22:54
FYI the workaround does not work when using iplot in jupyter notebook because there is no include_plotlyds argument.

**Comment by harish2rb** [comment] 2019-04-25 17:35
Any update on when this bug might be fixed?

**Comment by neilaronson** [comment] 2019-04-26 18:27
Also, using this old version of the Javascript causes the title to not show up on plots (see https://github.com/plotly/dash/issues/539)

**Comment by jonmmease** [comment] 2019-04-30 10:02
Hi all.  I don't think anyone has taken a look at this issue yet.  We're definitely open to help if someone would like to take a look at https://github.com/plotly/plotly.py/blob/master/plotly/figure_factory/_county_choropleth.py and try to work through what's going wrong.

**Comment by p3zo** [comment] 2019-06-29 02:02
I'm also encountering this issue with the following app dependencies
```
dash==1.0.0"
flask_caching==1.7.2"
geopandas==0.3.0"
plotly-geo==1.0.0a1"
pyshp==1.2.10"
shapely==1.6.3"
```

The hover info works fine on choropleths with < ~20 counties. There seems to be a threshold at which the hover stops working.

**Comment by p3zo** [comment] 2019-06-29 04:32
It looks like the bug creates duplicate hover tooltips and stores `x`, `y` coordinates for the duplicates that are lists instead of floats. 

e.g.
```
[-86.1224], [-88.2717], [-94.2067], [-84.6049]
```
instead of
```
-86.1224, -88.2717, -94.2067, -84.6049
```

De-duplicating and flattening restores functionality. Building on the code snippet from @jonmmease's original post..

```python
hover_ix, hover = [(ix, t) for ix, t in enumerate(fig['data']) if t.text][0]

# mismatching lengths indicates bug
if len(hover['text']) != len(df_sample_r):

    ht = pd.Series(hover['text'])
    hover['text'] = ht.drop_duplicates()

    no_dupe_ix = ht.index[~ht.duplicated()]

    hover_x_deduped = np.array(hover['x'])[no_dupe_ix]
    hover_y_deduped = np.array(hover['y'])[no_dupe_ix]

    new_hover_x = [x if type(x) == float else x[0] for x in hover_x_deduped]
    new_hover_y = [y if type(y) == float else y[0] for y in hover_y_deduped]

    fig['data'][hover_ix]['x'] = new_hover_x
    fig['data'][hover_ix]['y'] = new_hover_y
```

**Comment by gvwilson** [comment] 2024-06-13 19:24
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:24 UTC
Labels: bug
