### ISSUE TITLE
plot function (from plotly.offline) does not support (open) file handles as target

### ISSUE THREAD

**Issue by s-m-e** [plotly/plotly.py#1419] opened 2019-02-01 09:10 UTC
Currently, the `filename` parameter of `plot` only supports filenames (`temp-plot.html` is default). It does not support open file handles.

The latter is very useful when writing e.g. command line tools with [click](https://click.palletsprojects.com/en/7.x/) (or similar tools), which [handles opening files specified by a user on the command line transparently](https://click.palletsprojects.com/en/7.x/arguments/#file-arguments) and only provides a file handle to the script.

```python
from plotly.offline import plot
help(plot)

plot(figure_or_data, show_link=False, link_text='Export to plot.ly', validate=True, output_type='file', include_plotlyjs
=True, filename='temp-plot.html', auto_open=True, image=None, image_filename='plot_image', image_width=800, image_height
=600, config=None, include_mathjax=False)
[...]
```

**Comment by s-m-e** [comment] 2019-02-01 10:16
Just looked at the [relevant source code](https://github.com/plotly/plotly.py/blob/15aff13d8e596e0ed1872d872dbafcc6e070d1e5/plotly/offline/offline.py#L701) - it's fairly easy to add. Would you accept a pull request?

The interesting question then becomes how to handle the stuff between subsequent lines 731 and 744. Ignore `auto_open == True` and `include_plotlyjs == 'directory'` options or raise exceptions if `filename` is an open file handle?

**Comment by gvwilson** [comment] 2024-06-13 19:24
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:24 UTC
Labels: enhancement
