### ISSUE TITLE
How to Rotate Labels in a Sunburst Chart

### ISSUE THREAD

**Issue by parthhhh** [plotly/plotly.py#1661] opened 2019-07-10 23:53 UTC
There seems to be no way of rotating the text inside of the sunburst chart. Is there a way of fixing all the text orientation for the labels radially? So it would look like this:
![Capture](https://user-images.githubusercontent.com/20375380/61012449-7b5f1800-a333-11e9-97d7-831d34c4b5de.PNG)

**Comment by nicolaskruchten** [comment] 2019-07-11 15:16
Unfortunately the underlying plotly.js library doesn't have a feature for this at the moment. I would encourage you to create an issue in our sibling repo at https://github.com/plotly/plotly.js/issues/new 

Thanks!

**Comment by parthhhh** [comment] 2019-07-11 21:28
Thank you! Posted in js repo.

**Comment by Piplopp** [comment] 2020-01-09 10:41
Hello, the plotly.js library now have this feature available (#3590), it uses the `"insidetextorientation"` with the values `auto|horizontal|radial|tangential`

**Comment by nicolaskruchten** [comment] 2020-01-09 18:33
@Piplopp yep, we're working on the Python 4.5 release, which will support this.

**Comment by Kheirlb** [comment] 2020-01-14 04:51
Hello. I am using "insidetextorientation": 'radial' and it works super well. However I want to change my orientation to horizontal when I click and open a parent. Is this possible?

**Comment by sarnobat** [comment] 2022-08-07 04:46
Thank you for requesting this. I'm benefitting from this being discussed 3 years ago.

**Comment by gvwilson** [comment] 2024-06-13 19:41
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:41 UTC
