### ISSUE TITLE
Heatmapgl not rendering in jupyter notebook

### ISSUE THREAD

**Issue by nvaytet** [plotly/plotly.py#1772] opened 2019-09-15 12:31 UTC
Using `Heatmapgl` instead of `Heatmap` in a Jupyter notebook does not show the heatmap.
Only the colorscale appears next to a blank area.

Code:
```Python
import plotly.graph_objects as go
fig = go.Figure(data=go.Heatmapgl(
                    z=[[1, 20, 30],
                      [20, 1, 60],
                      [30, 60, 1]]))
fig.show()
```
and the result:
![Screenshot at 2019-09-15 14-24-52](https://user-images.githubusercontent.com/39047984/64921567-08579f00-d7c5-11e9-8dbc-818bff0d7565.png)

Using `Heatmap` works as expected:
![Screenshot at 2019-09-15 14-28-43](https://user-images.githubusercontent.com/39047984/64921576-27eec780-d7c5-11e9-962f-8b0fb95b7f49.png)

Another example using `Scattergl` also works fine. It seems to only be the `Heatmapgl`.

System:
- Ubuntu 18.04
- Python 3.6.8
- plotly 4.0.0

**Comment by ikaryss** [comment] 2021-11-14 09:29
Have you been able to deal with this problem? Because I have also encountered this in jupyter

**Comment by gvwilson** [comment] 2024-06-13 19:50
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:50 UTC
