### ISSUE TITLE
Feature request: 3D stem plot

### ISSUE THREAD

**Issue by fkromer** [plotly/plotly.py#1692] opened 2019-07-29 12:23 UTC
Seems like [plotly.py does not support a 3D stem plot](https://plot.ly/python/3d-charts/) yet. Could you guys add something similar to [matplot's stem3](https://de.mathworks.com/help/matlab/ref/stem3.html)? This feature relates to [Stem plot figure factory](https://github.com/plotly/plotly.py/issues/258).

**Comment by fkromer** [comment] 2019-07-30 15:35
As temporal workaround one can emulate a stem3 plot with properly configured scatter3d plots like [shown here](https://plot.ly/~philgoddard/19/_3d-stem-plot/#code).

**Comment by gvwilson** [comment] 2024-06-13 19:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:44 UTC
