### ISSUE TITLE
Plots displayed correctly in offline mode but not online

### ISSUE THREAD

**Issue by romainmartinez** [plotly/plotly.py#973] opened 2018-03-15 15:57 UTC
When I use the offline version of plotly in Jupyter, everything works perfectly. However, when I switch to the online version, some figures are not displayed correctly.

Here is an example with a custom function
```python
BASE_LAYOUT = go.Layout(hovermode='closest', font=dict(size=14), width=1096, height=822)

def count_bar(d, column, **kwargs):
    count = np.array(d[column].value_counts(sort=False))
    trace = go.Bar(
        x=count, y=kwargs.get('ylabel'), marker=MARKER_LAYOUT, orientation='h')

    layout = BASE_LAYOUT.copy()
    layout.update(
        dict(
            title=kwargs.get('title'),
            xaxis=dict(
                title=kwargs.get('xtitle'), showline=True, linewidth=1.5),
            yaxis=dict(
                title=kwargs.get('ytitle'), showline=True, linewidth=1.5)))

    # adjust y axis
    layout['yaxis'].update(nticks=count.shape[0])
    layout.update(margin=go.Margin(t=80, b=80, l=150, r=80, pad=0))
    return dict(data=[trace], layout=layout)
```

**Offline plot:**
```python
import plotly.offline as py
py.init_notebook_mode(connected=True)

test_count_bar = count_bar(
    df_tidy, 'test', title='Tests count', xtitle='n', ytitle='Tests')
py.iplot(test_count_bar, filename='mvc/test_count_bar')
```
![offline](https://user-images.githubusercontent.com/17710617/37474928-e33804a4-2847-11e8-94b8-f3c221a5b471.png)

**Online plot**:
```python
import plotly.plotly as py

test_count_bar = count_bar(
    df_tidy, 'test', title='Tests count', xtitle='n', ytitle='Tests')
py.iplot(test_count_bar, filename='mvc/test_count_bar')
```
![online](https://user-images.githubusercontent.com/17710617/37474939-e756a748-2847-11e8-81f9-817d7b3c36b2.png)

**Comment by cldougl** [comment] 2018-04-18 16:43
hey @romainmartinez 
can you:
1. make sure you're using the [latest version of the package](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md)
you can check your version by running:
```
import plotly
plotly.__version__
```

2. if you're still experiencing an issue can you include a fully reproducible example (ie with dummy data) that we can run to replicate your issue?

Thanks!

**Comment by cldougl** [comment] 2018-04-25 17:59
closing due to inability to reproduce
@romainmartinez feel free to comment or reopen if you have a reproducible example

**Closed by cldougl** 2018-04-25 17:59 UTC
