### ISSUE TITLE
[BUG] make_subplots row_titles

### ISSUE THREAD

**Issue by osljw** [plotly/plotly.py#1787] opened 2019-09-25 06:43 UTC
bug: row_titles not work with start_cell

```
import plotly
print(plotly.__version__)
```
4.0.0

```
fig = make_subplots(rows=2, cols=2,
                    specs=[
                        [{"rowspan":2}, {"type": "bar"}], 
                        [None,{"type": "bar"}]
                    ],
                    start_cell='top-left',
                    row_titles = ['111', '222']
                   )
fig.show()
```

： can i have horizontal row_titles ？

**Comment by gvwilson** [comment] 2024-06-13 19:51
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:51 UTC
