### ISSUE TITLE
Correlation Plot 

### ISSUE THREAD

**Issue by adithya8** [plotly/plotly.py#1771] opened 2019-09-15 04:41 UTC
I am not able to find the documentation for the correlation plot in Plotly. Is there a function for correlation plot in Plotly? Please point me in the right direction here. Thank you in advance!

**Comment by sursu** [comment] 2019-09-15 13:52
Something like this:

```python
import pandas as pd
import plotly_express as px

heights = pd.read_csv('http://www.randomservices.org/random/data/Galton.txt', sep='\t')
px.scatter_matrix(heights, width=1000, height=1000)
```

![newplot (6)](https://user-images.githubusercontent.com/12001304/64922552-caf90e80-d7d0-11e9-81b7-59d808b24be1.png)

?

**Comment by gvwilson** [comment] 2024-06-13 19:50
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:50 UTC
