### ISSUE TITLE
Plots of large datasets do not "release" output in jupyter interact_manual cells

### ISSUE THREAD

**Issue by HudsonMC16** [plotly/plotly.py#1729] opened 2019-08-19 22:11 UTC
The following code (in a jupyter lab notebook) should allow iterative plotting, but when the plots are sufficiently large (10-15 traces, 3 repeats), subsequent clicks of the "Run Interact" button do not clear the output and allow for new plots to populate. I modeled this generic code after some other workbook code which I was using, so it may contain some elements which are not contributing to the problem, and I'm sorry if it seems too specific, but hopefully somebody can reproduce it. 

```
import plotly.express as px
import plotly.graph_objects as go
from ipywidgets import interact_manual
import pandas as pd
import numpy as np

@interact_manual
def dataviz(traces=[x * 5 for x in range(5)], repeats=[x+1 for x in range(3)]):
    dfs = []
    for y in range(repeats):
        for x in range(traces):
            df = pd.DataFrame(np.random.normal(size=(3000, 2)), columns=['a', 'b'])
            df['x'] = range(3000)
            dfs.append(df)
        fig = px.scatter(pd.DataFrame())
        for num, df in enumerate(dfs):
            fig.add_trace(go.Scatter(x=df.x, y=df.a, name=df.b.mean(), mode='lines'))
        fig.show()
```

**Comment by gvwilson** [comment] 2024-06-13 19:45
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:45 UTC
