### ISSUE TITLE
px.scatter: color scale does not show in Visual Studio Code

### ISSUE THREAD

**Issue by realtime** [plotly/plotly.py#1924] opened 2019-11-23 14:47 UTC
In jupyter notebook

`import plotly.express as px
iris = px.data.iris()
px.scatter(iris, x="sepal_width", y="sepal_length", color="petal_length")`

draws a color scale (or color bar) to the right of the graph:

![chrome_2019-11-23_15-37-49](https://user-images.githubusercontent.com/3332186/69480516-48ac4c80-0e08-11ea-84b4-c8d37f2d82b5.png)

When I open the same .ipynb file in Visual Studio Code, the scale does not show:

![Code_2019-11-23_15-37-21](https://user-images.githubusercontent.com/3332186/69480533-75606400-0e08-11ea-9768-fcfca8e02b07.png)

**Comment by nicolaskruchten** [comment] 2019-11-23 14:57
You will likely need to update your copy of the vscode-python extension for this to work :)

**Comment by realtime** [comment] 2019-11-23 16:11
> You will likely need to update your copy of the vscode-python extension for this to work :)

I got version 2019.11.50794 of vscode-python, released yesterday. Which version would you suggest instead?

**Comment by nicolaskruchten** [comment] 2019-11-25 14:27
Hmm, that's odd indeed. I was under the impression this was an issue we had earlier this summer and which was fixed. It either wasn't fixed or it's regressed, but either way the issue unfortunately is in vscode-python. I've got a PR open over there at the moment which in principle should fix this along the way, so I'll follow up there. The PR is https://github.com/microsoft/vscode-python/pull/8744

**Comment by nicolaskruchten** [comment] 2019-11-25 16:10
Argh, ok, it turns out we definitely didn't fix the issue in the summer, but my PR should clear it up. feel free to go vote for it :)

**Comment by nicolaskruchten** [comment] 2019-11-26 14:41
My PR has been merged, so this should work in the next version of vscode-python, which I imagine will be released in mid-December.

**Comment by gvwilson** [comment] 2024-06-14 13:12
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:12 UTC
