### ISSUE TITLE
Jupyter notebook: plot data saved to json, but plot is empty

### ISSUE THREAD

**Issue by aamster** [plotly/plotly.py#2239] opened 2020-03-02 19:16 UTC
A few issues/annoyances with plots in notebooks:

1) Close notebook with plot, reopen, plot is empty
2) Export to html, plot is empty
3) Export to pdf, plot is empty

**Comment by gvwilson** [comment] 2024-06-14 13:06
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:06 UTC
