### ISSUE TITLE
ScatterGeo updatemenus button not updating plot

### ISSUE THREAD

**Issue by enerrio** [plotly/plotly.py#1150] opened 2018-09-01 23:12 UTC
Pandas version: 0.20.3
Plotly version: 3.1.1
macOS: 10.13.4
Python: 3.6.3

I am using Plotly offline plotting and came across an issue when trying to include a button in a `go.Scattergeo` plot. When I press the button I want some data points to disappear (`visible = False`) and other data points, that were previously invisible, to become visible. However when I press the button, all data points become invisible. Interacting with the plot makes the data points appear (moving a slider that appears when button is pressed, or clicking on a trace) however when the button is first pressed no data points are visible.

I recreated the issue below with some sample data. The initial `go.Scattergeo` is the data plotted by state and another `go.Scattergeo` is the data plotted by year. There are 2 buttons for switching between the 2 plots.

I have my some sample data loaded like this:
``` python
data = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_us_cities.csv')
data = data.iloc[:400] # Keep only first 400 samples
data.loc[:100, 'year'] = '1990'
data.loc[100:200, 'year'] = '1991'
data.loc[200:300, 'year'] = '1992'
data.loc[300:, 'year'] = '1993'
```

and setup my scatterGeo plots like so:
```python
cities = []
for state in data['name'].value_counts().index:
    data_sub = data.loc[data['name'] == state]
    city = dict(
        type = 'scattergeo',
        visible = True,
        locationmode = 'USA-states',
        lon = data_sub['lon'],
        lat = data_sub['lat'],
        mode = 'markers',
        marker = dict(
            size = 8,
            color = "rgb(255, 102, 102)",
            opacity = 0.4,
            line = dict(
                width=0.5,
                color='rgb(255, 102, 102)'
            )
        ),
        name = state
    )
    cities.append(city)

cities_year = []
for year in sorted(data.year.value_counts().index):
    data_sub = data.loc[data['year'] == year]
    city = dict(
        type = 'scattergeo',
        visible = False,
        locationmode = 'USA-states',
        lon = data_sub['lon'],
        lat = data_sub['lat'],
        mode = 'markers',
        marker = dict(
            size = 8,
            color = "rgb(255, 102, 102)",
            opacity = 0.4,
            line = dict(
                width=0.5,
                color='rgb(255, 102, 102)'
            )
        ),
        name = str(year)
    )
    cities_year.append(city)
```

I have 2 buttons that switch between which `go.Scattergeo` plot is visible: `states` and `years` (states is default). And I have a slider that appears when the `years` plot is visible.

``` python
from plotly.offline import plot

slider = [dict(active = 0,
               pad = dict(t = 1),
               steps = [dict(args = ["visible", ([False] * len(cities)) + [True, False, False, False]], 
                             label = "1990",
                             method = "restyle"
                            ),
                        dict(args = ["visible", ([False] * len(cities)) + [False, True, False, False]],
                             label = "1991", 
                             method = "restyle"
                            ),
                        dict(args = ["visible", ([False] * len(cities)) + [False, False, True, False]],
                             label = "1992",
                             method = "restyle"
                            ),
                        dict(args = ["visible", ([False] * len(cities)) + [False, False, False, True]],
                             label = "1993",
                             method = "restyle"
                            )
                       ]
              )
         ]

updatemenus = list([
    dict(type="buttons",
         active=0,
         buttons=list([   
            dict(label = 'states',
                 method = 'update',
                 args = [dict(visible = ([True] * len(cities)) + ([False] * len(cities_year))),
                         dict(sliders = [],
                              showlegend = True)]),
            dict(label = 'years',
                 method = 'update',
                 args = [dict(visible = ([False] * len(cities)) + [True, False, False, False]),
                         dict(sliders = slider,
                              showlegend = False)])
        ]),
     )
])

layout = dict(
    title = 'myplot',
    geo = dict(
        scope='usa',
        projection=dict(type='albers usa'),
        showland=True,
        showlakes = True,
        landcolor = 'rgb(217, 217, 217)',
        subunitwidth=1,
        countrywidth=1,
        subunitcolor="rgb(255, 255, 255)",
        countrycolor="rgb(255, 255, 255)"
    ),
    updatemenus=updatemenus
)

trace_data = cities + cities_year
fig = dict(data=trace_data, layout=layout)
plot(fig, validate=False)
```

When plot first appears, no issues:
![unknown](https://user-images.githubusercontent.com/12959255/44950557-ae757880-adff-11e8-85e4-303fe0c44282.png)

After pressing button, no data points appear:
<img width="1270" alt="screen shot 2018-09-01 at 3 56 02 pm" src="https://user-images.githubusercontent.com/12959255/44950560-c0efb200-adff-11e8-81a7-a02c111563fd.png">

I tried implementing the plots in a different way (using `updatemenus = go.layout.Updatemenu(...)`, `city = go.Scattergeo(...)`, etc.) but had the same problem. Strangely though when I click on "Download plot as a png" after pressing button, the png file shows the data points plotted correctly. The issue doesn't appear when using `go.Scatter` instead of `go.ScatterGeo` so it seems to me it has something to do with updatemenus and `go.scatterGeo`.

**Comment by jonmmease** [comment] 2018-09-06 10:44
Hi @enerrio , I do see what you mean. It seems like it's the introduction of the slider for the first time that's causing the points to disappear. This is something that would need to be addressed in plotly.js.

I'll try to simplify the example a bit, translate it into javascript, and post it as an issue at https://github.com/plotly/plotly.js/issues.

BTW, do you need this to end up as a standalone html file?  If you were using this only in a Jupyter notebook, then you'd have a lot more flexibility working with a `FigureWidget` and ipywidgets controls.

**Comment by enerrio** [comment] 2018-09-07 04:05
Hi @jonmmease, thanks for the response. I don't need it as a standalone html file, I just wanted the visualizations to appear in the notebook. I actually tried using `FigureWidget` with above data like this:
``` python
go.FigureWidget(data=trace_data, layout=layout)
```
But it still has the same error as above.

**Comment by jonmmease** [comment] 2018-09-08 13:36
Hi @enerrio , Here's an example of what I mean by using `FigureWidget` and `ipywidgets`

```python
# Imports
import pandas as pd
import plotly.graph_objs as go
from plotly.offline import plot
import ipywidgets as widgets

# Load data
data = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_us_cities.csv')
data = data.iloc[:400] # Keep only first 400 samples
data.loc[:100, 'year'] = '1990'
data.loc[100:200, 'year'] = '1991'
data.loc[200:300, 'year'] = '1992'
data.loc[300:, 'year'] = '1993'

# Create Figure
cities = []
for state in data['name'].value_counts().index:
    data_sub = data.loc[data['name'] == state]
    city = dict(
        type = 'scattergeo',
        visible = True,
        locationmode = 'USA-states',
        lon = data_sub['lon'],
        lat = data_sub['lat'],
        mode = 'markers',
        marker = dict(
            size = 8,
            color = "rgb(255, 102, 102)",
            opacity = 0.4,
            line = dict(
                width=0.5,
                color='rgb(255, 102, 102)'
            )
        ),
        name = state
    )
    cities.append(city)

cities_year = []
for year in sorted(data.year.value_counts().index):
    data_sub = data.loc[data['year'] == year]
    city = dict(
        type = 'scattergeo',
        visible = False,
        locationmode = 'USA-states',
        lon = data_sub['lon'],
        lat = data_sub['lat'],
        mode = 'markers',
        marker = dict(
            size = 8,
            color = "rgb(255, 102, 102)",
            opacity = 0.4,
            line = dict(
                width=0.5,
                color='rgb(255, 102, 102)'
            )
        ),
        name = str(year)
    )
    cities_year.append(city)

layout = dict(
    title = 'myplot',
    margin = dict(r=300),  # Keep map from resizing when legend changes
    geo = dict(
        scope='usa',
        projection=dict(type='albers usa'),
        showland=True,
        showlakes = True,
        landcolor = 'rgb(217, 217, 217)',
        subunitwidth=1,
        countrywidth=1,
        subunitcolor="rgb(255, 255, 255)",
        countrycolor="rgb(255, 255, 255)"
    )
)

trace_data = cities + cities_year
fig = go.FigureWidget(data=trace_data, layout=layout)

# Create year slider
year_slider = widgets.SelectionSlider(
    options=['1990', '1991', '1992', '1993'],
    index=0,
    description='Year:',
    disabled=True,
    orientation='horizontal',
    continuous_update=False,
    readout=True)

def set_year(*_):
    year_visibility = ['legendonly'] * 4
    year_visibility[year_slider.index] = True
    fig.plotly_restyle({'visible': ([False] * len(cities)) + year_visibility})

year_slider.observe(set_year)

# Create mode toggle
def set_mode(*_):
    if mode_toggle.value == 'States':
        year_slider.disabled = True
        fig.plotly_update({'visible': ([True] * len(cities)) + [False, False, False, False]})
    else:
        year_slider.disabled = False
        set_year()

mode_toggle = widgets.ToggleButtons(
    options=['States', 'Years'],
    disabled=False)

mode_toggle.observe(set_mode)

# Create widget layout
widgets.VBox([fig, mode_toggle, year_slider])
```
![geodashboard](https://user-images.githubusercontent.com/15064365/45254686-461c1f00-b34a-11e8-8d8a-334df55bd53a.gif)

I made a couple of other changes. I set `layout.margin.r` to keep map from jumping when legend changes. And I used `legendonly` rather than `False` for the `visible` property of years that aren't selected.

See https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html for more info on ipywidgets.

Hope that helps!

**Comment by gvwilson** [comment] 2024-06-13 17:40
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:40 UTC
Labels: bug, plotly.js
