### ISSUE TITLE
Version 4 discussion

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1420] opened 2019-02-02 14:42 UTC
## Overview
This is an issue for discussing what we'd like to work towards in a future version 4, mostly focusing on changes that would not be backwards compatible.  Nothing here is set in stone and feedback is welcome.

### Theming
Lets make the defualt theme be `plotly` or `plotly_white` (https://github.com/plotly/plotly.py/pull/1224)

### Integrate `px`
Integrate the `px` project for exploratory data analysis directly into plotly.py (https://github.com/plotly/px)

### Redo subplot support
There are a bunch of [outstanding issues](https://github.com/plotly/plotly.py/issues?q=is%3Aopen+is%3Aissue+label%3Amake_subplots) with the `make_subplots` function.  The most significant limitation being that it doesn't support non-Cartesian subplot types.

Last year, plotly.js introduced its own subplot layout system (`layout.grid`) so we could build the new subplot system on top of that (See https://github.com/plotly/plotly.js/issues/3507 ).  Hopefully we could still support the `make_subplots` API, but give most of the work to plotly.js

I would also like to add support for accessing traces by subplot.  Something like
`figure.get_traces(row=2, col=1)`.  This would allow users to construct an initial figure using `px`, and then easily grab particular traces to customize using `.update` or property assignment syntax. See https://github.com/plotly/plotly.py/issues/1484.

### Self displaying figures
I would like to allow `go.Figure` to display itself as a plotly.js figure when used in an ipython context.  We have a prototype of this in `px` with `FigurePx`

https://github.com/plotly/px/blob/610910fd5f167de2482b01753db13cd0bd01c171/plotly_express/_px.py#L22-L33

I would like to extend this a bit so that it's possible to use a global setting to configure how `go.Figure` should display itself.  `FigurePx` is using the `init_notebook_mode`/`iplot` approach, but I'd also like to support a static image display (using orca) that would be suitable for use in QtConsole/Spyder and for PDF export.

These changes would not affect `FigureWidget`.  `FigureWidget` will remain a separate class that is distinct from `go.Figure` in that is is a widget subclass and supports updating properties in place.

### Convert offline html export to `plotly.io` module
Replace the `plotly.offline.plot` function with functions in the `plotly.io` module (https://github.com/plotly/plotly.py/issues/1098)

### Split off choropleth figure factory into a separate package
Splitting the county choropleth figure factories into a separate package would help a lot with reducing the plotly.py package size.  Then we could add additional shape files to that geo-plotly package to support different geographic regions.

### Split off `plotly.plotly` chart-studio integration into a separate package
Split off the functionality in `plotly.plotly` into a separate package called `chart_studio`.  This will make it easier for people to understand that you can use plotly.py totally offline and without an account.  Everything in the `plotly` package would be offline, and the chart_studio integration is in the `chart_studio` package.

Along with the change to make figures self-displaying and to move the html output to `plotly.io`, this would mean that users would no longer need to figure out the `online`/`offline` distinction.  The plotly.py package just is offline, and you don't need to say offline anywhere to use it that way.

### Documentation
If not before, documentation should be updated to remove use of `iplot` and allow figures to display themselves in "offline" mode (https://github.com/plotly/documentation/issues/992)

Also, before the v3 to v4 jump we should finish working out how to version the documentation so that the version 3 docs can remain active alongside the version 4 docs.

cc @nicolaskruchten @jackparmer @chriddyp

**Comment by nicolaskruchten** [comment] 2019-02-02 14:57
Thanks for pulling this together! Agreed on all points I think!

**Comment by jackparmer** [comment] 2019-02-11 16:05
As discussed on Slack, v4 may also be a good opportunity to introduce default mobile support through the plotly.js `breakpoints` API. This would work well with the "Documentation" and "Theming" spirit of this release.

**Comment by PlatonB** [comment] 2019-03-05 20:09
Feedback for annotated heatmaps:
- Support for None values. Currently Plotly returns an error: `TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'.`
- Heatmaps with one axis. They will be useful, at least, in bioinformatics. Examples:
![](https://www.researchgate.net/profile/Bonnie_Joubert/publication/49835363/figure/fig2/AS:216358336897026@1428595255091/Linkage-disequilibrium-LD-observed-across-SNPs-of-MS4A2-r2-values-displayed-in.png)

![](https://estrip.org/content/users/tinypliny/0814/orig/reading_LD_blocks.png)

**Comment by Juanlu001** [comment] 2019-07-14 09:59
Target date for 4.0.0 release? :)

**Comment by jonmmease** [comment] 2019-07-14 12:02
Hopefully next week. Cross reference release candidate announcement https://community.plot.ly/t/introducing-plotly-py-4-0-0rc1/25639.

**Comment by nicolaskruchten** [comment] 2019-09-11 14:00
@jonmmease I'll let you close this one out :) Nice job!

**Comment by gvwilson** [comment] 2024-06-13 19:24
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:24 UTC
Labels: V4
