### ISSUE TITLE
Performance regression in 3.0.0

### ISSUE THREAD

**Issue by iandanforth** [plotly/plotly.py#1052] opened 2018-07-09 01:21 UTC
OS: OSX 10.13.2
Python: 3.6.4

I'm creating the following animated chart using the offline API.
![plotly-animation](https://user-images.githubusercontent.com/446062/42426044-5ae40b4c-82d9-11e8-8c47-a88b5e37802a.gif)

Using 2.7.0 generating the HTML file (30MB) takes ~11 seconds (0m11.044s)
Using 3.0.0 generating the HTML file takes: **4 MINUTES** (4m20.393s).

There is probably a much more efficient way of making this kind of animated scatter (please tell me if there is) but in 2.7 this was at least workable, in 3.0, not so much.

The following example reproduces the behavior. The size of the data is the same as in the gif above, the actual values are not.

```python
import numpy as np
import plotly.graph_objs as go
import colorlover as cl
from plotly.offline import plot

sim_duration = 40.0
time_inc = 0.1
motor_unit_count = 120
times = np.arange(0.0, sim_duration, time_inc)

# Setting colors for plot.
potvin_scheme = [
    'rgb(115, 0, 0)',
    'rgb(252, 33, 23)',
    'rgb(230, 185, 43)',
    'rgb(107, 211, 100)',
    'rgb(52, 211, 240)',
    'rgb(36, 81, 252)',
    'rgb(0, 6, 130)'
]
# It's hacky but also sorta cool.
c = cl.to_rgb(cl.interp(potvin_scheme, motor_unit_count))
c = [val.replace('rgb', 'rgba') for val in c]
c = [val.replace(')', ',{})') for val in c]


def get_color(trace_index: int) -> str:
    # The first and every 20th trace should be full opacity
    alpha = 0.2
    if trace_index == 0 or ((trace_index + 1) % 20 == 0):
        alpha = 1.0
    color = c[trace_index].format(alpha)
    return color


# Per Motor Unit Force
all_array = np.ones((120, len(times)))
data = []
annotations = []
anno_offsets = {
    0: 20,
    19: 30,
    39: 40,
    59: 45,
    79: 17,
    99: 56,
    119: 170
}
max_y = np.amax(all_array)
for i, t in enumerate(all_array):
    trace = go.Scatter(
        x=times[:1],
        y=t[:1],
        name=i + 1,
        marker=dict(
            color=get_color(i)
        )
    )
    data.append(trace)

frames = []
for i in range(1, len(times), 10):
    frame_data = []
    for j, t in enumerate(all_array):
        trace = go.Scatter(
            x=times[:i],
            y=t[:i],
            name=j + 1,
            marker=dict(
                color=get_color(j)
            )
        )
        frame_data.append(trace)

    frame = dict(
        data=frame_data
    )
    frames.append(frame)

layout = go.Layout(
    title='Motor Unit Forces by Time',
    yaxis=dict(
        title='Motor unit force (relative to MU1 tetanus)',
        range=[0, max_y],
        autorange=False
    ),
    xaxis=dict(
        title='Time (s)',
        range=[0, sim_duration],
        autorange=False
    ),
    updatemenus=[{
        'type': 'buttons',
        'buttons': [{
            'args': [
                None,
                {'frame': {'duration': 200, 'redraw': False},
                 'fromcurrent': True,
                 'transition': {'duration': 200, 'easing': 'linear'}
                 }
            ],
            'label': 'Play',
            'method': 'animate'
        }]
    }]
)
layout['annotations'] = annotations

fig = go.Figure(
    data=data,
    layout=layout,
    frames=frames
)
plot(fig, filename='regression.html')
```

**Comment by jonmmease** [comment] 2018-07-09 10:40
Hi @iandanforth , thanks for the report and the reproducible example. This will be really helpful for future performance optimization.

Construction `Figure` objects with lots of frames is probably always going to be a bit slower in 3.0 compared to 2.7 because of all of the extra validation and defensive copying that's happening now, but I expect we'll be able to improve this a fair amount with some profiling.

Here's what I recommend. Use objects from the `graph_objs` hierarchy when you're first building up the logic to construct your figure. This was you'll have the validation feedback while you're iterating on your design. Once you have it working the way you want, and you want to scale to a lot more frames, replace all of the graph_objs with plain `dict`s and set the `validate` param to `plot`\`iplot` to `False`. This way you will bypass all property validation and things will run much faster.

When I make these changes in your example, it runs in under 2 seconds.
```python
%%time
import numpy as np
import plotly.graph_objs as go
import colorlover as cl
from plotly.offline import plot

sim_duration = 40.0
time_inc = 0.1
motor_unit_count = 120
times = np.arange(0.0, sim_duration, time_inc)

# Setting colors for plot.
potvin_scheme = [
    'rgb(115, 0, 0)',
    'rgb(252, 33, 23)',
    'rgb(230, 185, 43)',
    'rgb(107, 211, 100)',
    'rgb(52, 211, 240)',
    'rgb(36, 81, 252)',
    'rgb(0, 6, 130)'
]
# It's hacky but also sorta cool.
c = cl.to_rgb(cl.interp(potvin_scheme, motor_unit_count))
c = [val.replace('rgb', 'rgba') for val in c]
c = [val.replace(')', ',{})') for val in c]

def get_color(trace_index: int) -> str:
    # The first and every 20th trace should be full opacity
    alpha = 0.2
    if trace_index == 0 or ((trace_index + 1) % 20 == 0):
        alpha = 1.0
    color = c[trace_index].format(alpha)
    return color

# Per Motor Unit Force
all_array = np.ones((120, len(times)))
data = []
annotations = []
anno_offsets = {
    0: 20,
    19: 30,
    39: 40,
    59: 45,
    79: 17,
    99: 56,
    119: 170
}

max_y = np.amax(all_array)
for i, t in enumerate(all_array):
    trace = dict(
        x=times[:1],
        y=t[:1],
        name=i + 1,
        marker=dict(
            color=get_color(i)
        )
    )
    data.append(trace)

frames = []
for i in range(1, len(times), 10):
    frame_data = []
    for j, t in enumerate(all_array):
        trace = dict(
            x=times[:i],
            y=t[:i],
            name=j + 1,
            marker=dict(
                color=get_color(j)
            )
        )
        frame_data.append(trace)

    frame = dict(
        data=frame_data
    )
    frames.append(frame)

layout = dict(
    title='Motor Unit Forces by Time',
    yaxis=dict(
        title='Motor unit force (relative to MU1 tetanus)',
        range=[0, max_y],
        autorange=False
    ),
    xaxis=dict(
        title='Time (s)',
        range=[0, sim_duration],
        autorange=False
    ),
    updatemenus=[{
        'type': 'buttons',
        'buttons': [{
            'args': [
                None,
                {'frame': {'duration': 200, 'redraw': False},
                 'fromcurrent': True,
                 'transition': {'duration': 200, 'easing': 'linear'}
                 }
            ],
            'label': 'Play',
            'method': 'animate'
        }]
    }]
)
layout['annotations'] = annotations

fig = dict(
    data=data,
    layout=layout,
    frames=frames
)

plot(fig, filename='regression.html', validate=False, auto_open=False)
```

I hope that's helpful.

**Comment by iandanforth** [comment] 2018-07-09 18:00
@jonmmease Thanks for taking the time to look into this! This fix is very helpful for me. My remaining concern is one of *optics*. If someone tries to do much-data-many-frames-wow! and finds plotly slow it may deter them from using the library.

To address that I recommend creating a ticket to modify the animation documentation to include exactly these points. I knew to use 'redraw=False' only because of those docs. (Which are very useful and put together!)

Thanks again!

**Comment by jonmmease** [comment] 2018-07-09 18:31
I'm glad this fix is working for you and thanks for the helpful suggestion regarding the documentation. 

I'm going to leave this issue open until I have a chance to profile your example and see what can be done to make the situation a bit less painful.

**Comment by JavascriptMick** [comment] 2018-07-17 01:46
+1 for this issue.  Rather than submit another ticket, I have attached my own example of poor 3.0.0 performance.  On my machine, the difference was .013 seconds to 30 seconds so ~2000 times slower.  As per above I got out of trouble by extracting the data as lists of dicts using the _data property and operating on them in that form, re-creating a modified figure later.
```
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff

import numpy as np

plotly.tools.set_credentials_file(username='xxxxxx', api_key='xxxxx')
plotly.tools.set_config_file(world_readable=False, sharing='private')
plotly.offline.init_notebook_mode(connected=True)

z = np.random.uniform(0, 1, size=(5000, 8))
myDendrogram = ff.create_dendrogram(z, orientation='bottom')
plotly.offline.iplot(myDendrogram) 

def placeAndScaleDendrogram(figure):
    data = figure['data']
    
    for col in data:
        col['xaxis'] = 'x'
        col['yaxis'] = 'y2'
        col['x'] = (col['x']/10.0) + 0.5  # rescale the dendrogram to match the x axis

get_ipython().run_line_magic('prun', 'placeAndScaleDendrogram(myDendrogram)')

def placeAndScaleDendrogramRaw(figure):
    data = figure._data
    
    for col in data:
        col['xaxis'] = 'x'
        col['yaxis'] = 'y2'
        col['x'] = (col['x']/10.0) + 0.5  # rescale the dendrogram to match the x axis

get_ipython().run_line_magic('prun', 'placeAndScaleDendrogramRaw(myDendrogram)')
```

**Comment by jonmmease** [comment] 2018-07-17 13:38
Thanks for the example and the profiling information @JavascriptMick, I'll see what I can come up with...

**Comment by jonmmease** [comment] 2018-07-17 18:35
Alright, I've made some progress in #1061 that will be included in version 3.0.1

@iandanforth Your initial example has gone from ~110s to ~42s

@JavascriptMick The creation of the dendrogram has gone from ~110s to ~20s, and the scaling that you were timing has gone from ~20s to ~2s.

That said, these are still far slower than version 2.7 where the `Figure` and `graph_objs` objects were basically just simple `dict` subclassses. We're not going to be able to get all of the performance back with the new feature set, but we should be able to keep making incremental progress.

Each of your use cases has ~5000 traces in total, and for cases like these I think we'll need to encourage people to work with `dict` objects rather than `graph_objs`, and work through whether there's anything we should do in the API to make that easier.

**Comment by jonmmease** [comment] 2018-08-02 10:25
Hi @JavascriptMick ,

I'd rather people not get in the habit of using the `_data` property for performance reasons because that will mess up the synchronization of the new `FigureWidget` class.

What do you think of the proposal in #1079 ? If this were implemented you could request that the figure factory return a `dict`, and then you could make modifications to the `dict` before converting it to a `Figure` (or even not converting it to a `Figure` if you use `plot`/`iplot` with `validate=False`).

Also, the dendrogram itself with that many points is a bit of a mess visually. I'm thinking we should expose the scipy `truncate_mode` property (see http://lagrange.univ-lyon1.fr/docs/scipy/0.17.1/generated/scipy.cluster.hierarchy.dendrogram.html) to have the option of limiting how many leaves are displayed.

Here's one thought for making the construction of clustermap easier (short of creating a dedicated figure factory).  For figure factories that only deal with a single axis (like dendrogram), it would be nice if you could pass in a `Figure` object that was initialized with [`tools.make_subplots`](https://plot.ly/python/subplots/#multiple-subplots-with-titles), along with the subplot `row`, `col` parameters.  In this case the figure factory would add all of its traces to the appropriate axes of the existing figure (In practice I'd prefer to refactor the internal logic a bit and have a separate function for adding traces to an existing figure, but that's the basic idea).

**Comment by arthurpham** [comment] 2019-06-14 01:31
It seems i can reproduce the same issue with this code :
```python
import plotly
import time
import plotly.plotly as py
import plotly.figure_factory as FF

print('plot version', plotly.__version__)
t1 = time.time()

z = []
for i in range(0, 100):
    z.append([j for j in range(0, 100)])

figure = FF.create_annotated_heatmap(z)
print('Timing', time.time() - t1)
```
With plotly version 3.10.0, i get around 24 seconds, versus 2.9 seconds for version 2.7.0.

Is it the right place to raise the issue ?

**Comment by gvwilson** [comment] 2024-06-13 17:41
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:41 UTC
Labels: performance
