### ISSUE TITLE
what is "plotlyServerURL" option in plotly offline plots html page

### ISSUE THREAD

**Issue by maddukurisrinivasarao** [plotly/plotly.py#1602] opened 2019-06-10 11:11 UTC
When I generate a html page using plotly offline plots, there are following references to plot.ly, what are they used for? are my plots exported to plot.ly by default?

window.PLOTLYENV.BASE_URL='https://plot.ly'

"linkText": "Export to plot.ly", 
"plotlyServerURL": "https://plot.ly"

**Comment by jonmmease** [comment] 2019-06-10 13:57
Hi @maddukurisrinivasarao,

No, plots are **not** exported to plot.ly by default.  This base URL is only used when you click the edit in chart studio button, or the Export to plot.ly link.  And both of these (the button and the link) are disabled by default.

But that said, it would probably be a good idea for us to blank out these URLs when a user export a figure without the link/button enabled.

**Comment by maddukurisrinivasarao** [comment] 2019-06-11 06:04
@jonmmease  thanks for the clarification. It would be great if there is an option to control the URLs generation.

**Comment by simplenotezy** [comment] 2020-12-28 12:00
Also, would be nice if "external" is not added to the `plotlyServerURL` URL.

**Comment by gvwilson** [comment] 2024-06-13 19:33
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:33 UTC
Labels: enhancement, V4
