### ISSUE TITLE
Latin1 encoding errors when exporting with orca

### ISSUE THREAD

**Issue by mgf-unige** [plotly/plotly.py#1486] opened 2019-03-31 09:50 UTC
I have a problem exporting plots using LATIN1 encoding for characters. When I produce the plot with the plotly command, it works well but when I export it with ocra, the encoding goes wrong for some characters (for example, le spanish 'á' becomes '�' as the character is unknown - � = Unicode U+FFFD replacement for unrecognized character). I export simply with:

```
orca(p, file = "myplot.png", width = 1000, height = 500, format = "png", scale = 1)
```

Should I do something within the orca command to plot those characters correctly?

**Comment by jonmmease** [comment] 2019-04-02 10:03
Hi @mgfasel-unige, thanks for the report.

Could you share a full example, including the definition of the figure?  Also, plotly.py doesn't have an `orca` function. What language/library are you using?  Thanks!

**Comment by mgfasel-unige** [comment] 2019-04-02 17:24
Hi,

Thanks, I use the R plotly library.

Here is an example:

```
ex  <- data.frame(region = c("Pará", "Pará", "Pará", "Pará", "Pará", "Region2", "Region2", "Region2", "Region2", "Region2", "Region3", "Region3", "Region3", "Region3", "Region3"),
                  country = c("Brazil", "Brazil", "Brazil", "Brazil", "Brazil", "Country2", "Country2", "Country2", "Country2", "Country2", "Country3", "Country3", "Country3", "Country3", "Country3"),
                  var = c("VAR1", "VAR1", "VAR1", "VAR1", "VAR1", "VAR1", "VAR1", "VAR1", "VAR1", "VAR1", "VAR1", "VAR1", "VAR1", "VAR1", "VAR1"),
                  value = c(2,5,7,5,4,3,9,5,7,5,3,7,6,9,3))
p <- plot_ly(ex) %>%
  add_trace(x = ~region, y = ~value,
            color = ~country, fillcolor = ~country, opacity = 1.0,
            type = 'box', boxpoints = "all", jitter = 0.0,
            pointpos = 0, line = list(width = 1),
            marker = list(color = '#000000', opacity = .8, size = 2),
            orientation = "v", showlegend = T) %>%
  layout(xaxis = list(title = 'Region', tickangle = 270, zeroline = FALSE,
                      categoryorder = "array",
                      categoryarray = c(unique(g$Country.x))),
         yaxis = list(title = 'Value', zeroline = FALSE),
         boxmode = "group", boxgap = 0.05, boxgroupgap = 0.3,
         shapes = list(hline(4, width = .8)),
         legend = list(bgcolor = 'transparent'))
p
plotly_IMAGE(p, width = 600, height = 400, format = "png", scale = 1, dpi = 600,
             out_file = paste0("D:/Ex01a.png"))
setwd(paste0("D:/"))
orca(p, file = paste0("Ex01b.png"),
     width = 600, height = 400, format = "png", scale = 1)
```

The plotly'IMAGE command results in:
![Ex01a](https://user-images.githubusercontent.com/48024091/55422714-907e1b00-557c-11e9-9ce7-017135a540a6.png)

While the orca command results in (note the á in the Pará label):
![Ex01b](https://user-images.githubusercontent.com/48024091/55422774-b3103400-557c-11e9-87b7-9621948b8c29.png)

**Comment by mgfasel-unige** [comment] 2019-04-02 17:33
You can delete the shapes = list(hline(4, width = .8)), line as you probably don't have the hline function...

**Comment by mgfasel-unige** [comment] 2019-04-02 19:11
I understand now that this threat is for Python. I will post it for R. Thanks..

**Comment by mgfasel-unige** [comment] 2019-04-02 19:18
I posted the issue in the orca thread. You can delete it here if better. Thanks again.

**Comment by gvwilson** [comment] 2024-06-13 19:26
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:26 UTC
Labels: question
