### ISSUE TITLE
Boxplot hovertext, and text are broken

### ISSUE THREAD

**Issue by susielu** [plotly/plotly.py#1639] opened 2019-06-26 19:22 UTC
In the Colored Box Plot example pulled from the docs, https://plot.ly/python/box-plots/ when you change the `go.Box` trace to have a `text` attribute and use `hoverinfo` with the text the hover does not display, it also doesn't work if you use the `hovertext` property: 

```py
import plotly as plotly
import plotly.graph_objs as go
import numpy as np

y0 = np.random.randn(50)
y1 = np.random.randn(50)+1

trace0 = go.Box(
    y=y0,
    name = 'Sample A',
    hovertext='text',
    marker = dict(
        color = 'rgb(214, 12, 140)',
    )
)
trace1 = go.Box(
    y=y1,
    name = 'Sample B',
    text='hello',
    hoverinfo='text',
    marker = dict(
        color = 'rgb(0, 128, 128)',
    )
)
data = [trace0, trace1]
plotly.offline.iplot(data, config={'displayModeBar': False})
```

**Comment by jonmmease** [comment] 2019-06-28 12:51
Hi @susielu,

The text/hovertext fields are setting text information for each point that is considered for the box plot.  So you will only have the hover text show up when hovering over the outlier points, not when hovering on the box itself.  Is this what you're seeing?  The trace's `name` property, on the other hand, is setting the name for the trace as a whole and it will show up when hovering over the box.

Is this what you're seeing?

**Comment by susielu** [comment] 2019-06-28 14:39
So hover just doesn't show up at all on the one that is using text/hovertext. In the example I provided the boxplot on the right has no hover even though text is set.

**Comment by gvwilson** [comment] 2024-06-13 19:33
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:33 UTC
Labels: question
