### ISSUE TITLE
Magic underscore error messages

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1557] opened 2019-05-08 15:03 UTC
in the following code

```python
import plotly_express as px
tips = px.data.tips()
px.scatter(
           tips, x="total_bill", y="tip", text="size",
           color="size", facet_col="sex",
           color_continuous_scale=px.colors.sequential.Viridis, 
).update_traces(text_position="top center")
```

The `text_position` magic underscore argument is incorrect (should be `textposition`) but the error message is not super-helpful:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-640c247e62b0> in <module>()
      5            color="size", facet_col="sex",
      6            color_continuous_scale=px.colors.sequential.Viridis,
----> 7 ).update_traces(text_position="top center")

~/miniconda2/envs/nb/lib/python3.6/site-packages/plotly/basedatatypes.py in update_traces(self, patch, selector, row, col, **kwargs)
    793         """
    794         for trace in self.select_traces(selector=selector, row=row, col=col):
--> 795             trace.update(patch, **kwargs)
    796         return self
    797 

~/miniconda2/envs/nb/lib/python3.6/site-packages/plotly/basedatatypes.py in update(self, dict1, **kwargs)
   3356             with self.figure.batch_update():
   3357                 BaseFigure._perform_update(self, dict1)
-> 3358                 BaseFigure._perform_update(self, kwargs)
   3359         else:
   3360             BaseFigure._perform_update(self, dict1)

~/miniconda2/envs/nb/lib/python3.6/site-packages/plotly/basedatatypes.py in _perform_update(plotly_obj, update_obj)
   2548             # -------------------------
   2549             invalid_props = [
-> 2550                 k for k in update_obj if k not in plotly_obj
   2551             ]
   2552 

~/miniconda2/envs/nb/lib/python3.6/site-packages/plotly/basedatatypes.py in <listcomp>(.0)
   2548             # -------------------------
   2549             invalid_props = [
-> 2550                 k for k in update_obj if k not in plotly_obj
   2551             ]
   2552 

~/miniconda2/envs/nb/lib/python3.6/site-packages/plotly/basedatatypes.py in __contains__(self, prop)
   3098                     return False
   3099             else:
-> 3100                 if obj is not None and p in obj._validators:
   3101                     obj = obj[p]
   3102                 else:

AttributeError: 'numpy.ndarray' object has no attribute '_validators'
```

**Comment by nicolaskruchten** [comment] 2019-11-02 18:18
This is basically because `text` is valid but it's meant to be an array or string, so `text_position` is read as `text.position` somehow but arrays don't support properties like this, I infer.

**Comment by gvwilson** [comment] 2024-06-13 19:32
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:32 UTC
Labels: documentation
