### ISSUE TITLE
Is the mouse scrolling speed for 3D plots customizable?

### ISSUE THREAD

**Issue by basilevh** [plotly/plotly.py#4029] opened 2023-01-19 17:44 UTC
I am running the first example on [this webpage](https://plotly.com/python/3d-isosurface-plots/) without modification in a Jupyter notebook inside VSCode:

```
import plotly.graph_objects as go

fig= go.Figure(data=go.Isosurface(
    x=[0,0,0,0,1,1,1,1],
    y=[1,0,1,0,1,0,1,0],
    z=[1,1,0,0,1,1,0,0],
    value=[1,2,3,4,5,6,7,8],
    isomin=2,
    isomax=6,
))

fig.show()
```

The mouse scroll speed is really, really slow inside my notebook. I am not experiencing performance issues, but the "zoom step size" is simply tiny. On the linked webpage, it's much better. I don't know why this difference arises, but anyway, is the scrolling speed configurable? [This issue](https://github.com/plotly/plotly.js/issues/1085) is related, but as far as I know, the feature has not yet been implemented.

Thank you!

**Comment by kzhang2** [comment] 2023-01-25 17:50
I am also having an issue with slow zoom speeds when I scroll a plotly 3d plot from within a Jupyter notebook. Bumping for visibility.

**Comment by AaronStiff** [comment] 2023-02-11 01:01
Yes, this does seem to be a duplicate of the issue you linked to. I'll close this one since it's something which would have to be added in `plotly.js`.

**Closed by AaronStiff** 2023-02-11 01:01 UTC
Labels: plotly.js, feature
