### ISSUE TITLE
set the yaxis parameters(tickformat='p')

### ISSUE THREAD

**Issue by fenghuoqiuqiu** [plotly/plotly.py#1537] opened 2019-04-27 01:59 UTC
I want to use percentage format(retain four decimal) ,When I set the yaxis parameters(tickformat='p'), but there are always some display problems. 

This is my code:
```
import plotly.offline as py
from plotly.graph_objs import Scatter, Layout
import plotly.graph_objs as go
py.init_notebook_mode(connected=True)

trace1=go.Scatter(
    name="lenged2",
    x=['2018-01','2018-02','2018-03','2018-04','2018-05','2018-06','2018-07','2018-08','2018-09'],
    y=[0.1,0.3,0.5,0.4,0.7,0.3,0.4,0.2,0.4,0.5], 
)

layout=go.Layout(
    showlegend=True, 
    legend=dict(x=1.05,y=1.1),
    xaxis=dict(showticklabels=True),
    yaxis=dict(
                tickformat='p',
                showgrid=False,

))
data=[trace1]
fig=go.Figure(data=data, layout=layout)
py.iplot(fig)
```

![image](https://user-images.githubusercontent.com/47968090/56843393-ac9e7f00-68d2-11e9-935e-24e9a016f051.png)

Any help is greatly appreciated.

**Comment by jonmmease** [comment] 2019-04-29 11:23
Hi @fenghuoqiuqiu, thanks for the report.  I've opened a corresponding issue with the JavaScript library at https://github.com/plotly/plotly.js/issues/3814.

As a workaround, you can manually specify the number of decimal places using the `'%'` format character.  For example:

```python
import plotly.offline as py
from plotly.graph_objs import Scatter, Layout
import plotly.graph_objs as go
py.init_notebook_mode(connected=True)

trace1=go.Scatter(
    name="lenged2",
    x=['2018-01','2018-02','2018-03','2018-04','2018-05','2018-06','2018-07','2018-08','2018-09'],
    y=[0.1,0.3,0.5,0.4,0.7,0.3,0.4,0.2,0.4,0.5], 
)

layout=go.Layout(
    showlegend=True, 
    legend=dict(x=1.05,y=1.1),
    xaxis=dict(showticklabels=True),
    yaxis=dict(
                tickformat='.0%',
                showgrid=False,

))
data=[trace1]
fig=go.Figure(data=data, layout=layout)
py.iplot(fig)
```
![newplot-2](https://user-images.githubusercontent.com/15064365/56893134-ae418180-6a4f-11e9-877b-280b2c40e16e.png)

**Comment by fenghuoqiuqiu** [comment] 2019-05-05 06:45
thank you for your help,but it remains an unsettling question,I want to use percentage format(retain four decimal,eg. 20.22%) .
When I manually specify the number of decimal places using the '%' format character,it only retain two decimal.But when I use  the 'p' format character,there are always some display problems.

![image](https://user-images.githubusercontent.com/47968090/57189646-8799b400-6f43-11e9-8896-a9a86495935d.png)

**Comment by fenghuoqiuqiu** [comment] 2019-05-05 07:07
> thank you for your help,but it remains an unsettling question,I want to use percentage format(retain four decimal,eg. 20.22%) .
> When I manually specify the number of decimal places using the '%' format character,it only retain two decimal.But when I use  the 'p' format character,there are always some display problems.

@jonmmease

**Comment by gvwilson** [comment] 2024-06-13 19:31
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:31 UTC
Labels: plotly.js
