### ISSUE TITLE
animation don't display all colors

### ISSUE THREAD

**Issue by yinshurman** [plotly/plotly.py#1734] opened 2019-08-22 10:09 UTC
```
import pandas as pd
import numpy as np 
from plotly import io as pio
from plotly import express as px
def make_case():
    max_length=10
    groups=['a','b','c']
    la=[10,9,8]
    lb=[6,5,4]
    lc=[5,4,3]
    def make_one(length,col):
        x=[max_length-i for i in range(length)]
        value=list(np.random.randint(0,length,size=(length,)))
        gr=length *[min(x)]
        color=length*[col]
        df=pd.DataFrame({'x':x,'group':gr,'y':value,'color':color})
        return df
    ls_a=[make_one(i,'a') for i in la]
    ls_b=[make_one(i,'b') for i in lb]
    ls_c=[make_one(i,'c') for i in lc]
    f=[pd.concat(j,axis=0) for j in [ls_a,ls_b,ls_c]]
    return pd.concat(f,axis=0).sort_values(['color','group','x'])
case=make_case()
fig=px.scatter(case,x='x',y='y',color='color',animation_frame='group')
fig.show()
```

**Comment by yinshurman** [comment] 2019-08-22 10:10
`
import pandas as pd
import numpy as np
from plotly import io as pio
from plotly import express as px

def make_case():
max_length=10
groups=['a','b','c']
la=[10,9,8]
lb=[6,5,4]
lc=[5,4,3]
def make_one(length,col):
x=[max_length-i for i in range(length)]
value=list(np.random.randint(0,length,size=(length,)))
gr=length [min(x)]
color=length[col]
df=pd.DataFrame({'x':x,'group':gr,'y':value,'color':color})
return df
ls_a=[make_one(i,'a') for i in la]
ls_b=[make_one(i,'b') for i in lb]
ls_c=[make_one(i,'c') for i in lc]
f=[pd.concat(j,axis=0) for j in [ls_a,ls_b,ls_c]]
return pd.concat(f,axis=0).sort_values(['color','group','x'])
case=make_case()
fig=px.scatter(case,x='x',y='y',color='color',animation_frame='group')
fig.show()

`

**Comment by yinshurman** [comment] 2019-08-22 10:44
with above code, the legend will only display one color instead of three.

**Comment by gvwilson** [comment] 2024-06-13 19:46
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:46 UTC
