### ISSUE TITLE
Jupyter renderer fails in IE11

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.py#1693] opened 2019-07-29 15:07 UTC
Adapted from https://github.com/plotly/plotly.js/issues/4015

----------

Using `plotly.py` v4 and python `3.6.8`:

```py
import plotly.graph_objs as go
fig = go.FigureWidget()

fig.add_scatter(y=[2, 1, 4, 3])
fig.add_bar(y=[1, 4, 3, 2])
fig.layout.title = 'Hello FigureWidget'

fig.show()
```

in IE11 off Windows7 (via browserstack) gives

![image](https://user-images.githubusercontent.com/6675409/62059057-83063400-b1f0-11e9-9769-ec70f4758061.png)

![image](https://user-images.githubusercontent.com/6675409/62059190-bea0fe00-b1f0-11e9-9e5f-fd80299f58bd.png)

while the corresponding `html` output (see https://community.plot.ly/t/plotly-charts-not-displaying-in-ie/26506/2) renders fine.

**Comment by gvwilson** [comment] 2024-06-13 19:44
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:44 UTC
