### ISSUE TITLE
Feature Request: Allow single trace in data argument.

### ISSUE THREAD

**Issue by Akronix** [plotly/plotly.py#1373] opened 2018-12-19 14:02 UTC
Calls to, for intance, iplot need the first argument, data to be a “list of traces”. However, often you just want to pass one trace and in this case the plot is not shown, wouldn’t be convenient to accept as well data being a single trace argument as well as a list? or at least convert single traces to a list with length 1, like this data=[trace], but do it behind the scenes, transparently to the user.

I expect this behaviour to be more intuitive and closer to how the plot function of R works.

[Original thread in discourse](https://community.plot.ly/t/why-the-data-argument-for-plots-has-to-be-a-list-and-cant-be-a-single-element/17030).

**Comment by gvwilson** [comment] 2024-06-13 17:42
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, so I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:42 UTC
Labels: enhancement
