### ISSUE TITLE
Animation of lines is not consistent with animation of markers : it does not take animation_group into account

### ISSUE THREAD

**Issue by MaximeWeyl** [plotly/plotly.py#1843] opened 2019-10-22 16:37 UTC
Hi, 
I'm using plotly 4.2.1

Here is a code example to show what my problem is : 

``` python
import numpy as np
import pandas as pd
import plotly.express as px

N = 100
window_size = 15

# We make our x,y couples
x = np.arange(1, N)
y = np.sin(x * 2.3)

# We are making views over or data, with length window_size
first_point = np.arange(1, N - window_size)

ind = pd.MultiIndex.from_product(
    [first_point,
     range(window_size)
     ],
    names=["begin", "win"]
)

join_x = (ind.get_level_values("begin") + ind.get_level_values("win")).rename("join_x")

df_plot = pd.Series(y, index=x, name="y").reindex(join_x).to_frame()
df_plot["begin"] = ind.get_level_values("begin")
df_plot["win"] = ind.get_level_values("win")
df_plot["x"] = join_x

plot = px.scatter(df_plot, "win", "y", animation_frame="begin", animation_group="x")
with open("trace.html", "w") as f:
    f.write(plot.to_html())

```

This example gives what I expect : it shows the trace of y=sin(x) for a moving window of length 15, and gives me a really nice animation : 

![scatter](https://user-images.githubusercontent.com/31591159/67306187-d8ec2e80-f4f6-11e9-9086-6cd8a034799a.gif)

Then, I replace "px.scatter" with "px.line". It gives me this really strange behavior : while I drag the cursor everything's OK. But when I play the animation, the lines are really strange.

![line](https://user-images.githubusercontent.com/31591159/67306536-6cbdfa80-f4f7-11e9-8198-fc1035918651.gif)

If I try to display both with this code : 

``` python
for f in plot.frames:
    for t in f.data:
        t.update(mode="markers+lines")

with open("trace.html", "w") as f:
    f.write(plot.to_html())
``` 

![both](https://user-images.githubusercontent.com/31591159/67307625-15b92500-f4f9-11e9-9324-29c46e4a928f.gif)

**Comment by nicolaskruchten** [comment] 2019-10-27 05:13
This is indeed pretty wierd! I think it has to do with line-simplification like in https://github.com/plotly/plotly.js/issues/4250 ... Maybe PX just needs to force line simplification to `false`.

**Comment by alexcjohnson** [comment] 2019-10-28 02:32
> while I drag the cursor everything's OK. But when I play the animation, the lines are really strange

I don't see any animation in your GIF when dragging, just a jump from one location to another. So it looks OK because your eyes correctly manage object constancy, not because the animation is correct in that case.

> I think it has to do with line-simplification

I highly doubt it, there's no simplification going on in that case. There's just no per-point object constancy built into the line paths, we're simply asking the path attr to [transition from one value to the next](https://github.com/plotly/plotly.js/blob/990a96050bbab12e1e405d0974985b2fea54d2e6/src/traces/scatter/plot.js#L271), which means transitioning each control point. Working in real object constancy seems like a frankly very tricky problem in the general case. For specific cases like this, where a leading point is dropped and a new point is added at the end, we could imagine a solution in 3 steps:

1. Before the transition, redraw the path instantaneously with an extra control point at the end (doubling up the last point)
2. Create the final path having that extra control point now at the beginning, and execute the transition
3. Redraw the path without the extra control point (or, I suppose, this step could be deferred until the next transition comes and we see what points have been added or removed)

That would work, and adding & removing points at the ends seems like a pretty common use case so may be worthwhile coding for. May be tricky to get it to work right on splines, we can't treat these ghost points like regular points that happen to overlap their neighbors as this wouldn't give the same curve to the next point; but it seems like there would be a way to handle it.

The more general case - points being inserted, removed, or reordered mid-group - creates all sorts of complications. Adding and removing points should be manageable, though accounting for all possible line shapes and getting it to look like the new points emerge from the line itself rather than splitting out of one of the existing points may be tricky. Reordering points it's not even clear to me what theoretically you should see. Take the simplest case where x, y, and id don't change, just their relative order. Then the markers wouldn't move at all, but you'd be asking the lines connecting them to change connection order? I don't see a way to do this without the lines disconnecting from the markers. Perhaps that's a sufficiently obscure edge case that this is acceptable?

**Comment by nicolaskruchten** [comment] 2019-10-28 04:23
> I highly doubt it, there's no simplification going on in that case.

You're right, I just tried it with line simplification set to off with no change.

Clearly, clearly though this is a bug: we have lines between points, the points move, and the lines unstick from the points. In cases like this with no reordering and no insertion/deletion between the points, we should be able to have the line touch each point at every step of the transition!

**Comment by alexcjohnson** [comment] 2019-10-28 14:17
Yes, this is definitely a bug, and you're right, in most cases we should be able to maintain contact between lines and points. My comment was just trying to lay out what it will take for us to fix it, and the cases in which it still may not work.

**Comment by gvwilson** [comment] 2024-06-14 13:14
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:14 UTC
