### ISSUE TITLE
OSError: Address 'http://127.0.0.1:8050' already in use.

### ISSUE THREAD

**Issue by mhechthz** [plotly/plotly.py#3953] opened 2022-11-15 17:05 UTC
Up to now I didn't find any solution for this.

I try in Jupyter-Notebook (Windows10, Google Chrome):
```
from jupyter_dash import JupyterDash
app = JupyterDash(__name__)
app.run_server(mode='inline',height=600,width='80%')
```
and get the error:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_9776\1759314688.py in <cell line: 0>()
----> 1 app.run_server(mode='inline',height=600,width='80%')#,debug=True, use_reloader=True)

C:\Python311\Lib\site-packages\jupyter_dash\jupyter_app.py in run_server(self, mode, width, height, inline_exceptions, **kwargs)
    337                 )
    338 
--> 339         wait_for_app()
    340 
    341         if JupyterDash._in_colab:

C:\Python311\Lib\site-packages\retrying.py in wrapped_f(*args, **kw)
     47             @six.wraps(f)
     48             def wrapped_f(*args, **kw):
---> 49                 return Retrying(*dargs, **dkw).call(f, *args, **kw)
     50 
     51             return wrapped_f

C:\Python311\Lib\site-packages\retrying.py in call(self, fn, *args, **kwargs)
    210                 if not self._wrap_exception and attempt.has_exception:
    211                     # get() on an attempt with an exception should cause it to be raised, but raise just in case
--> 212                     raise attempt.get()
    213                 else:
    214                     raise RetryError(attempt)

C:\Python311\Lib\site-packages\retrying.py in get(self, wrap_exception)
    245                 raise RetryError(self)
    246             else:
--> 247                 six.reraise(self.value[0], self.value[1], self.value[2])
    248         else:
    249             return self.value

C:\Python311\Lib\site-packages\six.py in reraise(tp, value, tb)
    717             if value.__traceback__ is not tb:
    718                 raise value.with_traceback(tb)
--> 719             raise value
    720         finally:
    721             value = None

C:\Python311\Lib\site-packages\retrying.py in call(self, fn, *args, **kwargs)
    198         while True:
    199             try:
--> 200                 attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
    201             except:
    202                 tb = sys.exc_info()

C:\Python311\Lib\site-packages\jupyter_dash\jupyter_app.py in wait_for_app()
    330                     host=host, port=port, token=JupyterDash._token
    331                 )
--> 332                 raise OSError(
    333                     "Address '{url}' already in use.\n"
    334                     "    Try passing a different port to run_server.".format(

OSError: Address 'http://127.0.0.1:8050/' already in use.
    Try passing a different port to run_server.
```
The error remains independent of chosen port, Python version 3.9, 3.10, 3.11, Jupyter or JupyterLab or browser (Chrome, Edge).

Where is the problem?

**Comment by AaronStiff** [comment] 2023-01-28 23:16
Probably a duplicate of #3900

**Closed** 2024-07-05 13:10 UTC
