### ISSUE TITLE
Display Static images in Kaggle to get visibility without Orca

### ISSUE THREAD

**Issue by LePuppy** [plotly/plotly.py#1769] opened 2019-09-13 14:24 UTC
I've recently published a kaggle kernel using plotly figures. It worked perfectly. However, html figures are not displayed in the kernel's overview and it's a shame because people can't pre-visualize the charts and might not look into the kernel. So I thought I could convert the figure to a static format but modifying the renderer raised an error :

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-e1bf1014636d> in <module>
----> 1 fig.show(renderer='png')

ValueError: 
The orca executable is required to export figures as static images,
but it could not be found on the system path.

Searched for executable 'orca' on the following path:
    /opt/conda/bin
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca.

After installation is complete, no further configuration should be needed.

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save()
```

Since I can't install orca package inside a kaggle kernel, is there a way to render these figures as static images so they feature in the kernel's overview ?

**Comment by Shubhamai** [comment] 2020-02-07 11:29
I am also getting the same error

**Comment by chekoduadarsh** [comment] 2020-04-05 10:01
@LePuppy , @Shubhamai 

you can use the following command to install Plotly-orca in Kaggle notebook

```
import sys
!conda install --yes --prefix {sys.prefix} -c plotly plotly-orca 
```

**Comment by gvwilson** [comment] 2024-06-13 19:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:49 UTC
