### ISSUE TITLE
ff.utils.validate_positive_scalars doesn't raise TypeError if user doesn't input a number

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.py#1286] opened 2018-11-23 19:18 UTC
This should result in an error:

```python
from plotly.figure_factory import utils
utils.validate_positive_scalars(a=1, b=0.001, c="aString")
```

The code to change is here: https://github.com/plotly/plotly.py/blob/master/plotly/figure_factory/utils.py#L101-L115

**Comment by gvwilson** [comment] 2024-06-13 17:43
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 17:43 UTC
Labels: enhancement, invalid
