### ISSUE TITLE
bug with px.pie and hover

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2210] opened 2020-02-18 03:55 UTC
See https://stackoverflow.com/questions/60158618/plotly-how-to-add-elements-to-hover-data-using-plotly-express-piechart

**Comment by emmanuelle** [comment] 2020-02-18 23:05
I don't think this is a `px` problem
```
import plotly.graph_objects as go

labels = ['Oxygen','Hydrogen','Carbon_Dioxide','Nitrogen']
values = [4500, 2500, 1053, 500]

custom_data = [['a', 'A'], ['b', 'B'], ['c', 'C'], ['d', 'D']]

fig = go.Figure(data=[go.Pie(labels=labels, values=values,
                            customdata=custom_data,
                            hovertemplate='bla:%{customdata[0]} <br> blo:%{customdata[1]}')])
fig.show()
```
![image](https://user-images.githubusercontent.com/263366/74785815-38760300-5279-11ea-8be6-9d6b2564ea39.png)

See how all the line is taken for the first field.

**Comment by nicolaskruchten** [comment] 2020-02-23 19:20
Seems like we could fix this in PX reasonably easily based on Etienne’s answer in JS-land, in unaggregated cases at least?

**Comment by gvwilson** [comment] 2024-06-14 13:07
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:07 UTC
