### ISSUE TITLE
Drawing of hatched histogram

### ISSUE THREAD

**Issue by mahmoudnabil** [plotly/plotly.py#1489] opened 2019-04-03 05:30 UTC
I would like to make a histogram that is hatched to add it to my paper, so that the black and white printing is readable. I could not find this option.

**Comment by jonmmease** [comment] 2019-04-04 09:44
Hi @mahmoudnabil, unfortunately I don't think hatching is possible.  You're welcome to open a request with the plotly.js project at https://github.com/plotly/plotly.js/issues to discuss the feasibility of adding this.  Thanks!

**Comment by gvwilson** [comment] 2024-06-13 19:27
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:27 UTC
Labels: enhancement, plotly.js
