### ISSUE TITLE
AttributeError when producing an Interactive plot

### ISSUE THREAD

**Issue by sursu** [plotly/plotly.py#1762] opened 2019-09-09 13:10 UTC
Plotly 4.1.0

I get an error when I try to run @jonmmease 's [Interact notebook](https://github.com/jonmmease/plotly_ipywidget_notebooks/blob/master/notebooks/Interact.ipynb):

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/interaction.py in update(self, *args)
    254                     value = widget.get_interact_value()
    255                     self.kwargs[widget._kwarg] = value
--> 256                 self.result = self.f(**self.kwargs)
    257                 show_inline_matplotlib_plots()
    258                 if self.auto_display and self.result is not None:

<ipython-input-27-8163515321f0> in update(a, b, color)
      4 def update(a=3.6, b=4.3, color='blue'):
      5     with fig.batch_update():
----> 6         scatt.x=xs
      7         scatt.y=np.sin(a*xs-b)
      8         scatt.line.color=color

/opt/anaconda3/lib/python3.7/site-packages/plotly/basedatatypes.py in __setattr__(self, prop, value)
    349         else:
    350             # Raise error on unknown public properties
--> 351             raise AttributeError(prop)
    352 
    353     def __getitem__(self, prop):

AttributeError: x
```

I get the same error wen I run the notebook with Binder.

**Comment by empet** [comment] 2019-09-09 14:39
@sursu  

`scatt = fig.add_scatter()` is ann instance of  `plotly.graph_objs._figurewidget.FigureWidget`, and  a FigureWidget has no `x` attribute.

Modify this this [example](https://github.com/jonmmease/plotly_ipywidget_notebooks/blob/master/notebooks/Interact.ipynb) as follows:

```
fig = go.FigureWidget()
fig.add_scatter()
scatt=fig.data[0]


xs=np.linspace(0, 6, 100)

@interact(a=(1.0, 4.0, 0.01), b=(0, 10.0, 0.01), color=['red', 'green', 'blue'])
def update(a=3.6, b=4.3, color='blue'):
    with fig.batch_update():
        scatt.x=xs
        scatt.y=np.sin(a*xs-b)
        scatt.line.color=color
```

**Comment by sursu** [comment] 2019-09-10 06:51
That averts the error, but the plot I get is not interactive anymore.

**Comment by empet** [comment] 2019-09-10 07:27
@sursu   Yes, you are right. Just don't rename fig.data[0]
and  replace the above scatt updates as follows:

```
xs=np.linspace(0, 6, 100)

@interact(a=(1.0, 4.0, 0.01), b=(0, 10.0, 0.01), color=['red', 'green', 'blue'])
def update(a=3.6, b=4.3, color='blue'):
    with fig.batch_update():
        fig.data[0].x=xs
        fig.data[0].y=np.sin(a*xs-b)
        fig.data[0].line.color=color
```

Please address such questions on Plotly forum [https://community.plot.ly/](https://community.plot.ly/), not here.

**Comment by sursu** [comment] 2019-09-10 20:28
Yes, thank you.

You'll agree though that there is an issue with the documentation here. And issues should be reported here.

**Comment by empet** [comment] 2019-09-10 21:34
@sursu  I'm sorry, but that notebook isn't documentation. It was just an example posted in August 2018, when the Plotly version 3.0 was released.

**Comment by nicolaskruchten** [comment] 2019-09-10 21:37
I think this is a fine place to report such issues which at first glance seem to be breakages. In this particular case, this was a breaking change we made in version 4, knowing that it would cause confusion for some people. @jonmmease it might be worth adding a note to your demo notebooks about the version?

**Comment by sursu** [comment] 2019-09-10 21:43
Or maybe add a simple example like that in the documentation.
I see now that there is the [`NYC Flights`](https://plot.ly/python/figurewidget-app/) which is a bit convoluted for me.

**Comment by nicolaskruchten** [comment] 2019-09-10 23:27
Ok, that’s good feedback, thanks! 

For reference, the change in behaviour was documented in the version 4 migration guide here: https://plot.ly/python/v4-migration/#add-trace-return-value along with a suggested workaround for adapting older code like the notebook you were initially working from.

**Comment by gvwilson** [comment] 2024-06-13 19:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:49 UTC
