### ISSUE TITLE
px.timeline loses type of x_end values

### ISSUE THREAD

**Issue by eyak** [plotly/plotly.py#2934] opened 2020-11-25 10:41 UTC
While px.timeline uses x_end values as expected and creates the proper graph,
trying to display the x_end values either as text or as hoverdata fails

![image](https://user-images.githubusercontent.com/5586769/100216563-18b3ef80-2f1b-11eb-8e62-3e41502f98c2.png)

```python
import pandas as pd
import plotly.express as px
import datetime

data = pd.DataFrame([{
    'Start Date': datetime.datetime(2020, 1, 1),
    'End Date': datetime.datetime(2020, 2, 1),
    'Test Date': datetime.datetime(2020, 2, 1),
    'y': 100
},
    {
    'Start Date': datetime.datetime(2020, 1, 10),
    'End Date': datetime.datetime(2020, 2, 10),
    'Test Date': datetime.datetime(2020, 2, 10),
    'y': 90
}])

hover_data = {
    'Start Date': '|%x',
    'End Date': '|%x',
    'Test Date': '|%x'
}

fig = px.timeline(data, x_start="Start Date", x_end="End Date",
                  y="y", text='End Date', hover_data=hover_data)
fig.show()
```

**Comment by eyak** [comment] 2020-11-29 07:44
Here's what happens inside process_dataframe_timeline:
https://github.com/plotly/plotly.py/blob/fe7a5d559d9505b16f2d562d3b2496d2a73bbae9/packages/python/plotly/plotly/express/_core.py#L1608-L1609
x_end is overwritten internally, so downstream references to x_end result in the 'massaged' data instead of the original data

**Comment by nicolaskruchten** [comment] 2020-12-23 19:10
Related to/duplicate of https://github.com/plotly/plotly.py/issues/2518 ... it seems like at the moment, using `text="End Date"` or having `"End Date"` in `hover_data` causes type issues.

**Comment by nicolaskruchten** [comment] 2021-01-12 13:05
See also https://community.plotly.com/t/issue-with-px-timeline-datetime-formats/43641/17

**Comment by nicolaskruchten** [comment] 2021-01-12 14:09
OK, so I have a fix for the `hover_data` case, but I won't have a fix for the `text` case for a while, so I'm breaking that off into a separate issue here: https://github.com/plotly/plotly.py/issues/3019

For now, the workaround for `text` is to pass in a separate column:

```python
import plotly.express as px
import pandas as pd

df = pd.DataFrame([
    dict(Task="Job A", Start='2009-01-01', Finish='2009-02-28', Resource="Alex"),
    dict(Task="Job B", Start='2009-03-05', Finish='2009-04-15', Resource="Alex"),
    dict(Task="Job C", Start='2009-02-20', Finish='2009-05-30', Resource="Max")
])
fig = px.timeline(df, x_start="Start", x_end="Finish", y="Task", text=df["Finish"].copy())
fig.update_yaxes(autorange="reversed")
fig.show()
```

**Closed** 2021-01-12 14:33 UTC
