### ISSUE TITLE
Excessive margin on the right when the actual margin is set to 0

### ISSUE THREAD

**Issue by ZmicierGT** [plotly/plotly.py#3975] opened 2022-12-03 10:01 UTC
Hi.

I see the excessive margin on the right even if the actual margin is set to 0. The wider the chart, the bigger is the excessive margin. The issue happens on 5.10.0 and 5.11.0 both on Mac and Ubuntu. Python version is 3.9.10.

Here is the illustration:
![image](https://user-images.githubusercontent.com/39563347/205434886-1108dba0-dd62-49b4-9800-846befd66fca.png)

It is the code to reproduce:

```
import plotly.express as px

import plotly.graph_objects as go
from plotly import subplots

df = px.data.gapminder().query("country=='Canada'")

fig = subplots.make_subplots(rows=1,
                             cols=1,
                             subplot_titles=["test"],
                             shared_xaxes=True,
                             vertical_spacing=0,
                             horizontal_spacing=0,
                             specs=[[{"secondary_y": True}]])

fig.add_trace(go.Scatter(x=df['year'],
                         y=df['lifeExp'],
                         mode='lines',
                         name='some data'),
              row=1, col=1,
              secondary_y=False)

fig.update_layout(
    title_text="Title",
    autosize=False,
    width=2500,
    height=600,
    legend_x=0,
    margin=dict(
        l=50,
        r=0,
        b=0,
        t=70,
        pad=4,
    ),
    legend=dict(
        bordercolor="Black",
        borderwidth=2
    ),
    paper_bgcolor="LightSteelBlue")

print(fig.layout)

fig.show()
```

It is the layout of the figure:

```
Layout({
    'annotations': [{'font': {'size': 16},
                     'showarrow': False,
                     'text': 'test',
                     'x': 0.47,
                     'xanchor': 'center',
                     'xref': 'paper',
                     'y': 1.0,
                     'yanchor': 'bottom',
                     'yref': 'paper'}],
    'autosize': False,
    'height': 600,
    'legend': {'bordercolor': 'Black', 'borderwidth': 2, 'x': 0},
    'margin': {'b': 0, 'l': 50, 'pad': 4, 'r': 0, 't': 70},
    'paper_bgcolor': 'LightSteelBlue',
    'template': '...',
    'title': {'text': 'Title'},
    'width': 2500,
    'xaxis': {'anchor': 'y', 'domain': [0.0, 0.94]},
    'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0]},
    'yaxis2': {'anchor': 'x', 'overlaying': 'y', 'side': 'right'}
})
```

I appreciate any help.

**Comment by AaronStiff** [comment] 2023-01-27 15:24
Duplicate of #3210

**Comment by AaronStiff** [comment] 2023-01-27 15:26
**Workaround**: because this is being caused by the `secondary_y` option, if you don't need a secondary y-axis, turning it off will remove the wide right margin.

**Closed** 2024-07-05 13:07 UTC
Labels: duplicate
