### ISSUE TITLE
Adding padding around marginals (plotly express)

### ISSUE THREAD

**Issue by harisbal** [plotly/plotly.py#2196] opened 2020-02-14 13:41 UTC
I was wondering whether there is any easy fix for adjusting the space between the main plot and its marginals.
As you can see below I want to draw the `xaxis` values along the `marginal_y` distribution but they end up inside the main plot area.
![Annotation 2020-02-14 153731](https://user-images.githubusercontent.com/6556306/74536090-05153a80-4f40-11ea-973b-e7749641e7d8.png)

Setting `automargin=True` for all axes did not help. I suppose a dirty fix of the domains could do the trick but I wanted to make sure there is no other "cleaner" alternative.

**Comment by gvwilson** [comment] 2024-06-14 13:08
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:08 UTC
